package com.exponential.app.ui.emoji

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertSame
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * EXP-551 — the shared emoji dataset and the rules every client mirrors:
 * parsing the COMMITTED `assets/emoji.json` (generated by packages/emoji, the
 * same bytes on web/iOS/desktop), the search ranking, the `:shortcode` token
 * shape and the per-device prefs.
 *
 * The asset is read from the source tree rather than through an AssetManager —
 * these are plain JVM tests, and the point is to lock the file the app ships.
 */
class EmojiCatalogTest {

    private val data: EmojiData by lazy { EmojiCatalog.parse(emojiAssetJson()) }

    // --- the committed dataset ---------------------------------------------

    @Test
    fun parsesTheCommittedAsset() {
        assertEquals(9, data.dataset.groups.size)
        assertEquals(1906, data.dataset.emojis.size)
        assertTrue(data.dataset.version.isNotBlank())
        assertEquals("Smileys & emotion", data.dataset.groups.first())
        assertEquals("Flags", data.dataset.groups.last())
    }

    @Test
    fun everyRecordLandsInExactlyOneGroup() {
        assertEquals(data.dataset.emojis.size, data.groups.sumOf { it.emojis.size })
        assertTrue(data.groups.all { group -> group.emojis.all { it.group == group.index } })
    }

    // --- search ranking -----------------------------------------------------

    @Test
    fun aShortcodePrefixRanksTheSmileFamilyFirst() {
        val hits = data.search("smi", limit = 5)
        assertEquals(5, hits.size)
        assertTrue(
            hits.joinToString { it.label },
            hits.all { hit -> hit.shortcodes.any { it.startsWith("smi") } },
        )
        assertEquals("smiley", hits[0].shortcodes.first())
        assertEquals("smile", hits[1].shortcodes.first())
    }

    @Test
    fun anExactShortcodeWins() {
        assertEquals("smile", data.search("smile", limit = 3).first().shortcodes.first())
        assertEquals("tada", data.search("tada", limit = 3).first().shortcodes.first())
    }

    /** Shortcodes are not all alphanumeric — `+1` must be searchable as typed. */
    @Test
    fun plusOneFindsThumbsUp() {
        val hits = data.search("+1", limit = 3)
        assertEquals("thumbs up", hits.first().label)
        assertEquals(data.findShortcode("+1")!!.unicode, hits.first().unicode)
    }

    @Test
    fun searchIsCaseInsensitiveAndTolerantOfTypedColons() {
        val plain = data.search("tada", limit = 3)
        assertEquals(plain, data.search("TADA", limit = 3))
        assertEquals(plain, data.search(":tada:", limit = 3))
        assertEquals(plain, data.search("  tada  ", limit = 3))
    }

    @Test
    fun anEmptyQueryMatchesNothing() {
        assertTrue(data.search("", limit = 8).isEmpty())
        assertTrue(data.search("   ", limit = 8).isEmpty())
    }

    @Test
    fun theLimitCaps() {
        assertEquals(8, data.search("a", limit = 8).size)
        assertTrue(data.search("a", limit = 64).size <= 64)
    }

    /**
     * The exact rank ladder, locked on a synthetic dataset so the assertion is
     * about the ORDER (shortcode exact > shortcode prefix > label prefix > tag
     * exact/prefix > label/tag substring) and not about emojibase's contents.
     */
    @Test
    fun theRankLadderIsShortcodeThenLabelThenTagThenSubstring() {
        val synthetic = EmojiCatalog.parse(
            """
            {"version":"test","groups":["G"],"emojis":[
              {"u":"5","l":"nothing","g":0,"s":[],"t":["unrelated"]},
              {"u":"4","l":"a cat sat","g":0,"s":[],"t":[]},
              {"u":"3","l":"zzz","g":0,"s":[],"t":["cathode"]},
              {"u":"2","l":"cat face","g":0,"s":[],"t":[]},
              {"u":"1","l":"zzz","g":0,"s":["cats"],"t":[]},
              {"u":"0","l":"zzz","g":0,"s":["cat"],"t":[]}
            ]}
            """.trimIndent(),
        )
        assertEquals(
            listOf("0", "1", "2", "3", "4"),
            synthetic.search("cat", limit = 10).map { it.unicode },
        )
    }

    /** Same-rank hits keep dataset order (the pickers' display order). */
    @Test
    fun tiesKeepDatasetOrder() {
        val synthetic = EmojiCatalog.parse(
            """
            {"version":"test","groups":["G"],"emojis":[
              {"u":"first","l":"zzz","g":0,"s":["cat_a"],"t":[]},
              {"u":"second","l":"zzz","g":0,"s":["cat_b"],"t":[]},
              {"u":"third","l":"zzz","g":0,"s":["cat_c"],"t":[]}
            ]}
            """.trimIndent(),
        )
        assertEquals(
            listOf("first", "second", "third"),
            synthetic.search("cat", limit = 10).map { it.unicode },
        )
        // And on the real dataset, within the one rank the `smi` prefix hits share.
        val hits = data.search("smi", limit = 5)
        val order = data.dataset.emojis.withIndex().associate { (i, e) -> e.unicode to i }
        val indexes = hits.map { order.getValue(it.unicode) }
        assertEquals(indexes.sorted(), indexes)
    }

    // --- lookups ------------------------------------------------------------

    @Test
    fun shortcodeLookupIsCaseInsensitive() {
        val record = data.findShortcode("TADA")
        assertNotNull(record)
        assertEquals("party popper", record!!.label)
        assertSame(record, data.findShortcode("tada"))
        assertNull(data.findShortcode("definitely-not-a-shortcode"))
    }

    @Test
    fun unicodeLookupResolvesARecentsEntry() {
        val record = data.findShortcode("tada")!!
        assertSame(record, data.findUnicode(record.unicode))
        assertNull(data.findUnicode("not an emoji"))
    }

    // EXP-600: skin tones are gone — pickers only ever insert `unicode`; the
    // dataset's `k` variants stay decodable (shape parity) but unread.
    @Test
    fun aTonedEmojiStillDecodesItsVariants() {
        val thumbsUp = data.findShortcode("+1")!!
        assertEquals(5, thumbsUp.tones!!.size)
        assertNull(data.findShortcode("tada")!!.tones)
    }

    // --- `:shortcode` token -------------------------------------------------

    @Test
    fun anOpenTokenMatchesFromTwoCharacters() {
        val match = matchEmojiToken("hey :sm")
        assertNotNull(match)
        assertEquals("sm", match!!.query)
        assertEquals(false, match.closed)
        assertEquals(3, match.length)
    }

    @Test
    fun aClosedTokenReportsItsClosingColon() {
        val match = matchEmojiToken(":smile:")
        assertNotNull(match)
        assertEquals("smile", match!!.query)
        assertEquals(true, match.closed)
        assertEquals(7, match.length)
    }

    @Test
    fun timesAndTrailingColonsNeverTrigger() {
        assertNull(matchEmojiToken("12:30"))
        assertNull(matchEmojiToken("note:"))
        assertNull(matchEmojiToken(":)"))
        assertNull(matchEmojiToken(":a"))
        assertNull(matchEmojiToken("http://x"))
        assertNull(matchEmojiToken("https://example.com"))
    }

    // --- prefs --------------------------------------------------------------

    private class FakeStore : EmojiPrefsStore {
        val values = mutableMapOf<String, String>()
        override fun get(key: String): String? = values[key]
        override fun set(key: String, value: String?) {
            if (value == null) values.remove(key) else values[key] = value
        }
    }

    @Test
    fun recentsAreMostRecentFirstDedupedAndCapped() {
        val prefs = EmojiPrefs(FakeStore())
        assertTrue(prefs.recents().isEmpty())
        prefs.pushRecent("🎉")
        prefs.pushRecent("👍")
        assertEquals(listOf("👍", "🎉"), prefs.recents())
        // Re-picking moves it to the head instead of duplicating.
        assertEquals(listOf("🎉", "👍"), prefs.pushRecent("🎉"))

        val many = data.dataset.emojis.take(MAX_RECENT_EMOJI + 6).map { it.unicode }
        many.forEach { prefs.pushRecent(it) }
        val recents = prefs.recents()
        assertEquals(MAX_RECENT_EMOJI, recents.size)
        assertEquals(many.last(), recents.first())
        assertEquals(recents.distinct(), recents)
    }

    @Test
    fun recentsSurviveARoundTripThroughTheStore() {
        val store = FakeStore()
        EmojiPrefs(store).pushRecent("👍")
        EmojiPrefs(store).pushRecent("🎉")
        assertEquals(listOf("🎉", "👍"), EmojiPrefs(store).recents())
    }
}

/**
 * The committed asset, located relative to the Gradle test working directory
 * (the `app` module dir) with fallbacks so the suite also runs from the repo
 * root or the `apps/android` dir.
 */
private fun emojiAssetJson(): String {
    val candidates = listOf(
        "src/main/assets/emoji.json",
        "app/src/main/assets/emoji.json",
        "apps/android/app/src/main/assets/emoji.json",
    )
    val file = candidates.map(::File).firstOrNull { it.isFile }
        ?: error("emoji.json not found from ${File(".").absolutePath}")
    return file.readText()
}
