#!/usr/bin/env bash
# Writes PeerHello's DevTickets.kt from results/.tickets-dev.json (gitignored).
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
J="$HERE/../results/.tickets-dev.json"
GEN="$HERE/PeerHello/app/src/main/java/at/exponential/peerhello"; mkdir -p "$GEN"
VIEWER=""; SESSION="vapp3-dev"
if [ -f "$J" ]; then
  VIEWER=$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["viewer"])' "$J")
  SESSION=$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["sessionId"])' "$J")
fi
LANIP=$(ipconfig getifaddr en0 2>/dev/null || echo 192.168.178.71)
cat > "$GEN/DevTickets.kt" <<KT
// Generated by write-dev-tickets.sh (gitignored). Dev defaults only.
package at.exponential.peerhello

object DevTickets {
    const val VIEWER = "$VIEWER"
    const val SESSION_ID = "$SESSION"
    const val MAC_HOST = "$LANIP"
}
KT
echo "wrote $GEN/DevTickets.kt (mac $LANIP)"
