// AUTO-GENERATED by packages/domain-contract/scripts/generate.ts — do not edit.
// Single source of truth: packages/domain-contract/contract.json.

import Foundation

enum DomainContract {
    static let issueStatusValues: [String] = ["backlog", "todo", "in_progress", "done", "cancelled"]
    static let issueStatusDisplayOrder: [String] = ["in_progress", "todo", "backlog", "done", "cancelled"]
    static let issuePriorityValues: [String] = ["none", "urgent", "high", "medium", "low"]
    static let issuePriorityDisplayOrder: [String] = ["urgent", "high", "medium", "low", "none"]
    static let recurrenceUnitValues: [String] = ["day", "week", "month"]
    static let workspaceRoleValues: [String] = ["owner", "member", "agent"]
    static let publicWritePolicyValues: [String] = ["members", "everyone"]
    static let commentKindValues: [String] = ["regular", "question", "plan"]
    static let recurrenceIntervals: [Int] = [1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 21, 30]

    static let workspaceRoleOwner: String = "owner"
    static let workspaceRoleMember: String = "member"
    static let workspaceRoleAgent: String = "agent"
    static let publicWritePolicyMembers: String = "members"
    static let publicWritePolicyEveryone: String = "everyone"
    static let commentKindRegular: String = "regular"
    static let commentKindQuestion: String = "question"
    static let commentKindPlan: String = "plan"
}
