// AUTO-GENERATED by packages/domain-contract/scripts/generate.ts — do not edit.
// Single source of truth: packages/domain-contract/contract.json.

import Foundation

enum DomainContract {
    static let issueStatusValues: [String] = ["backlog", "todo", "in_progress", "done", "cancelled"]
    static let issueStatusDisplayOrder: [String] = ["in_progress", "todo", "backlog", "done", "cancelled"]
    static let issuePriorityValues: [String] = ["none", "urgent", "high", "medium", "low"]
    static let issuePriorityDisplayOrder: [String] = ["urgent", "high", "medium", "low", "none"]
    static let recurrenceUnitValues: [String] = ["day", "week", "month"]
    static let workspaceRoleValues: [String] = ["owner", "member"]
    static let publicWritePolicyValues: [String] = ["members", "everyone"]
    static let recurrenceIntervals: [Int] = [1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 21, 30]
}
