import Foundation

/// The bundled third-party licence notice (EXP-262).
///
/// `Exponential/Resources/NOTICES.txt` is generated by `@exp/licenses`
/// (EXP-375) and packaged by the app targets' `Resources/**` Tuist glob. The
/// renderer's format contract (`packages/licenses/src/render.ts`): every
/// heading is a "rule sandwich" — a full-width rule line (78 `=` or `-`
/// characters), one or two title lines, then a matching closing rule.
/// Reproduced licence bodies are emitted verbatim and never contain that
/// exact shape, so a sandwich split is exact where a markdown-style heading
/// split would tear licence bodies apart. The 78-column width is gated on
/// the web side (`apps/web/src/lib/licenses.test.ts`), so this parser and
/// the generator cannot drift silently.
public enum ThirdPartyNotices {
    /// The renderer's `WIDTH` — rule lines are exactly this long.
    private static let ruleWidth = 78

    public struct Section: Equatable, Sendable {
        /// Empty for the preamble (anything before the first heading).
        public let title: String
        public let body: String

        public init(title: String, body: String) {
            self.title = title
            self.body = body
        }
    }

    /// The raw notice text, or nil when the resource is missing from the
    /// bundle (never crashes — the screen shows a fallback instead).
    public static func load(bundle: Bundle = .main) -> String? {
        guard let url = bundle.url(forResource: "NOTICES", withExtension: "txt") else {
            return nil
        }
        return try? String(contentsOf: url, encoding: .utf8)
    }

    /// A full-width rule line's character (`=` or `-`), or nil.
    private static func ruleChar(_ line: Substring) -> Character? {
        guard line.count == ruleWidth,
              let first = line.first, first == "=" || first == "-",
              line.allSatisfy({ $0 == first })
        else { return nil }
        return first
    }

    /// Split on rule sandwiches. CRLF input is tolerated; shorter dashed or
    /// doubled rules inside licence bodies stay body text. The preamble (if
    /// any) becomes a title-less first section.
    public static func parse(_ text: String) -> [Section] {
        let lines = text
            .replacingOccurrences(of: "\r\n", with: "\n")
            .split(separator: "\n", omittingEmptySubsequences: false)

        var sections: [Section] = []
        var title = ""
        var body: [Substring] = []

        func flush() {
            let joined = body
                .joined(separator: "\n")
                .trimmingCharacters(in: .whitespacesAndNewlines)
            if !joined.isEmpty || !title.isEmpty {
                sections.append(Section(title: title, body: joined))
            }
            body = []
        }

        var index = 0
        while index < lines.count {
            if let char = ruleChar(lines[index]) {
                var middles: [Substring] = []
                var closing = index + 1
                while closing < lines.count, middles.count < 3, ruleChar(lines[closing]) == nil {
                    middles.append(lines[closing])
                    closing += 1
                }
                if closing < lines.count,
                   ruleChar(lines[closing]) == char,
                   (1 ... 2).contains(middles.count),
                   middles.allSatisfy({ !$0.trimmingCharacters(in: .whitespaces).isEmpty }) {
                    flush()
                    title = middles
                        .map { $0.trimmingCharacters(in: .whitespaces) }
                        .joined(separator: " — ")
                    index = closing + 1
                    continue
                }
            }
            body.append(lines[index])
            index += 1
        }
        flush()
        return sections
    }
}
