//! `.exp-pi-mcp.ts` for spawned `pi` sessions (EXP-201) — pi has **no native
//! MCP support**, so the launcher writes this TypeScript extension into the
//! worktree and passes it via `-e`/`--extension`. The extension bridges the
//! Exponential MCP server into pi's own tool registry: it speaks MCP
//! streamable-HTTP JSON-RPC (initialize → tools/list → per-call tools/call)
//! against `EXP_MCP_URL` and registers every `exponential_*` tool under its
//! ORIGINAL name, so the seed prompts' tool contract
//! (`exponential_comments_list` → implement → `exponential_pr_open`) needs no
//! pi-specific variant.
//!
//! Unlike `.exp-mcp.json`, this file carries **no secret**: the server URL and
//! the raw `expu_` key ride the spawn env (`EXP_MCP_URL` / `EXP_MCP_TOKEN`),
//! so the bridge is a static byte-stable artifact. It still lands in the
//! worktree (pi resolves `-e` paths relative to cwd) and is kept out of
//! `git add -A` via the same repo-local excludes as the MCP config.
//!
//! Loading via `-e` is deliberate: it works independent of pi's project-trust
//! prompt (which gates `.pi/extensions/` auto-discovery), and the launcher
//! never passes `-a`/`--approve` — that would auto-trust repo-carried
//! extensions in a permission-free session. The file has ZERO imports: pi
//! loads extensions through jiti (plain TypeScript is fine), but `typebox`
//! may not resolve from an arbitrary worktree — and MCP `inputSchema` values
//! are plain JSON Schema objects, which is exactly what TypeBox schemas are
//! at runtime, so they pass through verbatim.

use std::io;
use std::path::{Path, PathBuf};

use crate::mcp_json::write_private;

pub const PI_BRIDGE_FILE: &str = ".exp-pi-mcp.ts";

/// The bridge source — static and byte-stable (no interpolation; the env
/// carries the per-session values).
pub const PI_BRIDGE_SOURCE: &str = r#"// AUTO-GENERATED by the Exponential desktop launcher — do not edit or commit.
// Bridges pi (no native MCP support) to the Exponential MCP server: registers
// every exponential_* tool by speaking MCP streamable-HTTP JSON-RPC against
// EXP_MCP_URL with the bearer token from EXP_MCP_TOKEN. No secrets in this
// file; both values ride the spawn environment.
export default async function (pi: any) {
  const url = process.env.EXP_MCP_URL
  const token = process.env.EXP_MCP_TOKEN
  if (!url || !token) return
  let sessionId: string | undefined
  let nextId = 1
  const rpc = async (method: string, params?: unknown): Promise<any> => {
    const headers: Record<string, string> = {
      "content-type": "application/json",
      accept: "application/json, text/event-stream",
      authorization: `Bearer ${token}`,
    }
    if (sessionId) headers["mcp-session-id"] = sessionId
    // EXP-637: the run's coding_sessions row, so exponential_sessions_end
    // (and the self-merge spare) resolve the caller. Not a secret.
    const runSession = process.env.EXP_MCP_SESSION_ID
    if (runSession) headers["x-exp-session-id"] = runSession
    const body: Record<string, unknown> = { jsonrpc: "2.0", method }
    if (params !== undefined) body.params = params
    const notification = method.startsWith("notifications/")
    if (!notification) body.id = nextId++
    const res = await fetch(url, { method: "POST", headers, body: JSON.stringify(body) })
    sessionId = res.headers.get("mcp-session-id") ?? sessionId
    if (notification) return undefined
    if (!res.ok) throw new Error(`MCP ${method} failed: HTTP ${res.status}`)
    const contentType = res.headers.get("content-type") ?? ""
    let payload: any
    if (contentType.includes("text/event-stream")) {
      // Streamable HTTP may answer a POST as a one-shot SSE stream — the
      // response is the last data: event carrying JSON.
      for (const line of (await res.text()).split("\n")) {
        const trimmed = line.trim()
        if (trimmed.startsWith("data:")) {
          try {
            payload = JSON.parse(trimmed.slice(5).trim())
          } catch {}
        }
      }
    } else {
      payload = await res.json()
    }
    if (!payload) throw new Error(`MCP ${method} returned no response`)
    if (payload.error) throw new Error(payload.error.message ?? `MCP ${method} error`)
    return payload.result
  }

  await rpc("initialize", {
    protocolVersion: "2025-03-26",
    capabilities: {},
    clientInfo: { name: "exponential-pi-bridge", version: "1.0.0" },
  })
  await rpc("notifications/initialized")
  const listed = await rpc("tools/list")
  const tools = listed?.tools ?? []
  for (const tool of tools) {
    pi.registerTool({
      name: tool.name,
      label: tool.name,
      description: tool.description ?? tool.name,
      // MCP inputSchema is plain JSON Schema — the same shape TypeBox
      // schemas have at runtime, so it passes through verbatim.
      parameters: tool.inputSchema ?? { type: "object", properties: {} },
      async execute(_toolCallId: string, params: any) {
        const result = await rpc("tools/call", { name: tool.name, arguments: params ?? {} })
        const text = (result?.content ?? [])
          .filter((block: any) => block?.type === "text")
          .map((block: any) => block.text)
          .join("\n")
        if (result?.isError) throw new Error(text || `${tool.name} failed`)
        return { content: [{ type: "text", text }], details: {} }
      },
    })
  }

  // EXP-637 — tool search. The whole exponential_* surface is far more
  // context than a run needs up front, so only the CORE set (the server's
  // per-tool `_meta["anthropic/alwaysLoad"]`, the same flag Claude Code and
  // codex honor natively) stays active; everything else is discovered on
  // demand through exponential_search_tools. Every call is wrapped: a pi
  // build without get/setActiveTools degrades OPEN — all tools active, which
  // is exactly the pre-EXP-637 behavior.
  const core = tools
    .filter((tool: any) => tool?._meta?.["anthropic/alwaysLoad"] === true)
    .map((tool: any) => tool.name)
  const SEARCH_TOOL = "exponential_search_tools"
  pi.registerTool({
    name: SEARCH_TOOL,
    label: SEARCH_TOOL,
    description:
      "Search the Exponential MCP tools by keyword and ACTIVATE the matches for this " +
      "session. Use it before any operation the currently loaded exponential_* tools " +
      "do not cover (boards, labels, members, attachments, notifications, actions, " +
      "automations, repositories, invites, teams).",
    parameters: {
      type: "object",
      properties: { query: { type: "string", description: "Keywords, e.g. \"labels\"." } },
      required: ["query"],
    },
    async execute(_toolCallId: string, params: any) {
      const terms = String(params?.query ?? "")
        .toLowerCase()
        .split(/\s+/)
        .filter(Boolean)
      const matches = tools.filter((tool: any) => {
        const haystack = `${tool.name} ${tool.description ?? ""}`.toLowerCase()
        return terms.length === 0 || terms.some((term: string) => haystack.includes(term))
      })
      try {
        const active = pi.getActiveTools?.() ?? []
        pi.setActiveTools?.([...new Set([...active, ...matches.map((t: any) => t.name)])])
      } catch {}
      const text = matches.length
        ? matches.map((t: any) => `${t.name} — ${t.description ?? ""}`.trim()).join("\n")
        : "No matching Exponential tools."
      return { content: [{ type: "text", text }], details: {} }
    },
  })
  const activateCore = () => {
    try {
      const active = pi.getActiveTools?.()
      if (!active || !pi.setActiveTools) return
      const foreign = active.filter((name: string) => !name.startsWith("exponential_"))
      pi.setActiveTools([...new Set([...foreign, ...core, SEARCH_TOOL])])
    } catch {}
  }
  try {
    pi.on?.("session_start", activateCore)
  } catch {}
  activateCore()
}
"#;

/// Write the bridge into the worktree root. Overwrites every launch so a
/// newer app version's bridge always wins over a stale copy in a reused
/// worktree. Same private-write posture as `.exp-mcp.json` (no secret here,
/// but no reason to be looser).
pub fn write_pi_bridge(worktree: &Path) -> io::Result<PathBuf> {
    let path = worktree.join(PI_BRIDGE_FILE);
    write_private(&path, PI_BRIDGE_SOURCE)?;
    Ok(path)
}

pub const PI_OBSERVER_FILE: &str = ".exp-pi-observer.ts";

/// The observer extension (EXP-383) — the pi analogue of the claude hooks
/// sidecar. Subscribes to pi's extension events and POSTs batched activity
/// to the desktop's loopback observer server (`steer::pi_observer`), and
/// long-polls it for remote steer messages applied via `pi.sendUserMessage`
/// (pi's own queue semantics — while streaming, `deliverAs` is REQUIRED and
/// `"steer"` delivers at the next tool boundary; when idle it must be
/// OMITTED so the message triggers a turn).
///
/// EXP-724: the same long-poll carries remote SLASH COMMANDS, which must
/// never go through `sendUserMessage` — pi dispatches its built-ins only in
/// the TUI's `onSubmit`, so `/compact` sent as a message is just text for
/// the model. `compact` runs `ctx.compact()`, `new` runs `ctx.newSession()`
/// and `model` resolves through `ctx.modelRegistry` into `pi.setModel`; the
/// live `ctx` is rebound on every `session_start` so a `/new` leaves the
/// pump steering the session that replaced it. The compaction edges pi
/// raises (`session_before_compact`/`session_compact`) are reported too —
/// they are the only agent's compaction with a real START marker.
///
/// Same contract as the MCP bridge: static byte-stable file, zero imports,
/// no secrets (url + token ride `EXP_OBSERVER_URL`/`EXP_OBSERVER_TOKEN` in
/// the spawn env — the file is inert without them). Extension rules per pi
/// v0.83 docs: never write to stdout (the TUI owns it), start background
/// work in `session_start` (never the factory — `--list-models` runs
/// factories without a session), stop it in `session_shutdown`, and swallow
/// every failure — a dead sidecar must never wedge the coding session.
/// Unknown `pi.on` event names are no-ops on older pi versions.
pub const PI_OBSERVER_SOURCE: &str = r#"// AUTO-GENERATED by the Exponential desktop launcher — do not edit or commit.
// Reports pi session activity to the desktop's loopback observer sidecar and
// applies remote steer messages via pi.sendUserMessage. No secrets in this
// file; EXP_OBSERVER_URL / EXP_OBSERVER_TOKEN ride the spawn environment.
export default function (pi: any) {
  const url = process.env.EXP_OBSERVER_URL
  const token = process.env.EXP_OBSERVER_TOKEN
  if (!url || !token) return
  const cwd = process.cwd()

  let stopped = false
  let queue: any[] = []
  let flushTimer: any = null

  const post = async (path: string, body: unknown): Promise<any> => {
    const res = await fetch(`${url}${path}`, {
      method: "POST",
      headers: { "content-type": "application/json", authorization: `Bearer ${token}` },
      body: JSON.stringify(body),
    })
    if (!res.ok) throw new Error(`observer ${path}: HTTP ${res.status}`)
    return res.status === 204 ? undefined : await res.json()
  }

  const flush = () => {
    if (flushTimer) { clearTimeout(flushTimer); flushTimer = null }
    if (!queue.length) return
    const events = queue
    queue = []
    post("/events", { cwd, events }).catch(() => {})
  }
  // Coalesce: one POST per burst, never one per event.
  const emit = (event: Record<string, unknown>) => {
    if (stopped) return
    queue.push(event)
    if (queue.length >= 20) return void flush()
    if (!flushTimer) flushTimer = setTimeout(flush, 300)
  }

  const on = (name: string, handler: (e: any, ctx: any) => void) => {
    // Unknown events are a no-op on older pi; a throwing handler must never
    // reach pi's error surface.
    pi.on(name, (e: any, ctx: any) => {
      try { handler(e, ctx) } catch {}
    })
  }

  // The live session context. Rebound on every session_start, so a /new
  // (ctx.newSession) leaves the pump steering the CURRENT session.
  let liveCtx: any = null

  // --- commands (inbound) --------------------------------------------------
  // Built-in slash commands dispatch only in pi's TUI onSubmit, so
  // sendUserMessage("/compact") would just send the literal text to the
  // model. These run pi's own APIs instead.
  const failCommand = (name: string, err: any) => {
    emit({ kind: "command_failed", name, message: String(err?.message ?? err) })
    flush()
  }
  const resolveModel = (spec: string): any => {
    const registry = liveCtx?.modelRegistry
    if (!registry || !spec) return undefined
    const slash = spec.indexOf("/")
    if (slash > 0) {
      const found = registry.find?.(spec.slice(0, slash), spec.slice(slash + 1))
      if (found) return found
    }
    // Bare id: prefer the models this machine actually has auth for —
    // getAll() also lists providers with no API key, and setModel() then
    // returns false on a name that looked like a perfect match.
    const lowered = spec.toLowerCase()
    for (const pool of [registry.getAvailable?.() ?? [], registry.getAll?.() ?? []]) {
      const hit = pool.find((model: any) => model?.id === spec)
        ?? pool.find((model: any) => String(model?.id ?? "").toLowerCase() === lowered)
      if (hit) return hit
    }
    return undefined
  }
  const runCommand = async (name: string, args: string) => {
    try {
      const ctx = liveCtx
      if (name === "compact") {
        if (typeof ctx?.compact !== "function") throw new Error("this pi build has no compact API")
        ctx.compact({
          customInstructions: args || undefined,
          onError: (err: any) => failCommand(name, err),
        })
      } else if (name === "new") {
        if (typeof ctx?.newSession !== "function") throw new Error("this pi build cannot start a new session")
        await ctx.newSession()
      } else if (name === "model") {
        const model = resolveModel(args)
        if (!model) throw new Error(`no model matches ${args}`)
        // false = no API key configured for that model (pi docs).
        if ((await pi.setModel(model)) === false) throw new Error(`no API key for ${args}`)
      } else {
        return
      }
      emit({ kind: "command", name, args })
      flush()
    } catch (err) {
      failCommand(name, err)
    }
  }

  // --- steering (inbound) --------------------------------------------------
  // Long-poll the sidecar; apply each remote composer message through pi's
  // own queue and each remote slash command through pi's own API. Started
  // from session_start (never the factory), stopped by session_shutdown.
  let pumping = false
  const startSteerPump = (bootCtx: any) => {
    if (pumping) return
    pumping = true
    const pump = async () => {
      while (!stopped) {
        try {
          const next = await post("/steer", { cwd })
          const ctx = liveCtx ?? bootCtx
          for (const text of next?.messages ?? []) {
            if (typeof text !== "string" || !text.length) continue
            try {
              // deliverAs is REQUIRED while streaming and must be OMITTED
              // when idle (it would throw / not start a turn otherwise).
              if (ctx.isIdle()) pi.sendUserMessage(text)
              else pi.sendUserMessage(text, { deliverAs: "steer" })
            } catch {}
          }
          for (const command of next?.commands ?? []) {
            if (typeof command?.name !== "string") continue
            await runCommand(command.name, typeof command.args === "string" ? command.args : "")
          }
        } catch {
          await new Promise((resolve) => setTimeout(resolve, 2000))
        }
      }
    }
    void pump()
  }

  // --- observation ---------------------------------------------------------
  on("session_start", (_e, ctx) => {
    liveCtx = ctx
    emit({ kind: "session_start" })
    startSteerPump(ctx)
  })
  on("input", (e) => {
    // interactive = typed in the TUI; extension = our own injected steer
    // (forwarded so OTHER viewers see it — the sender's client dedupes).
    if (e?.source !== "interactive" && e?.source !== "extension") return
    if (typeof e?.text !== "string" || !e.text.length) return
    emit({ kind: "input", text: e.text, source: e.source })
  })
  on("agent_start", () => emit({ kind: "agent_start" }))
  // agent_settled is the true idle signal: pi may still auto-retry,
  // auto-compact, or continue with queued follow-ups after agent_end. It is
  // also a recent addition (absent before ~0.8x), so agent_end doubles as
  // the fallback — on newer pi both fire and the flag write is idempotent;
  // a premature idle from agent_end is corrected by the next agent_start.
  on("agent_settled", () => { emit({ kind: "agent_settled" }); flush() })
  on("agent_end", () => { emit({ kind: "agent_settled" }); flush() })
  on("message_update", (e) => {
    const ev = e?.assistantMessageEvent
    if (ev?.type === "text_end" && typeof ev.content === "string" && ev.content.length) {
      emit({ kind: "text", text: ev.content })
    } else if (ev?.type === "thinking_end" && typeof ev.content === "string" && ev.content.length) {
      emit({ kind: "thinking", text: ev.content })
    }
  })
  on("tool_execution_start", (e) => {
    if (typeof e?.toolName !== "string") return
    emit({ kind: "tool_start", id: e.toolCallId ?? "", name: e.toolName, args: e.args ?? {} })
  })
  on("tool_execution_end", (e) => {
    if (typeof e?.toolName !== "string") return
    emit({ kind: "tool_end", id: e.toolCallId ?? "", isError: e.isError === true })
  })
  // Compaction: pi's reason vocabulary is manual | threshold | overflow; the
  // steer wire carries manual | auto only.
  on("session_before_compact", (e) => {
    emit({ kind: "compaction", phase: "started", trigger: e?.reason === "manual" ? "manual" : "auto" })
    flush()
  })
  on("session_compact", () => { emit({ kind: "compaction", phase: "ended" }); flush() })
  on("session_shutdown", () => {
    emit({ kind: "session_shutdown" })
    flush()
    stopped = true
  })
}
"#;

/// Write the observer extension next to the MCP bridge. Same overwrite +
/// private-write posture as [`write_pi_bridge`].
pub fn write_pi_observer(worktree: &Path) -> io::Result<PathBuf> {
    let path = worktree.join(PI_OBSERVER_FILE);
    write_private(&path, PI_OBSERVER_SOURCE)?;
    Ok(path)
}

pub const PI_PLAN_FILE: &str = ".exp-pi-plan.ts";

/// Plan mode for pi (EXP-441) — pi has no native plan mode, so this
/// launcher-written extension implements one: a plan-first system-prompt
/// section, a mutating-tool gate (`write`/`edit` plus mutating
/// `exponential_*` MCP tools; bash stays available under read-only prompt
/// discipline), and an `exit_plan_mode` tool whose approval runs through
/// pi's native `ctx.ui.confirm` dialog. The plan lifecycle posts
/// `plan_pending`/`plan_resolved` events to the observer sidecar so remote
/// viewers get the standard plan-approval card and the emitter can resolve
/// the dialog by pty keystroke on a remote answer (`steer::pi_activity`).
///
/// Same contract as the other two extensions: static byte-stable file, zero
/// imports, no stdout, no secrets (`EXP_PI_PLAN_MODE=1` gates it on;
/// `EXP_OBSERVER_URL`/`EXP_OBSERVER_TOKEN` ride the spawn env), and every
/// failure swallowed — a dead sidecar or an older pi API surface must never
/// wedge the coding session. A pi without `ctx.ui.confirm` degrades OPEN
/// (auto-approve): a gate nobody can ever approve would wedge the session
/// outright, which is worse than losing the gate.
pub const PI_PLAN_SOURCE: &str = r###"// AUTO-GENERATED by the Exponential desktop launcher — do not edit or commit.
// Plan mode for pi: blocks mutating tools until the user approves a plan
// presented via the exit_plan_mode tool and pi's native confirm dialog.
// Inert without EXP_PI_PLAN_MODE=1. No secrets in this file;
// EXP_OBSERVER_URL / EXP_OBSERVER_TOKEN ride the spawn environment.
export default function (pi: any) {
  if (process.env.EXP_PI_PLAN_MODE !== "1") return
  const url = process.env.EXP_OBSERVER_URL
  const token = process.env.EXP_OBSERVER_TOKEN
  const cwd = process.cwd()

  let planning = true

  // One-shot POST to the observer sidecar's /events route (same wire shape
  // the observer extension batches). Never batched: a pending plan must
  // reach remote viewers immediately. Failures are swallowed — without a
  // sidecar the local confirm dialog still works.
  const post = (event: Record<string, unknown>): Promise<void> => {
    if (!url || !token) return Promise.resolve()
    return fetch(`${url}/events`, {
      method: "POST",
      headers: { "content-type": "application/json", authorization: `Bearer ${token}` },
      body: JSON.stringify({ cwd, events: [event] }),
    }).then(() => undefined, () => undefined)
  }

  const setStatus = (ctx: any, text: string | undefined) => {
    try { ctx?.ui?.setStatus?.("exp-plan", text) } catch {}
  }

  // Read-only exponential_* MCP tools stay callable during planning; every
  // other exponential_* tool mutates (create/update/delete/pr_open/...).
  const readOnlySuffixes = ["_list", "_get", "_pr_files", "_branch_diff"]
  const blockedWhilePlanning = (name: string): boolean => {
    if (name === "write" || name === "edit") return true
    // EXP-637: tool SEARCH is read-only discovery — planning needs it to
    // reach the deferred exponential_* surface at all.
    if (name === "exponential_search_tools") return false
    if (name.startsWith("exponential_")) {
      return !readOnlySuffixes.some((suffix) => name.endsWith(suffix))
    }
    return false
  }

  const planPrompt = [
    "",
    "## Plan mode (active)",
    "The user wants to review an implementation plan before you change anything.",
    "- Do NOT modify anything yet. The write and edit tools are blocked, and bash",
    "  must be used strictly read-only: no file writes or deletes, no git",
    "  commit/push, no package installs, no state-changing commands.",
    "- Investigate the repository first, then call the exit_plan_mode tool with",
    "  your full implementation plan as markdown.",
    "- The user approves or rejects the plan. Only after approval may you start",
    "  making changes. If rejected, wait for feedback, revise, and call",
    "  exit_plan_mode again.",
  ].join("\n")

  try {
    pi.registerTool({
      name: "exit_plan_mode",
      label: "Exit plan mode",
      description:
        "Present your implementation plan to the user for approval. Call this once your investigation is complete, passing the full plan as markdown. Implementation may only begin after this tool returns approval.",
      parameters: {
        type: "object",
        properties: {
          plan: { type: "string", description: "The full implementation plan, as markdown." },
        },
        required: ["plan"],
      },
      async execute(_toolCallId: string, _params: any) {
        // Approval already ran in the tool_call interceptor below — a
        // rejected plan never reaches execute (the call is blocked there).
        return {
          content: [{ type: "text", text: "Plan approved — proceed with the implementation." }],
          details: {},
        }
      },
    })
  } catch {}

  try {
    pi.on("before_agent_start", (event: any) => {
      try {
        if (!planning) return undefined
        return { systemPrompt: `${event?.systemPrompt ?? ""}${planPrompt}` }
      } catch {
        return undefined
      }
    })
  } catch {}

  try {
    pi.on("session_start", (_event: any, ctx: any) => {
      try {
        if (planning) setStatus(ctx, "plan mode")
      } catch {}
    })
  } catch {}

  try {
    pi.on("tool_call", async (event: any, ctx: any) => {
      try {
        const name = event?.toolName
        if (typeof name !== "string") return undefined
        if (name === "exit_plan_mode") {
          if (!planning) return undefined
          const input = event?.input ?? {}
          const plan = typeof input.plan === "string" ? input.plan : ""
          const id =
            typeof event?.toolCallId === "string" && event.toolCallId.length
              ? event.toolCallId
              : `plan-${Date.now()}`
          await post({ kind: "plan_pending", id, plan })
          setStatus(ctx, "plan awaiting approval")
          let approved = false
          const confirm = ctx?.ui?.confirm
          if (typeof confirm !== "function") {
            // Older pi without a confirm surface: degrade OPEN — an
            // unapprovable plan gate would wedge the session outright.
            approved = true
          } else {
            try {
              approved = (await confirm.call(ctx.ui, "Approve plan?", plan)) === true
            } catch {
              approved = false
            }
          }
          await post({ kind: "plan_resolved", id, approved })
          if (approved) {
            planning = false
            setStatus(ctx, undefined)
            return undefined // allow the tool — execute() returns the approval text
          }
          setStatus(ctx, "plan mode")
          // terminate stops the agent after this blocked batch (verified
          // against pi 0.84.1: early termination fires when every blocked
          // call in the batch sets it — this is a single call), handing
          // control back to the user for feedback.
          return {
            block: true,
            reason:
              "The user rejected the plan. Stay in plan mode: wait for their feedback, then revise the plan and call exit_plan_mode again.",
            terminate: true,
          }
        }
        if (planning && blockedWhilePlanning(name)) {
          return {
            block: true,
            reason: `Plan mode is active: ${name} is not allowed yet. Investigate read-only and present your plan via the exit_plan_mode tool first.`,
          }
        }
        return undefined
      } catch {
        return undefined
      }
    })
  } catch {}
}
"###;

/// Write the plan-mode extension next to the bridge and the observer. Same
/// overwrite + private-write posture as [`write_pi_bridge`].
pub fn write_pi_plan(worktree: &Path) -> io::Result<PathBuf> {
    let path = worktree.join(PI_PLAN_FILE);
    write_private(&path, PI_PLAN_SOURCE)?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn bridge_is_static_env_configured_and_importless() {
        // No per-session interpolation — the env carries url + token, so the
        // file itself must never contain a secret placeholder.
        assert!(!PI_BRIDGE_SOURCE.contains("expu_"));
        assert!(PI_BRIDGE_SOURCE.contains("EXP_MCP_URL"));
        assert!(PI_BRIDGE_SOURCE.contains("EXP_MCP_TOKEN"));
        // Zero imports: typebox/pi packages may not resolve from an arbitrary
        // worktree; the extension must be self-contained.
        assert!(!PI_BRIDGE_SOURCE.contains("import "));
        // The pi extension contract: default async factory + registerTool.
        assert!(PI_BRIDGE_SOURCE.contains("export default async function (pi: any)"));
        assert!(PI_BRIDGE_SOURCE.contains("pi.registerTool"));
        // The MCP handshake + tool pass-through (original tool names).
        for needle in ["initialize", "notifications/initialized", "tools/list", "tools/call"] {
            assert!(PI_BRIDGE_SOURCE.contains(needle), "missing {needle}");
        }
    }

    /// EXP-637: the bridge defers the full exponential_* surface behind a
    /// search tool (pi's documented dynamic tool loading) and identifies the
    /// run to the server. Still zero-import, still secret-free.
    #[test]
    fn bridge_defers_tools_behind_search_and_sends_the_session_header() {
        assert!(PI_BRIDGE_SOURCE.contains("exponential_search_tools"));
        assert!(PI_BRIDGE_SOURCE.contains(r#"anthropic/alwaysLoad"#));
        assert!(PI_BRIDGE_SOURCE.contains("setActiveTools"));
        assert!(PI_BRIDGE_SOURCE.contains("getActiveTools"));
        assert!(PI_BRIDGE_SOURCE.contains(r#"pi.on?.("session_start""#));
        // The session header (env-carried, never interpolated into the file).
        assert!(PI_BRIDGE_SOURCE.contains("EXP_MCP_SESSION_ID"));
        assert!(PI_BRIDGE_SOURCE.contains("x-exp-session-id"));
        // The file stays byte-stable, import-free and secret-free.
        assert!(!PI_BRIDGE_SOURCE.contains("import "));
        assert!(!PI_BRIDGE_SOURCE.contains("console."));
        assert!(!PI_BRIDGE_SOURCE.contains("expu_"));
        // Degrading OPEN matters more than deferring: every registry call is
        // wrapped, so a pi without the API keeps all tools active.
        assert!(PI_BRIDGE_SOURCE.contains("} catch {}"));
    }

    #[test]
    fn observer_is_static_env_configured_importless_and_stdout_free() {
        // Same contract as the MCP bridge: env-configured, zero imports.
        assert!(!PI_OBSERVER_SOURCE.contains("expu_"));
        assert!(PI_OBSERVER_SOURCE.contains("EXP_OBSERVER_URL"));
        assert!(PI_OBSERVER_SOURCE.contains("EXP_OBSERVER_TOKEN"));
        assert!(!PI_OBSERVER_SOURCE.contains("import "));
        // pi's TUI owns stdout — an extension must never write to it.
        assert!(!PI_OBSERVER_SOURCE.contains("console."));
        assert!(PI_OBSERVER_SOURCE.contains("export default function (pi: any)"));
        // The full observation set (unknown names no-op on older pi).
        for event in [
            "session_start",
            "input",
            "agent_start",
            "agent_settled",
            "agent_end", // idle fallback for pi builds predating agent_settled
            "message_update",
            "tool_execution_start",
            "tool_execution_end",
            // EXP-724: pi is the one agent with a real compaction START.
            "session_before_compact",
            "session_compact",
            "session_shutdown",
        ] {
            assert!(
                PI_OBSERVER_SOURCE.contains(&format!("on(\"{event}\"")),
                "missing subscription: {event}"
            );
        }
        // EXP-724: commands run pi's own APIs — never sendUserMessage, which
        // would hand `/compact` to the model as literal text.
        assert!(PI_OBSERVER_SOURCE.contains("ctx.compact({"));
        assert!(PI_OBSERVER_SOURCE.contains("ctx.newSession()"));
        assert!(PI_OBSERVER_SOURCE.contains("pi.setModel(model)"));
        assert!(PI_OBSERVER_SOURCE.contains("next?.commands ?? []"));
        // The steer contract: deliverAs required while streaming, omitted
        // when idle; background work starts in session_start, never the
        // factory (pi runs factories for --list-models etc.).
        assert!(PI_OBSERVER_SOURCE.contains("ctx.isIdle()"));
        assert!(PI_OBSERVER_SOURCE.contains(r#"{ deliverAs: "steer" }"#));
        assert!(PI_OBSERVER_SOURCE.contains("startSteerPump(ctx)"));
        // The sidecar routes: batched events + the steer long-poll.
        assert!(PI_OBSERVER_SOURCE.contains(r#""/events""#));
        assert!(PI_OBSERVER_SOURCE.contains(r#""/steer""#));
    }

    #[test]
    fn plan_is_static_env_gated_importless_and_stdout_free() {
        // Same contract as the other two extensions: env-configured, zero
        // imports, no secrets, stdout untouched.
        assert!(!PI_PLAN_SOURCE.contains("expu_"));
        assert!(PI_PLAN_SOURCE.contains("EXP_PI_PLAN_MODE"));
        assert!(PI_PLAN_SOURCE.contains("EXP_OBSERVER_URL"));
        assert!(PI_PLAN_SOURCE.contains("EXP_OBSERVER_TOKEN"));
        assert!(!PI_PLAN_SOURCE.contains("import "));
        assert!(!PI_PLAN_SOURCE.contains("console."));
        assert!(PI_PLAN_SOURCE.contains("export default function (pi: any)"));
        // The plan gate: the approval tool, both lifecycle events on the
        // observer wire, and the two hooks the mode rides on.
        assert!(PI_PLAN_SOURCE.contains("pi.registerTool"));
        assert!(PI_PLAN_SOURCE.contains("exit_plan_mode"));
        assert!(PI_PLAN_SOURCE.contains(r#""plan_pending""#));
        assert!(PI_PLAN_SOURCE.contains(r#""plan_resolved""#));
        assert!(PI_PLAN_SOURCE.contains(r#"pi.on("before_agent_start""#));
        assert!(PI_PLAN_SOURCE.contains(r#"pi.on("tool_call""#));
        // EXP-637: tool search is read-only discovery — never blocked.
        assert!(PI_PLAN_SOURCE.contains(r#"if (name === "exponential_search_tools") return false"#));
        // Rejection terminates the turn so the user can give feedback.
        assert!(PI_PLAN_SOURCE.contains("terminate: true"));
        // Bash stays available (prompt discipline only) — the hard block is
        // write/edit plus mutating exponential_* tools.
        assert!(!PI_PLAN_SOURCE.contains(r#"name === "bash""#));
        for suffix in ["_list", "_get", "_pr_files", "_branch_diff"] {
            assert!(
                PI_PLAN_SOURCE.contains(&format!("\"{suffix}\"")),
                "missing read-only suffix: {suffix}"
            );
        }
        // The sidecar wire shape matches the observer's /events contract.
        assert!(PI_PLAN_SOURCE.contains(r#"`${url}/events`"#));
        assert!(PI_PLAN_SOURCE.contains("cwd, events"));
    }

    #[test]
    fn plan_write_lands_next_to_the_bridge_and_overwrites() {
        let mut dir = std::env::temp_dir();
        dir.push(format!(
            "exp-coding-pi-plan-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join(PI_PLAN_FILE), "stale").unwrap();
        let path = write_pi_plan(&dir).unwrap();
        assert_eq!(path, dir.join(PI_PLAN_FILE));
        assert_eq!(fs::read_to_string(&path).unwrap(), PI_PLAN_SOURCE);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn observer_write_lands_next_to_the_bridge() {
        let mut dir = std::env::temp_dir();
        dir.push(format!(
            "exp-coding-pi-observer-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&dir).unwrap();
        let path = write_pi_observer(&dir).unwrap();
        assert_eq!(path, dir.join(PI_OBSERVER_FILE));
        assert_eq!(fs::read_to_string(&path).unwrap(), PI_OBSERVER_SOURCE);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn write_lands_in_the_worktree_root_and_overwrites() {
        let mut dir = std::env::temp_dir();
        dir.push(format!(
            "exp-coding-pi-bridge-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&dir).unwrap();

        fs::write(dir.join(PI_BRIDGE_FILE), "stale").unwrap();
        let path = write_pi_bridge(&dir).unwrap();
        assert_eq!(path, dir.join(PI_BRIDGE_FILE));
        assert_eq!(fs::read_to_string(&path).unwrap(), PI_BRIDGE_SOURCE);

        let _ = fs::remove_dir_all(&dir);
    }
}
