//! `.exp-pi-mcp.ts` for spawned `pi` sessions (EXP-201) — pi has **no native
//! MCP support**, so the launcher writes this TypeScript extension into the
//! worktree and passes it via `-e`/`--extension`. The extension bridges the
//! Exponential MCP server into pi's own tool registry: it speaks MCP
//! streamable-HTTP JSON-RPC (initialize → tools/list → per-call tools/call)
//! against `EXP_MCP_URL` and registers every `exponential_*` tool under its
//! ORIGINAL name, so the seed prompts' tool contract
//! (`exponential_comments_list` → implement → `exponential_pr_open`) needs no
//! pi-specific variant.
//!
//! Unlike `.exp-mcp.json`, this file carries **no secret**: the server URL and
//! the raw `expu_` key ride the spawn env (`EXP_MCP_URL` / `EXP_MCP_TOKEN`),
//! so the bridge is a static byte-stable artifact. It still lands in the
//! worktree (pi resolves `-e` paths relative to cwd) and is kept out of
//! `git add -A` via the same repo-local excludes as the MCP config.
//!
//! Loading via `-e` is deliberate: it works independent of pi's project-trust
//! prompt (which gates `.pi/extensions/` auto-discovery), and the launcher
//! never passes `-a`/`--approve` — that would auto-trust repo-carried
//! extensions in a permission-free session. The file has ZERO imports: pi
//! loads extensions through jiti (plain TypeScript is fine), but `typebox`
//! may not resolve from an arbitrary worktree — and MCP `inputSchema` values
//! are plain JSON Schema objects, which is exactly what TypeBox schemas are
//! at runtime, so they pass through verbatim.

use std::io;
use std::path::{Path, PathBuf};

use crate::mcp_json::write_private;

pub const PI_BRIDGE_FILE: &str = ".exp-pi-mcp.ts";

/// The bridge source — static and byte-stable (no interpolation; the env
/// carries the per-session values).
pub const PI_BRIDGE_SOURCE: &str = r#"// AUTO-GENERATED by the Exponential desktop launcher — do not edit or commit.
// Bridges pi (no native MCP support) to the Exponential MCP server: registers
// every exponential_* tool by speaking MCP streamable-HTTP JSON-RPC against
// EXP_MCP_URL with the bearer token from EXP_MCP_TOKEN. No secrets in this
// file; both values ride the spawn environment.
export default async function (pi: any) {
  const url = process.env.EXP_MCP_URL
  const token = process.env.EXP_MCP_TOKEN
  if (!url || !token) return
  let sessionId: string | undefined
  let nextId = 1
  const rpc = async (method: string, params?: unknown): Promise<any> => {
    const headers: Record<string, string> = {
      "content-type": "application/json",
      accept: "application/json, text/event-stream",
      authorization: `Bearer ${token}`,
    }
    if (sessionId) headers["mcp-session-id"] = sessionId
    const body: Record<string, unknown> = { jsonrpc: "2.0", method }
    if (params !== undefined) body.params = params
    const notification = method.startsWith("notifications/")
    if (!notification) body.id = nextId++
    const res = await fetch(url, { method: "POST", headers, body: JSON.stringify(body) })
    sessionId = res.headers.get("mcp-session-id") ?? sessionId
    if (notification) return undefined
    if (!res.ok) throw new Error(`MCP ${method} failed: HTTP ${res.status}`)
    const contentType = res.headers.get("content-type") ?? ""
    let payload: any
    if (contentType.includes("text/event-stream")) {
      // Streamable HTTP may answer a POST as a one-shot SSE stream — the
      // response is the last data: event carrying JSON.
      for (const line of (await res.text()).split("\n")) {
        const trimmed = line.trim()
        if (trimmed.startsWith("data:")) {
          try {
            payload = JSON.parse(trimmed.slice(5).trim())
          } catch {}
        }
      }
    } else {
      payload = await res.json()
    }
    if (!payload) throw new Error(`MCP ${method} returned no response`)
    if (payload.error) throw new Error(payload.error.message ?? `MCP ${method} error`)
    return payload.result
  }

  await rpc("initialize", {
    protocolVersion: "2025-03-26",
    capabilities: {},
    clientInfo: { name: "exponential-pi-bridge", version: "1.0.0" },
  })
  await rpc("notifications/initialized")
  const listed = await rpc("tools/list")
  for (const tool of listed?.tools ?? []) {
    pi.registerTool({
      name: tool.name,
      label: tool.name,
      description: tool.description ?? tool.name,
      // MCP inputSchema is plain JSON Schema — the same shape TypeBox
      // schemas have at runtime, so it passes through verbatim.
      parameters: tool.inputSchema ?? { type: "object", properties: {} },
      async execute(_toolCallId: string, params: any) {
        const result = await rpc("tools/call", { name: tool.name, arguments: params ?? {} })
        const text = (result?.content ?? [])
          .filter((block: any) => block?.type === "text")
          .map((block: any) => block.text)
          .join("\n")
        if (result?.isError) throw new Error(text || `${tool.name} failed`)
        return { content: [{ type: "text", text }], details: {} }
      },
    })
  }
}
"#;

/// Write the bridge into the worktree root. Overwrites every launch so a
/// newer app version's bridge always wins over a stale copy in a reused
/// worktree. Same private-write posture as `.exp-mcp.json` (no secret here,
/// but no reason to be looser).
pub fn write_pi_bridge(worktree: &Path) -> io::Result<PathBuf> {
    let path = worktree.join(PI_BRIDGE_FILE);
    write_private(&path, PI_BRIDGE_SOURCE)?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn bridge_is_static_env_configured_and_importless() {
        // No per-session interpolation — the env carries url + token, so the
        // file itself must never contain a secret placeholder.
        assert!(!PI_BRIDGE_SOURCE.contains("expu_"));
        assert!(PI_BRIDGE_SOURCE.contains("EXP_MCP_URL"));
        assert!(PI_BRIDGE_SOURCE.contains("EXP_MCP_TOKEN"));
        // Zero imports: typebox/pi packages may not resolve from an arbitrary
        // worktree; the extension must be self-contained.
        assert!(!PI_BRIDGE_SOURCE.contains("import "));
        // The pi extension contract: default async factory + registerTool.
        assert!(PI_BRIDGE_SOURCE.contains("export default async function (pi: any)"));
        assert!(PI_BRIDGE_SOURCE.contains("pi.registerTool"));
        // The MCP handshake + tool pass-through (original tool names).
        for needle in ["initialize", "notifications/initialized", "tools/list", "tools/call"] {
            assert!(PI_BRIDGE_SOURCE.contains(needle), "missing {needle}");
        }
    }

    #[test]
    fn write_lands_in_the_worktree_root_and_overwrites() {
        let mut dir = std::env::temp_dir();
        dir.push(format!(
            "exp-coding-pi-bridge-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&dir).unwrap();

        fs::write(dir.join(PI_BRIDGE_FILE), "stale").unwrap();
        let path = write_pi_bridge(&dir).unwrap();
        assert_eq!(path, dir.join(PI_BRIDGE_FILE));
        assert_eq!(fs::read_to_string(&path).unwrap(), PI_BRIDGE_SOURCE);

        let _ = fs::remove_dir_all(&dir);
    }
}
