#!/usr/bin/env bash
# VAPP-91: write the tagged SwiftPM distribution repo of ExponentialUI.
#
#   bash release/make-release-package.sh <version> <xcframework-zip-url> <checksum> <outdir>
#   bash release/make-release-package.sh <version> - - <outdir> --local <ExponentialUIFFI.xcframework>
#
# <outdir> gets: Package.swift (the binary target ALWAYS declared, as
# `url:` + `checksum:`; `--local` swaps in `path:` and copies the
# xcframework, for a local `swift build` check, since SwiftPM refuses file
# URLs for binary targets), Sources/ (ExponentialUICore = the generated
# UniFFI binding, ExponentialUI, ExponentialUIPrimitives), LICENSE + NOTICE
# from the repo root, a README. Commit that tree to the distribution repo and
# tag it <version>. The zip + checksum come from release/zip-xcframework.sh.
set -euo pipefail

usage() {
  echo "usage: $0 <version> <xcframework-zip-url> <checksum> <outdir> [--local <xcframework>]" >&2
  exit 2
}
[ $# -ge 4 ] || usage
version="$1"; url="$2"; checksum="$3"; outdir="$4"; shift 4
local_xcf=""
if [ $# -gt 0 ]; then
  [ "$1" = "--local" ] && [ $# -eq 2 ] || usage
  local_xcf="$2"
  [ -d "$local_xcf" ] || { echo "no xcframework at $local_xcf" >&2; exit 1; }
fi
[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-+].*)?$ ]] || { echo "version must be semver, got $version" >&2; exit 1; }
if [ -z "$local_xcf" ]; then
  [[ "$url" == https://* ]] || { echo "the xcframework url must be https://" >&2; exit 1; }
  [[ "$checksum" =~ ^[0-9a-f]{64}$ ]] || { echo "checksum must be the 64-hex swift package compute-checksum" >&2; exit 1; }
fi

pkg="$(cd "$(dirname "$0")/.." && pwd)"
repo="$(cd "$pkg/../.." && pwd)"

rm -rf "$outdir"
mkdir -p "$outdir/Sources"
for target in ExponentialUICore ExponentialUI ExponentialUIPrimitives; do
  cp -R "$pkg/Sources/$target" "$outdir/Sources/$target"
done
cp "$repo/LICENSE" "$repo/NOTICE" "$outdir/"

if [ -n "$local_xcf" ]; then
  mkdir -p "$outdir/Binaries"
  cp -R "$local_xcf" "$outdir/Binaries/ExponentialUIFFI.xcframework"
  binary='.binaryTarget(name: "ExponentialUIFFI", path: "Binaries/ExponentialUIFFI.xcframework")'
else
  binary=".binaryTarget(name: \"ExponentialUIFFI\", url: \"$url\", checksum: \"$checksum\")"
fi

cat > "$outdir/Package.swift" <<SWIFT
// swift-tools-version: 5.10
// ExponentialUI $version: the SwiftUI renderer of the Exponential UI SDK
// (https://ui.exponential.at). GENERATED by release/make-release-package.sh
// from packages/exponential-ui-swift; do not edit here.
import PackageDescription

let package = Package(
    name: "ExponentialUI",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "ExponentialUI", targets: ["ExponentialUI"]),
        .library(name: "ExponentialUIPrimitives", targets: ["ExponentialUIPrimitives"]),
    ],
    targets: [
        // The Rust core behind its UniFFI facade (iOS device + simulator + macOS).
        $binary,
        .target(name: "ExponentialUICore", dependencies: ["ExponentialUIFFI"]),
        .target(name: "ExponentialUIPrimitives"),
        .target(name: "ExponentialUI", dependencies: ["ExponentialUICore", "ExponentialUIPrimitives"]),
    ]
)
SWIFT

cat > "$outdir/README.md" <<MD
# ExponentialUI $version

The SwiftUI renderer of the Exponential UI SDK: A2UI surfaces streamed from
any server, painted natively on iOS 17+ and macOS 14+ at the frames the Rust
core computes. Docs, the catalog, themes and the host API:
**https://ui.exponential.at**.

\`\`\`swift
// Package.swift
.package(url: "<this repository>", from: "$version")
// target
.product(name: "ExponentialUI", package: "ExponentialUI")
\`\`\`

\`\`\`swift
import ExponentialUI

let host = ExponentialHost(HostOptions(transport: JSONLStreamTransport(url: URL(string: "https://example.com/a2ui.jsonl")!)))
host.connect()
// in a view
ScrollView { HostSurface(host: host, surfaceId: "main") }
\`\`\`

| product | what |
|---|---|
| \`ExponentialUI\` | the painter + the host API (\`ExponentialHost\`, transports, \`HostSurface\`) |
| \`ExponentialUIPrimitives\` | the generic SwiftUI primitives the catalog natives are painted with |

Licence: see LICENSE and NOTICE. Generated from the Exponential monorepo
(\`packages/exponential-ui-swift\`); issues and changes go there.
MD

echo "wrote $outdir ($( [ -n "$local_xcf" ] && echo "local path binary" || echo "$url" ))"
