#!/usr/bin/env bun
// Emits the canonical design tokens from tokens.json into native sources.
// Run from the repo root with: `bun run --filter @exp/design-tokens generate`.
//
// The `palette` colors are authored in OKLCH (verbatim from the web theme in
// apps/web/src/styles.css) and converted to sRGB hex here, so the native
// palette is derived — never hand-transcribed — from the web source of truth.
// Currently wired: Android (Compose). iOS/macOS (SwiftUI) ships in the Mac
// handoff phase; Linux GTK already carries the matching theme.

import { writeFileSync, readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const repoRoot = join(__dirname, "..", "..", "..")

interface Tokens {
  palette: Record<string, string>
  semantic: Record<string, string>
  radius: Record<string, number>
  size: Record<string, number>
  type: { fontFamily: string; baseSize: number }
}

const tokens: Tokens = JSON.parse(
  readFileSync(join(__dirname, "..", "tokens.json"), "utf8")
)

// ── Color conversion ───────────────────────────────────────────────────────

interface Rgba {
  r: number
  g: number
  b: number
  a: number
} // each 0–255

function srgbGamma(linear: number): number {
  const c = Math.max(0, Math.min(1, linear))
  return c <= 0.0031308 ? 12.92 * c : 1.055 * Math.pow(c, 1 / 2.4) - 0.055
}

// OKLCH → linear OKLab → linear sRGB → gamma sRGB (Björn Ottosson's matrices).
function oklchToRgb(
  L: number,
  C: number,
  hDeg: number
): [number, number, number] {
  const h = (hDeg * Math.PI) / 180
  const a = C * Math.cos(h)
  const b = C * Math.sin(h)

  const l_ = L + 0.3963377774 * a + 0.2158037573 * b
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b
  const s_ = L - 0.0894841775 * a - 1.291485548 * b

  const l = l_ * l_ * l_
  const m = m_ * m_ * m_
  const s = s_ * s_ * s_

  const r = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
  const g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
  const bl = -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s

  return [srgbGamma(r), srgbGamma(g), srgbGamma(bl)]
}

function to255(unit: number): number {
  return Math.round(Math.max(0, Math.min(1, unit)) * 255)
}

function parseColor(input: string): Rgba {
  const s = input.trim()

  if (s.startsWith(`#`)) {
    const hex = s.slice(1)
    const r = parseInt(hex.slice(0, 2), 16)
    const g = parseInt(hex.slice(2, 4), 16)
    const b = parseInt(hex.slice(4, 6), 16)
    const a = hex.length >= 8 ? parseInt(hex.slice(6, 8), 16) : 255
    return { r, g, b, a }
  }

  const m = s.match(
    /^oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*(?:\/\s*([\d.]+)(%?)\s*)?\)$/
  )
  if (!m) throw new Error(`Unparseable color: ${input}`)
  const L = parseFloat(m[1])
  const C = parseFloat(m[2])
  const H = parseFloat(m[3])
  let a = 255
  if (m[4] !== undefined) {
    const raw = parseFloat(m[4])
    a = to255(m[5] === `%` ? raw / 100 : raw)
  }
  const [r, g, b] = oklchToRgb(L, C, H)
  return { r: to255(r), g: to255(g), b: to255(b), a }
}

function byte(n: number): string {
  return n.toString(16).toUpperCase().padStart(2, `0`)
}

// Compose Color literal: 0xAARRGGBB.
function kotlinColor(input: string): string {
  const { r, g, b, a } = parseColor(input)
  return `Color(0x${byte(a)}${byte(r)}${byte(g)}${byte(b)})`
}

// ── Emit helpers ─────────────────────────────────────────────────────────────

function pascalCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

const HEADER_KOTLIN = `// AUTO-GENERATED by packages/design-tokens/scripts/generate.ts — do not edit.
// Single source of truth: packages/design-tokens/tokens.json.
`

function emitKotlin(): string {
  const palette = Object.entries(tokens.palette)
    .filter(([k]) => !k.startsWith(`$`))
    .map(([k, v]) => `        val ${pascalCase(k)}: Color = ${kotlinColor(v)}`)
    .join(`\n`)
  const semantic = Object.entries(tokens.semantic)
    .filter(([k]) => !k.startsWith(`$`))
    .map(([k, v]) => `        val ${pascalCase(k)}: Color = ${kotlinColor(v)}`)
    .join(`\n`)
  const radius = Object.entries(tokens.radius)
    .filter(([k]) => !k.startsWith(`$`))
    .map(([k, v]) => `        val ${pascalCase(k)}: Dp = ${v}.dp`)
    .join(`\n`)
  const size = Object.entries(tokens.size)
    .filter(([k]) => !k.startsWith(`$`))
    .map(([k, v]) => `        val ${pascalCase(k)}: Dp = ${v}.dp`)
    .join(`\n`)

  return `${HEADER_KOTLIN}
package com.exponential.app.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object DesignTokens {
    // Forced-dark surface palette, derived from the web OKLCH theme.
    object Palette {
${palette}
    }

    // Fixed brand accents (status / priority / due-date / agent-plan).
    object Semantic {
${semantic}
    }

    // Corner radii (px ≡ dp), matching the web rounded-* scale.
    object Radius {
${radius}
    }

    // Control geometry, matching the web control heights.
    object Size {
${size}
    }
}
`
}

const kotlinPath = join(
  repoRoot,
  `apps/android/app/src/main/java/com/exponential/app/ui/theme/DesignTokens.generated.kt`
)

writeFileSync(kotlinPath, emitKotlin())

// eslint-disable-next-line no-console
console.log(`design-tokens: wrote ${kotlinPath}`)
