// AUTO-GENERATED by packages/domain-contract/scripts/generate.ts — do not edit.
// Single source of truth: packages/domain-contract/contract.json.

pub const issue_status_values = [_][]const u8{ "backlog", "todo", "in_progress", "done", "cancelled" };
pub const issue_status_display_order = [_][]const u8{ "in_progress", "todo", "backlog", "done", "cancelled" };
pub const issue_priority_values = [_][]const u8{ "none", "urgent", "high", "medium", "low" };
pub const issue_priority_display_order = [_][]const u8{ "urgent", "high", "medium", "low", "none" };
pub const recurrence_unit_values = [_][]const u8{ "day", "week", "month" };
pub const workspace_role_values = [_][]const u8{ "owner", "member", "agent" };
pub const public_write_policy_values = [_][]const u8{ "members", "everyone" };
pub const comment_kind_values = [_][]const u8{ "regular", "question", "plan" };
pub const recurrence_intervals = [_]i32{ 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 21, 30 };

pub const workspace_role_owner: []const u8 = "owner";
pub const workspace_role_member: []const u8 = "member";
pub const workspace_role_agent: []const u8 = "agent";
pub const public_write_policy_members: []const u8 = "members";
pub const public_write_policy_everyone: []const u8 = "everyone";
pub const comment_kind_regular: []const u8 = "regular";
pub const comment_kind_question: []const u8 = "question";
pub const comment_kind_plan: []const u8 = "plan";
