/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WSplatRouteImport } from './routes/w/$'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthConsentRouteImport } from './routes/auth/consent'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiMobileOauthStartRouteImport } from './routes/api/mobile-oauth-start'
import { Route as ApiMobileOauthReturnRouteImport } from './routes/api/mobile-oauth-return'
import { Route as ApiMobileOauthExchangeRouteImport } from './routes/api/mobile-oauth-exchange'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiAuthConfigRouteImport } from './routes/api/auth-config'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotwellKnownChar93OauthAuthorizationServerRouteImport } from './routes/[.well-known]/oauth-authorization-server'
import { Route as Char91DotwellKnownChar93AssetlinksChar91DotChar93jsonRouteImport } from './routes/[.well-known]/assetlinks[.]json'
import { Route as Char91DotwellKnownChar93AppleAppSiteAssociationRouteImport } from './routes/[.well-known]/apple-app-site-association'
import { Route as TWorkspaceSlugRouteRouteImport } from './routes/t/$workspaceSlug/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as TWorkspaceSlugIndexRouteImport } from './routes/t/$workspaceSlug/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiWidgetSubmitRouteImport } from './routes/api/widget/submit'
import { Route as ApiWidgetConfigRouteImport } from './routes/api/widget/config'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api/webhooks/github'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiShapesWorkspacesRouteImport } from './routes/api/shapes/workspaces'
import { Route as ApiShapesWorkspaceMembersRouteImport } from './routes/api/shapes/workspace-members'
import { Route as ApiShapesWorkspaceInvitesRouteImport } from './routes/api/shapes/workspace-invites'
import { Route as ApiShapesUsersRouteImport } from './routes/api/shapes/users'
import { Route as ApiShapesProjectsRouteImport } from './routes/api/shapes/projects'
import { Route as ApiShapesNotificationsRouteImport } from './routes/api/shapes/notifications'
import { Route as ApiShapesLabelsRouteImport } from './routes/api/shapes/labels'
import { Route as ApiShapesIssuesRouteImport } from './routes/api/shapes/issues'
import { Route as ApiShapesIssueSubscribersRouteImport } from './routes/api/shapes/issue-subscribers'
import { Route as ApiShapesIssueLabelsRouteImport } from './routes/api/shapes/issue-labels'
import { Route as ApiShapesIssueEventsRouteImport } from './routes/api/shapes/issue-events'
import { Route as ApiShapesCommentsRouteImport } from './routes/api/shapes/comments'
import { Route as ApiShapesCodingSessionsRouteImport } from './routes/api/shapes/coding-sessions'
import { Route as ApiShapesAttachmentsRouteImport } from './routes/api/shapes/attachments'
import { Route as ApiEmailUnsubscribeRouteImport } from './routes/api/email/unsubscribe'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAttachmentsAttachmentIdRouteImport } from './routes/api/attachments/$attachmentId'
import { Route as AuthenticatedAdminWorkspacesRouteImport } from './routes/_authenticated/admin/workspaces'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAccountNotificationsRouteImport } from './routes/_authenticated/account/notifications'
import { Route as TWorkspaceSlugSettingsIndexRouteImport } from './routes/t/$workspaceSlug/settings/index'
import { Route as TWorkspaceSlugReviewsIndexRouteImport } from './routes/t/$workspaceSlug/reviews/index'
import { Route as TWorkspaceSlugMyIssuesIndexRouteImport } from './routes/t/$workspaceSlug/my-issues/index'
import { Route as TWorkspaceSlugInboxIndexRouteImport } from './routes/t/$workspaceSlug/inbox/index'
import { Route as TWorkspaceSlugAgentsIndexRouteImport } from './routes/t/$workspaceSlug/agents/index'
import { Route as ApiIssuesIssueIdImagesRouteImport } from './routes/api/issues/$issueId/images'
import { Route as ApiIntegrationsGithubSetupRouteImport } from './routes/api/integrations/github/setup'
import { Route as ApiIntegrationsGithubCallbackRouteImport } from './routes/api/integrations/github/callback'
import { Route as AuthenticatedIntegrationsGithubInstalledRouteImport } from './routes/_authenticated/integrations/github/installed'
import { Route as AuthenticatedIntegrationsGithubClaimRouteImport } from './routes/_authenticated/integrations/github/claim'
import { Route as AuthenticatedAdminWorkspacesWorkspaceIdRouteImport } from './routes/_authenticated/admin/workspaces_.$workspaceId'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users_.$userId'
import { Route as TWorkspaceSlugProjectsProjectSlugIndexRouteImport } from './routes/t/$workspaceSlug/projects/$projectSlug/index'
import { Route as TWorkspaceSlugProjectsProjectSlugIssuesIssueIdentifierRouteImport } from './routes/t/$workspaceSlug/projects/$projectSlug/issues/$issueIdentifier'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WSplatRoute = WSplatRouteImport.update({
  id: '/w/$',
  path: '/w/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConsentRoute = AuthConsentRouteImport.update({
  id: '/auth/consent',
  path: '/auth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileOauthStartRoute = ApiMobileOauthStartRouteImport.update({
  id: '/api/mobile-oauth-start',
  path: '/api/mobile-oauth-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileOauthReturnRoute = ApiMobileOauthReturnRouteImport.update({
  id: '/api/mobile-oauth-return',
  path: '/api/mobile-oauth-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileOauthExchangeRoute = ApiMobileOauthExchangeRouteImport.update({
  id: '/api/mobile-oauth-exchange',
  path: '/api/mobile-oauth-exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConfigRoute = ApiAuthConfigRouteImport.update({
  id: '/api/auth-config',
  path: '/api/auth-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthAuthorizationServerRoute =
  Char91DotwellKnownChar93OauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93AssetlinksChar91DotChar93jsonRoute =
  Char91DotwellKnownChar93AssetlinksChar91DotChar93jsonRouteImport.update({
    id: '/.well-known/assetlinks.json',
    path: '/.well-known/assetlinks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93AppleAppSiteAssociationRoute =
  Char91DotwellKnownChar93AppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const TWorkspaceSlugRouteRoute = TWorkspaceSlugRouteRouteImport.update({
  id: '/t/$workspaceSlug',
  path: '/t/$workspaceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TWorkspaceSlugIndexRoute = TWorkspaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TWorkspaceSlugRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiWidgetSubmitRoute = ApiWidgetSubmitRouteImport.update({
  id: '/api/widget/submit',
  path: '/api/widget/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetConfigRoute = ApiWidgetConfigRouteImport.update({
  id: '/api/widget/config',
  path: '/api/widget/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesWorkspacesRoute = ApiShapesWorkspacesRouteImport.update({
  id: '/api/shapes/workspaces',
  path: '/api/shapes/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesWorkspaceMembersRoute =
  ApiShapesWorkspaceMembersRouteImport.update({
    id: '/api/shapes/workspace-members',
    path: '/api/shapes/workspace-members',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShapesWorkspaceInvitesRoute =
  ApiShapesWorkspaceInvitesRouteImport.update({
    id: '/api/shapes/workspace-invites',
    path: '/api/shapes/workspace-invites',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShapesUsersRoute = ApiShapesUsersRouteImport.update({
  id: '/api/shapes/users',
  path: '/api/shapes/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesProjectsRoute = ApiShapesProjectsRouteImport.update({
  id: '/api/shapes/projects',
  path: '/api/shapes/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesNotificationsRoute = ApiShapesNotificationsRouteImport.update({
  id: '/api/shapes/notifications',
  path: '/api/shapes/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesLabelsRoute = ApiShapesLabelsRouteImport.update({
  id: '/api/shapes/labels',
  path: '/api/shapes/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesIssuesRoute = ApiShapesIssuesRouteImport.update({
  id: '/api/shapes/issues',
  path: '/api/shapes/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesIssueSubscribersRoute =
  ApiShapesIssueSubscribersRouteImport.update({
    id: '/api/shapes/issue-subscribers',
    path: '/api/shapes/issue-subscribers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShapesIssueLabelsRoute = ApiShapesIssueLabelsRouteImport.update({
  id: '/api/shapes/issue-labels',
  path: '/api/shapes/issue-labels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesIssueEventsRoute = ApiShapesIssueEventsRouteImport.update({
  id: '/api/shapes/issue-events',
  path: '/api/shapes/issue-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesCommentsRoute = ApiShapesCommentsRouteImport.update({
  id: '/api/shapes/comments',
  path: '/api/shapes/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesCodingSessionsRoute = ApiShapesCodingSessionsRouteImport.update({
  id: '/api/shapes/coding-sessions',
  path: '/api/shapes/coding-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesAttachmentsRoute = ApiShapesAttachmentsRouteImport.update({
  id: '/api/shapes/attachments',
  path: '/api/shapes/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailUnsubscribeRoute = ApiEmailUnsubscribeRouteImport.update({
  id: '/api/email/unsubscribe',
  path: '/api/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsAttachmentIdRoute =
  ApiAttachmentsAttachmentIdRouteImport.update({
    id: '/api/attachments/$attachmentId',
    path: '/api/attachments/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminWorkspacesRoute =
  AuthenticatedAdminWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAccountNotificationsRoute =
  AuthenticatedAccountNotificationsRouteImport.update({
    id: '/account/notifications',
    path: '/account/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const TWorkspaceSlugSettingsIndexRoute =
  TWorkspaceSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => TWorkspaceSlugRouteRoute,
  } as any)
const TWorkspaceSlugReviewsIndexRoute =
  TWorkspaceSlugReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => TWorkspaceSlugRouteRoute,
  } as any)
const TWorkspaceSlugMyIssuesIndexRoute =
  TWorkspaceSlugMyIssuesIndexRouteImport.update({
    id: '/my-issues/',
    path: '/my-issues/',
    getParentRoute: () => TWorkspaceSlugRouteRoute,
  } as any)
const TWorkspaceSlugInboxIndexRoute =
  TWorkspaceSlugInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => TWorkspaceSlugRouteRoute,
  } as any)
const TWorkspaceSlugAgentsIndexRoute =
  TWorkspaceSlugAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => TWorkspaceSlugRouteRoute,
  } as any)
const ApiIssuesIssueIdImagesRoute = ApiIssuesIssueIdImagesRouteImport.update({
  id: '/api/issues/$issueId/images',
  path: '/api/issues/$issueId/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsGithubSetupRoute =
  ApiIntegrationsGithubSetupRouteImport.update({
    id: '/api/integrations/github/setup',
    path: '/api/integrations/github/setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGithubCallbackRoute =
  ApiIntegrationsGithubCallbackRouteImport.update({
    id: '/api/integrations/github/callback',
    path: '/api/integrations/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedIntegrationsGithubInstalledRoute =
  AuthenticatedIntegrationsGithubInstalledRouteImport.update({
    id: '/integrations/github/installed',
    path: '/integrations/github/installed',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsGithubClaimRoute =
  AuthenticatedIntegrationsGithubClaimRouteImport.update({
    id: '/integrations/github/claim',
    path: '/integrations/github/claim',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkspacesWorkspaceIdRoute =
  AuthenticatedAdminWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces_/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users_/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const TWorkspaceSlugProjectsProjectSlugIndexRoute =
  TWorkspaceSlugProjectsProjectSlugIndexRouteImport.update({
    id: '/projects/$projectSlug/',
    path: '/projects/$projectSlug/',
    getParentRoute: () => TWorkspaceSlugRouteRoute,
  } as any)
const TWorkspaceSlugProjectsProjectSlugIssuesIssueIdentifierRoute =
  TWorkspaceSlugProjectsProjectSlugIssuesIssueIdentifierRouteImport.update({
    id: '/projects/$projectSlug/issues/$issueIdentifier',
    path: '/projects/$projectSlug/issues/$issueIdentifier',
    getParentRoute: () => TWorkspaceSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/t/$workspaceSlug': typeof TWorkspaceSlugRouteRouteWithChildren
  '/.well-known/apple-app-site-association': typeof Char91DotwellKnownChar93AppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof Char91DotwellKnownChar93AssetlinksChar91DotChar93jsonRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/auth-config': typeof ApiAuthConfigRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/mobile-oauth-exchange': typeof ApiMobileOauthExchangeRoute
  '/api/mobile-oauth-return': typeof ApiMobileOauthReturnRoute
  '/api/mobile-oauth-start': typeof ApiMobileOauthStartRoute
  '/api/version': typeof ApiVersionRoute
  '/auth/consent': typeof AuthConsentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/w/$': typeof WSplatRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/email/unsubscribe': typeof ApiEmailUnsubscribeRoute
  '/api/shapes/attachments': typeof ApiShapesAttachmentsRoute
  '/api/shapes/coding-sessions': typeof ApiShapesCodingSessionsRoute
  '/api/shapes/comments': typeof ApiShapesCommentsRoute
  '/api/shapes/issue-events': typeof ApiShapesIssueEventsRoute
  '/api/shapes/issue-labels': typeof ApiShapesIssueLabelsRoute
  '/api/shapes/issue-subscribers': typeof ApiShapesIssueSubscribersRoute
  '/api/shapes/issues': typeof ApiShapesIssuesRoute
  '/api/shapes/labels': typeof ApiShapesLabelsRoute
  '/api/shapes/notifications': typeof ApiShapesNotificationsRoute
  '/api/shapes/projects': typeof ApiShapesProjectsRoute
  '/api/shapes/users': typeof ApiShapesUsersRoute
  '/api/shapes/workspace-invites': typeof ApiShapesWorkspaceInvitesRoute
  '/api/shapes/workspace-members': typeof ApiShapesWorkspaceMembersRoute
  '/api/shapes/workspaces': typeof ApiShapesWorkspacesRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/widget/config': typeof ApiWidgetConfigRoute
  '/api/widget/submit': typeof ApiWidgetSubmitRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/t/$workspaceSlug/': typeof TWorkspaceSlugIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/admin/workspaces/$workspaceId': typeof AuthenticatedAdminWorkspacesWorkspaceIdRoute
  '/integrations/github/claim': typeof AuthenticatedIntegrationsGithubClaimRoute
  '/integrations/github/installed': typeof AuthenticatedIntegrationsGithubInstalledRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/github/setup': typeof ApiIntegrationsGithubSetupRoute
  '/api/issues/$issueId/images': typeof ApiIssuesIssueIdImagesRoute
  '/t/$workspaceSlug/agents/': typeof TWorkspaceSlugAgentsIndexRoute
  '/t/$workspaceSlug/inbox/': typeof TWorkspaceSlugInboxIndexRoute
  '/t/$workspaceSlug/my-issues/': typeof TWorkspaceSlugMyIssuesIndexRoute
  '/t/$workspaceSlug/reviews/': typeof TWorkspaceSlugReviewsIndexRoute
  '/t/$workspaceSlug/settings/': typeof TWorkspaceSlugSettingsIndexRoute
  '/t/$workspaceSlug/projects/$projectSlug/': typeof TWorkspaceSlugProjectsProjectSlugIndexRoute
  '/t/$workspaceSlug/projects/$projectSlug/issues/$issueIdentifier': typeof TWorkspaceSlugProjectsProjectSlugIssuesIssueIdentifierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/apple-app-site-association': typeof Char91DotwellKnownChar93AppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof Char91DotwellKnownChar93AssetlinksChar91DotChar93jsonRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/auth-config': typeof ApiAuthConfigRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/mobile-oauth-exchange': typeof ApiMobileOauthExchangeRoute
  '/api/mobile-oauth-return': typeof ApiMobileOauthReturnRoute
  '/api/mobile-oauth-start': typeof ApiMobileOauthStartRoute
  '/api/version': typeof ApiVersionRoute
  '/auth/consent': typeof AuthConsentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/w/$': typeof WSplatRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/email/unsubscribe': typeof ApiEmailUnsubscribeRoute
  '/api/shapes/attachments': typeof ApiShapesAttachmentsRoute
  '/api/shapes/coding-sessions': typeof ApiShapesCodingSessionsRoute
  '/api/shapes/comments': typeof ApiShapesCommentsRoute
  '/api/shapes/issue-events': typeof ApiShapesIssueEventsRoute
  '/api/shapes/issue-labels': typeof ApiShapesIssueLabelsRoute
  '/api/shapes/issue-subscribers': typeof ApiShapesIssueSubscribersRoute
  '/api/shapes/issues': typeof ApiShapesIssuesRoute
  '/api/shapes/labels': typeof ApiShapesLabelsRoute
  '/api/shapes/notifications': typeof ApiShapesNotificationsRoute
  '/api/shapes/projects': typeof ApiShapesProjectsRoute
  '/api/shapes/users': typeof ApiShapesUsersRoute
  '/api/shapes/workspace-invites': typeof ApiShapesWorkspaceInvitesRoute
  '/api/shapes/workspace-members': typeof ApiShapesWorkspaceMembersRoute
  '/api/shapes/workspaces': typeof ApiShapesWorkspacesRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/widget/config': typeof ApiWidgetConfigRoute
  '/api/widget/submit': typeof ApiWidgetSubmitRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/t/$workspaceSlug': typeof TWorkspaceSlugIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/admin/workspaces/$workspaceId': typeof AuthenticatedAdminWorkspacesWorkspaceIdRoute
  '/integrations/github/claim': typeof AuthenticatedIntegrationsGithubClaimRoute
  '/integrations/github/installed': typeof AuthenticatedIntegrationsGithubInstalledRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/github/setup': typeof ApiIntegrationsGithubSetupRoute
  '/api/issues/$issueId/images': typeof ApiIssuesIssueIdImagesRoute
  '/t/$workspaceSlug/agents': typeof TWorkspaceSlugAgentsIndexRoute
  '/t/$workspaceSlug/inbox': typeof TWorkspaceSlugInboxIndexRoute
  '/t/$workspaceSlug/my-issues': typeof TWorkspaceSlugMyIssuesIndexRoute
  '/t/$workspaceSlug/reviews': typeof TWorkspaceSlugReviewsIndexRoute
  '/t/$workspaceSlug/settings': typeof TWorkspaceSlugSettingsIndexRoute
  '/t/$workspaceSlug/projects/$projectSlug': typeof TWorkspaceSlugProjectsProjectSlugIndexRoute
  '/t/$workspaceSlug/projects/$projectSlug/issues/$issueIdentifier': typeof TWorkspaceSlugProjectsProjectSlugIssuesIssueIdentifierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/t/$workspaceSlug': typeof TWorkspaceSlugRouteRouteWithChildren
  '/.well-known/apple-app-site-association': typeof Char91DotwellKnownChar93AppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof Char91DotwellKnownChar93AssetlinksChar91DotChar93jsonRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/auth-config': typeof ApiAuthConfigRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/mobile-oauth-exchange': typeof ApiMobileOauthExchangeRoute
  '/api/mobile-oauth-return': typeof ApiMobileOauthReturnRoute
  '/api/mobile-oauth-start': typeof ApiMobileOauthStartRoute
  '/api/version': typeof ApiVersionRoute
  '/auth/consent': typeof AuthConsentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/w/$': typeof WSplatRoute
  '/_authenticated/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/email/unsubscribe': typeof ApiEmailUnsubscribeRoute
  '/api/shapes/attachments': typeof ApiShapesAttachmentsRoute
  '/api/shapes/coding-sessions': typeof ApiShapesCodingSessionsRoute
  '/api/shapes/comments': typeof ApiShapesCommentsRoute
  '/api/shapes/issue-events': typeof ApiShapesIssueEventsRoute
  '/api/shapes/issue-labels': typeof ApiShapesIssueLabelsRoute
  '/api/shapes/issue-subscribers': typeof ApiShapesIssueSubscribersRoute
  '/api/shapes/issues': typeof ApiShapesIssuesRoute
  '/api/shapes/labels': typeof ApiShapesLabelsRoute
  '/api/shapes/notifications': typeof ApiShapesNotificationsRoute
  '/api/shapes/projects': typeof ApiShapesProjectsRoute
  '/api/shapes/users': typeof ApiShapesUsersRoute
  '/api/shapes/workspace-invites': typeof ApiShapesWorkspaceInvitesRoute
  '/api/shapes/workspace-members': typeof ApiShapesWorkspaceMembersRoute
  '/api/shapes/workspaces': typeof ApiShapesWorkspacesRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/widget/config': typeof ApiWidgetConfigRoute
  '/api/widget/submit': typeof ApiWidgetSubmitRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/t/$workspaceSlug/': typeof TWorkspaceSlugIndexRoute
  '/_authenticated/admin/users_/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/admin/workspaces_/$workspaceId': typeof AuthenticatedAdminWorkspacesWorkspaceIdRoute
  '/_authenticated/integrations/github/claim': typeof AuthenticatedIntegrationsGithubClaimRoute
  '/_authenticated/integrations/github/installed': typeof AuthenticatedIntegrationsGithubInstalledRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/github/setup': typeof ApiIntegrationsGithubSetupRoute
  '/api/issues/$issueId/images': typeof ApiIssuesIssueIdImagesRoute
  '/t/$workspaceSlug/agents/': typeof TWorkspaceSlugAgentsIndexRoute
  '/t/$workspaceSlug/inbox/': typeof TWorkspaceSlugInboxIndexRoute
  '/t/$workspaceSlug/my-issues/': typeof TWorkspaceSlugMyIssuesIndexRoute
  '/t/$workspaceSlug/reviews/': typeof TWorkspaceSlugReviewsIndexRoute
  '/t/$workspaceSlug/settings/': typeof TWorkspaceSlugSettingsIndexRoute
  '/t/$workspaceSlug/projects/$projectSlug/': typeof TWorkspaceSlugProjectsProjectSlugIndexRoute
  '/t/$workspaceSlug/projects/$projectSlug/issues/$issueIdentifier': typeof TWorkspaceSlugProjectsProjectSlugIssuesIssueIdentifierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/t/$workspaceSlug'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/feedback'
    | '/onboarding'
    | '/api/auth-config'
    | '/api/contact'
    | '/api/health'
    | '/api/mcp'
    | '/api/mobile-oauth-exchange'
    | '/api/mobile-oauth-return'
    | '/api/mobile-oauth-start'
    | '/api/version'
    | '/auth/consent'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/w/$'
    | '/account/notifications'
    | '/admin/users'
    | '/admin/workspaces'
    | '/api/attachments/$attachmentId'
    | '/api/auth/$'
    | '/api/email/unsubscribe'
    | '/api/shapes/attachments'
    | '/api/shapes/coding-sessions'
    | '/api/shapes/comments'
    | '/api/shapes/issue-events'
    | '/api/shapes/issue-labels'
    | '/api/shapes/issue-subscribers'
    | '/api/shapes/issues'
    | '/api/shapes/labels'
    | '/api/shapes/notifications'
    | '/api/shapes/projects'
    | '/api/shapes/users'
    | '/api/shapes/workspace-invites'
    | '/api/shapes/workspace-members'
    | '/api/shapes/workspaces'
    | '/api/trpc/$'
    | '/api/webhooks/github'
    | '/api/widget/config'
    | '/api/widget/submit'
    | '/admin/'
    | '/t/$workspaceSlug/'
    | '/admin/users/$userId'
    | '/admin/workspaces/$workspaceId'
    | '/integrations/github/claim'
    | '/integrations/github/installed'
    | '/api/integrations/github/callback'
    | '/api/integrations/github/setup'
    | '/api/issues/$issueId/images'
    | '/t/$workspaceSlug/agents/'
    | '/t/$workspaceSlug/inbox/'
    | '/t/$workspaceSlug/my-issues/'
    | '/t/$workspaceSlug/reviews/'
    | '/t/$workspaceSlug/settings/'
    | '/t/$workspaceSlug/projects/$projectSlug/'
    | '/t/$workspaceSlug/projects/$projectSlug/issues/$issueIdentifier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/feedback'
    | '/onboarding'
    | '/api/auth-config'
    | '/api/contact'
    | '/api/health'
    | '/api/mcp'
    | '/api/mobile-oauth-exchange'
    | '/api/mobile-oauth-return'
    | '/api/mobile-oauth-start'
    | '/api/version'
    | '/auth/consent'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/w/$'
    | '/account/notifications'
    | '/admin/users'
    | '/admin/workspaces'
    | '/api/attachments/$attachmentId'
    | '/api/auth/$'
    | '/api/email/unsubscribe'
    | '/api/shapes/attachments'
    | '/api/shapes/coding-sessions'
    | '/api/shapes/comments'
    | '/api/shapes/issue-events'
    | '/api/shapes/issue-labels'
    | '/api/shapes/issue-subscribers'
    | '/api/shapes/issues'
    | '/api/shapes/labels'
    | '/api/shapes/notifications'
    | '/api/shapes/projects'
    | '/api/shapes/users'
    | '/api/shapes/workspace-invites'
    | '/api/shapes/workspace-members'
    | '/api/shapes/workspaces'
    | '/api/trpc/$'
    | '/api/webhooks/github'
    | '/api/widget/config'
    | '/api/widget/submit'
    | '/admin'
    | '/t/$workspaceSlug'
    | '/admin/users/$userId'
    | '/admin/workspaces/$workspaceId'
    | '/integrations/github/claim'
    | '/integrations/github/installed'
    | '/api/integrations/github/callback'
    | '/api/integrations/github/setup'
    | '/api/issues/$issueId/images'
    | '/t/$workspaceSlug/agents'
    | '/t/$workspaceSlug/inbox'
    | '/t/$workspaceSlug/my-issues'
    | '/t/$workspaceSlug/reviews'
    | '/t/$workspaceSlug/settings'
    | '/t/$workspaceSlug/projects/$projectSlug'
    | '/t/$workspaceSlug/projects/$projectSlug/issues/$issueIdentifier'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/t/$workspaceSlug'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/feedback'
    | '/_authenticated/onboarding'
    | '/api/auth-config'
    | '/api/contact'
    | '/api/health'
    | '/api/mcp'
    | '/api/mobile-oauth-exchange'
    | '/api/mobile-oauth-return'
    | '/api/mobile-oauth-start'
    | '/api/version'
    | '/auth/consent'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/w/$'
    | '/_authenticated/account/notifications'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/workspaces'
    | '/api/attachments/$attachmentId'
    | '/api/auth/$'
    | '/api/email/unsubscribe'
    | '/api/shapes/attachments'
    | '/api/shapes/coding-sessions'
    | '/api/shapes/comments'
    | '/api/shapes/issue-events'
    | '/api/shapes/issue-labels'
    | '/api/shapes/issue-subscribers'
    | '/api/shapes/issues'
    | '/api/shapes/labels'
    | '/api/shapes/notifications'
    | '/api/shapes/projects'
    | '/api/shapes/users'
    | '/api/shapes/workspace-invites'
    | '/api/shapes/workspace-members'
    | '/api/shapes/workspaces'
    | '/api/trpc/$'
    | '/api/webhooks/github'
    | '/api/widget/config'
    | '/api/widget/submit'
    | '/_authenticated/admin/'
    | '/t/$workspaceSlug/'
    | '/_authenticated/admin/users_/$userId'
    | '/_authenticated/admin/workspaces_/$workspaceId'
    | '/_authenticated/integrations/github/claim'
    | '/_authenticated/integrations/github/installed'
    | '/api/integrations/github/callback'
    | '/api/integrations/github/setup'
    | '/api/issues/$issueId/images'
    | '/t/$workspaceSlug/agents/'
    | '/t/$workspaceSlug/inbox/'
    | '/t/$workspaceSlug/my-issues/'
    | '/t/$workspaceSlug/reviews/'
    | '/t/$workspaceSlug/settings/'
    | '/t/$workspaceSlug/projects/$projectSlug/'
    | '/t/$workspaceSlug/projects/$projectSlug/issues/$issueIdentifier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TWorkspaceSlugRouteRoute: typeof TWorkspaceSlugRouteRouteWithChildren
  Char91DotwellKnownChar93AppleAppSiteAssociationRoute: typeof Char91DotwellKnownChar93AppleAppSiteAssociationRoute
  Char91DotwellKnownChar93AssetlinksChar91DotChar93jsonRoute: typeof Char91DotwellKnownChar93AssetlinksChar91DotChar93jsonRoute
  Char91DotwellKnownChar93OauthAuthorizationServerRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAuthConfigRoute: typeof ApiAuthConfigRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiMobileOauthExchangeRoute: typeof ApiMobileOauthExchangeRoute
  ApiMobileOauthReturnRoute: typeof ApiMobileOauthReturnRoute
  ApiMobileOauthStartRoute: typeof ApiMobileOauthStartRoute
  ApiVersionRoute: typeof ApiVersionRoute
  AuthConsentRoute: typeof AuthConsentRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  WSplatRoute: typeof WSplatRoute
  ApiAttachmentsAttachmentIdRoute: typeof ApiAttachmentsAttachmentIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEmailUnsubscribeRoute: typeof ApiEmailUnsubscribeRoute
  ApiShapesAttachmentsRoute: typeof ApiShapesAttachmentsRoute
  ApiShapesCodingSessionsRoute: typeof ApiShapesCodingSessionsRoute
  ApiShapesCommentsRoute: typeof ApiShapesCommentsRoute
  ApiShapesIssueEventsRoute: typeof ApiShapesIssueEventsRoute
  ApiShapesIssueLabelsRoute: typeof ApiShapesIssueLabelsRoute
  ApiShapesIssueSubscribersRoute: typeof ApiShapesIssueSubscribersRoute
  ApiShapesIssuesRoute: typeof ApiShapesIssuesRoute
  ApiShapesLabelsRoute: typeof ApiShapesLabelsRoute
  ApiShapesNotificationsRoute: typeof ApiShapesNotificationsRoute
  ApiShapesProjectsRoute: typeof ApiShapesProjectsRoute
  ApiShapesUsersRoute: typeof ApiShapesUsersRoute
  ApiShapesWorkspaceInvitesRoute: typeof ApiShapesWorkspaceInvitesRoute
  ApiShapesWorkspaceMembersRoute: typeof ApiShapesWorkspaceMembersRoute
  ApiShapesWorkspacesRoute: typeof ApiShapesWorkspacesRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
  ApiWidgetConfigRoute: typeof ApiWidgetConfigRoute
  ApiWidgetSubmitRoute: typeof ApiWidgetSubmitRoute
  ApiIntegrationsGithubCallbackRoute: typeof ApiIntegrationsGithubCallbackRoute
  ApiIntegrationsGithubSetupRoute: typeof ApiIntegrationsGithubSetupRoute
  ApiIssuesIssueIdImagesRoute: typeof ApiIssuesIssueIdImagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$': {
      id: '/w/$'
      path: '/w/$'
      fullPath: '/w/$'
      preLoaderRoute: typeof WSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/consent': {
      id: '/auth/consent'
      path: '/auth/consent'
      fullPath: '/auth/consent'
      preLoaderRoute: typeof AuthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile-oauth-start': {
      id: '/api/mobile-oauth-start'
      path: '/api/mobile-oauth-start'
      fullPath: '/api/mobile-oauth-start'
      preLoaderRoute: typeof ApiMobileOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile-oauth-return': {
      id: '/api/mobile-oauth-return'
      path: '/api/mobile-oauth-return'
      fullPath: '/api/mobile-oauth-return'
      preLoaderRoute: typeof ApiMobileOauthReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile-oauth-exchange': {
      id: '/api/mobile-oauth-exchange'
      path: '/api/mobile-oauth-exchange'
      fullPath: '/api/mobile-oauth-exchange'
      preLoaderRoute: typeof ApiMobileOauthExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-config': {
      id: '/api/auth-config'
      path: '/api/auth-config'
      fullPath: '/api/auth-config'
      preLoaderRoute: typeof ApiAuthConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/assetlinks.json': {
      id: '/.well-known/assetlinks.json'
      path: '/.well-known/assetlinks.json'
      fullPath: '/.well-known/assetlinks.json'
      preLoaderRoute: typeof Char91DotwellKnownChar93AssetlinksChar91DotChar93jsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof Char91DotwellKnownChar93AppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$workspaceSlug': {
      id: '/t/$workspaceSlug'
      path: '/t/$workspaceSlug'
      fullPath: '/t/$workspaceSlug'
      preLoaderRoute: typeof TWorkspaceSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/t/$workspaceSlug/': {
      id: '/t/$workspaceSlug/'
      path: '/'
      fullPath: '/t/$workspaceSlug/'
      preLoaderRoute: typeof TWorkspaceSlugIndexRouteImport
      parentRoute: typeof TWorkspaceSlugRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/widget/submit': {
      id: '/api/widget/submit'
      path: '/api/widget/submit'
      fullPath: '/api/widget/submit'
      preLoaderRoute: typeof ApiWidgetSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widget/config': {
      id: '/api/widget/config'
      path: '/api/widget/config'
      fullPath: '/api/widget/config'
      preLoaderRoute: typeof ApiWidgetConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/workspaces': {
      id: '/api/shapes/workspaces'
      path: '/api/shapes/workspaces'
      fullPath: '/api/shapes/workspaces'
      preLoaderRoute: typeof ApiShapesWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/workspace-members': {
      id: '/api/shapes/workspace-members'
      path: '/api/shapes/workspace-members'
      fullPath: '/api/shapes/workspace-members'
      preLoaderRoute: typeof ApiShapesWorkspaceMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/workspace-invites': {
      id: '/api/shapes/workspace-invites'
      path: '/api/shapes/workspace-invites'
      fullPath: '/api/shapes/workspace-invites'
      preLoaderRoute: typeof ApiShapesWorkspaceInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/users': {
      id: '/api/shapes/users'
      path: '/api/shapes/users'
      fullPath: '/api/shapes/users'
      preLoaderRoute: typeof ApiShapesUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/projects': {
      id: '/api/shapes/projects'
      path: '/api/shapes/projects'
      fullPath: '/api/shapes/projects'
      preLoaderRoute: typeof ApiShapesProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/notifications': {
      id: '/api/shapes/notifications'
      path: '/api/shapes/notifications'
      fullPath: '/api/shapes/notifications'
      preLoaderRoute: typeof ApiShapesNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/labels': {
      id: '/api/shapes/labels'
      path: '/api/shapes/labels'
      fullPath: '/api/shapes/labels'
      preLoaderRoute: typeof ApiShapesLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/issues': {
      id: '/api/shapes/issues'
      path: '/api/shapes/issues'
      fullPath: '/api/shapes/issues'
      preLoaderRoute: typeof ApiShapesIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/issue-subscribers': {
      id: '/api/shapes/issue-subscribers'
      path: '/api/shapes/issue-subscribers'
      fullPath: '/api/shapes/issue-subscribers'
      preLoaderRoute: typeof ApiShapesIssueSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/issue-labels': {
      id: '/api/shapes/issue-labels'
      path: '/api/shapes/issue-labels'
      fullPath: '/api/shapes/issue-labels'
      preLoaderRoute: typeof ApiShapesIssueLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/issue-events': {
      id: '/api/shapes/issue-events'
      path: '/api/shapes/issue-events'
      fullPath: '/api/shapes/issue-events'
      preLoaderRoute: typeof ApiShapesIssueEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/comments': {
      id: '/api/shapes/comments'
      path: '/api/shapes/comments'
      fullPath: '/api/shapes/comments'
      preLoaderRoute: typeof ApiShapesCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/coding-sessions': {
      id: '/api/shapes/coding-sessions'
      path: '/api/shapes/coding-sessions'
      fullPath: '/api/shapes/coding-sessions'
      preLoaderRoute: typeof ApiShapesCodingSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/attachments': {
      id: '/api/shapes/attachments'
      path: '/api/shapes/attachments'
      fullPath: '/api/shapes/attachments'
      preLoaderRoute: typeof ApiShapesAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/unsubscribe': {
      id: '/api/email/unsubscribe'
      path: '/api/email/unsubscribe'
      fullPath: '/api/email/unsubscribe'
      preLoaderRoute: typeof ApiEmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/$attachmentId': {
      id: '/api/attachments/$attachmentId'
      path: '/api/attachments/$attachmentId'
      fullPath: '/api/attachments/$attachmentId'
      preLoaderRoute: typeof ApiAttachmentsAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/workspaces': {
      id: '/_authenticated/admin/workspaces'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AuthenticatedAdminWorkspacesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/account/notifications': {
      id: '/_authenticated/account/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AuthenticatedAccountNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/t/$workspaceSlug/settings/': {
      id: '/t/$workspaceSlug/settings/'
      path: '/settings'
      fullPath: '/t/$workspaceSlug/settings/'
      preLoaderRoute: typeof TWorkspaceSlugSettingsIndexRouteImport
      parentRoute: typeof TWorkspaceSlugRouteRoute
    }
    '/t/$workspaceSlug/reviews/': {
      id: '/t/$workspaceSlug/reviews/'
      path: '/reviews'
      fullPath: '/t/$workspaceSlug/reviews/'
      preLoaderRoute: typeof TWorkspaceSlugReviewsIndexRouteImport
      parentRoute: typeof TWorkspaceSlugRouteRoute
    }
    '/t/$workspaceSlug/my-issues/': {
      id: '/t/$workspaceSlug/my-issues/'
      path: '/my-issues'
      fullPath: '/t/$workspaceSlug/my-issues/'
      preLoaderRoute: typeof TWorkspaceSlugMyIssuesIndexRouteImport
      parentRoute: typeof TWorkspaceSlugRouteRoute
    }
    '/t/$workspaceSlug/inbox/': {
      id: '/t/$workspaceSlug/inbox/'
      path: '/inbox'
      fullPath: '/t/$workspaceSlug/inbox/'
      preLoaderRoute: typeof TWorkspaceSlugInboxIndexRouteImport
      parentRoute: typeof TWorkspaceSlugRouteRoute
    }
    '/t/$workspaceSlug/agents/': {
      id: '/t/$workspaceSlug/agents/'
      path: '/agents'
      fullPath: '/t/$workspaceSlug/agents/'
      preLoaderRoute: typeof TWorkspaceSlugAgentsIndexRouteImport
      parentRoute: typeof TWorkspaceSlugRouteRoute
    }
    '/api/issues/$issueId/images': {
      id: '/api/issues/$issueId/images'
      path: '/api/issues/$issueId/images'
      fullPath: '/api/issues/$issueId/images'
      preLoaderRoute: typeof ApiIssuesIssueIdImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/github/setup': {
      id: '/api/integrations/github/setup'
      path: '/api/integrations/github/setup'
      fullPath: '/api/integrations/github/setup'
      preLoaderRoute: typeof ApiIntegrationsGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/github/callback': {
      id: '/api/integrations/github/callback'
      path: '/api/integrations/github/callback'
      fullPath: '/api/integrations/github/callback'
      preLoaderRoute: typeof ApiIntegrationsGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/integrations/github/installed': {
      id: '/_authenticated/integrations/github/installed'
      path: '/integrations/github/installed'
      fullPath: '/integrations/github/installed'
      preLoaderRoute: typeof AuthenticatedIntegrationsGithubInstalledRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/github/claim': {
      id: '/_authenticated/integrations/github/claim'
      path: '/integrations/github/claim'
      fullPath: '/integrations/github/claim'
      preLoaderRoute: typeof AuthenticatedIntegrationsGithubClaimRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workspaces_/$workspaceId': {
      id: '/_authenticated/admin/workspaces_/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/admin/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedAdminWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users_/$userId': {
      id: '/_authenticated/admin/users_/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/t/$workspaceSlug/projects/$projectSlug/': {
      id: '/t/$workspaceSlug/projects/$projectSlug/'
      path: '/projects/$projectSlug'
      fullPath: '/t/$workspaceSlug/projects/$projectSlug/'
      preLoaderRoute: typeof TWorkspaceSlugProjectsProjectSlugIndexRouteImport
      parentRoute: typeof TWorkspaceSlugRouteRoute
    }
    '/t/$workspaceSlug/projects/$projectSlug/issues/$issueIdentifier': {
      id: '/t/$workspaceSlug/projects/$projectSlug/issues/$issueIdentifier'
      path: '/projects/$projectSlug/issues/$issueIdentifier'
      fullPath: '/t/$workspaceSlug/projects/$projectSlug/issues/$issueIdentifier'
      preLoaderRoute: typeof TWorkspaceSlugProjectsProjectSlugIssuesIssueIdentifierRouteImport
      parentRoute: typeof TWorkspaceSlugRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWorkspacesRoute: typeof AuthenticatedAdminWorkspacesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminWorkspacesWorkspaceIdRoute: typeof AuthenticatedAdminWorkspacesWorkspaceIdRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminWorkspacesRoute: AuthenticatedAdminWorkspacesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
    AuthenticatedAdminWorkspacesWorkspaceIdRoute:
      AuthenticatedAdminWorkspacesWorkspaceIdRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAccountNotificationsRoute: typeof AuthenticatedAccountNotificationsRoute
  AuthenticatedIntegrationsGithubClaimRoute: typeof AuthenticatedIntegrationsGithubClaimRoute
  AuthenticatedIntegrationsGithubInstalledRoute: typeof AuthenticatedIntegrationsGithubInstalledRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAccountNotificationsRoute:
    AuthenticatedAccountNotificationsRoute,
  AuthenticatedIntegrationsGithubClaimRoute:
    AuthenticatedIntegrationsGithubClaimRoute,
  AuthenticatedIntegrationsGithubInstalledRoute:
    AuthenticatedIntegrationsGithubInstalledRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface TWorkspaceSlugRouteRouteChildren {
  TWorkspaceSlugIndexRoute: typeof TWorkspaceSlugIndexRoute
  TWorkspaceSlugAgentsIndexRoute: typeof TWorkspaceSlugAgentsIndexRoute
  TWorkspaceSlugInboxIndexRoute: typeof TWorkspaceSlugInboxIndexRoute
  TWorkspaceSlugMyIssuesIndexRoute: typeof TWorkspaceSlugMyIssuesIndexRoute
  TWorkspaceSlugReviewsIndexRoute: typeof TWorkspaceSlugReviewsIndexRoute
  TWorkspaceSlugSettingsIndexRoute: typeof TWorkspaceSlugSettingsIndexRoute
  TWorkspaceSlugProjectsProjectSlugIndexRoute: typeof TWorkspaceSlugProjectsProjectSlugIndexRoute
  TWorkspaceSlugProjectsProjectSlugIssuesIssueIdentifierRoute: typeof TWorkspaceSlugProjectsProjectSlugIssuesIssueIdentifierRoute
}

const TWorkspaceSlugRouteRouteChildren: TWorkspaceSlugRouteRouteChildren = {
  TWorkspaceSlugIndexRoute: TWorkspaceSlugIndexRoute,
  TWorkspaceSlugAgentsIndexRoute: TWorkspaceSlugAgentsIndexRoute,
  TWorkspaceSlugInboxIndexRoute: TWorkspaceSlugInboxIndexRoute,
  TWorkspaceSlugMyIssuesIndexRoute: TWorkspaceSlugMyIssuesIndexRoute,
  TWorkspaceSlugReviewsIndexRoute: TWorkspaceSlugReviewsIndexRoute,
  TWorkspaceSlugSettingsIndexRoute: TWorkspaceSlugSettingsIndexRoute,
  TWorkspaceSlugProjectsProjectSlugIndexRoute:
    TWorkspaceSlugProjectsProjectSlugIndexRoute,
  TWorkspaceSlugProjectsProjectSlugIssuesIssueIdentifierRoute:
    TWorkspaceSlugProjectsProjectSlugIssuesIssueIdentifierRoute,
}

const TWorkspaceSlugRouteRouteWithChildren =
  TWorkspaceSlugRouteRoute._addFileChildren(TWorkspaceSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TWorkspaceSlugRouteRoute: TWorkspaceSlugRouteRouteWithChildren,
  Char91DotwellKnownChar93AppleAppSiteAssociationRoute:
    Char91DotwellKnownChar93AppleAppSiteAssociationRoute,
  Char91DotwellKnownChar93AssetlinksChar91DotChar93jsonRoute:
    Char91DotwellKnownChar93AssetlinksChar91DotChar93jsonRoute,
  Char91DotwellKnownChar93OauthAuthorizationServerRoute:
    Char91DotwellKnownChar93OauthAuthorizationServerRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAuthConfigRoute: ApiAuthConfigRoute,
  ApiContactRoute: ApiContactRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiMobileOauthExchangeRoute: ApiMobileOauthExchangeRoute,
  ApiMobileOauthReturnRoute: ApiMobileOauthReturnRoute,
  ApiMobileOauthStartRoute: ApiMobileOauthStartRoute,
  ApiVersionRoute: ApiVersionRoute,
  AuthConsentRoute: AuthConsentRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  WSplatRoute: WSplatRoute,
  ApiAttachmentsAttachmentIdRoute: ApiAttachmentsAttachmentIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEmailUnsubscribeRoute: ApiEmailUnsubscribeRoute,
  ApiShapesAttachmentsRoute: ApiShapesAttachmentsRoute,
  ApiShapesCodingSessionsRoute: ApiShapesCodingSessionsRoute,
  ApiShapesCommentsRoute: ApiShapesCommentsRoute,
  ApiShapesIssueEventsRoute: ApiShapesIssueEventsRoute,
  ApiShapesIssueLabelsRoute: ApiShapesIssueLabelsRoute,
  ApiShapesIssueSubscribersRoute: ApiShapesIssueSubscribersRoute,
  ApiShapesIssuesRoute: ApiShapesIssuesRoute,
  ApiShapesLabelsRoute: ApiShapesLabelsRoute,
  ApiShapesNotificationsRoute: ApiShapesNotificationsRoute,
  ApiShapesProjectsRoute: ApiShapesProjectsRoute,
  ApiShapesUsersRoute: ApiShapesUsersRoute,
  ApiShapesWorkspaceInvitesRoute: ApiShapesWorkspaceInvitesRoute,
  ApiShapesWorkspaceMembersRoute: ApiShapesWorkspaceMembersRoute,
  ApiShapesWorkspacesRoute: ApiShapesWorkspacesRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
  ApiWidgetConfigRoute: ApiWidgetConfigRoute,
  ApiWidgetSubmitRoute: ApiWidgetSubmitRoute,
  ApiIntegrationsGithubCallbackRoute: ApiIntegrationsGithubCallbackRoute,
  ApiIntegrationsGithubSetupRoute: ApiIntegrationsGithubSetupRoute,
  ApiIssuesIssueIdImagesRoute: ApiIssuesIssueIdImagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
