package com.exponential.app.ui.emoji

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

// EXP-551 — the emoji picker + `:shortcode` typeahead dataset.
//
// `assets/emoji.json` is the SHARED file generated by packages/emoji and
// committed byte-identically into all four clients, so every client searches
// the same labels, GitHub shortcodes and tags. Never hand-edit it.
//
// The ranking, skin-tone and recents rules below are the hand-mirrored twin of
// web's `lib/emoji.ts` (and iOS `EmojiCatalog.swift` / desktop `emoji.rs`).
// Pickers insert the UNICODE — never `:shortcode:` text — because
// `issues.description` / `comments.body` are plain GFM shared with clients
// that render only unicode.

private const val EMOJI_ASSET = "emoji.json"

/** Number of skin-tone variants a toned emoji carries (`k.size`). */
const val EMOJI_TONES = 5

/** Recently picked base emoji kept per device. */
const val MAX_RECENT_EMOJI = 24

/** One pickable emoji. Short keys: the file ships inside the app bundle. */
@Serializable
data class EmojiRecord(
    /** The unicode sequence to insert (fully qualified, no skin tone). */
    @SerialName("u") val unicode: String,
    /** Human label, lowercase, e.g. `grinning face`. */
    @SerialName("l") val label: String,
    /** Index into [EmojiDataset.groups]. */
    @SerialName("g") val group: Int = 0,
    /** Shortcodes without colons, GitHub's set where it has one (`+1`, `tada`). */
    @SerialName("s") val shortcodes: List<String> = emptyList(),
    /** Search tags. */
    @SerialName("t") val tags: List<String> = emptyList(),
    /**
     * The five uniform skin-tone variants, light → dark, present only when the
     * emoji supports every one of them (mixed-tone multi-person emoji are
     * deliberately not offered).
     */
    @SerialName("k") val tones: List<String>? = null,
)

@Serializable
data class EmojiDataset(
    /** The emojibase-data version the file was generated from. */
    val version: String = "",
    /** Group labels, indexed by [EmojiRecord.group]. */
    val groups: List<String> = emptyList(),
    /** In display order (emojibase `order`). */
    val emojis: List<EmojiRecord> = emptyList(),
)

/** One picker section: a dataset group and its emoji, in dataset order. */
data class EmojiGroup(val index: Int, val label: String, val emojis: List<EmojiRecord>)

/** The parsed dataset plus the lookup indexes the picker and typeahead need. */
class EmojiData(val dataset: EmojiDataset) {
    val groups: List<EmojiGroup>

    /** Lowercased shortcode → record (first record wins on collisions). */
    private val byShortcode: Map<String, EmojiRecord>

    /** Base unicode → record, so a recents entry can resolve back to a record. */
    private val byUnicode: Map<String, EmojiRecord>

    init {
        val buckets = dataset.groups.indices.map { mutableListOf<EmojiRecord>() }
        val shortcodes = HashMap<String, EmojiRecord>()
        val unicodes = HashMap<String, EmojiRecord>()
        for (emoji in dataset.emojis) {
            buckets.getOrNull(emoji.group)?.add(emoji)
            unicodes.putIfAbsent(emoji.unicode, emoji)
            for (code in emoji.shortcodes) shortcodes.putIfAbsent(code.lowercase(), emoji)
        }
        groups = dataset.groups.mapIndexed { index, label ->
            EmojiGroup(index, label, buckets[index].toList())
        }
        byShortcode = shortcodes
        byUnicode = unicodes
    }

    /**
     * Ranked search: shortcode exact > shortcode prefix > label prefix > tag
     * exact/prefix > label/tag substring; ties keep dataset order. Empty query
     * matches nothing (the picker shows its groups instead).
     */
    fun search(query: String, limit: Int): List<EmojiRecord> {
        val q = query.trim().lowercase().removePrefix(":").removeSuffix(":")
        if (q.isEmpty() || limit <= 0) return emptyList()
        // sortedBy is stable, so iterating the dataset in order is the tie-break.
        return dataset.emojis
            .mapNotNull { emoji -> rank(emoji, q)?.let { emoji to it } }
            .sortedBy { it.second }
            .take(limit)
            .map { it.first }
    }

    /** Exact shortcode lookup (`tada` → 🎉), used by the `:tada:` auto-commit. */
    fun findShortcode(shortcode: String): EmojiRecord? = byShortcode[shortcode.lowercase()]

    /** The record a stored recents entry names, or null once a build drops it. */
    fun findUnicode(unicode: String): EmojiRecord? = byUnicode[unicode]

    private fun rank(emoji: EmojiRecord, q: String): Int? {
        val label = emoji.label.lowercase()
        if (emoji.shortcodes.any { it.lowercase() == q }) return 0
        if (emoji.shortcodes.any { it.lowercase().startsWith(q) }) return 1
        if (label.startsWith(q)) return 2
        if (emoji.tags.any { it == q || it.startsWith(q) }) return 3
        if (label.contains(q) || emoji.tags.any { it.contains(q) }) return 4
        return null
    }
}

/**
 * Loads and indexes `assets/emoji.json` ONCE per process, off the main thread —
 * ~245KB of JSON, so every picker and typeahead shares the one parse.
 */
object EmojiCatalog {
    private val json = Json { ignoreUnknownKeys = true }
    private val mutex = Mutex()

    @Volatile
    private var cached: EmojiData? = null

    suspend fun get(context: Context): EmojiData? {
        cached?.let { return it }
        val appContext = context.applicationContext
        return mutex.withLock {
            cached ?: withContext(Dispatchers.IO) {
                runCatching {
                    parse(appContext.assets.open(EMOJI_ASSET).bufferedReader().use { it.readText() })
                }.getOrNull()
            }?.also { cached = it }
        }
    }

    /** Parses the shared dataset. Exposed so tests can feed the committed asset. */
    fun parse(rawJson: String): EmojiData = EmojiData(json.decodeFromString(EmojiDataset.serializer(), rawJson))
}

/** The unicode to insert for [emoji] under [tone] (the base when untoned). */
fun applySkinTone(emoji: EmojiRecord, tone: Int): String {
    val tones = emoji.tones
    if (tone <= 0 || tones == null || tones.size != EMOJI_TONES) return emoji.unicode
    return tones.getOrNull(tone - 1) ?: emoji.unicode
}

// --- `:shortcode` typeahead -------------------------------------------------

/**
 * The in-progress `:shortcode` token at the end of the text BEFORE the caret:
 * a colon at start-of-text or after whitespace ('\n' counts, so line starts
 * inside a multi-line run trigger too), then at least two shortcode
 * characters, optionally the closing colon. Two characters keep `12:30`,
 * `note:` and `:)` from ever opening a menu; the optional closing colon keeps
 * the menu alive when the user habitually types `:smile:` so it can
 * auto-commit instead of leaving literal shortcode text. Mirrors web's
 * `EMOJI_AT_CARET` and the shape of MENTION_AT_CARET / ISSUE_REF_AT_CARET.
 */
val EMOJI_AT_CARET = Regex("(?:^|\\s):([a-z0-9_+-]{2,})(:?)$", RegexOption.IGNORE_CASE)

data class EmojiTokenMatch(
    val query: String,
    /** Whether the closing colon has been typed (`:smile:`). */
    val closed: Boolean,
    /** UTF-16 length of the whole token: `:` + query + optional `:`. */
    val length: Int,
)

fun matchEmojiToken(textBefore: String): EmojiTokenMatch? {
    val match = EMOJI_AT_CARET.find(textBefore) ?: return null
    val query = match.groupValues[1]
    val closed = match.groupValues[2] == ":"
    return EmojiTokenMatch(query = query, closed = closed, length = query.length + 1 + if (closed) 1 else 0)
}

// --- Per-device prefs -------------------------------------------------------

/**
 * The tiny key/value surface the emoji prefs need, so the rules below are
 * unit-testable against an in-memory fake (production binds it to the app's
 * SecureStore — see `rememberEmojiPrefs`).
 */
interface EmojiPrefsStore {
    fun get(key: String): String?
    fun set(key: String, value: String?)
}

/**
 * Skin-tone preference (0 = none, 1..5 light → dark) and the recently picked
 * BASE emoji, most recent first. Same keys as the other clients.
 */
class EmojiPrefs(private val store: EmojiPrefsStore) {
    fun skinTone(): Int = store.get(TONE_KEY)?.toIntOrNull()?.takeIf { it in 0..EMOJI_TONES } ?: 0

    fun setSkinTone(tone: Int) {
        store.set(TONE_KEY, tone.coerceIn(0, EMOJI_TONES).toString())
    }

    fun recents(): List<String> = store.get(RECENT_KEY)
        ?.split(SEPARATOR)
        ?.filter { it.isNotEmpty() }
        ?.take(MAX_RECENT_EMOJI)
        ?: emptyList()

    /** Records a pick (by BASE unicode) at the head of the list, deduped. */
    fun pushRecent(unicode: String): List<String> {
        if (unicode.isEmpty()) return recents()
        val next = (listOf(unicode) + recents().filter { it != unicode }).take(MAX_RECENT_EMOJI)
        store.set(RECENT_KEY, next.joinToString(SEPARATOR))
        return next
    }

    companion object {
        const val TONE_KEY = "exp.emojiSkinTone"
        const val RECENT_KEY = "exp.emojiRecent"

        // '\n' can never appear inside an emoji sequence, so a joined string
        // beats a nested JSON document for a two-field pref.
        private const val SEPARATOR = "\n"
    }
}
