#!/usr/bin/env bun
// Emits the canonical enum value lists from contract.json into Swift (iOS),
// Kotlin (Android), Rust (crates/agent-core), and Zig (apps/linux) sources.
// Run from the repo root with: `bun run --filter @exp/domain-contract generate`.
//
// The mobile native enums (IssueStatus.swift, IssueStatus.kt, …) are
// hand-written so they can carry language-specific affordances (SF Symbols,
// Material icons, colors); their raw values must stay in sync with these
// generated constants. On the web side, contract.json parity is enforced by
// the domain-contract drift test (apps/web/src/lib/domain-contract.test.ts).

import { writeFileSync, mkdirSync, readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const repoRoot = join(__dirname, "..", "..", "..")

interface Section {
  values: string[]
  displayOrder?: string[]
}
interface Contract {
  issueStatus: Section
  issuePriority: Section
  recurrenceUnit: Section
  workspaceRole: Section
  publicWritePolicy: Section
  commentKind: Section
  recurrenceIntervals: number[]
}

const contract: Contract = JSON.parse(
  readFileSync(join(__dirname, "..", "contract.json"), "utf8")
)

const HEADER_SWIFT = `// AUTO-GENERATED by packages/domain-contract/scripts/generate.ts — do not edit.
// Single source of truth: packages/domain-contract/contract.json.
`

const HEADER_KOTLIN = `// AUTO-GENERATED by packages/domain-contract/scripts/generate.ts — do not edit.
// Single source of truth: packages/domain-contract/contract.json.
`

function swiftStringArray(name: string, values: string[]): string {
  return `    static let ${name}: [String] = [${values.map((v) => `"${v}"`).join(", ")}]`
}

function kotlinStringArray(name: string, values: string[]): string {
  return `    val ${name}: List<String> = listOf(${values.map((v) => `"${v}"`).join(", ")})`
}

function kotlinIntArray(name: string, values: number[]): string {
  return `    val ${name}: List<Int> = listOf(${values.join(", ")})`
}

function camelCase(s: string): string {
  return s.replace(/_([a-z])/g, (_, ch) => ch.toUpperCase())
}

function pascalCase(s: string): string {
  const c = camelCase(s)
  return c.charAt(0).toUpperCase() + c.slice(1)
}

// Emits per-value named constants so call sites can reference
// `DomainContract.workspaceRoleOwner` instead of the bare string literal.
function swiftNamedValues(prefix: string, values: string[]): string {
  return values
    .map(
      (v) =>
        `    static let ${prefix}${pascalCase(v)}: String = "${v}"`
    )
    .join(`\n`)
}

function kotlinNamedValues(prefix: string, values: string[]): string {
  return values
    .map((v) => `    const val ${prefix}${pascalCase(v)}: String = "${v}"`)
    .join(`\n`)
}

// --- Rust + Zig (consumed by crates/agent-core and apps/linux) ---

function screamingSnake(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase()
}

function snakeCase(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase()
}

function identSuffix(value: string): string {
  return value.replace(/[^A-Za-z0-9]+/g, "_")
}

function rustStrSlice(name: string, values: string[]): string {
  return `pub const ${screamingSnake(name)}: &[&str] = &[${values.map((v) => `"${v}"`).join(", ")}];`
}

function rustNamedValues(prefix: string, values: string[]): string {
  return values
    .map(
      (v) =>
        `pub const ${screamingSnake(prefix)}_${identSuffix(v).toUpperCase()}: &str = "${v}";`
    )
    .join(`\n`)
}

function zigStrArray(name: string, values: string[]): string {
  return `pub const ${snakeCase(name)} = [_][]const u8{ ${values.map((v) => `"${v}"`).join(", ")} };`
}

function zigNamedValues(prefix: string, values: string[]): string {
  return values
    .map(
      (v) =>
        `pub const ${snakeCase(prefix)}_${identSuffix(v).toLowerCase()}: []const u8 = "${v}";`
    )
    .join(`\n`)
}

const swift = `${HEADER_SWIFT}
import Foundation

enum DomainContract {
${swiftStringArray("issueStatusValues", contract.issueStatus.values)}
${swiftStringArray("issueStatusDisplayOrder", contract.issueStatus.displayOrder ?? contract.issueStatus.values)}
${swiftStringArray("issuePriorityValues", contract.issuePriority.values)}
${swiftStringArray("issuePriorityDisplayOrder", contract.issuePriority.displayOrder ?? contract.issuePriority.values)}
${swiftStringArray("recurrenceUnitValues", contract.recurrenceUnit.values)}
${swiftStringArray("workspaceRoleValues", contract.workspaceRole.values)}
${swiftStringArray("publicWritePolicyValues", contract.publicWritePolicy.values)}
${swiftStringArray("commentKindValues", contract.commentKind.values)}
    static let recurrenceIntervals: [Int] = [${contract.recurrenceIntervals.join(", ")}]

${swiftNamedValues("workspaceRole", contract.workspaceRole.values)}
${swiftNamedValues("publicWritePolicy", contract.publicWritePolicy.values)}
${swiftNamedValues("commentKind", contract.commentKind.values)}
}
`

const kotlin = `${HEADER_KOTLIN}package com.exponential.app.domain

object DomainContract {
${kotlinStringArray("issueStatusValues", contract.issueStatus.values)}
${kotlinStringArray("issueStatusDisplayOrder", contract.issueStatus.displayOrder ?? contract.issueStatus.values)}
${kotlinStringArray("issuePriorityValues", contract.issuePriority.values)}
${kotlinStringArray("issuePriorityDisplayOrder", contract.issuePriority.displayOrder ?? contract.issuePriority.values)}
${kotlinStringArray("recurrenceUnitValues", contract.recurrenceUnit.values)}
${kotlinStringArray("workspaceRoleValues", contract.workspaceRole.values)}
${kotlinStringArray("publicWritePolicyValues", contract.publicWritePolicy.values)}
${kotlinStringArray("commentKindValues", contract.commentKind.values)}
${kotlinIntArray("recurrenceIntervals", contract.recurrenceIntervals)}

${kotlinNamedValues("workspaceRole", contract.workspaceRole.values)}
${kotlinNamedValues("publicWritePolicy", contract.publicWritePolicy.values)}
${kotlinNamedValues("commentKind", contract.commentKind.values)}
}
`

const HEADER_RUST = `// AUTO-GENERATED by packages/domain-contract/scripts/generate.ts — do not edit.
// Single source of truth: packages/domain-contract/contract.json.
`

const HEADER_ZIG = `// AUTO-GENERATED by packages/domain-contract/scripts/generate.ts — do not edit.
// Single source of truth: packages/domain-contract/contract.json.
`

const rust = `${HEADER_RUST}#![allow(dead_code)]

${rustStrSlice("issueStatusValues", contract.issueStatus.values)}
${rustStrSlice("issueStatusDisplayOrder", contract.issueStatus.displayOrder ?? contract.issueStatus.values)}
${rustStrSlice("issuePriorityValues", contract.issuePriority.values)}
${rustStrSlice("issuePriorityDisplayOrder", contract.issuePriority.displayOrder ?? contract.issuePriority.values)}
${rustStrSlice("recurrenceUnitValues", contract.recurrenceUnit.values)}
${rustStrSlice("workspaceRoleValues", contract.workspaceRole.values)}
${rustStrSlice("publicWritePolicyValues", contract.publicWritePolicy.values)}
${rustStrSlice("commentKindValues", contract.commentKind.values)}
pub const RECURRENCE_INTERVALS: &[i32] = &[${contract.recurrenceIntervals.join(", ")}];

${rustNamedValues("workspaceRole", contract.workspaceRole.values)}
${rustNamedValues("publicWritePolicy", contract.publicWritePolicy.values)}
${rustNamedValues("commentKind", contract.commentKind.values)}
`

const zig = `${HEADER_ZIG}
${zigStrArray("issueStatusValues", contract.issueStatus.values)}
${zigStrArray("issueStatusDisplayOrder", contract.issueStatus.displayOrder ?? contract.issueStatus.values)}
${zigStrArray("issuePriorityValues", contract.issuePriority.values)}
${zigStrArray("issuePriorityDisplayOrder", contract.issuePriority.displayOrder ?? contract.issuePriority.values)}
${zigStrArray("recurrenceUnitValues", contract.recurrenceUnit.values)}
${zigStrArray("workspaceRoleValues", contract.workspaceRole.values)}
${zigStrArray("publicWritePolicyValues", contract.publicWritePolicy.values)}
${zigStrArray("commentKindValues", contract.commentKind.values)}
pub const recurrence_intervals = [_]i32{ ${contract.recurrenceIntervals.join(", ")} };

${zigNamedValues("workspaceRole", contract.workspaceRole.values)}
${zigNamedValues("publicWritePolicy", contract.publicWritePolicy.values)}
${zigNamedValues("commentKind", contract.commentKind.values)}
`

const swiftPath = join(
  repoRoot,
  "apps/ios/Exponential/Domain/DomainContract.generated.swift"
)
const kotlinPath = join(
  repoRoot,
  "apps/android/app/src/main/java/com/exponential/app/domain/DomainContract.generated.kt"
)

const rustPath = join(repoRoot, "crates/agent-core/src/domain_contract.rs")
const zigPath = join(
  repoRoot,
  "apps/linux/src/core/domain/contract.generated.zig"
)

mkdirSync(dirname(swiftPath), { recursive: true })
mkdirSync(dirname(kotlinPath), { recursive: true })
mkdirSync(dirname(rustPath), { recursive: true })
mkdirSync(dirname(zigPath), { recursive: true })
writeFileSync(swiftPath, swift)
writeFileSync(kotlinPath, kotlin)
writeFileSync(rustPath, rust)
writeFileSync(zigPath, zig)

console.log(`Wrote ${swiftPath}`)
console.log(`Wrote ${kotlinPath}`)
console.log(`Wrote ${rustPath}`)
console.log(`Wrote ${zigPath}`)
