// AUTO-GENERATED by packages/design-tokens/scripts/generate.ts — do not edit.
// Single source of truth: packages/design-tokens/tokens.json.
use crate::Srgb8;

// Forced-dark surface palette, derived from the web OKLCH theme.
pub const BACKGROUND: Srgb8 = Srgb8 { r: 10, g: 10, b: 10, a: 255 };
pub const FOREGROUND: Srgb8 = Srgb8 { r: 250, g: 250, b: 250, a: 255 };
pub const CARD: Srgb8 = Srgb8 { r: 23, g: 23, b: 23, a: 255 };
pub const CARD_FOREGROUND: Srgb8 = Srgb8 { r: 250, g: 250, b: 250, a: 255 };
pub const POPOVER: Srgb8 = Srgb8 { r: 23, g: 23, b: 23, a: 255 };
pub const POPOVER_FOREGROUND: Srgb8 = Srgb8 { r: 250, g: 250, b: 250, a: 255 };
pub const PRIMARY: Srgb8 = Srgb8 { r: 229, g: 229, b: 229, a: 255 };
pub const PRIMARY_FOREGROUND: Srgb8 = Srgb8 { r: 23, g: 23, b: 23, a: 255 };
pub const SECONDARY: Srgb8 = Srgb8 { r: 38, g: 38, b: 38, a: 255 };
pub const SECONDARY_FOREGROUND: Srgb8 = Srgb8 { r: 250, g: 250, b: 250, a: 255 };
pub const MUTED: Srgb8 = Srgb8 { r: 38, g: 38, b: 38, a: 255 };
pub const MUTED_FOREGROUND: Srgb8 = Srgb8 { r: 161, g: 161, b: 161, a: 255 };
pub const ACCENT: Srgb8 = Srgb8 { r: 38, g: 38, b: 38, a: 255 };
pub const ACCENT_FOREGROUND: Srgb8 = Srgb8 { r: 250, g: 250, b: 250, a: 255 };
pub const DESTRUCTIVE: Srgb8 = Srgb8 { r: 255, g: 100, b: 103, a: 255 };
pub const BORDER: Srgb8 = Srgb8 { r: 255, g: 255, b: 255, a: 26 };
pub const INPUT: Srgb8 = Srgb8 { r: 255, g: 255, b: 255, a: 38 };
pub const RING: Srgb8 = Srgb8 { r: 115, g: 115, b: 115, a: 255 };
pub const SIDEBAR: Srgb8 = Srgb8 { r: 23, g: 23, b: 23, a: 255 };
pub const SIDEBAR_FOREGROUND: Srgb8 = Srgb8 { r: 250, g: 250, b: 250, a: 255 };
pub const SIDEBAR_ACCENT: Srgb8 = Srgb8 { r: 38, g: 38, b: 38, a: 255 };
pub const SIDEBAR_BORDER: Srgb8 = Srgb8 { r: 255, g: 255, b: 255, a: 26 };

// Fixed brand accents (status / priority / due-date).
pub const NEUTRAL: Srgb8 = Srgb8 { r: 161, g: 161, b: 170, a: 255 };
pub const YELLOW: Srgb8 = Srgb8 { r: 250, g: 204, b: 21, a: 255 };
pub const GREEN: Srgb8 = Srgb8 { r: 34, g: 197, b: 94, a: 255 };
pub const RED: Srgb8 = Srgb8 { r: 239, g: 68, b: 68, a: 255 };
pub const ORANGE: Srgb8 = Srgb8 { r: 249, g: 115, b: 22, a: 255 };
pub const BLUE: Srgb8 = Srgb8 { r: 59, g: 130, b: 246, a: 255 };

// Corner radii in px, matching the web rounded-* scale.
pub mod radius {
    pub const SM: f32 = 6.0;
    pub const MD: f32 = 8.0;
    pub const LG: f32 = 10.0;
    pub const XL: f32 = 14.0;
}

// Control geometry in px, matching the web control heights.
pub mod size {
    pub const CONTROL_LG: f32 = 36.0;
    pub const CONTROL_MD: f32 = 32.0;
    pub const CONTROL_SM: f32 = 24.0;
    pub const INPUT_HEIGHT: f32 = 36.0;
    pub const ROW_HEIGHT: f32 = 32.0;
}
