// AUTO-GENERATED by packages/domain-contract/scripts/generate.ts — do not edit.
// Single source of truth: packages/domain-contract/contract.json.
package com.exponential.app.domain

object DomainContract {
    val issueStatusValues: List<String> = listOf("backlog", "todo", "in_progress", "done", "cancelled")
    val issueStatusDisplayOrder: List<String> = listOf("in_progress", "todo", "backlog", "done", "cancelled")
    val issuePriorityValues: List<String> = listOf("none", "urgent", "high", "medium", "low")
    val issuePriorityDisplayOrder: List<String> = listOf("urgent", "high", "medium", "low", "none")
    val recurrenceUnitValues: List<String> = listOf("day", "week", "month")
    val workspaceRoleValues: List<String> = listOf("owner", "member", "agent")
    val publicWritePolicyValues: List<String> = listOf("members", "everyone")
    val commentKindValues: List<String> = listOf("regular", "question", "plan")
    val recurrenceIntervals: List<Int> = listOf(1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 21, 30)

    const val workspaceRoleOwner: String = "owner"
    const val workspaceRoleMember: String = "member"
    const val workspaceRoleAgent: String = "agent"
    const val publicWritePolicyMembers: String = "members"
    const val publicWritePolicyEveryone: String = "everyone"
    const val commentKindRegular: String = "regular"
    const val commentKindQuestion: String = "question"
    const val commentKindPlan: String = "plan"
}
