// AUTO-GENERATED by packages/domain-contract/scripts/generate.ts — do not edit.
// Single source of truth: packages/domain-contract/contract.json.
package com.exponential.app.domain

object DomainContract {
    val issueStatusValues: List<String> = listOf("backlog", "todo", "in_progress", "in_review", "done", "cancelled", "duplicate")
    val issueStatusDisplayOrder: List<String> = listOf("in_progress", "in_review", "todo", "backlog", "done", "cancelled", "duplicate")
    val issuePriorityValues: List<String> = listOf("none", "urgent", "high", "medium", "low")
    val issuePriorityDisplayOrder: List<String> = listOf("urgent", "high", "medium", "low", "none")
    val teamRoleValues: List<String> = listOf("owner", "member")
    val boardIconValues: List<String> = listOf("code", "square-kanban", "megaphone", "bug", "rocket", "book-open", "globe", "heart", "star", "zap", "wrench", "shield", "package", "terminal", "lightbulb", "message-circle")
    val commentKindValues: List<String> = listOf("regular")
    val notificationTypeValues: List<String> = listOf("issue_assigned", "issue_comment", "issue_status_changed", "issue_mention", "issue_created", "pr_opened", "pr_merged", "support_reply")
    val prStateValues: List<String> = listOf("open", "closed", "merged", "draft")
    val codingSessionStatusValues: List<String> = listOf("running", "in_review", "ended")
    val subscriberSourceValues: List<String> = listOf("creator", "assignee", "commenter", "manual", "mention", "widget_reporter")
    val issueEventTypeValues: List<String> = listOf("status_changed", "assignee_changed", "label_added", "label_removed", "pr_opened", "pr_merged", "board_moved")
    val codingAgentValues: List<String> = listOf("claude", "codex", "pi")
    val codingModelValues: List<String> = listOf("fable", "opus", "sonnet")
    val codingEffortValues: List<String> = listOf("low", "medium", "high", "xhigh", "max")
    val codexModelValues: List<String> = listOf("gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna")
    val codexEffortValues: List<String> = listOf("minimal", "low", "medium", "high", "xhigh")
    val piModelValues: List<String> = listOf("fable", "opus", "sonnet", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "grok-4.5")
    val piThinkingValues: List<String> = listOf("off", "minimal", "low", "medium", "high", "xhigh", "max")

    const val codingSessionStaleMs: Long = 7200000L

    const val teamRoleOwner: String = "owner"
    const val teamRoleMember: String = "member"
    const val commentKindRegular: String = "regular"
    const val notificationTypeIssueAssigned: String = "issue_assigned"
    const val notificationTypeIssueComment: String = "issue_comment"
    const val notificationTypeIssueStatusChanged: String = "issue_status_changed"
    const val notificationTypeIssueMention: String = "issue_mention"
    const val notificationTypeIssueCreated: String = "issue_created"
    const val notificationTypePrOpened: String = "pr_opened"
    const val notificationTypePrMerged: String = "pr_merged"
    const val notificationTypeSupportReply: String = "support_reply"
    const val prStateOpen: String = "open"
    const val prStateClosed: String = "closed"
    const val prStateMerged: String = "merged"
    const val prStateDraft: String = "draft"
    const val codingSessionStatusRunning: String = "running"
    const val codingSessionStatusInReview: String = "in_review"
    const val codingSessionStatusEnded: String = "ended"
    const val subscriberSourceCreator: String = "creator"
    const val subscriberSourceAssignee: String = "assignee"
    const val subscriberSourceCommenter: String = "commenter"
    const val subscriberSourceManual: String = "manual"
    const val subscriberSourceMention: String = "mention"
    const val subscriberSourceWidgetReporter: String = "widget_reporter"
    const val issueEventTypeStatusChanged: String = "status_changed"
    const val issueEventTypeAssigneeChanged: String = "assignee_changed"
    const val issueEventTypeLabelAdded: String = "label_added"
    const val issueEventTypeLabelRemoved: String = "label_removed"
    const val issueEventTypePrOpened: String = "pr_opened"
    const val issueEventTypePrMerged: String = "pr_merged"
    const val issueEventTypeBoardMoved: String = "board_moved"
}
