package com.exponential.app.domain

/**
 * The bundled third-party licence notice splitter (EXP-262).
 *
 * `assets/NOTICES.txt` is generated by `@exp/licenses` (EXP-375). The
 * renderer's format contract (`packages/licenses/src/render.ts`): every
 * heading is a "rule sandwich" — a full-width rule line (78 `=` or `-`
 * characters), one or two title lines, then a matching closing rule.
 * Reproduced licence bodies are emitted verbatim and never contain that exact
 * shape, so a sandwich split is exact where a markdown-style heading split
 * would tear licence bodies apart. The 78-column width is gated on the web
 * side (`apps/web/src/lib/licenses.test.ts`), so this parser and the
 * generator cannot drift silently. Pure JVM (no Android imports) so it stays
 * unit-testable.
 */
object ThirdPartyNotices {
    /** The renderer's `WIDTH` — rule lines are exactly this long. */
    private const val RULE_WIDTH = 78

    /** [title] is empty for the preamble (anything before the first heading). */
    data class Section(val title: String, val body: String)

    /** The full-width rule line's character (`=` or `-`), or null. */
    private fun ruleChar(line: String): Char? {
        if (line.length != RULE_WIDTH) return null
        val first = line[0]
        if (first != '=' && first != '-') return null
        return if (line.all { it == first }) first else null
    }

    /**
     * Split on rule sandwiches. CRLF input is tolerated; shorter dashed or
     * doubled rules inside licence bodies stay body text. The preamble (if
     * any) becomes a title-less first section.
     */
    fun parse(text: String): List<Section> {
        val lines = text.replace("\r\n", "\n").split("\n")
        val sections = mutableListOf<Section>()
        var title = ""
        val body = mutableListOf<String>()

        fun flush() {
            val joined = body.joinToString("\n").trim()
            if (joined.isNotEmpty() || title.isNotEmpty()) {
                sections.add(Section(title, joined))
            }
            body.clear()
        }

        var index = 0
        while (index < lines.size) {
            val char = ruleChar(lines[index])
            if (char != null) {
                val middles = mutableListOf<String>()
                var closing = index + 1
                while (closing < lines.size && middles.size < 3 && ruleChar(lines[closing]) == null) {
                    middles.add(lines[closing])
                    closing++
                }
                if (closing < lines.size &&
                    ruleChar(lines[closing]) == char &&
                    middles.size in 1..2 &&
                    middles.all { it.isNotBlank() }
                ) {
                    flush()
                    title = middles.joinToString(" — ") { it.trim() }
                    index = closing + 1
                    continue
                }
            }
            body.add(lines[index])
            index++
        }
        flush()
        return sections
    }
}
