// VAPP-89: `at.exponential:ui-compose`, the Compose painter of the Exponential
// UI SDK. One AAR = the UniFFI facade `exponential-ui-ffi` (its `.so` for
// arm64-v8a, armeabi-v7a and x86_64, built by
// apps/desktop/crates/exponential-ui-ffi/build-android.sh) + the generated
// Kotlin bindings (a committed source, package `at.exponential.ui.ffi`) + the
// painter. Depends on nothing from the Exponential app.
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    id("maven-publish")
    // Test-only: the component image snapshots (src/test/snapshots/images).
    alias(libs.plugins.roborazzi)
}

val repoRoot = rootDir.parentFile.parentFile
val ffiCrate = File(repoRoot, "apps/desktop/crates/exponential-ui-ffi")
/** The host dylib the JVM unit tests load through JNA (the release build of the facade). */
val cargoTarget = System.getenv("CARGO_TARGET_DIR")?.let(::File) ?: File(repoRoot, "apps/desktop/target")

// The Maven coordinates (the POM maps project dependencies through them).
// `-PuiVersion=…` sets the release version (VAPP-91).
group = "at.exponential"
version = (findProperty("uiVersion") as String?) ?: "0.1.0"

android {
    namespace = "at.exponential.ui"
    compileSdk = 36

    defaultConfig {
        minSdk = 26
        consumerProguardFiles("consumer-rules.pro")
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    sourceSets {
        getByName("main") {
            // The committed UniFFI binding (regenerated by build-android.sh).
            kotlin.srcDir(File(ffiCrate, "bindings/kotlin"))
            // The native facade per ABI (gitignored; build-android.sh writes it).
            jniLibs.srcDir(File(ffiCrate, "out/jniLibs"))
        }
    }

    buildFeatures {
        compose = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.isIncludeAndroidResources = true
        unitTests.isReturnDefaultValues = true
        unitTests.all {
            // JNA finds the facade's host build (`cargo build -p exponential-ui-ffi --release --features cli`).
            it.systemProperty("jna.library.path", File(cargoTarget, "release").absolutePath)
            it.systemProperty("exponential.ui.fixtures", File(repoRoot, "packages/exponential-ui/fixtures").absolutePath)
            it.systemProperty("exponential.ui.record", System.getenv("EXPONENTIAL_UI_RECORD") ?: "")
            // ConformanceTest: the default report path and the renderer version (VAPP-91).
            it.systemProperty("exponential.ui.conformanceReport", File(repoRoot, ".conformance/exponential-ui-compose.json").absolutePath)
            it.systemProperty("exponential.ui.version", project.version.toString())
            it.maxHeapSize = "3g"
            // One JVM per test class: the facade keeps ONE callback vtable per
            // process, registered by whichever classloader loaded the binding
            // last, so plain-JVM and Robolectric-sandbox classes must never
            // share a JVM ("UniffiHandleMap.get: Invalid handle").
            it.forkEvery = 1
            it.maxParallelForks = 2
        }
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}

dependencies {
    api(project(":ui-compose-primitives"))
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.text)
    implementation(libs.compose.foundation)
    implementation(libs.compose.material3)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.android)
    implementation("${libs.jna.aar.get()}@aar")

    testImplementation(libs.junit)
    testImplementation(libs.jna.aar)
    testImplementation(libs.robolectric)
    testImplementation(platform(libs.compose.bom))
    testImplementation(libs.compose.ui.test.junit4)
    testImplementation(libs.compose.ui.test.manifest)
    testImplementation(libs.roborazzi)
    testImplementation(libs.roborazzi.compose)
    testImplementation(libs.roborazzi.junit.rule)
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:${libs.versions.kotlinx.coroutines.get()}")
    androidTestImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.androidx.test.rules)
    androidTestImplementation(platform(libs.compose.bom))
    androidTestImplementation(libs.compose.ui.test.junit4)
    debugImplementation(libs.compose.ui.test.manifest)
}

publishing {
    publications {
        register<MavenPublication>("release") {
            groupId = "at.exponential"
            artifactId = "ui-compose"
            version = project.version.toString()
            afterEvaluate { from(components["release"]) }
            // The rest of the POM (url, licence, developers, scm): the root build script.
            pom {
                name.set("Exponential UI Compose")
                description.set("The Jetpack Compose renderer of the Exponential UI SDK: paints A2UI surfaces at the frames the Rust core computes, with the host runtime (transports, policy, sources).")
            }
        }
    }
}
