// AUTO-GENERATED by packages/domain-contract/scripts/generate.ts — do not edit.
// Single source of truth: packages/domain-contract/contract.json.
#![allow(dead_code)]

pub const ISSUE_STATUS_VALUES: &[&str] = &["backlog", "todo", "in_progress", "done", "cancelled"];
pub const ISSUE_STATUS_DISPLAY_ORDER: &[&str] = &["in_progress", "todo", "backlog", "done", "cancelled"];
pub const ISSUE_PRIORITY_VALUES: &[&str] = &["none", "urgent", "high", "medium", "low"];
pub const ISSUE_PRIORITY_DISPLAY_ORDER: &[&str] = &["urgent", "high", "medium", "low", "none"];
pub const RECURRENCE_UNIT_VALUES: &[&str] = &["day", "week", "month"];
pub const WORKSPACE_ROLE_VALUES: &[&str] = &["owner", "member", "agent"];
pub const PUBLIC_WRITE_POLICY_VALUES: &[&str] = &["members", "everyone"];
pub const COMMENT_KIND_VALUES: &[&str] = &["regular", "question", "plan"];
pub const RECURRENCE_INTERVALS: &[i32] = &[1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 21, 30];

pub const WORKSPACE_ROLE_OWNER: &str = "owner";
pub const WORKSPACE_ROLE_MEMBER: &str = "member";
pub const WORKSPACE_ROLE_AGENT: &str = "agent";
pub const PUBLIC_WRITE_POLICY_MEMBERS: &str = "members";
pub const PUBLIC_WRITE_POLICY_EVERYONE: &str = "everyone";
pub const COMMENT_KIND_REGULAR: &str = "regular";
pub const COMMENT_KIND_QUESTION: &str = "question";
pub const COMMENT_KIND_PLAN: &str = "plan";
