// AUTO-GENERATED by packages/domain-contract/scripts/generate.ts — do not edit.
// Single source of truth: packages/domain-contract/contract.json.
#![allow(dead_code)]

pub const ISSUE_STATUS_VALUES: &[&str] = &["backlog", "todo", "in_progress", "done", "cancelled"];
pub const ISSUE_STATUS_DISPLAY_ORDER: &[&str] = &["in_progress", "todo", "backlog", "done", "cancelled"];
pub const ISSUE_PRIORITY_VALUES: &[&str] = &["none", "urgent", "high", "medium", "low"];
pub const ISSUE_PRIORITY_DISPLAY_ORDER: &[&str] = &["urgent", "high", "medium", "low", "none"];
pub const RECURRENCE_UNIT_VALUES: &[&str] = &["day", "week", "month"];
pub const WORKSPACE_ROLE_VALUES: &[&str] = &["owner", "member", "agent"];
pub const PUBLIC_WRITE_POLICY_VALUES: &[&str] = &["members", "everyone"];
pub const COMMENT_KIND_VALUES: &[&str] = &["regular"];
pub const AGENT_PLAN_STATE_VALUES: &[&str] = &["drafting", "awaiting_approval", "awaiting_answer", "approved", "coding", "planning", "in_review", "pushed"];
pub const NOTIFICATION_TYPE_VALUES: &[&str] = &["issue_assigned", "issue_comment", "issue_status_changed", "issue_mention", "agent_plan_review", "agent_question"];
pub const PR_STATE_VALUES: &[&str] = &["open", "closed", "merged", "draft"];
pub const RUN_MODE_VALUES: &[&str] = &["background", "interactive"];
pub const SUBSCRIBER_SOURCE_VALUES: &[&str] = &["creator", "assignee", "commenter", "manual", "mention"];
pub const ISSUE_EVENT_TYPE_VALUES: &[&str] = &["status_changed", "assignee_changed", "label_added", "label_removed", "pr_opened", "pr_merged", "plan_ready", "agent_error", "agent_started", "agent_question", "agent_answer"];
pub const MODERATION_RESTRICTED_FIELDS: &[&str] = &["status", "priority", "assigneeId", "dueDate", "dueTime", "endTime", "recurrenceInterval", "recurrenceUnit", "archivedAt"];
pub const RECURRENCE_INTERVALS: &[i32] = &[1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 21, 30];

pub const WORKSPACE_ROLE_OWNER: &str = "owner";
pub const WORKSPACE_ROLE_MEMBER: &str = "member";
pub const WORKSPACE_ROLE_AGENT: &str = "agent";
pub const PUBLIC_WRITE_POLICY_MEMBERS: &str = "members";
pub const PUBLIC_WRITE_POLICY_EVERYONE: &str = "everyone";
pub const COMMENT_KIND_REGULAR: &str = "regular";
pub const AGENT_PLAN_STATE_DRAFTING: &str = "drafting";
pub const AGENT_PLAN_STATE_AWAITING_APPROVAL: &str = "awaiting_approval";
pub const AGENT_PLAN_STATE_AWAITING_ANSWER: &str = "awaiting_answer";
pub const AGENT_PLAN_STATE_APPROVED: &str = "approved";
pub const AGENT_PLAN_STATE_CODING: &str = "coding";
pub const AGENT_PLAN_STATE_PLANNING: &str = "planning";
pub const AGENT_PLAN_STATE_IN_REVIEW: &str = "in_review";
pub const AGENT_PLAN_STATE_PUSHED: &str = "pushed";
pub const NOTIFICATION_TYPE_ISSUE_ASSIGNED: &str = "issue_assigned";
pub const NOTIFICATION_TYPE_ISSUE_COMMENT: &str = "issue_comment";
pub const NOTIFICATION_TYPE_ISSUE_STATUS_CHANGED: &str = "issue_status_changed";
pub const NOTIFICATION_TYPE_ISSUE_MENTION: &str = "issue_mention";
pub const NOTIFICATION_TYPE_AGENT_PLAN_REVIEW: &str = "agent_plan_review";
pub const NOTIFICATION_TYPE_AGENT_QUESTION: &str = "agent_question";
pub const PR_STATE_OPEN: &str = "open";
pub const PR_STATE_CLOSED: &str = "closed";
pub const PR_STATE_MERGED: &str = "merged";
pub const PR_STATE_DRAFT: &str = "draft";
pub const RUN_MODE_BACKGROUND: &str = "background";
pub const RUN_MODE_INTERACTIVE: &str = "interactive";
pub const SUBSCRIBER_SOURCE_CREATOR: &str = "creator";
pub const SUBSCRIBER_SOURCE_ASSIGNEE: &str = "assignee";
pub const SUBSCRIBER_SOURCE_COMMENTER: &str = "commenter";
pub const SUBSCRIBER_SOURCE_MANUAL: &str = "manual";
pub const SUBSCRIBER_SOURCE_MENTION: &str = "mention";
pub const ISSUE_EVENT_TYPE_STATUS_CHANGED: &str = "status_changed";
pub const ISSUE_EVENT_TYPE_ASSIGNEE_CHANGED: &str = "assignee_changed";
pub const ISSUE_EVENT_TYPE_LABEL_ADDED: &str = "label_added";
pub const ISSUE_EVENT_TYPE_LABEL_REMOVED: &str = "label_removed";
pub const ISSUE_EVENT_TYPE_PR_OPENED: &str = "pr_opened";
pub const ISSUE_EVENT_TYPE_PR_MERGED: &str = "pr_merged";
pub const ISSUE_EVENT_TYPE_PLAN_READY: &str = "plan_ready";
pub const ISSUE_EVENT_TYPE_AGENT_ERROR: &str = "agent_error";
pub const ISSUE_EVENT_TYPE_AGENT_STARTED: &str = "agent_started";
pub const ISSUE_EVENT_TYPE_AGENT_QUESTION: &str = "agent_question";
pub const ISSUE_EVENT_TYPE_AGENT_ANSWER: &str = "agent_answer";

// --- Agent-core pipeline state machine (consumed by dispatcher.rs / pipeline.rs) ---
pub const AGENT_PIPELINE_NON_TERMINAL_STATUSES: &[&str] = &["queued", "claimed", "planning", "awaiting_approval", "coding", "pushed"];
pub const AGENT_PIPELINE_REENTRY_STATUSES: &[&str] = &["queued", "cancelled", "failed", "awaiting_approval", "needs_human"];
pub const AGENT_PIPELINE_PLAN_REVISION_CAP: i64 = 8;
