#!/usr/bin/env bash
# Writes PeerHello/Sources/Generated/DevTickets.swift from results/.tickets-dev.json (gitignored).
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
J="$HERE/../results/.tickets-dev.json"
GEN="$HERE/PeerHello/Sources/Generated"; mkdir -p "$GEN"
VIEWER=""; SESSION="vapp3-dev"
if [ -f "$J" ]; then
  VIEWER=$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["viewer"])' "$J")
  SESSION=$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["sessionId"])' "$J")
fi
LANIP=$(ipconfig getifaddr en0 2>/dev/null || echo 192.168.178.71)
cat > "$GEN/DevTickets.swift" <<SW
// Generated by write-dev-tickets.sh (gitignored). Dev defaults only.
enum DevTickets {
    static let viewer = "$VIEWER"
    static let sessionId = "$SESSION"
    static let macHost = "$LANIP"
}
SW
echo "wrote $GEN/DevTickets.swift (mac $LANIP)"
