package com.exponential.app.ui.settings

import android.content.Context
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.exponential.app.domain.ThirdPartyNotices
import com.exponential.app.ui.components.EmptyState
import com.exponential.app.ui.icons.ExpIcons
import com.exponential.app.ui.theme.AppBackground
import com.exponential.app.ui.theme.TextEmphasis
import com.exponential.app.ui.theme.glassRow
import dagger.hilt.android.lifecycle.HiltViewModel
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * About → Third-party licenses (EXP-262): `assets/NOTICES.txt` (generated by
 * `@exp/licenses`, packaged automatically by AGP from `src/main/assets/`),
 * split into sections OFF the main thread and rendered one `Text` per section
 * in a `LazyColumn`. Deliberately not `MarkdownView` (commonmark on the main
 * thread on first frame) and not Play's `OssLicensesMenuActivity` (only covers
 * Gradle deps with POM metadata and diverges from the other three clients).
 */
@HiltViewModel
class ThirdPartyLicensesViewModel @Inject constructor(
    @ApplicationContext context: Context,
) : ViewModel() {
    sealed interface State {
        data object Loading : State
        data object Missing : State
        data class Ready(val sections: List<ThirdPartyNotices.Section>) : State
    }

    private val _state = MutableStateFlow<State>(State.Loading)
    val state: StateFlow<State> = _state

    init {
        viewModelScope.launch {
            _state.value = withContext(Dispatchers.IO) {
                runCatching {
                    context.assets.open("NOTICES.txt").bufferedReader().use { it.readText() }
                }.fold(
                    onSuccess = { State.Ready(ThirdPartyNotices.parse(it)) },
                    onFailure = { State.Missing },
                )
            }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ThirdPartyLicensesScreen(
    onBack: () -> Unit,
    viewModel: ThirdPartyLicensesViewModel = hiltViewModel(),
) {
    val state by viewModel.state.collectAsStateWithLifecycle()

    AppBackground {
        Scaffold(
            containerColor = Color.Transparent,
            topBar = {
                TopAppBar(
                    title = { Text("Third-party licenses") },
                    navigationIcon = {
                        IconButton(onClick = onBack) {
                            Icon(ExpIcons.uiBack, contentDescription = "Back")
                        }
                    },
                    colors = TopAppBarDefaults.topAppBarColors(containerColor = Color.Transparent),
                )
            },
        ) { padding ->
            when (val current = state) {
                ThirdPartyLicensesViewModel.State.Loading -> Unit
                ThirdPartyLicensesViewModel.State.Missing ->
                    androidx.compose.foundation.layout.Box(
                        Modifier.padding(padding).fillMaxSize(),
                    ) {
                        EmptyState(message = "The bundled notices file is missing from this build.")
                    }
                is ThirdPartyLicensesViewModel.State.Ready ->
                    LazyColumn(
                        modifier = Modifier.padding(padding).fillMaxSize(),
                        contentPadding = PaddingValues(16.dp),
                        verticalArrangement = Arrangement.spacedBy(12.dp),
                    ) {
                        item {
                            Text(
                                "Exponential is built with open-source software. These licenses cover the components bundled in this build.",
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.onSurface.copy(
                                    alpha = TextEmphasis.Secondary,
                                ),
                                modifier = Modifier.padding(horizontal = 4.dp),
                            )
                        }
                        itemsIndexed(current.sections) { _, section ->
                            SectionBlock(section)
                        }
                    }
            }
        }
    }
}

@Composable
private fun SectionBlock(section: ThirdPartyNotices.Section) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .glassRow()
            .padding(horizontal = 14.dp, vertical = 12.dp),
        verticalArrangement = Arrangement.spacedBy(6.dp),
    ) {
        if (section.title.isNotEmpty()) {
            Text(
                section.title,
                style = MaterialTheme.typography.labelMedium,
                color = MaterialTheme.colorScheme.onSurface,
            )
        }
        Text(
            section.body,
            style = MaterialTheme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace),
            color = MaterialTheme.colorScheme.onSurface.copy(alpha = TextEmphasis.Secondary),
        )
    }
}
