// AUTO-GENERATED by packages/design-tokens/scripts/generate.ts — do not edit.
// Single source of truth: packages/design-tokens/tokens.json.

package com.exponential.app.ui.theme

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.animation.core.Easing
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object DesignTokens {
    // Forced-dark surface palette, derived from the web OKLCH theme.
    object Palette {
        val Background: Color = Color(0xFF0A0A0A)
        val Foreground: Color = Color(0xFFFAFAFA)
        val Card: Color = Color(0xFF171717)
        val CardForeground: Color = Color(0xFFFAFAFA)
        val Popover: Color = Color(0xFF171717)
        val PopoverForeground: Color = Color(0xFFFAFAFA)
        val Primary: Color = Color(0xFFE5E5E5)
        val PrimaryForeground: Color = Color(0xFF171717)
        val Secondary: Color = Color(0xFF262626)
        val SecondaryForeground: Color = Color(0xFFFAFAFA)
        val Muted: Color = Color(0xFF262626)
        val MutedForeground: Color = Color(0xFFA1A1A1)
        val Accent: Color = Color(0xFF262626)
        val AccentForeground: Color = Color(0xFFFAFAFA)
        val Destructive: Color = Color(0xFFFF6467)
        val Border: Color = Color(0x1AFFFFFF)
        val Input: Color = Color(0x26FFFFFF)
        val Ring: Color = Color(0xFF737373)
        val Sidebar: Color = Color(0xFF171717)
        val SidebarForeground: Color = Color(0xFFFAFAFA)
        val SidebarAccent: Color = Color(0xFF262626)
        val SidebarBorder: Color = Color(0x1AFFFFFF)
    }

    // Fixed brand accents (status / priority / due-date).
    object Semantic {
        val Neutral: Color = Color(0xFFA1A1AA)
        val Yellow: Color = Color(0xFFFACC15)
        val Green: Color = Color(0xFF22C55E)
        val Red: Color = Color(0xFFEF4444)
        val Orange: Color = Color(0xFFF97316)
        val Blue: Color = Color(0xFF3B82F6)
        val CodeText: Color = Color(0xFF8AB4F8)
        val CodeFill: Color = Color(0x1F8AB4F8)
        val CodeStroke: Color = Color(0x338AB4F8)
    }

    // Avatar fallback hues (EXP-698 r4) — index = fnv1a32(userId) % Hues.size,
    // see ui/components/Avatars.kt. Order is the contract; never reorder.
    object Avatar {
        val Red: Color = Color(0xFFF87171)
        val Orange: Color = Color(0xFFFB923C)
        val Yellow: Color = Color(0xFFFACC15)
        val Green: Color = Color(0xFF4ADE80)
        val Teal: Color = Color(0xFF2DD4BF)
        val Blue: Color = Color(0xFF60A5FA)
        val Violet: Color = Color(0xFFA78BFA)
        val Pink: Color = Color(0xFFF472B6)
        val Hues: List<Color> = listOf(Red, Orange, Yellow, Green, Teal, Blue, Violet, Pink)
    }

    // Glass surfaces (EXP-269) — read through the ui/theme/Glass.kt GlassTokens
    // aliases; the styleguide Components group renders the same values (EXP-698).
    object Glass {
        val BackgroundTop: Color = Color(0xFF09090B)
        val BackgroundBottom: Color = Color(0xFF18181B)
        val FillSection: Color = Color(0x0AFFFFFF)
        val FillRow: Color = Color(0x0DFFFFFF)
        val FillCard: Color = Color(0x0FFFFFFF)
        val FillActive: Color = Color(0x26FFFFFF)
        val StrokeRow: Color = Color(0x0FFFFFFF)
        val StrokeSection: Color = Color(0x14FFFFFF)
        val StrokeCard: Color = Color(0x1AFFFFFF)
        val StrokeStrong: Color = Color(0x1FFFFFFF)
        val StrokeActive: Color = Color(0x33FFFFFF)
    }

    // Corner radii (px ≡ dp), matching the web rounded-* scale.
    object Radius {
        val Sm: Dp = 8.dp
        val Md: Dp = 10.dp
        val Lg: Dp = 12.dp
        val Xl: Dp = 16.dp
        val Xl2: Dp = 20.dp
        val Xl3: Dp = 24.dp
    }

    // Control geometry, matching the web control heights.
    object Size {
        val ControlLg: Dp = 36.dp
        val ControlMd: Dp = 32.dp
        val ControlSm: Dp = 24.dp
        val InputHeight: Dp = 36.dp
        val RowHeight: Dp = 32.dp
    }

    // Motion (EXP-523) — durations in MILLISECONDS (Compose's `tween` unit),
    // easings as CSS cubic-bezier control points. Read these through
    // ui/theme/Motion.kt, which collapses them to `snap()` when the OS has
    // animations turned off; never call `tween(…)` with a literal.
    object Motion {
        object Duration {
            const val Fast: Int = 120
            const val Standard: Int = 180
            const val Slow: Int = 280
        }

        object Ease {
            val Standard: Easing = CubicBezierEasing(0.2f, 0.0f, 0.0f, 1.0f)
            val Decelerate: Easing = CubicBezierEasing(0.0f, 0.0f, 0.2f, 1.0f)
            val Accelerate: Easing = CubicBezierEasing(0.3f, 0.0f, 1.0f, 1.0f)
        }
    }
}
