// AUTO-GENERATED by packages/design-tokens/scripts/generate.ts — do not edit.
// Single source of truth: packages/design-tokens/tokens.json.

package com.exponential.app.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object DesignTokens {
    // Forced-dark surface palette, derived from the web OKLCH theme.
    object Palette {
        val Background: Color = Color(0xFF0A0A0A)
        val Foreground: Color = Color(0xFFFAFAFA)
        val Card: Color = Color(0xFF171717)
        val CardForeground: Color = Color(0xFFFAFAFA)
        val Popover: Color = Color(0xFF171717)
        val PopoverForeground: Color = Color(0xFFFAFAFA)
        val Primary: Color = Color(0xFFE5E5E5)
        val PrimaryForeground: Color = Color(0xFF171717)
        val Secondary: Color = Color(0xFF262626)
        val SecondaryForeground: Color = Color(0xFFFAFAFA)
        val Muted: Color = Color(0xFF262626)
        val MutedForeground: Color = Color(0xFFA1A1A1)
        val Accent: Color = Color(0xFF262626)
        val AccentForeground: Color = Color(0xFFFAFAFA)
        val Destructive: Color = Color(0xFFFF6467)
        val Border: Color = Color(0x1AFFFFFF)
        val Input: Color = Color(0x26FFFFFF)
        val Ring: Color = Color(0xFF737373)
        val Sidebar: Color = Color(0xFF171717)
        val SidebarForeground: Color = Color(0xFFFAFAFA)
        val SidebarAccent: Color = Color(0xFF262626)
        val SidebarBorder: Color = Color(0x1AFFFFFF)
    }

    // Fixed brand accents (status / priority / due-date).
    object Semantic {
        val Neutral: Color = Color(0xFFA1A1AA)
        val Yellow: Color = Color(0xFFFACC15)
        val Green: Color = Color(0xFF22C55E)
        val Red: Color = Color(0xFFEF4444)
        val Orange: Color = Color(0xFFF97316)
        val Blue: Color = Color(0xFF3B82F6)
    }

    // Corner radii (px ≡ dp), matching the web rounded-* scale.
    object Radius {
        val Sm: Dp = 6.dp
        val Md: Dp = 8.dp
        val Lg: Dp = 10.dp
        val Xl: Dp = 14.dp
    }

    // Control geometry, matching the web control heights.
    object Size {
        val ControlLg: Dp = 36.dp
        val ControlMd: Dp = 32.dp
        val ControlSm: Dp = 24.dp
        val InputHeight: Dp = 36.dp
        val RowHeight: Dp = 32.dp
    }
}
