//! EXP-551: the emoji catalog — the shared dataset plus the search / recents
//! rules the emoji picker and the `:shortcode` typeahead run on.
//!
//! `assets/emoji.json` is GENERATED by `packages/emoji` (never hand-edited)
//! and shipped byte-identical to web, iOS and Android, so `smi` ranks the same
//! glyphs on every client. The ranking and recents rules below are the
//! hand-mirrored twins of `apps/web/src/lib/emoji.ts`
//! (`EmojiCatalog.swift` / `EmojiCatalog.kt` mirror the same).
//!
//! Pickers insert the UNICODE — never `:shortcode:` text — because
//! `issues.description` / `comments.body` are plain GFM shared with clients
//! that render only unicode.

use std::collections::HashMap;
use std::sync::OnceLock;

use gpui::App;
use serde::Deserialize;

/// The generated dataset, embedded (~245KB) like every other desktop asset —
/// a runtime file read would have to survive the .app/.AppImage/.exe layouts.
const EMOJI_JSON: &str = include_str!("../../../assets/emoji.json");

/// One dataset record. The short field names are the generator's (the file is
/// one record per line and ships in four apps, so the bytes matter).
#[derive(Debug, Clone, Deserialize)]
pub(crate) struct EmojiRecord {
    /// The unicode to INSERT. Opaque: some records end in U+FE0F (the
    /// emoji-style variation selector) and must never be trimmed.
    #[serde(rename = "u")]
    pub unicode: String,
    /// CLDR-ish display name (`grinning face`).
    #[serde(rename = "l")]
    pub label: String,
    /// Index into [`EmojiCatalog::groups`].
    #[serde(rename = "g")]
    pub group: usize,
    /// GitHub shortcodes WITHOUT the colons.
    #[serde(rename = "s", default)]
    pub shortcodes: Vec<String>,
    /// Search keywords (already lowercased by the generator).
    #[serde(rename = "t", default)]
    pub tags: Vec<String>,
    // The dataset's `k` skin-tone variants are deliberately unread (EXP-600:
    // pickers only ever offer/insert the base yellow glyph).
}

#[derive(Debug, Deserialize)]
struct RawDataset {
    #[allow(dead_code)]
    version: String,
    groups: Vec<String>,
    emojis: Vec<EmojiRecord>,
}

/// The parsed dataset plus the two lookup indexes every surface needs.
pub(crate) struct EmojiCatalog {
    groups: Vec<String>,
    emojis: Vec<EmojiRecord>,
    /// Lowercased shortcode → record index (first record wins on collisions,
    /// web parity).
    by_shortcode: HashMap<String, usize>,
    /// Base unicode → record index (the recents list stores base unicodes).
    by_unicode: HashMap<String, usize>,
    /// Record indices per group, in dataset order.
    group_members: Vec<Vec<usize>>,
}

/// The catalog, parsed once per process on first use.
pub(crate) fn catalog() -> &'static EmojiCatalog {
    static CATALOG: OnceLock<EmojiCatalog> = OnceLock::new();
    CATALOG.get_or_init(|| {
        let raw: RawDataset =
            serde_json::from_str(EMOJI_JSON).expect("assets/emoji.json is generated and valid");
        let mut by_shortcode = HashMap::new();
        let mut by_unicode = HashMap::new();
        let mut group_members = vec![Vec::new(); raw.groups.len()];
        for (index, emoji) in raw.emojis.iter().enumerate() {
            by_unicode.entry(emoji.unicode.clone()).or_insert(index);
            for code in &emoji.shortcodes {
                by_shortcode.entry(code.to_lowercase()).or_insert(index);
            }
            if let Some(members) = group_members.get_mut(emoji.group) {
                members.push(index);
            }
        }
        EmojiCatalog {
            groups: raw.groups,
            emojis: raw.emojis,
            by_shortcode,
            by_unicode,
            group_members,
        }
    })
}

impl EmojiCatalog {
    pub(crate) fn groups(&self) -> &[String] {
        &self.groups
    }

    /// The whole dataset in order (test-only — every surface goes through
    /// [`Self::search`] or [`Self::group`]).
    #[cfg(test)]
    pub(crate) fn emojis(&self) -> &[EmojiRecord] {
        &self.emojis
    }

    /// The records of one group, in dataset order.
    pub(crate) fn group(&self, index: usize) -> &[usize] {
        self.group_members
            .get(index)
            .map(Vec::as_slice)
            .unwrap_or_default()
    }

    pub(crate) fn get(&self, index: usize) -> Option<&EmojiRecord> {
        self.emojis.get(index)
    }

    /// Base-unicode lookup — resolves a stored recent back to its dataset
    /// index (an unknown/retired unicode simply drops out of the row).
    pub(crate) fn index_of_unicode(&self, unicode: &str) -> Option<usize> {
        self.by_unicode.get(unicode).copied()
    }

    /// Exact shortcode lookup (`tada` → 🎉) — what the `:tada:` auto-commit
    /// resolves against.
    pub(crate) fn find_shortcode(&self, shortcode: &str) -> Option<&EmojiRecord> {
        self.by_shortcode
            .get(&shortcode.to_lowercase())
            .and_then(|index| self.emojis.get(*index))
    }

    /// Ranked search (web `searchEmoji`): exact shortcode > shortcode prefix >
    /// label prefix > tag exact/prefix > label/tag substring; ties keep
    /// dataset order. An empty query matches NOTHING (the picker shows its
    /// Recent + group grid instead). Returns dataset INDICES — both callers
    /// (the picker grid and the typeahead) key on them.
    pub(crate) fn search(&self, query: &str, limit: usize) -> Vec<usize> {
        let needle = normalize_query(query);
        if needle.is_empty() || limit == 0 {
            return Vec::new();
        }
        let mut scored: Vec<(u8, usize)> = self
            .emojis
            .iter()
            .enumerate()
            .filter_map(|(order, emoji)| rank(emoji, &needle).map(|rank| (rank, order)))
            .collect();
        scored.sort_by(|a, b| a.0.cmp(&b.0).then_with(|| a.1.cmp(&b.1)));
        scored.truncate(limit);
        scored.into_iter().map(|(_, order)| order).collect()
    }
}

/// Web parity: the query is lowercased and stripped of ONE leading and one
/// trailing colon, so `:tada:` and `tada` search alike.
fn normalize_query(query: &str) -> String {
    let trimmed = query.trim().to_lowercase();
    let trimmed = trimmed.strip_prefix(':').unwrap_or(&trimmed);
    trimmed.strip_suffix(':').unwrap_or(trimmed).to_string()
}

/// Lower rank = better. `None` = no match. Mirrors web `rankEmoji`.
fn rank(emoji: &EmojiRecord, needle: &str) -> Option<u8> {
    let label = emoji.label.to_lowercase();
    if emoji
        .shortcodes
        .iter()
        .any(|code| code.to_lowercase() == needle)
    {
        return Some(0);
    }
    if emoji
        .shortcodes
        .iter()
        .any(|code| code.to_lowercase().starts_with(needle))
    {
        return Some(1);
    }
    if label.starts_with(needle) {
        return Some(2);
    }
    if emoji
        .tags
        .iter()
        .any(|tag| tag == needle || tag.starts_with(needle))
    {
        return Some(3);
    }
    if label.contains(needle) || emoji.tags.iter().any(|tag| tag.contains(needle)) {
        return Some(4);
    }
    None
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

/// The platform's COLOR emoji face. gpui's fallback chain can reach a
/// monochrome symbol font first (EXP-600: the picker drew ☺-style outlines),
/// so every emoji-glyph surface names the color font explicitly — the web
/// `.emoji-glyph` utility's twin. A glyph the named face lacks still falls
/// back through the system chain.
#[cfg(target_os = "macos")]
pub(crate) const EMOJI_FONT_FAMILY: &str = "Apple Color Emoji";
#[cfg(target_os = "windows")]
pub(crate) const EMOJI_FONT_FAMILY: &str = "Segoe UI Emoji";
#[cfg(not(any(target_os = "macos", target_os = "windows")))]
pub(crate) const EMOJI_FONT_FAMILY: &str = "Noto Color Emoji";

// ---------------------------------------------------------------------------
// Per-install prefs (recents)
// ---------------------------------------------------------------------------

/// How many recent picks the picker remembers (web `MAX_RECENT_EMOJI`).
pub(crate) const MAX_RECENT_EMOJI: usize = 24;

/// Recently picked BASE unicodes, most recent first. Persisted in the
/// per-install `settings.json` — the app's ONE merge-preserving local store,
/// next to the rail state (EXP-282's precedent); emoji prefs are per-DEVICE,
/// never synced.
///
/// READS go through the non-creating `global_ref`: materializing the coding
/// hub kicks a doctor run (and a store read), which opening an emoji picker
/// has no business doing.
pub(crate) fn recent_emoji(cx: &App) -> Vec<String> {
    let mut recents = crate::coding_flow::CodingHub::global_ref(cx)
        .map(|hub| hub.read(cx).settings.emoji_recents.clone())
        .unwrap_or_default();
    recents.truncate(MAX_RECENT_EMOJI);
    recents
}

/// Record a pick at the head of the recents list (deduped, capped).
pub(crate) fn push_recent_emoji(cx: &mut App, unicode: &str) {
    // Materializing the hub reads the synced Store; a Store-less context
    // (the typeahead unit tests) simply drops the recent.
    if crate::coding_flow::CodingHub::global_ref(cx).is_none()
        && sync::Store::try_global(cx).is_none()
    {
        return;
    }
    let hub = crate::coding_flow::CodingHub::global(cx);
    let mut settings = hub.read(cx).settings.clone();
    settings.emoji_recents = next_recents(&settings.emoji_recents, unicode);
    crate::coding_flow::CodingHub::save_ui_prefs(&hub, settings, cx);
}

/// The pure recents rule (web `pushRecentEmoji`): newest first, deduped,
/// capped at [`MAX_RECENT_EMOJI`].
fn next_recents(current: &[String], unicode: &str) -> Vec<String> {
    let mut next = Vec::with_capacity(current.len() + 1);
    next.push(unicode.to_string());
    next.extend(
        current
            .iter()
            .filter(|item| item.as_str() != unicode)
            .cloned(),
    );
    next.truncate(MAX_RECENT_EMOJI);
    next
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generated asset must parse, and its shape is the contract the
    /// other three clients read (`packages/emoji/README.md`).
    #[test]
    fn the_generated_dataset_parses() {
        let catalog = catalog();
        assert_eq!(catalog.groups().len(), 9);
        assert_eq!(catalog.emojis().len(), 1906);
        // Every record lands in exactly one group bucket.
        let grouped: usize = (0..catalog.groups().len())
            .map(|index| catalog.group(index).len())
            .sum();
        assert_eq!(grouped, catalog.emojis().len());
    }

    #[test]
    fn shortcode_lookup_is_case_insensitive() {
        let catalog = catalog();
        let tada = catalog.find_shortcode("tada").expect("tada");
        assert_eq!(tada.unicode, "🎉");
        assert_eq!(
            catalog.find_shortcode("TADA").map(|e| e.unicode.as_str()),
            Some("🎉")
        );
        assert!(catalog.find_shortcode("definitely-not-an-emoji").is_none());
    }

    #[test]
    fn an_empty_query_matches_nothing() {
        assert!(catalog().search("", 64).is_empty());
        assert!(catalog().search("   ", 64).is_empty());
    }

    /// The first hit's unicode, or `None`.
    fn top(query: &str) -> Option<String> {
        let catalog = catalog();
        catalog
            .search(query, 8)
            .first()
            .and_then(|index| catalog.get(*index))
            .map(|emoji| emoji.unicode.clone())
    }

    #[test]
    fn search_ranks_exact_shortcodes_first() {
        // `+1` is ONLY reachable as a shortcode — no label or tag contains it.
        // Its `u` carries a trailing U+FE0F (emoji-style variation selector):
        // the field is OPAQUE and must be inserted verbatim.
        assert_eq!(top("+1").as_deref(), Some("👍\u{fe0f}"));
        // A colon-wrapped query is the same query (`:tada:` == `tada`).
        assert_eq!(top(":tada:").as_deref(), Some("🎉"));
    }

    /// The variation selector is part of the record and never trimmed — a
    /// stripped `u` would render text-style on some platforms.
    #[test]
    fn variation_selectors_survive_lookup() {
        let catalog = catalog();
        let thumbs = catalog.find_shortcode("+1").expect("+1");
        assert!(thumbs.unicode.ends_with('\u{fe0f}'));
        assert_eq!(
            catalog.index_of_unicode(&thumbs.unicode),
            catalog.index_of_unicode("👍\u{fe0f}")
        );
    }

    #[test]
    fn search_prefers_the_smile_family_for_a_prefix() {
        let catalog = catalog();
        let hits = catalog.search("smi", 8);
        assert!(!hits.is_empty());
        // Rank 1 (shortcode prefix) beats every label/tag substring hit.
        let first = catalog.get(hits[0]).expect("record");
        assert!(first.shortcodes.iter().any(|code| code.starts_with("smi")));
    }

    #[test]
    fn search_is_capped_and_case_insensitive() {
        assert!(catalog().search("a", 64).len() <= 64);
        assert_eq!(top("GRINNING"), top("grinning"));
    }

    /// EXP-600: pickers only ever offer the base yellow glyph — a toned `k`
    /// variant never leaves a picker, so the base unicode IS the insert.
    #[test]
    fn toned_variants_are_never_offered() {
        let catalog = catalog();
        let wave = catalog.find_shortcode("wave").expect("wave");
        assert!(!wave.unicode.contains('\u{1F3FF}'));
    }

    #[test]
    fn recents_resolve_back_to_records() {
        let catalog = catalog();
        let index = catalog.index_of_unicode("🎉").expect("indexed");
        assert_eq!(catalog.get(index).map(|e| e.unicode.as_str()), Some("🎉"));
        assert_eq!(catalog.index_of_unicode("not an emoji"), None);
    }

    #[test]
    fn recents_dedupe_and_cap() {
        let mut recents: Vec<String> = Vec::new();
        recents = next_recents(&recents, "🎉");
        recents = next_recents(&recents, "👍");
        recents = next_recents(&recents, "🎉");
        assert_eq!(recents, vec!["🎉".to_string(), "👍".to_string()]);
        for emoji in catalog().emojis().iter().take(MAX_RECENT_EMOJI + 10) {
            recents = next_recents(&recents, &emoji.unicode);
        }
        assert_eq!(recents.len(), MAX_RECENT_EMOJI);
    }
}
