// AUTO-GENERATED by packages/icons/scripts/generate.ts — do not edit.
// Source of truth: packages/icons/icons.json + lucide-react's shipped geometry.
//
// The icon geometry reproduced in this file is from Lucide
// (https://lucide.dev) and is licensed ISC. Glyphs listed under icons.json
// `custom` are Exponential's own work, licensed Apache-2.0 with the rest of
// this repository (see the top-level LICENSE).
//
// ISC License
//
// Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as
// part of Feather (MIT). All other copyright (c) for Lucide are held by
// Lucide Contributors 2022.
//
// Permission to use, copy, modify, and/or distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//
// `ExpIcon` variants come from the `icon_named!` macro scanning
// `apps/desktop/assets/icons`, which this generator also populates — so every
// arm below is guaranteed to have its SVG on disk.
//
// Included via `include!` from icons.rs, which carries the `allow(dead_code)`
// — the registry is shared by four clients, so most concepts have no desktop
// call site yet.

use crate::icons::ExpIcon;

/// One pickable icon name (board icons + action icons), in display order.
pub const PICKABLE_ICONS: &[&str] = &[
    "code",
    "square-kanban",
    "megaphone",
    "bug",
    "rocket",
    "book-open",
    "globe",
    "heart",
    "star",
    "zap",
    "wrench",
    "shield",
    "package",
    "terminal",
    "lightbulb",
    "message-circle",
    "palette",
    "pen-tool",
    "database",
    "server",
    "cloud",
    "cpu",
    "layers",
    "boxes",
    "folder",
    "file-text",
    "calendar",
    "clock",
    "users",
    "user",
    "flag",
    "target",
    "trophy",
    "lock",
    "key",
    "mail",
    "phone",
    "bell",
    "git-branch",
    "bot",
    "sparkles",
    "flask-conical",
    "shopping-cart",
    "credit-card",
    "map-pin",
    "compass",
    "briefcase",
    "graduation-cap",
    "puzzle",
    "gamepad-2",
    "coffee",
    "plane",
    "house",
    "building",
    "leaf",
    "sun",
    "activity",
    "chart-line",
    "scale",
    "car",
];

/// A pickable/stored icon name -> its glyph. `None` for an unknown name so
/// callers can apply their own fallback.
pub fn icon_by_name(name: &str) -> Option<ExpIcon> {
    Some(match name {
        "activity" => ExpIcon::Activity,
        "archive" => ExpIcon::Archive,
        "arrow-down-left" => ExpIcon::ArrowDownLeft,
        "arrow-left" => ExpIcon::ArrowLeft,
        "arrow-left-right" => ExpIcon::ArrowLeftRight,
        "arrow-right" => ExpIcon::ArrowRight,
        "arrow-up-right" => ExpIcon::ArrowUpRight,
        "at-sign" => ExpIcon::AtSign,
        "bell" => ExpIcon::Bell,
        "bell-off" => ExpIcon::BellOff,
        "bold" => ExpIcon::Bold,
        "book-open" => ExpIcon::BookOpen,
        "bot" => ExpIcon::Bot,
        "boxes" => ExpIcon::Boxes,
        "briefcase" => ExpIcon::Briefcase,
        "brush-cleaning" => ExpIcon::BrushCleaning,
        "bug" => ExpIcon::Bug,
        "building" => ExpIcon::Building,
        "building-2" => ExpIcon::Building2,
        "calendar" => ExpIcon::Calendar,
        "calendar-days" => ExpIcon::CalendarDays,
        "car" => ExpIcon::Car,
        "chart-line" => ExpIcon::ChartLine,
        "check" => ExpIcon::Check,
        "chevron-down" => ExpIcon::ChevronDown,
        "chevron-left" => ExpIcon::ChevronLeft,
        "chevron-right" => ExpIcon::ChevronRight,
        "chevron-up" => ExpIcon::ChevronUp,
        "chevrons-up-down" => ExpIcon::ChevronsUpDown,
        "circle" => ExpIcon::Circle,
        "circle-arrow-up" => ExpIcon::CircleArrowUp,
        "circle-check" => ExpIcon::CircleCheck,
        "circle-dashed" => ExpIcon::CircleDashed,
        "circle-dot" => ExpIcon::CircleDot,
        "circle-question-mark" => ExpIcon::CircleQuestionMark,
        "circle-user" => ExpIcon::CircleUser,
        "circle-x" => ExpIcon::CircleX,
        "clipboard-list" => ExpIcon::ClipboardList,
        "clock" => ExpIcon::Clock,
        "cloud" => ExpIcon::Cloud,
        "code" => ExpIcon::Code,
        "coffee" => ExpIcon::Coffee,
        "compass" => ExpIcon::Compass,
        "copy" => ExpIcon::Copy,
        "cpu" => ExpIcon::Cpu,
        "credit-card" => ExpIcon::CreditCard,
        "crown" => ExpIcon::Crown,
        "database" => ExpIcon::Database,
        "download" => ExpIcon::Download,
        "ellipsis" => ExpIcon::Ellipsis,
        "ellipsis-vertical" => ExpIcon::EllipsisVertical,
        "external-link" => ExpIcon::ExternalLink,
        "eye" => ExpIcon::Eye,
        "file" => ExpIcon::File,
        "file-diff" => ExpIcon::FileDiff,
        "file-text" => ExpIcon::FileText,
        "flag" => ExpIcon::Flag,
        "flask-conical" => ExpIcon::FlaskConical,
        "folder" => ExpIcon::Folder,
        "folder-kanban" => ExpIcon::FolderKanban,
        "folder-open" => ExpIcon::FolderOpen,
        "gamepad-2" => ExpIcon::Gamepad2,
        "git-branch" => ExpIcon::GitBranch,
        "git-merge" => ExpIcon::GitMerge,
        "git-pull-request" => ExpIcon::GitPullRequest,
        "github" => ExpIcon::Github,
        "globe" => ExpIcon::Globe,
        "graduation-cap" => ExpIcon::GraduationCap,
        "hard-drive" => ExpIcon::HardDrive,
        "hash" => ExpIcon::Hash,
        "heading-1" => ExpIcon::Heading1,
        "heading-2" => ExpIcon::Heading2,
        "heading-3" => ExpIcon::Heading3,
        "heart" => ExpIcon::Heart,
        "house" => ExpIcon::House,
        "image" => ExpIcon::Image,
        "inbox" => ExpIcon::Inbox,
        "info" => ExpIcon::Info,
        "italic" => ExpIcon::Italic,
        "key" => ExpIcon::Key,
        "layers" => ExpIcon::Layers,
        "leaf" => ExpIcon::Leaf,
        "life-buoy" => ExpIcon::LifeBuoy,
        "lightbulb" => ExpIcon::Lightbulb,
        "link" => ExpIcon::Link,
        "list" => ExpIcon::List,
        "list-checks" => ExpIcon::ListChecks,
        "list-filter" => ExpIcon::ListFilter,
        "list-ordered" => ExpIcon::ListOrdered,
        "list-todo" => ExpIcon::ListTodo,
        "loader-circle" => ExpIcon::LoaderCircle,
        "lock" => ExpIcon::Lock,
        "log-in" => ExpIcon::LogIn,
        "log-out" => ExpIcon::LogOut,
        "mail" => ExpIcon::Mail,
        "map-pin" => ExpIcon::MapPin,
        "megaphone" => ExpIcon::Megaphone,
        "message-circle" => ExpIcon::MessageCircle,
        "message-square" => ExpIcon::MessageSquare,
        "message-square-plus" => ExpIcon::MessageSquarePlus,
        "minus" => ExpIcon::Minus,
        "monitor" => ExpIcon::Monitor,
        "monitor-off" => ExpIcon::MonitorOff,
        "move" => ExpIcon::Move,
        "package" => ExpIcon::Package,
        "palette" => ExpIcon::Palette,
        "panel-left-close" => ExpIcon::PanelLeftClose,
        "panel-left-open" => ExpIcon::PanelLeftOpen,
        "paperclip" => ExpIcon::Paperclip,
        "pen-tool" => ExpIcon::PenTool,
        "pencil" => ExpIcon::Pencil,
        "phone" => ExpIcon::Phone,
        "plane" => ExpIcon::Plane,
        "play" => ExpIcon::Play,
        "plug" => ExpIcon::Plug,
        "plus" => ExpIcon::Plus,
        "progress-1-4" => ExpIcon::Progress14,
        "progress-1-5" => ExpIcon::Progress15,
        "progress-2-4" => ExpIcon::Progress24,
        "progress-2-5" => ExpIcon::Progress25,
        "progress-3-4" => ExpIcon::Progress34,
        "progress-3-5" => ExpIcon::Progress35,
        "progress-4-5" => ExpIcon::Progress45,
        "puzzle" => ExpIcon::Puzzle,
        "quote" => ExpIcon::Quote,
        "refresh-cw" => ExpIcon::RefreshCw,
        "remove-formatting" => ExpIcon::RemoveFormatting,
        "repeat" => ExpIcon::Repeat,
        "rocket" => ExpIcon::Rocket,
        "scale" => ExpIcon::Scale,
        "search" => ExpIcon::Search,
        "search-x" => ExpIcon::SearchX,
        "send" => ExpIcon::Send,
        "server" => ExpIcon::Server,
        "settings" => ExpIcon::Settings,
        "share-2" => ExpIcon::Share2,
        "shield" => ExpIcon::Shield,
        "shield-check" => ExpIcon::ShieldCheck,
        "shield-question-mark" => ExpIcon::ShieldQuestionMark,
        "shopping-cart" => ExpIcon::ShoppingCart,
        "signal-high" => ExpIcon::SignalHigh,
        "signal-low" => ExpIcon::SignalLow,
        "signal-medium" => ExpIcon::SignalMedium,
        "sliders-horizontal" => ExpIcon::SlidersHorizontal,
        "smile" => ExpIcon::Smile,
        "sparkles" => ExpIcon::Sparkles,
        "square-kanban" => ExpIcon::SquareKanban,
        "square-pen" => ExpIcon::SquarePen,
        "square-terminal" => ExpIcon::SquareTerminal,
        "star" => ExpIcon::Star,
        "strikethrough" => ExpIcon::Strikethrough,
        "sun" => ExpIcon::Sun,
        "tag" => ExpIcon::Tag,
        "target" => ExpIcon::Target,
        "terminal" => ExpIcon::Terminal,
        "trash-2" => ExpIcon::Trash2,
        "triangle-alert" => ExpIcon::TriangleAlert,
        "trophy" => ExpIcon::Trophy,
        "undo-2" => ExpIcon::Undo2,
        "unlink" => ExpIcon::Unlink,
        "upload" => ExpIcon::Upload,
        "user" => ExpIcon::User,
        "user-minus" => ExpIcon::UserMinus,
        "user-plus" => ExpIcon::UserPlus,
        "user-x" => ExpIcon::UserX,
        "users" => ExpIcon::Users,
        "wifi-off" => ExpIcon::WifiOff,
        "wrench" => ExpIcon::Wrench,
        "x" => ExpIcon::X,
        "zap" => ExpIcon::Zap,
        _ => return None,
    })
}

/// Registry concept `action-automation` -> Lucide `zap`.
pub const ACTION_AUTOMATION: ExpIcon = ExpIcon::Zap;
/// Registry concept `action-create` -> Lucide `plus`.
pub const ACTION_CREATE: ExpIcon = ExpIcon::Plus;
/// Registry concept `action-default` -> Lucide `zap`.
pub const ACTION_DEFAULT: ExpIcon = ExpIcon::Zap;
/// Registry concept `action-repository` -> Lucide `git-branch`.
pub const ACTION_REPOSITORY: ExpIcon = ExpIcon::GitBranch;
/// Registry concept `action-run` -> Lucide `play`.
pub const ACTION_RUN: ExpIcon = ExpIcon::Play;
/// Registry concept `action-suggestion` -> Lucide `lightbulb`.
pub const ACTION_SUGGESTION: ExpIcon = ExpIcon::Lightbulb;
/// Registry concept `coding-assistant` -> Lucide `sparkles`.
pub const CODING_ASSISTANT: ExpIcon = ExpIcon::Sparkles;
/// Registry concept `coding-diff` -> Lucide `file-diff`.
pub const CODING_DIFF: ExpIcon = ExpIcon::FileDiff;
/// Registry concept `coding-ended` -> Lucide `circle-check`.
pub const CODING_ENDED: ExpIcon = ExpIcon::CircleCheck;
/// Registry concept `coding-in-review` -> Lucide `git-pull-request`.
pub const CODING_IN_REVIEW: ExpIcon = ExpIcon::GitPullRequest;
/// Registry concept `coding-needs-input` -> Lucide `triangle-alert`.
pub const CODING_NEEDS_INPUT: ExpIcon = ExpIcon::TriangleAlert;
/// Registry concept `coding-plan` -> Lucide `clipboard-list`.
pub const CODING_PLAN: ExpIcon = ExpIcon::ClipboardList;
/// Registry concept `coding-running` -> Lucide `play`.
pub const CODING_RUNNING: ExpIcon = ExpIcon::Play;
/// Registry concept `coding-stop` -> Lucide `circle-x`.
pub const CODING_STOP: ExpIcon = ExpIcon::CircleX;
/// Registry concept `coding-subagent` -> Lucide `bot`.
pub const CODING_SUBAGENT: ExpIcon = ExpIcon::Bot;
/// Registry concept `coding-tool` -> Lucide `wrench`.
pub const CODING_TOOL: ExpIcon = ExpIcon::Wrench;
/// Registry concept `editor-bold` -> Lucide `bold`.
pub const EDITOR_BOLD: ExpIcon = ExpIcon::Bold;
/// Registry concept `editor-clear-formatting` -> Lucide `remove-formatting`.
pub const EDITOR_CLEAR_FORMATTING: ExpIcon = ExpIcon::RemoveFormatting;
/// Registry concept `editor-code` -> Lucide `code`.
pub const EDITOR_CODE: ExpIcon = ExpIcon::Code;
/// Registry concept `editor-emoji` -> Lucide `smile`.
pub const EDITOR_EMOJI: ExpIcon = ExpIcon::Smile;
/// Registry concept `editor-heading-1` -> Lucide `heading-1`.
pub const EDITOR_HEADING_1: ExpIcon = ExpIcon::Heading1;
/// Registry concept `editor-heading-2` -> Lucide `heading-2`.
pub const EDITOR_HEADING_2: ExpIcon = ExpIcon::Heading2;
/// Registry concept `editor-heading-3` -> Lucide `heading-3`.
pub const EDITOR_HEADING_3: ExpIcon = ExpIcon::Heading3;
/// Registry concept `editor-image` -> Lucide `image`.
pub const EDITOR_IMAGE: ExpIcon = ExpIcon::Image;
/// Registry concept `editor-issue-ref` -> Lucide `hash`.
pub const EDITOR_ISSUE_REF: ExpIcon = ExpIcon::Hash;
/// Registry concept `editor-italic` -> Lucide `italic`.
pub const EDITOR_ITALIC: ExpIcon = ExpIcon::Italic;
/// Registry concept `editor-link` -> Lucide `link`.
pub const EDITOR_LINK: ExpIcon = ExpIcon::Link;
/// Registry concept `editor-list` -> Lucide `list`.
pub const EDITOR_LIST: ExpIcon = ExpIcon::List;
/// Registry concept `editor-list-ordered` -> Lucide `list-ordered`.
pub const EDITOR_LIST_ORDERED: ExpIcon = ExpIcon::ListOrdered;
/// Registry concept `editor-list-todo` -> Lucide `list-todo`.
pub const EDITOR_LIST_TODO: ExpIcon = ExpIcon::ListTodo;
/// Registry concept `editor-mention` -> Lucide `at-sign`.
pub const EDITOR_MENTION: ExpIcon = ExpIcon::AtSign;
/// Registry concept `editor-quote` -> Lucide `quote`.
pub const EDITOR_QUOTE: ExpIcon = ExpIcon::Quote;
/// Registry concept `editor-strikethrough` -> Lucide `strikethrough`.
pub const EDITOR_STRIKETHROUGH: ExpIcon = ExpIcon::Strikethrough;
/// Registry concept `editor-unlink` -> Lucide `unlink`.
pub const EDITOR_UNLINK: ExpIcon = ExpIcon::Unlink;
/// Registry concept `event-assignee-changed` -> Lucide `user-plus`.
pub const EVENT_ASSIGNEE_CHANGED: ExpIcon = ExpIcon::UserPlus;
/// Registry concept `event-board-moved` -> Lucide `move`.
pub const EVENT_BOARD_MOVED: ExpIcon = ExpIcon::Move;
/// Registry concept `event-label-added` -> Lucide `tag`.
pub const EVENT_LABEL_ADDED: ExpIcon = ExpIcon::Tag;
/// Registry concept `event-label-removed` -> Lucide `tag`.
pub const EVENT_LABEL_REMOVED: ExpIcon = ExpIcon::Tag;
/// Registry concept `event-priority-changed` -> Lucide `signal-high`.
pub const EVENT_PRIORITY_CHANGED: ExpIcon = ExpIcon::SignalHigh;
/// Registry concept `event-status-changed` -> Lucide `circle-dot`.
pub const EVENT_STATUS_CHANGED: ExpIcon = ExpIcon::CircleDot;
/// Registry concept `nav-account` -> Lucide `circle-user`.
pub const NAV_ACCOUNT: ExpIcon = ExpIcon::CircleUser;
/// Registry concept `nav-admin` -> Lucide `shield`.
pub const NAV_ADMIN: ExpIcon = ExpIcon::Shield;
/// Registry concept `nav-agents` -> Lucide `bot`.
pub const NAV_AGENTS: ExpIcon = ExpIcon::Bot;
/// Registry concept `nav-boards` -> Lucide `folder-kanban`.
pub const NAV_BOARDS: ExpIcon = ExpIcon::FolderKanban;
/// Registry concept `nav-changelog` -> Lucide `megaphone`.
pub const NAV_CHANGELOG: ExpIcon = ExpIcon::Megaphone;
/// Registry concept `nav-create-issue` -> Lucide `square-pen`.
pub const NAV_CREATE_ISSUE: ExpIcon = ExpIcon::SquarePen;
/// Registry concept `nav-files` -> Lucide `folder`.
pub const NAV_FILES: ExpIcon = ExpIcon::Folder;
/// Registry concept `nav-filter` -> Lucide `list-filter`.
pub const NAV_FILTER: ExpIcon = ExpIcon::ListFilter;
/// Registry concept `nav-getting-started` -> Lucide `sparkles`.
pub const NAV_GETTING_STARTED: ExpIcon = ExpIcon::Sparkles;
/// Registry concept `nav-inbox` -> Lucide `inbox`.
pub const NAV_INBOX: ExpIcon = ExpIcon::Inbox;
/// Registry concept `nav-issues` -> Lucide `list`.
pub const NAV_ISSUES: ExpIcon = ExpIcon::List;
/// Registry concept `nav-my-issues` -> Lucide `list`.
pub const NAV_MY_ISSUES: ExpIcon = ExpIcon::List;
/// Registry concept `nav-notifications` -> Lucide `bell`.
pub const NAV_NOTIFICATIONS: ExpIcon = ExpIcon::Bell;
/// Registry concept `nav-rail-collapse` -> Lucide `panel-left-close`.
pub const NAV_RAIL_COLLAPSE: ExpIcon = ExpIcon::PanelLeftClose;
/// Registry concept `nav-rail-expand` -> Lucide `panel-left-open`.
pub const NAV_RAIL_EXPAND: ExpIcon = ExpIcon::PanelLeftOpen;
/// Registry concept `nav-reviews` -> Lucide `git-pull-request`.
pub const NAV_REVIEWS: ExpIcon = ExpIcon::GitPullRequest;
/// Registry concept `nav-search` -> Lucide `search`.
pub const NAV_SEARCH: ExpIcon = ExpIcon::Search;
/// Registry concept `nav-settings` -> Lucide `settings`.
pub const NAV_SETTINGS: ExpIcon = ExpIcon::Settings;
/// Registry concept `nav-sign-out` -> Lucide `log-out`.
pub const NAV_SIGN_OUT: ExpIcon = ExpIcon::LogOut;
/// Registry concept `nav-source-control` -> Lucide `git-merge`.
pub const NAV_SOURCE_CONTROL: ExpIcon = ExpIcon::GitMerge;
/// Registry concept `nav-support` -> Lucide `life-buoy`.
pub const NAV_SUPPORT: ExpIcon = ExpIcon::LifeBuoy;
/// Registry concept `nav-team-switcher` -> Lucide `chevrons-up-down`.
pub const NAV_TEAM_SWITCHER: ExpIcon = ExpIcon::ChevronsUpDown;
/// Registry concept `nav-terminal` -> Lucide `square-terminal`.
pub const NAV_TERMINAL: ExpIcon = ExpIcon::SquareTerminal;
/// Registry concept `notification-issue-assigned` -> Lucide `user-plus`.
pub const NOTIFICATION_ISSUE_ASSIGNED: ExpIcon = ExpIcon::UserPlus;
/// Registry concept `notification-issue-comment` -> Lucide `message-square`.
pub const NOTIFICATION_ISSUE_COMMENT: ExpIcon = ExpIcon::MessageSquare;
/// Registry concept `notification-issue-created` -> Lucide `circle-dot`.
pub const NOTIFICATION_ISSUE_CREATED: ExpIcon = ExpIcon::CircleDot;
/// Registry concept `notification-issue-mention` -> Lucide `at-sign`.
pub const NOTIFICATION_ISSUE_MENTION: ExpIcon = ExpIcon::AtSign;
/// Registry concept `notification-issue-status-changed` -> Lucide `circle-check`.
pub const NOTIFICATION_ISSUE_STATUS_CHANGED: ExpIcon = ExpIcon::CircleCheck;
/// Registry concept `notification-mark-read` -> Lucide `list-checks`.
pub const NOTIFICATION_MARK_READ: ExpIcon = ExpIcon::ListChecks;
/// Registry concept `notification-mute` -> Lucide `bell-off`.
pub const NOTIFICATION_MUTE: ExpIcon = ExpIcon::BellOff;
/// Registry concept `notification-pr-merged` -> Lucide `git-merge`.
pub const NOTIFICATION_PR_MERGED: ExpIcon = ExpIcon::GitMerge;
/// Registry concept `notification-pr-opened` -> Lucide `git-pull-request`.
pub const NOTIFICATION_PR_OPENED: ExpIcon = ExpIcon::GitPullRequest;
/// Registry concept `notification-support-reply` -> Lucide `life-buoy`.
pub const NOTIFICATION_SUPPORT_REPLY: ExpIcon = ExpIcon::LifeBuoy;
/// Registry concept `pr-closed` -> Lucide `circle-x`.
pub const PR_CLOSED: ExpIcon = ExpIcon::CircleX;
/// Registry concept `pr-draft` -> Lucide `circle-dot`.
pub const PR_DRAFT: ExpIcon = ExpIcon::CircleDot;
/// Registry concept `pr-merged` -> Lucide `git-merge`.
pub const PR_MERGED: ExpIcon = ExpIcon::GitMerge;
/// Registry concept `pr-open` -> Lucide `git-pull-request`.
pub const PR_OPEN: ExpIcon = ExpIcon::GitPullRequest;
/// Registry concept `priority-high` -> Lucide `signal-high`.
pub const PRIORITY_HIGH: ExpIcon = ExpIcon::SignalHigh;
/// Registry concept `priority-low` -> Lucide `signal-low`.
pub const PRIORITY_LOW: ExpIcon = ExpIcon::SignalLow;
/// Registry concept `priority-medium` -> Lucide `signal-medium`.
pub const PRIORITY_MEDIUM: ExpIcon = ExpIcon::SignalMedium;
/// Registry concept `priority-none` -> Lucide `minus`.
pub const PRIORITY_NONE: ExpIcon = ExpIcon::Minus;
/// Registry concept `priority-urgent` -> Lucide `triangle-alert`.
pub const PRIORITY_URGENT: ExpIcon = ExpIcon::TriangleAlert;
/// Registry concept `sc-push` -> Lucide `upload`.
pub const SC_PUSH: ExpIcon = ExpIcon::Upload;
/// Registry concept `settings-about` -> Lucide `info`.
pub const SETTINGS_ABOUT: ExpIcon = ExpIcon::Info;
/// Registry concept `settings-account` -> Lucide `circle-user`.
pub const SETTINGS_ACCOUNT: ExpIcon = ExpIcon::CircleUser;
/// Registry concept `settings-agents` -> Lucide `bot`.
pub const SETTINGS_AGENTS: ExpIcon = ExpIcon::Bot;
/// Registry concept `settings-api` -> Lucide `key`.
pub const SETTINGS_API: ExpIcon = ExpIcon::Key;
/// Registry concept `settings-billing` -> Lucide `credit-card`.
pub const SETTINGS_BILLING: ExpIcon = ExpIcon::CreditCard;
/// Registry concept `settings-boards` -> Lucide `square-kanban`.
pub const SETTINGS_BOARDS: ExpIcon = ExpIcon::SquareKanban;
/// Registry concept `settings-general` -> Lucide `building-2`.
pub const SETTINGS_GENERAL: ExpIcon = ExpIcon::Building2;
/// Registry concept `settings-labels` -> Lucide `tag`.
pub const SETTINGS_LABELS: ExpIcon = ExpIcon::Tag;
/// Registry concept `settings-licenses` -> Lucide `scale`.
pub const SETTINGS_LICENSES: ExpIcon = ExpIcon::Scale;
/// Registry concept `settings-local-repos` -> Lucide `hard-drive`.
pub const SETTINGS_LOCAL_REPOS: ExpIcon = ExpIcon::HardDrive;
/// Registry concept `settings-members` -> Lucide `users`.
pub const SETTINGS_MEMBERS: ExpIcon = ExpIcon::Users;
/// Registry concept `settings-notifications` -> Lucide `bell`.
pub const SETTINGS_NOTIFICATIONS: ExpIcon = ExpIcon::Bell;
/// Registry concept `settings-rate` -> Lucide `star`.
pub const SETTINGS_RATE: ExpIcon = ExpIcon::Star;
/// Registry concept `settings-repositories` -> Lucide `github`.
pub const SETTINGS_REPOSITORIES: ExpIcon = ExpIcon::Github;
/// Registry concept `settings-servers` -> Lucide `server`.
pub const SETTINGS_SERVERS: ExpIcon = ExpIcon::Server;
/// Registry concept `settings-statuses` -> Lucide `circle-dot`.
pub const SETTINGS_STATUSES: ExpIcon = ExpIcon::CircleDot;
/// Registry concept `settings-storage` -> Lucide `hard-drive`.
pub const SETTINGS_STORAGE: ExpIcon = ExpIcon::HardDrive;
/// Registry concept `settings-sync` -> Lucide `refresh-cw`.
pub const SETTINGS_SYNC: ExpIcon = ExpIcon::RefreshCw;
/// Registry concept `settings-tools` -> Lucide `square-terminal`.
pub const SETTINGS_TOOLS: ExpIcon = ExpIcon::SquareTerminal;
/// Registry concept `settings-widget` -> Lucide `message-square-plus`.
pub const SETTINGS_WIDGET: ExpIcon = ExpIcon::MessageSquarePlus;
/// Registry concept `status-backlog` -> Lucide `circle-dashed`.
pub const STATUS_BACKLOG: ExpIcon = ExpIcon::CircleDashed;
/// Registry concept `status-cancelled` -> Lucide `circle-x`.
pub const STATUS_CANCELLED: ExpIcon = ExpIcon::CircleX;
/// Registry concept `status-done` -> Lucide `circle-check`.
pub const STATUS_DONE: ExpIcon = ExpIcon::CircleCheck;
/// Registry concept `status-duplicate` -> Lucide `copy`.
pub const STATUS_DUPLICATE: ExpIcon = ExpIcon::Copy;
/// Registry concept `status-in-progress` -> Lucide `progress-2-4`.
pub const STATUS_IN_PROGRESS: ExpIcon = ExpIcon::Progress24;
/// Registry concept `status-in-review` -> Lucide `progress-3-4`.
pub const STATUS_IN_REVIEW: ExpIcon = ExpIcon::Progress34;
/// Registry concept `status-todo` -> Lucide `circle`.
pub const STATUS_TODO: ExpIcon = ExpIcon::Circle;
/// Registry concept `support-open` -> Lucide `circle-dot`.
pub const SUPPORT_OPEN: ExpIcon = ExpIcon::CircleDot;
/// Registry concept `support-resolved` -> Lucide `circle-check`.
pub const SUPPORT_RESOLVED: ExpIcon = ExpIcon::CircleCheck;
/// Registry concept `ui-add` -> Lucide `plus`.
pub const UI_ADD: ExpIcon = ExpIcon::Plus;
/// Registry concept `ui-agent-source` -> Lucide `bot`.
pub const UI_AGENT_SOURCE: ExpIcon = ExpIcon::Bot;
/// Registry concept `ui-archive` -> Lucide `archive`.
pub const UI_ARCHIVE: ExpIcon = ExpIcon::Archive;
/// Registry concept `ui-arrow-right` -> Lucide `arrow-right`.
pub const UI_ARROW_RIGHT: ExpIcon = ExpIcon::ArrowRight;
/// Registry concept `ui-assignee` -> Lucide `circle-user`.
pub const UI_ASSIGNEE: ExpIcon = ExpIcon::CircleUser;
/// Registry concept `ui-attach` -> Lucide `paperclip`.
pub const UI_ATTACH: ExpIcon = ExpIcon::Paperclip;
/// Registry concept `ui-avatar-placeholder` -> Lucide `user`.
pub const UI_AVATAR_PLACEHOLDER: ExpIcon = ExpIcon::User;
/// Registry concept `ui-back` -> Lucide `arrow-left`.
pub const UI_BACK: ExpIcon = ExpIcon::ArrowLeft;
/// Registry concept `ui-branch` -> Lucide `git-branch`.
pub const UI_BRANCH: ExpIcon = ExpIcon::GitBranch;
/// Registry concept `ui-check` -> Lucide `check`.
pub const UI_CHECK: ExpIcon = ExpIcon::Check;
/// Registry concept `ui-checklist` -> Lucide `list-checks`.
pub const UI_CHECKLIST: ExpIcon = ExpIcon::ListChecks;
/// Registry concept `ui-chevron-down` -> Lucide `chevron-down`.
pub const UI_CHEVRON_DOWN: ExpIcon = ExpIcon::ChevronDown;
/// Registry concept `ui-chevron-left` -> Lucide `chevron-left`.
pub const UI_CHEVRON_LEFT: ExpIcon = ExpIcon::ChevronLeft;
/// Registry concept `ui-chevron-right` -> Lucide `chevron-right`.
pub const UI_CHEVRON_RIGHT: ExpIcon = ExpIcon::ChevronRight;
/// Registry concept `ui-chevron-up` -> Lucide `chevron-up`.
pub const UI_CHEVRON_UP: ExpIcon = ExpIcon::ChevronUp;
/// Registry concept `ui-clean` -> Lucide `brush-cleaning`.
pub const UI_CLEAN: ExpIcon = ExpIcon::BrushCleaning;
/// Registry concept `ui-clear` -> Lucide `circle-x`.
pub const UI_CLEAR: ExpIcon = ExpIcon::CircleX;
/// Registry concept `ui-clock` -> Lucide `clock`.
pub const UI_CLOCK: ExpIcon = ExpIcon::Clock;
/// Registry concept `ui-close` -> Lucide `x`.
pub const UI_CLOSE: ExpIcon = ExpIcon::X;
/// Registry concept `ui-cloud` -> Lucide `cloud`.
pub const UI_CLOUD: ExpIcon = ExpIcon::Cloud;
/// Registry concept `ui-copy` -> Lucide `copy`.
pub const UI_COPY: ExpIcon = ExpIcon::Copy;
/// Registry concept `ui-delete` -> Lucide `trash-2`.
pub const UI_DELETE: ExpIcon = ExpIcon::Trash2;
/// Registry concept `ui-delete-account` -> Lucide `user-x`.
pub const UI_DELETE_ACCOUNT: ExpIcon = ExpIcon::UserX;
/// Registry concept `ui-device` -> Lucide `monitor`.
pub const UI_DEVICE: ExpIcon = ExpIcon::Monitor;
/// Registry concept `ui-device-offline` -> Lucide `monitor-off`.
pub const UI_DEVICE_OFFLINE: ExpIcon = ExpIcon::MonitorOff;
/// Registry concept `ui-download` -> Lucide `download`.
pub const UI_DOWNLOAD: ExpIcon = ExpIcon::Download;
/// Registry concept `ui-due-date` -> Lucide `calendar-days`.
pub const UI_DUE_DATE: ExpIcon = ExpIcon::CalendarDays;
/// Registry concept `ui-edit` -> Lucide `pencil`.
pub const UI_EDIT: ExpIcon = ExpIcon::Pencil;
/// Registry concept `ui-empty-search` -> Lucide `search-x`.
pub const UI_EMPTY_SEARCH: ExpIcon = ExpIcon::SearchX;
/// Registry concept `ui-error` -> Lucide `circle-x`.
pub const UI_ERROR: ExpIcon = ExpIcon::CircleX;
/// Registry concept `ui-external-link` -> Lucide `external-link`.
pub const UI_EXTERNAL_LINK: ExpIcon = ExpIcon::ExternalLink;
/// Registry concept `ui-file` -> Lucide `file`.
pub const UI_FILE: ExpIcon = ExpIcon::File;
/// Registry concept `ui-folder` -> Lucide `folder`.
pub const UI_FOLDER: ExpIcon = ExpIcon::Folder;
/// Registry concept `ui-folder-open` -> Lucide `folder-open`.
pub const UI_FOLDER_OPEN: ExpIcon = ExpIcon::FolderOpen;
/// Registry concept `ui-github` -> Lucide `github`.
pub const UI_GITHUB: ExpIcon = ExpIcon::Github;
/// Registry concept `ui-help` -> Lucide `circle-question-mark`.
pub const UI_HELP: ExpIcon = ExpIcon::CircleQuestionMark;
/// Registry concept `ui-info` -> Lucide `info`.
pub const UI_INFO: ExpIcon = ExpIcon::Info;
/// Registry concept `ui-invite` -> Lucide `user-plus`.
pub const UI_INVITE: ExpIcon = ExpIcon::UserPlus;
/// Registry concept `ui-issue` -> Lucide `file-text`.
pub const UI_ISSUE: ExpIcon = ExpIcon::FileText;
/// Registry concept `ui-loading` -> Lucide `loader-circle`.
pub const UI_LOADING: ExpIcon = ExpIcon::LoaderCircle;
/// Registry concept `ui-mcp` -> Lucide `plug`.
pub const UI_MCP: ExpIcon = ExpIcon::Plug;
/// Registry concept `ui-member` -> Lucide `shield-check`.
pub const UI_MEMBER: ExpIcon = ExpIcon::ShieldCheck;
/// Registry concept `ui-minus` -> Lucide `minus`.
pub const UI_MINUS: ExpIcon = ExpIcon::Minus;
/// Registry concept `ui-more` -> Lucide `ellipsis`.
pub const UI_MORE: ExpIcon = ExpIcon::Ellipsis;
/// Registry concept `ui-more-vertical` -> Lucide `ellipsis-vertical`.
pub const UI_MORE_VERTICAL: ExpIcon = ExpIcon::EllipsisVertical;
/// Registry concept `ui-offline` -> Lucide `wifi-off`.
pub const UI_OFFLINE: ExpIcon = ExpIcon::WifiOff;
/// Registry concept `ui-organization` -> Lucide `building-2`.
pub const UI_ORGANIZATION: ExpIcon = ExpIcon::Building2;
/// Registry concept `ui-owner` -> Lucide `crown`.
pub const UI_OWNER: ExpIcon = ExpIcon::Crown;
/// Registry concept `ui-permission` -> Lucide `shield-question-mark`.
pub const UI_PERMISSION: ExpIcon = ExpIcon::ShieldQuestionMark;
/// Registry concept `ui-private` -> Lucide `lock`.
pub const UI_PRIVATE: ExpIcon = ExpIcon::Lock;
/// Registry concept `ui-properties` -> Lucide `sliders-horizontal`.
pub const UI_PROPERTIES: ExpIcon = ExpIcon::SlidersHorizontal;
/// Registry concept `ui-redock` -> Lucide `arrow-down-left`.
pub const UI_REDOCK: ExpIcon = ExpIcon::ArrowDownLeft;
/// Registry concept `ui-refresh` -> Lucide `refresh-cw`.
pub const UI_REFRESH: ExpIcon = ExpIcon::RefreshCw;
/// Registry concept `ui-remove-member` -> Lucide `user-minus`.
pub const UI_REMOVE_MEMBER: ExpIcon = ExpIcon::UserMinus;
/// Registry concept `ui-repeat` -> Lucide `repeat`.
pub const UI_REPEAT: ExpIcon = ExpIcon::Repeat;
/// Registry concept `ui-repository` -> Lucide `code`.
pub const UI_REPOSITORY: ExpIcon = ExpIcon::Code;
/// Registry concept `ui-selected` -> Lucide `circle-check`.
pub const UI_SELECTED: ExpIcon = ExpIcon::CircleCheck;
/// Registry concept `ui-selector` -> Lucide `chevrons-up-down`.
pub const UI_SELECTOR: ExpIcon = ExpIcon::ChevronsUpDown;
/// Registry concept `ui-send` -> Lucide `send`.
pub const UI_SEND: ExpIcon = ExpIcon::Send;
/// Registry concept `ui-server` -> Lucide `server`.
pub const UI_SERVER: ExpIcon = ExpIcon::Server;
/// Registry concept `ui-share` -> Lucide `share-2`.
pub const UI_SHARE: ExpIcon = ExpIcon::Share2;
/// Registry concept `ui-sign-in` -> Lucide `log-in`.
pub const UI_SIGN_IN: ExpIcon = ExpIcon::LogIn;
/// Registry concept `ui-staging` -> Lucide `flask-conical`.
pub const UI_STAGING: ExpIcon = ExpIcon::FlaskConical;
/// Registry concept `ui-submit` -> Lucide `circle-arrow-up`.
pub const UI_SUBMIT: ExpIcon = ExpIcon::CircleArrowUp;
/// Registry concept `ui-subscribe` -> Lucide `bell`.
pub const UI_SUBSCRIBE: ExpIcon = ExpIcon::Bell;
/// Registry concept `ui-success` -> Lucide `circle-check`.
pub const UI_SUCCESS: ExpIcon = ExpIcon::CircleCheck;
/// Registry concept `ui-swap` -> Lucide `arrow-left-right`.
pub const UI_SWAP: ExpIcon = ExpIcon::ArrowLeftRight;
/// Registry concept `ui-team` -> Lucide `users`.
pub const UI_TEAM: ExpIcon = ExpIcon::Users;
/// Registry concept `ui-unassigned` -> Lucide `user-x`.
pub const UI_UNASSIGNED: ExpIcon = ExpIcon::UserX;
/// Registry concept `ui-undo` -> Lucide `undo-2`.
pub const UI_UNDO: ExpIcon = ExpIcon::Undo2;
/// Registry concept `ui-undock` -> Lucide `arrow-up-right`.
pub const UI_UNDOCK: ExpIcon = ExpIcon::ArrowUpRight;
/// Registry concept `ui-unselected` -> Lucide `circle`.
pub const UI_UNSELECTED: ExpIcon = ExpIcon::Circle;
/// Registry concept `ui-unsubscribe` -> Lucide `bell-off`.
pub const UI_UNSUBSCRIBE: ExpIcon = ExpIcon::BellOff;
/// Registry concept `ui-update` -> Lucide `circle-arrow-up`.
pub const UI_UPDATE: ExpIcon = ExpIcon::CircleArrowUp;
/// Registry concept `ui-warning` -> Lucide `triangle-alert`.
pub const UI_WARNING: ExpIcon = ExpIcon::TriangleAlert;
/// Registry concept `ui-watch` -> Lucide `eye`.
pub const UI_WATCH: ExpIcon = ExpIcon::Eye;
/// Registry concept `ui-widget` -> Lucide `megaphone`.
pub const UI_WIDGET: ExpIcon = ExpIcon::Megaphone;
