/* Bundles the guides' example files (guides/**, compiled from a fresh
   project by guides/check.ts in CI) into src/generated/guide-sources.ts, so
   the guide pages show exactly what CI compiles, in the browser AND in the
   Bun prerender (which has no `?raw` imports). Runs before dev, build and
   typecheck; the output is gitignored. */
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs"
import { join, relative, resolve } from "node:path"

const ROOT = resolve(import.meta.dirname, `..`)
const GUIDES = join(ROOT, `guides`)
const OUT = join(ROOT, `src/generated/guide-sources.ts`)
const SKIP = new Set([`node_modules`, `build`, `.build`, `target`, `.gradle`, `dist`, `gradle`, `.swiftpm`])
const EXTENSIONS = /\.(tsx?|json|swift|kt|kts|rs|toml|md|html|properties)$/

function walk(dir: string, out: string[]): void {
  for (const name of readdirSync(dir).sort()) {
    if (SKIP.has(name) || name.startsWith(`.`)) continue
    const path = join(dir, name)
    if (statSync(path).isDirectory()) walk(path, out)
    else if (EXTENSIONS.test(name) && name !== `check.ts` && name !== `package-lock.json`) out.push(path)
  }
}

const files: string[] = []
if (existsSync(GUIDES)) walk(GUIDES, files)
const entries = files.map((f) => [relative(GUIDES, f), readFileSync(f, `utf8`)] as const)
mkdirSync(join(ROOT, `src/generated`), { recursive: true })
writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/guide-sources.ts from apps/ui-site/guides/** — do not edit.\nexport const GUIDE_SOURCES: Record<string, string> = ${JSON.stringify(Object.fromEntries(entries), null, 2)}\n`
)
console.log(`guide-sources: ${entries.length} files`)
