/* Which stored shots exist (shots/exponential-ui-<view>/<platform>.webp at
   the repo root) → src/generated/shot-index.ts, so a page knows at prerender
   time whether to show a shot or the "shot pending" state (never a broken
   image). Runs before dev, build, typecheck and test; gitignored. */
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"

const ROOT = resolve(import.meta.dirname, `..`)
const SHOTS = resolve(ROOT, `../../shots`)
const OUT = join(ROOT, `src/generated/shot-index.ts`)
const PREFIX = `exponential-ui-`

const index: Record<string, string[]> = {}
if (existsSync(SHOTS)) {
  for (const view of readdirSync(SHOTS).sort()) {
    const dir = join(SHOTS, view)
    if (!view.startsWith(PREFIX) || !statSync(dir).isDirectory()) continue
    index[view] = readdirSync(dir)
      .filter((f) => f.endsWith(`.webp`))
      .map((f) => f.slice(0, -`.webp`.length))
      .sort()
  }
}
mkdirSync(join(ROOT, `src/generated`), { recursive: true })
writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/shot-index.ts from shots/exponential-ui-*/ — do not edit.\nexport const SHOT_INDEX: Record<string, readonly string[]> = ${JSON.stringify(index, null, 2)}\n`
)
console.log(`shot-index: ${Object.keys(index).length} views`)
