// Round 4 (VAPP-103): the contract fixture of the styling + semantics
// lane. Inputs are hand-written HERE; every `expected` comes from the TS
// reference, so the Rust core (tests/round4_fixtures.rs) and the painters
// that run on it replay the same answers.
//
//   fixtures/round4-contract.json
//     validate       authored trees → the reducer's issues (style keys and
//                    tokens, literal colours, unknown functions, Table slot
//                    columns)
//     filter         the core `filter` function: args → the kept items
//     ownWrite       an interaction's action resolves against the data WITH
//                    the component's own write (withOwnWrites + runAction)
//     closeOnSubmit  a successful Form submit closes the nearest overlay
//                    around it when that is a dismissible Dialog/Drawer
//                    (submitClosesOverlay)

import { CORE_CATALOG_ID } from "../src/catalog"
import { runAction, submitClosesOverlay, withOwnWrites, writePointer, absolutePath } from "../src/dynamic"
import { CORE_FUNCTIONS, isBinding } from "../src/expr"
import { templateBudget, templateSiteKey } from "../src/list"
import { reduceNested } from "../src/reducer"
import type { Action, NestedNode, UiNode } from "../src/types"

const HEADER = `AUTO-GENERATED by packages/exponential-ui/scripts/generate-round4.ts — do not edit (inputs live there).`
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`

// ---------------------------------------------------------------------------
// validate
// ---------------------------------------------------------------------------

/** A chain of `depth` Cards around a Text: 2 levels per Card once
 *  expanded (Box > body Box). */
const cardChain = (depth: number, prefix = ``, leaf: NestedNode = { id: `${prefix}leaf`, component: `Text`, props: { text: `deepest` } }): NestedNode => {
  let n = leaf
  for (let i = depth - 1; i >= 0; i--) n = { id: `${prefix}card${i}`, component: `Card`, children: [n] }
  return n
}

const VALIDATE: { name: string; input: NestedNode }[] = [
  // maxDepth holds AFTER macro expansion: 47 authored levels pass the
  // authored check, the expanded chain is 95 deep; the first node past 48
  // (card24, expanded depth 49) is the Unknown placeholder with the depth
  // issue, its subtree dropped.
  { name: `depth: counted after macro expansion (a 47-deep Card chain)`, input: cardChain(47) },
  { name: `style: a key outside the Box whitelist`, input: { id: `root`, component: `Box`, style: { fontColor: `$color.primary` } } },
  { name: `style: an unknown token`, input: { id: `root`, component: `Stack`, style: { gap: `$spacing.huge` } } },
  { name: `style: a literal colour (a node colour is a token)`, input: { id: `root`, component: `Box`, style: { backgroundColor: `#ff0000`, color: `$color.foreground` } } },
  { name: `style: a literal colour inside a media block`, input: { id: `root`, component: `Box`, style: { "@media (min-width: $breakpoint.md)": { borderColor: `#000000` } } } },
  { name: `style: a literal gradient stop`, input: { id: `root`, component: `Box`, style: { backgroundGradient: { angle: 90, stops: [{ color: `$color.primary`, offset: 0 }, { color: `#00000000`, offset: 1 }] } } } },
  { name: `prop: a literal colour`, input: { id: `root`, component: `Chip`, props: { label: `Bug`, dot: `#ef4444` } } },
  { name: `prop: a colour token passes`, input: { id: `root`, component: `Chip`, props: { label: `Bug`, dot: `$color.destructive` } } },
  {
    name: `action: an unknown function`,
    input: { id: `root`, component: `Button`, props: { label: `Docs` }, on: { press: { functionCall: { call: `opneUrl`, args: { url: `https://ui.exponential.at/` } } } } },
  },
  {
    name: `action: a namespaced host function passes`,
    input: { id: `root`, component: `Button`, props: { label: `Wave` }, on: { press: { functionCall: { call: `app.toast`, args: { text: `Hi` } } } } },
  },
  {
    name: `action: an unknown function inside the event context`,
    input: { id: `root`, component: `Button`, props: { label: `Save` }, on: { press: { event: { name: `save`, context: { title: { call: `trimm`, args: { value: { path: `/title` } } } } } } } },
  },
  { name: `prop: an unknown function in a binding`, input: { id: `root`, component: `Text`, props: { text: { call: `concatt`, args: { values: [`a`, `b`] } } } } },
  { name: `visible: an unknown function`, input: { id: `root`, component: `Text`, props: { text: `x` }, visible: { call: `nott`, args: { value: { path: `/hide` } } } } },
  {
    name: `data: a literal Table row with a call key is a row, never a function`,
    input: { id: `root`, component: `Table`, props: { columns: [{ key: `name`, label: `Name` }, { key: `call`, label: `Call` }], rows: [{ id: `r1`, name: `Ana`, call: `+1 555 0100` }, { id: `r2`, call: `follow up`, args: {} }] } },
  },
  {
    name: `shaped: a call in a bindable option label is checked`,
    input: { id: `root`, component: `Select`, props: { name: `s`, options: [{ label: { call: `uppr`, args: { value: `a` } }, value: `a` }, { label: `B`, value: `b` }] } },
  },
  {
    name: `action: an unknown function nested in another call's args`,
    input: { id: `root`, component: `Button`, props: { label: `Go` }, on: { press: { functionCall: { call: `set`, args: { path: `/n`, value: { call: `ad`, args: { a: 1, b: 2 } } } } } } },
  },
  {
    name: `Table: a slot column naming a missing slot`,
    input: {
      id: `root`,
      component: `Table`,
      props: { columns: [{ key: `title`, label: `Title` }, { key: `status`, label: `Status`, type: `slot`, slot: `status` }, { key: `owner`, label: `Owner`, type: `slot` }], rows: { path: `/rows` } },
      slots: { state: { id: `state-cell`, component: `Badge`, props: { text: { path: `status` } } } },
    },
  },
  {
    name: `Table: slot columns naming its slots pass; rows bound to a filter`,
    input: {
      id: `root`,
      component: `Table`,
      props: {
        columns: [{ key: `title`, label: `Title` }, { key: `status`, label: `Status`, type: `slot`, slot: `status` }],
        rows: { call: `filter`, args: { items: { path: `/rows` }, query: { path: `/query` }, fields: [`title`], where: { status: { path: `/status` } } } },
      },
      slots: { status: { id: `status-cell`, component: `Badge`, props: { text: { path: `status` } } } },
    },
  },
]

// ---------------------------------------------------------------------------
// filter
// ---------------------------------------------------------------------------

const ISSUES = [
  { id: `i1`, title: `Ship the release`, status: `open`, points: 3 },
  { id: `i2`, title: `Fix the shipping form`, status: `done`, points: 5 },
  { id: `i3`, title: `Write the changelog`, status: `open`, points: 1 },
  { id: `i4`, title: `Release notes`, status: `open`, points: 15 },
]

const FILTER: { name: string; args: Record<string, unknown> }[] = [
  { name: `query over fields, case-insensitive`, args: { items: ISSUES, query: `SHIP`, fields: [`title`] } },
  { name: `query over every text and number field when fields is absent`, args: { items: ISSUES, query: `5` } },
  { name: `where: every field must equal`, args: { items: ISSUES, where: { status: `open` } } },
  { name: `where with a number spelled as a string (eq)`, args: { items: ISSUES, where: { points: `3` } } },
  { name: `where and query together`, args: { items: ISSUES, query: `re`, fields: [`title`], where: { status: `open` } } },
  { name: `an empty where value and a blank query constrain nothing`, args: { items: ISSUES, query: `  `, where: { status: `` } } },
  { name: `a query is trimmed`, args: { items: ISSUES, query: ` notes `, fields: [`title`] } },
  { name: `a field missing on an item never matches where`, args: { items: ISSUES, where: { owner: `ana` } } },
  { name: `string items match themselves`, args: { items: [`Alpha`, `beta`, `Gamma`, 42], query: `a` } },
  { name: `not an array: no items`, args: { items: `abc`, query: `a` } },
]

// ---------------------------------------------------------------------------
// ownWrite
// ---------------------------------------------------------------------------

// `payload` = the interaction a host dispatches (the Rust `event` input);
// `own` = EXACTLY what the component writes, by prop (default: the
// payload); `sent` = the payload its event carries (default: the payload).
const FILE = (name: string, size: number, type: string) => ({ name, size, type })
const OWN_WRITE: { name: string; input: NestedNode; data: Record<string, unknown>; target: string; event: string; payload: Record<string, unknown>; own?: Record<string, unknown>; sent?: Record<string, unknown> }[] = [
  {
    name: `Input change: the bound context reads the text just typed`,
    input: {
      id: `root`,
      component: `Box`,
      children: [{ id: `q`, component: `Input`, props: { name: `q`, label: `Search`, value: { path: `/query` } }, on: { change: { event: { name: `search`, context: { query: { path: `/query` } } } } } }],
    },
    data: { query: `` },
    target: `q`,
    event: `change`,
    payload: { value: `ship` },
  },
  {
    name: `Input change: a filter in the context sees the new query`,
    input: {
      id: `root`,
      component: `Box`,
      children: [
        {
          id: `q`,
          component: `Input`,
          props: { name: `q`, label: `Search`, value: { path: `/query` } },
          on: { change: { event: { name: `search`, context: { hits: { call: `len`, args: { value: { call: `filter`, args: { items: { path: `/issues` }, query: { path: `/query` }, fields: [`title`] } } } } } } } },
        },
      ],
    },
    data: { query: ``, issues: ISSUES },
    target: `q`,
    event: `change`,
    payload: { value: `ship` },
  },
  {
    name: `Switch change: the bound context reads the new state`,
    input: {
      id: `root`,
      component: `Box`,
      children: [{ id: `s`, component: `Switch`, props: { name: `s`, label: `Notify`, checked: { path: `/notify` } }, on: { change: { event: { name: `toggled`, context: { notify: { path: `/notify` } } } } } }],
    },
    data: { notify: false },
    target: `s`,
    event: `change`,
    payload: { checked: true },
  },
  {
    name: `FileUpload upload: the own write is the MERGED list, the payload carries it plus the new batch (added)`,
    input: {
      id: `root`,
      component: `Box`,
      children: [
        {
          id: `u`,
          component: `FileUpload`,
          props: { name: `att`, label: `Attachments`, multiple: true, files: { path: `/att` } },
          on: { upload: { event: { name: `uploaded`, context: { count: { call: `len`, args: { value: { path: `/att` } } } } } } },
        },
      ],
    },
    data: { att: [FILE(`a.pdf`, 1, `application/pdf`), FILE(`b.pdf`, 2, `application/pdf`)] },
    target: `u`,
    event: `upload`,
    payload: { files: [FILE(`c.png`, 3, `image/png`)] },
    own: { files: [FILE(`a.pdf`, 1, `application/pdf`), FILE(`b.pdf`, 2, `application/pdf`), FILE(`c.png`, 3, `image/png`)] },
    sent: { files: [FILE(`a.pdf`, 1, `application/pdf`), FILE(`b.pdf`, 2, `application/pdf`), FILE(`c.png`, 3, `image/png`)], added: [FILE(`c.png`, 3, `image/png`)] },
  },
]

// ---------------------------------------------------------------------------
// closeOnSubmit
// ---------------------------------------------------------------------------

const form = (id: string, submit: string): NestedNode => ({
  id,
  component: `Form`,
  props: { name: id },
  on: { submit: { event: { name: submit } } },
  children: [
    { id: `${id}-title`, component: `Input`, props: { name: `title`, label: `Title`, value: { path: `/draft` } } },
    { id: `${id}-go`, component: `Button`, props: { label: `Create`, submit: true } },
  ],
})

const CLOSE_ON_SUBMIT: { name: string; input: NestedNode; data: Record<string, unknown>; form: string; actions: string[] }[] = [
  {
    name: `a Form in a Dialog: submit, then the Dialog closes (bound open written false, change fired)`,
    input: { id: `root`, component: `Box`, children: [{ id: `dlg`, component: `Dialog`, props: { title: `New issue`, open: { path: `/open` } }, on: { change: { event: { name: `dialogChanged` } } }, children: [form(`f`, `create`)] }] },
    data: { open: true, draft: `Ship it` },
    form: `f`,
    actions: [`create`, `dialogChanged`],
  },
  {
    name: `a Form in a Drawer closes the Drawer`,
    input: { id: `root`, component: `Box`, children: [{ id: `drw`, component: `Drawer`, props: { title: `Filters`, open: { path: `/panel` }, side: `right` }, children: [form(`f`, `apply`)] }] },
    data: { panel: true, draft: `x` },
    form: `f`,
    actions: [`apply`],
  },
  {
    name: `a Form in a Popover closes nothing (the nearest overlay decides)`,
    input: { id: `root`, component: `Box`, children: [{ id: `pop`, component: `Popover`, props: { open: { path: `/pop` } }, children: [form(`f`, `apply`)] }] },
    data: { pop: true, draft: `x` },
    form: `f`,
    actions: [`apply`],
  },
  {
    name: `a Form in a Popover inside a Dialog closes neither`,
    input: {
      id: `root`,
      component: `Box`,
      children: [{ id: `dlg`, component: `Dialog`, props: { title: `Edit`, open: { path: `/open` } }, children: [{ id: `pop`, component: `Popover`, props: { open: { path: `/pop` } }, slots: { trigger: { id: `pop-trigger`, component: `Button`, props: { label: `Filters` } } }, children: [form(`f`, `apply`)] }] }],
    },
    data: { open: true, pop: true, draft: `x` },
    form: `f`,
    actions: [`apply`],
  },
  {
    name: `a Form in a non-dismissible Dialog never auto-closes it`,
    input: { id: `root`, component: `Box`, children: [{ id: `dlg`, component: `Dialog`, props: { title: `Required`, open: { path: `/open` }, dismissible: false }, children: [form(`f`, `create`)] }] },
    data: { open: true, draft: `x` },
    form: `f`,
    actions: [`create`],
  },
  {
    name: `a Form in an AlertDialog never auto-closes it`,
    input: { id: `root`, component: `Box`, children: [{ id: `alert`, component: `AlertDialog`, props: { title: `Delete?`, open: { path: `/open` } }, children: [form(`f`, `confirmName`)] }] },
    data: { open: true, draft: `x` },
    form: `f`,
    actions: [`confirmName`],
  },
  {
    name: `a Form outside any overlay closes nothing`,
    input: { id: `root`, component: `Box`, children: [form(`f`, `create`)] },
    data: { draft: `x` },
    form: `f`,
    actions: [`create`],
  },
]

function byId(root: UiNode, id: string): UiNode | undefined {
  if (root.id === id) return root
  for (const n of [...Object.values(root.slots ?? {}), ...root.children]) {
    const hit = byId(n, id)
    if (hit) return hit
  }
  return undefined
}

// ---------------------------------------------------------------------------
// depth (after expansion) + the template budget
// ---------------------------------------------------------------------------

const DEPTH: { name: string; input: NestedNode }[] = [
  // card24 sits at expanded level 49: the Unknown placeholder, subtree dropped.
  { name: `the root tree: the first node past maxDepth after expansion is the placeholder`, input: cardChain(47) },
  // A lifted template starts at level 1 again: 25 Cards = card24 at 49.
  {
    name: `a lifted template is capped from its own level 1`,
    input: { id: `root`, component: `Stack`, children: [{ id: `list`, component: `Stack`, template: { component: `tcard0`, path: `/items` } }, { id: `defs`, component: `Box`, visible: false, children: [cardChain(25, `t`)] }] },
  },
  // An unknown component at level 49 is already a placeholder: one issue (its own).
  { name: `an Unknown leaf at maxDepth + 1 is not reported again`, input: cardChain(24, ``, { id: `nope`, component: `NoSuchComponent` }) },
]

/** The Unknown placeholders of a reduced result, per tree (`root` or the
 *  template id), pre-order. */
function placeholders(result: { root: UiNode; templates?: Record<string, UiNode> }): { tree: string; id: string; component: unknown }[] {
  const out: { tree: string; id: string; component: unknown }[] = []
  const walk = (tree: string, n: UiNode) => {
    if (n.component === `Unknown`) out.push({ tree, id: n.id, component: n.props.component })
    for (const c of n.children) walk(tree, c)
    for (const c of Object.values(n.slots ?? {})) walk(tree, c)
  }
  walk(`root`, result.root)
  for (const [id, n] of Object.entries(result.templates ?? {})) walk(id, n)
  return out
}

/** `{ "$fill": n }` in a budget case's data = n zeros (the fixture stays small). */
function expandFill(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(expandFill)
  if (v && typeof v === `object`) {
    const o = v as Record<string, unknown>
    if (typeof o.$fill === `number`) return Array(o.$fill).fill(0)
    return Object.fromEntries(Object.entries(o).map(([k, x]) => [k, expandFill(x)]))
  }
  return v
}

interface BudgetSite { holder: string; scope: string; template: string; instance: string; items: number }

const BUDGET: { name: string; input: NestedNode; data: unknown; sites: BudgetSite[] }[] = [
  {
    // 3 static nodes; row 0 + its 9,998 cells = 9,999 items, row 1 = 10,000:
    // row 1's first cell is refused, and every later item (row 2) with it.
    name: `maxTemplateItems: items are charged depth-first, an item's nested items before the next item`,
    input: {
      id: `root`,
      component: `Stack`,
      children: [
        { id: `list`, component: `Stack`, template: { component: `row`, path: `/outer` } },
        { id: `defs`, component: `Box`, visible: false, children: [{ id: `row`, component: `Stack`, template: { component: `cell`, path: `inner` } }, { id: `cell`, component: `Text`, props: { text: `x` } }] },
      ],
    },
    data: { outer: [{ inner: { $fill: 9998 } }, { inner: { $fill: 2 } }, { inner: { $fill: 2 } }] },
    sites: [
      { holder: `list`, scope: ``, template: `row`, instance: ``, items: 3 },
      { holder: `row`, scope: `/outer/0`, template: `cell`, instance: `.0`, items: 9998 },
      { holder: `row`, scope: `/outer/1`, template: `cell`, instance: `.1`, items: 2 },
      { holder: `row`, scope: `/outer/2`, template: `cell`, instance: `.2`, items: 2 },
    ],
  },
  {
    // 4 static nodes + 3 per row: 6,665 rows fit (19,999 nodes), the next
    // would make 20,002; the later site builds nothing (no second issue).
    name: `maxComponents: the build starts at the reduced tree's nodes and each item costs its template subtree`,
    input: {
      id: `root`,
      component: `Stack`,
      children: [
        { id: `rows`, component: `Stack`, template: { component: `row`, path: `/rows` } },
        { id: `more`, component: `Stack`, template: { component: `extra`, path: `/more` } },
        { id: `defs`, component: `Box`, visible: false, children: [{ id: `row`, component: `Stack`, children: [{ id: `row-a`, component: `Text`, props: { text: `a` } }, { id: `row-b`, component: `Text`, props: { text: `b` } }] }, { id: `extra`, component: `Text`, props: { text: `e` } }] },
      ],
    },
    data: { rows: { $fill: 7000 }, more: { $fill: 1 } },
    sites: [
      { holder: `rows`, scope: ``, template: `row`, instance: ``, items: 7000 },
      { holder: `more`, scope: ``, template: `extra`, instance: ``, items: 1 },
    ],
  },
  {
    name: `under both limits every item is built, no issue`,
    input: {
      id: `root`,
      component: `Stack`,
      children: [
        { id: `rows`, component: `Stack`, template: { component: `row`, path: `/rows` } },
        { id: `defs`, component: `Box`, visible: false, children: [{ id: `row`, component: `Text`, props: { text: `r` } }] },
      ],
    },
    data: { rows: { $fill: 5 } },
    sites: [{ holder: `rows`, scope: ``, template: `row`, instance: ``, items: 5 }],
  },
]

export function round4Fixture() {
  const reduce = (input: NestedNode) => reduceNested(input, { catalogId: CORE_CATALOG_ID })
  return {
    $comment: `${HEADER} Round 4 (VAPP-103), replayed by the TS reference (src/round4.test.ts) and the Rust core (tests/round4_fixtures.rs). validate: reduce the nested input with the core catalog: the issues equal \`issues\` in order. depth: reduce the nested input: the issues equal \`issues\` and the Unknown placeholders (pre-order, root then each lifted template: children before slots) equal \`placeholders\` (maxDepth holds AFTER expansion, each tree from level 1). templateBudget: reduce, set the data (\`{\"$fill\": n}\` = n zeros) and build every item: each template site (\`holder\` in \`scope\`) builds its first \`built\` items (ids \`template + instance + .i\`), and the build reports \`issues\` (ONE: the template whose next item did not fit maxTemplateItems or maxComponents) (a node's style, then the functions its props, visible and on actions call, then a Table's slot columns; a colour is a \`$color.*\` token, never a literal; a host function is namespaced, \`app.toast\`). filter: call the core \`filter\` with \`args\`: the result equals \`expected\`. ownWrite: fire \`event\` with \`payload\` on \`target\` (the interaction): the component writes \`own\` (by prop, exactly what it wrote, never inferred from the payload) and sends \`sent\`; the data model equals \`expected.data\` and the action that leaves carries \`expected.action\` (its context resolved AFTER the own write, \`sent\` merged over it). closeOnSubmit: submit the valid \`form\`: the actions leave in \`actions\` order, the overlay \`expected.overlay\` closes (null = none: the NEAREST enclosing overlay of any kind decides, and only a dismissible Dialog or Drawer closes) and the data equals \`expected.data\`.`,
    catalogId: CORE_CATALOG_ID,
    validate: VALIDATE.map((c) => ({ ...c, issues: reduce(c.input).issues })),
    depth: DEPTH.map((c) => {
      const result = reduce(c.input)
      return { ...c, issues: result.issues, placeholders: placeholders(result) }
    }),
    templateBudget: BUDGET.map((c) => {
      const result = reduce(c.input)
      if (result.issues.length) throw new Error(`round4 templateBudget "${c.name}": ${JSON.stringify(result.issues)}`)
      const budget = templateBudget(result.root, expandFill(c.data), (id) => result.templates?.[id])
      return { ...c, sites: c.sites.map((site) => ({ ...site, built: budget.allowed.get(templateSiteKey(site.holder, site.scope)) ?? 0 })), issues: budget.issue ? [budget.issue] : [] }
    }),
    filter: FILTER.map((c) => ({ ...c, expected: CORE_FUNCTIONS.filter!(c.args) })),
    ownWrite: OWN_WRITE.map((c) => {
      const { root, issues } = reduce(c.input)
      if (issues.length) throw new Error(`round4 ownWrite "${c.name}": ${JSON.stringify(issues)}`)
      const node = byId(root, c.target)!
      const own = c.own ?? c.payload
      const sent = c.sent ?? c.payload
      const data = withOwnWrites(c.data, node.props, own)
      const outcome = runAction(node.on![c.event] as Action, data)
      return { ...c, own, sent, expected: { data: outcome.data, action: { name: outcome.event!.name, context: { ...(outcome.event!.context ?? {}), ...sent } } } }
    }),
    closeOnSubmit: CLOSE_ON_SUBMIT.map((c) => {
      const { root, issues } = reduce(c.input)
      if (issues.length) throw new Error(`round4 closeOnSubmit "${c.name}": ${JSON.stringify(issues)}`)
      const overlay = submitClosesOverlay(root, c.form)
      const open = overlay ? byId(root, overlay)!.props.open : undefined
      const data = isBinding(open) ? writePointer(c.data, absolutePath(open.path), false).data : c.data
      return { ...c, expected: { overlay, data } }
    }),
  }
}

export function renderRound4(): Record<string, string> {
  return { "fixtures/round4-contract.json": json(round4Fixture()) }
}
