// VAPP-92: the theme half of the generator (scripts/generate.ts merges it).
//
// Outputs (all committed, drift-gated by src/generate.test.ts):
//   themes/exponential.theme.json           the built-in Exponential theme, COMPOSED from
//                                           packages/design-tokens/tokens.json (token values),
//                                           packages/ui/src/styles.css (the light + dark palettes,
//                                           through the builder's importer) and
//                                           themes/exponential.recipes.json (the glass recipes)
//   catalog/theme.schema.json               the theme file as JSON Schema
//   generated/ExponentialUIThemes.generated.{swift,kt,rs}  the built-ins RESOLVED, embedded
//   docs/themes.generated.json              tokens, parts, states, keys for the site
//   fixtures/theme-resolved.json            every built-in resolved (what a painter holds)
//   fixtures/theme-recipes.json             theme × component part × props → visuals per mode/state
//   fixtures/theme-extends.json             `extends` cases (inputs hand-written, expected filled)
//   fixtures/theme-invalid.json             bad themes → the issues they must raise
//   fixtures/control-geometry.json          theme × control × props → the measure contract

import { readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { CORE_CATALOG_ID, TOKEN_GROUPS, coreCatalog } from "../src/catalog"
import { toThemeHex } from "../src/color"
import { importShadcnCss } from "../src/builder"
import { CONTROL_PARTS, controlGeometry } from "../src/geometry"
import { nativeRecipeProps, recipeParts, RECIPE_KEYS, RECIPE_STATES } from "../src/recipes"
import { reduceNested } from "../src/reducer"
import { MODES, THEME_SCHEMA_ID, loadTheme, resolveRecipe, tryLoadTheme } from "../src/theme"
import { STYLE_TRANSFORM_PATTERN, styleKeyEnum } from "../src/style"
import type { ModeName, RecipeQuery, ResolvedStyle, ResolvedTheme, ThemeSource } from "../src/theme-types"
import type { NestedNode, UiNode } from "../src/types"
import neutralJson from "../themes/neutral.theme.json" with { type: "json" }
import playfulJson from "../themes/playful.theme.json" with { type: "json" }
import exponentialRecipes from "../themes/exponential.recipes.json" with { type: "json" }

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), `..`)
const repoRoot = join(pkgRoot, `..`, `..`)
const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`

export const THEME_HEADER = `AUTO-GENERATED by packages/exponential-ui/scripts/generate.ts — do not edit.
Source of truth: packages/exponential-ui/themes/*.theme.json, themes/exponential.recipes.json, catalog/recipes.json, catalog/tokens.json (+ packages/design-tokens/tokens.json and packages/ui/src/styles.css for the exponential theme).`

// ---------------------------------------------------------------------------
// The Exponential theme, composed
// ---------------------------------------------------------------------------

interface DesignTokens {
  palette: Record<string, string>
  semantic: Record<string, string>
  glass: Record<string, string>
  radius: Record<string, number>
  size: Record<string, number>
  motion: { duration: Record<string, number>; ease: Record<string, [number, number, number, number]> }
  spacing: Record<string, number>
  type: { fontFamily: string; size: Record<string, number>; lineHeight: Record<string, number>; weight: Record<string, number>; emphasis: Record<string, number> }
}

/** A design-tokens group without its `$comment`. */
function numbers(group: Record<string, unknown>): Record<string, number> {
  return Object.fromEntries(Object.entries(group).filter(([k, v]) => !k.startsWith(`$`) && typeof v === `number`)) as Record<string, number>
}

function hex(value: string): `#${string}` {
  const h = toThemeHex(value)
  if (!h) throw new Error(`design token colour not parseable: ${value}`)
  return h
}

export function composeExponential(): ThemeSource {
  const design = JSON.parse(readFileSync(join(repoRoot, `packages/design-tokens/tokens.json`), `utf8`)) as DesignTokens
  const css = readFileSync(join(repoRoot, `packages/ui/src/styles.css`), `utf8`)
  const imported = importShadcnCss(css)
  const light = { ...(imported.modes.light?.color ?? {}) }
  const dark = { ...(imported.modes.dark?.color ?? {}) }
  for (const [mode, table] of [[`light`, light], [`dark`, dark]] as const) {
    for (const name of [`background`, `foreground`, `card`, `primary`, `muted`, `border`, `ring`, `chart1`])
      if (!table[name]) throw new Error(`styles.css ${mode} palette lacks --${name}`)
  }
  // The glass look: the dark surfaces are white-alpha fills over the ground
  // (packages/design-tokens `glass`), not the opaque shadcn greys.
  dark.card = hex(design.glass.fillCard)
  dark.muted = hex(design.glass.fillSection)
  dark.secondary = hex(design.glass.fillRow)
  dark.accent = hex(design.glass.fillActive)
  dark.border = hex(design.glass.strokeCard)
  dark.input = hex(design.palette.input)
  // Status semantics are fixed hues on every client (design-tokens `semantic`).
  for (const table of [light, dark]) {
    table.success = hex(design.semantic.green)
    table.warning = hex(design.semantic.yellow)
    table.info = hex(design.semantic.blue)
    table.warningForeground = `#1c1917`
    table.infoForeground = `#ffffff`
  }
  light.successForeground = `#ffffff`
  dark.successForeground = `#052e16`
  light.destructiveForeground ??= `#ffffff`
  dark.destructiveForeground ??= light.foreground
  const shadow = (a: string) => ({
    none: [],
    sm: [{ x: 0, y: 1, blur: 2, spread: 0, color: hex(`rgb(0 0 0 / ${a})`) }],
    md: [{ x: 0, y: 4, blur: 12, spread: -2, color: hex(`rgb(0 0 0 / ${a})`) }],
    lg: [{ x: 0, y: 12, blur: 32, spread: -8, color: hex(`rgb(0 0 0 / ${a})`) }],
    xl: [{ x: 0, y: 20, blur: 48, spread: -12, color: hex(`rgb(0 0 0 / ${a})`) }],
  })
  const s = design.size
  const mono = `ui-monospace`
  return {
    $schema: THEME_SCHEMA_ID,
    id: `exponential`,
    name: `Exponential`,
    extends: `neutral`,
    modes: {
      light: { color: light, shadow: shadow(`0.08`) },
      dark: { color: dark, shadow: shadow(`0.4`) },
    },
    tokens: {
      spacing: { none: 0, ...numbers(design.spacing), xl3: 48 },
      radius: { none: 0, ...numbers(design.radius), full: 9999 },
      type: {
        size: { ...numbers(design.type.size), xl3: 30 },
        lineHeight: { ...numbers(design.type.lineHeight), xl3: 36 },
        weight: numbers(design.type.weight),
        family: { sans: design.type.fontFamily, mono },
      },
      control: {
        buttonSm: s.controlSm, buttonMd: s.controlMd, buttonLg: s.controlLg, buttonIcon: s.controlMd,
        input: s.inputHeight, textarea: 64,
        row: s.rowHeight, rowCompact: 28,
        pill: s.controlSm, badge: 20, chip: s.controlSm,
        toggle: s.controlMd, switch: 20, checkbox: 16, slider: 16,
        progress: 8, meter: 8,
        avatarSm: 24, avatarMd: 32, avatarLg: 40,
        iconSm: 16, iconMd: 20, iconLg: 24,
        hairline: 1,
        appBar: 48, tabBar: 56, toast: 56,
      },
      opacity: { ...numbers(design.type.emphasis), disabled: 0.5 },
      border: { none: 0, hairline: 1, thick: 2 },
      motion: numbers(design.motion.duration),
      // Round 1: the app's easing curves (design-tokens `motion.ease`, the
      // same names) back `$ease.*`; breakpoints and density inherit neutral's.
      ease: Object.fromEntries(Object.entries(design.motion.ease).filter(([k]) => !k.startsWith(`$`))) as Record<string, [number, number, number, number]>,
    },
    fonts: {
      [design.type.fontFamily]: { fallback: `ui-sans-serif, system-ui, sans-serif`, weights: [400, 500, 600, 700], source: `host` },
      [mono]: { fallback: `SFMono-Regular, Menlo, Consolas, monospace`, source: `system` },
    },
    recipes: exponentialRecipes.recipes as unknown as ThemeSource[`recipes`],
  }
}

// ---------------------------------------------------------------------------
// The built-ins, resolved
// ---------------------------------------------------------------------------

export function builtinSources(): ThemeSource[] {
  return [neutralJson as unknown as ThemeSource, composeExponential(), playfulJson as unknown as ThemeSource]
}

export function resolvedBuiltins(): ResolvedTheme[] {
  const sources = builtinSources()
  return sources.map((s) => loadTheme(s, { themes: sources }))
}

// ---------------------------------------------------------------------------
// JSON Schema for a theme file
// ---------------------------------------------------------------------------

export function themeSchema(): Record<string, unknown> {
  const parts = recipeParts()
  const hexSchema = { $ref: `#/$defs/hex` }
  const numberMap = (names: readonly string[]) => ({ type: `object`, additionalProperties: false, properties: Object.fromEntries(names.map((n) => [n, { type: `number` }])) })
  const stringMap = (names: readonly string[]) => ({ type: `object`, additionalProperties: false, properties: Object.fromEntries(names.map((n) => [n, { type: `string`, minLength: 1 }])) })
  const colorOrToken = { anyOf: [hexSchema, { type: `string`, pattern: `^\\$color\\.[a-zA-Z0-9]+$` }] }
  const numOrToken = (groups: string[]) => ({ anyOf: [{ type: `number` }, { type: `string`, pattern: `^\\$(${groups.join(`|`).replace(/\./g, `\\.`)})\\.[a-zA-Z0-9]+$` }] })
  const styleProps: Record<string, unknown> = {
    backgroundColor: colorOrToken,
    color: colorOrToken,
    borderColor: colorOrToken,
    borderWidth: numOrToken([`border`, `control`]),
    borderTopWidth: numOrToken([`border`, `control`]),
    borderRightWidth: numOrToken([`border`, `control`]),
    borderBottomWidth: numOrToken([`border`, `control`]),
    borderLeftWidth: numOrToken([`border`, `control`]),
    borderRadius: numOrToken([`radius`, `spacing`]),
    borderStyle: { enum: styleKeyEnum(`borderStyle`) },
    padding: numOrToken([`spacing`]),
    paddingHorizontal: numOrToken([`spacing`]),
    paddingVertical: numOrToken([`spacing`]),
    gap: numOrToken([`spacing`]),
    width: numOrToken([`control`, `spacing`, `border`]),
    height: numOrToken([`control`, `spacing`, `border`]),
    minWidth: numOrToken([`control`, `spacing`]),
    minHeight: numOrToken([`control`, `spacing`]),
    fontSize: numOrToken([`type.size`]),
    fontWeight: { anyOf: [{ enum: styleKeyEnum(`fontWeight`) }, { type: `string`, pattern: `^\\$type\\.weight\\.[a-zA-Z0-9]+$` }] },
    lineHeight: numOrToken([`type.lineHeight`]),
    fontFamily: { type: `string`, pattern: `^\\$type\\.family\\.[a-zA-Z0-9]+$` },
    letterSpacing: { type: `number` },
    textDecoration: { enum: styleKeyEnum(`textDecoration`) },
    textTransform: { enum: styleKeyEnum(`textTransform`) },
    fontStyle: { enum: styleKeyEnum(`fontStyle`) },
    boxShadow: { type: `string`, pattern: `^\\$shadow\\.[a-zA-Z0-9]+$` },
    opacity: { anyOf: [{ type: `number`, minimum: 0, maximum: 1 }, { type: `string`, pattern: `^\\$opacity\\.[a-zA-Z0-9]+$` }] },
    transition: { type: `string`, pattern: `^\\$motion\\.[a-zA-Z0-9]+$` },
    transitionEasing: { type: `string`, pattern: `^\\$ease\\.[a-zA-Z0-9]+$` },
    transform: { type: `string`, pattern: STYLE_TRANSFORM_PATTERN },
    backdropBlur: { type: `string`, pattern: `^\\$blur\\.[a-zA-Z0-9]+$` },
    animation: { enum: styleKeyEnum(`animation`) },
    native: { type: `boolean` },
  }
  for (const key of RECIPE_KEYS) if (!styleProps[key]) throw new Error(`theme schema: no schema for recipe key ${key}`)
  const whenValue = { anyOf: [{ type: `string` }, { type: `number` }, { type: `boolean` }, { type: `array`, items: { anyOf: [{ type: `string` }, { type: `number` }, { type: `boolean` }] } }] }
  const rule = (props: string[]) => ({
    type: `object`,
    additionalProperties: false,
    required: [`style`],
    properties: {
      when: {
        type: `object`,
        additionalProperties: false,
        properties: {
          state: { anyOf: [{ enum: RECIPE_STATES }, { type: `array`, items: { enum: RECIPE_STATES } }] },
          ...Object.fromEntries(props.map((p) => [p, whenValue])),
        },
      },
      style: { $ref: `#/$defs/recipeStyle` },
    },
  })
  const recipes = {
    type: `object`,
    additionalProperties: false,
    properties: Object.fromEntries(
      Object.entries(parts).map(([component, spec]) => [
        component,
        { type: `object`, additionalProperties: false, properties: Object.fromEntries(spec.parts.map((part) => [part, { type: `array`, items: rule(spec.props) }])) },
      ])
    ),
  }
  const mode = {
    type: `object`,
    additionalProperties: false,
    properties: {
      color: { type: `object`, additionalProperties: false, properties: Object.fromEntries(TOKEN_GROUPS.color.map((n) => [n, hexSchema])) },
      shadow: { type: `object`, additionalProperties: false, properties: Object.fromEntries(TOKEN_GROUPS.shadow.map((n) => [n, { $ref: `#/$defs/shadow` }])) },
    },
  }
  return {
    $schema: `https://json-schema.org/draft/2020-12/schema`,
    $id: THEME_SCHEMA_ID,
    title: `Exponential UI theme`,
    description: `${THEME_HEADER} A theme = token VALUES per mode (colours, shadows) + the mode-less token groups + fonts + component recipes. With \`extends\`, every section is optional and overrides the parent's; a root theme must give every token a value (the loader checks completeness, which a schema cannot).`,
    type: `object`,
    additionalProperties: false,
    required: [`id`, `name`],
    properties: {
      $schema: { type: `string` },
      $comment: { type: `string` },
      id: { type: `string`, pattern: `^[a-z][a-z0-9-]*$` },
      name: { type: `string`, minLength: 1 },
      extends: { type: `string`, description: `The id of the theme this one overrides (a built-in or a loaded theme).` },
      modes: { type: `object`, additionalProperties: false, properties: { light: mode, dark: mode } },
      contrast: { type: `object`, additionalProperties: false, description: `High-contrast overlays per mode: colours/shadows a renderer merges over the mode when the platform (or the host) asks for more contrast.`, properties: { light: mode, dark: mode } },
      tokens: {
        type: `object`,
        additionalProperties: false,
        properties: {
          spacing: numberMap(TOKEN_GROUPS.spacing),
          radius: numberMap(TOKEN_GROUPS.radius),
          type: {
            type: `object`,
            additionalProperties: false,
            properties: {
              size: numberMap(TOKEN_GROUPS[`type.size`]),
              lineHeight: numberMap(TOKEN_GROUPS[`type.lineHeight`]),
              weight: numberMap(TOKEN_GROUPS[`type.weight`]),
              family: stringMap(TOKEN_GROUPS[`type.family`]),
            },
          },
          control: numberMap(TOKEN_GROUPS.control),
          opacity: numberMap(TOKEN_GROUPS.opacity),
          border: numberMap(TOKEN_GROUPS.border),
          motion: numberMap(TOKEN_GROUPS.motion),
          breakpoint: numberMap(TOKEN_GROUPS.breakpoint),
          ease: { type: `object`, additionalProperties: false, properties: Object.fromEntries(TOKEN_GROUPS.ease.map((n) => [n, { type: `array`, items: { type: `number` }, minItems: 4, maxItems: 4 }])) },
          density: numberMap(TOKEN_GROUPS.density),
          blur: numberMap(TOKEN_GROUPS.blur),
        },
      },
      fonts: {
        type: `object`,
        additionalProperties: {
          type: `object`,
          additionalProperties: false,
          properties: { fallback: { type: `string` }, weights: { type: `array`, items: { type: `number` } }, source: { enum: [`system`, `host`] } },
        },
      },
      recipes,
    },
    if: { not: { required: [`extends`] } },
    then: { required: [`modes`, `tokens`, `recipes`] },
    $defs: {
      hex: { type: `string`, pattern: `^#([0-9a-f]{6}|[0-9a-f]{8})$`, description: `#rrggbb or #rrggbbaa, lowercase.` },
      shadow: { type: `array`, items: { type: `object`, additionalProperties: false, required: [`x`, `y`, `blur`, `spread`, `color`], properties: { x: { type: `number` }, y: { type: `number` }, blur: { type: `number` }, spread: { type: `number` }, color: hexSchema } } },
      recipeStyle: { type: `object`, additionalProperties: false, properties: styleProps },
    },
  }
}

// ---------------------------------------------------------------------------
// Native outputs: the resolved built-ins embedded
// ---------------------------------------------------------------------------

function nativeRows(themes: ResolvedTheme[]) {
  const parts = recipeParts()
  return {
    ids: themes.map((t) => t.id),
    names: themes.map((t) => t.name),
    jsons: themes.map((t) => JSON.stringify(t)),
    components: Object.keys(parts),
    partLists: Object.values(parts).map((p) => p.parts.join(`,`)),
    propLists: Object.values(parts).map((p) => p.props.join(`,`)),
  }
}

export function renderThemesSwift(themes: ResolvedTheme[]): string {
  const r = nativeRows(themes)
  const arr = (name: string, values: readonly string[]) => `    public static let ${name}: [String] = [${values.map((v) => JSON.stringify(v)).join(`, `)}]`
  return `// ${THEME_HEADER.split(`\n`).join(`\n// `)}

import Foundation

public enum ExponentialUIThemes {
    public static let schemaId: String = ${JSON.stringify(THEME_SCHEMA_ID)}
    public static let defaultThemeId: String = "exponential"
${arr(`builtinIds`, r.ids)}
${arr(`builtinNames`, r.names)}
    /// The built-ins RESOLVED (extends flattened, every token present), one JSON document each; parse once at startup.
    public static let builtinJson: [String] = [
${r.jsons.map((j) => `        ##"${j}"##,`).join(`\n`)}
    ]
${arr(`recipeStates`, RECIPE_STATES)}
${arr(`recipeKeys`, RECIPE_KEYS)}
${arr(`recipeComponents`, r.components)}
${arr(`recipeParts`, r.partLists)}
${arr(`recipeProps`, r.propLists)}
}
`
}

export function renderThemesKotlin(themes: ResolvedTheme[]): string {
  const r = nativeRows(themes)
  const arr = (name: string, values: readonly string[]) => `    val ${name}: List<String> = listOf(${values.map((v) => JSON.stringify(v)).join(`, `)})`
  const raw = (j: string) => `"""${j.replace(/\$/g, () => `\${'$'}`)}"""`
  return `// ${THEME_HEADER.split(`\n`).join(`\n// `)}

package at.exponential.ui

object ExponentialUIThemes {
    const val schemaId: String = ${JSON.stringify(THEME_SCHEMA_ID)}
    const val defaultThemeId: String = "exponential"
${arr(`builtinIds`, r.ids)}
${arr(`builtinNames`, r.names)}
    /** The built-ins RESOLVED (extends flattened, every token present), one JSON document each; parse once at startup. */
    val builtinJson: List<String> = listOf(
${r.jsons.map((j) => `        ${raw(j)},`).join(`\n`)}
    )
${arr(`recipeStates`, RECIPE_STATES)}
${arr(`recipeKeys`, RECIPE_KEYS)}
${arr(`recipeComponents`, r.components)}
${arr(`recipeParts`, r.partLists)}
${arr(`recipeProps`, r.propLists)}
}
`
}

export function renderThemesRust(themes: ResolvedTheme[]): string {
  const r = nativeRows(themes)
  const arr = (name: string, values: readonly string[]) => `pub const ${name}: &[&str] = &[${values.map((v) => JSON.stringify(v)).join(`, `)}];`
  return `// ${THEME_HEADER.split(`\n`).join(`\n// `)}
// Consumed by apps/desktop/crates/exponential-ui (VAPP-86): the generator copies this file to
// apps/desktop/crates/exponential-ui/src/generated/themes.rs (drift-gated there) so the crate packages standalone.

pub const THEME_SCHEMA_ID: &str = ${JSON.stringify(THEME_SCHEMA_ID)};
pub const DEFAULT_THEME_ID: &str = "exponential";
${arr(`BUILTIN_THEME_IDS`, r.ids)}
${arr(`BUILTIN_THEME_NAMES`, r.names)}
/// The built-ins RESOLVED (extends flattened, every token present), one JSON document each; parse once at startup.
pub const BUILTIN_THEME_JSON: &[&str] = &[
${r.jsons.map((j) => `    r####"${j}"####,`).join(`\n`)}
];
${arr(`RECIPE_STATES`, RECIPE_STATES)}
${arr(`RECIPE_KEYS`, RECIPE_KEYS)}
${arr(`RECIPE_COMPONENTS`, r.components)}
${arr(`RECIPE_PARTS`, r.partLists)}
${arr(`RECIPE_PROPS`, r.propLists)}
`
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

interface RecipeTuple {
  component: string
  part: string
  props: Record<string, unknown>
}

function tupleKey(t: RecipeTuple): string {
  return `${t.component}/${t.part}/${JSON.stringify(t.props)}`
}

function walk(node: UiNode, visit: (n: UiNode) => void): void {
  visit(node)
  for (const slot of Object.values(node.slots ?? {})) walk(slot, visit)
  node.children.forEach((c) => walk(c, visit))
}

/** Every (component, part, props) a theme can be asked about: each native
 *  part × its props varied one at a time over the defaults, each macro part
 *  as the component cases + the kitchen sink produce it. */
export function recipeTuples(componentCases: { node: NestedNode }[], kitchen: NestedNode): RecipeTuple[] {
  const parts = recipeParts()
  const seen = new Map<string, RecipeTuple>()
  const add = (t: RecipeTuple) => {
    const key = tupleKey(t)
    if (!seen.has(key)) seen.set(key, t)
  }
  for (const [name, def] of Object.entries(coreCatalog.components)) {
    if (def.kind !== `native`) continue
    const spec = parts[name]
    const defaults = nativeRecipeProps(name, def.example ?? {})
    const combos: Record<string, unknown>[] = [defaults]
    for (const prop of spec.props) {
      const schema = def.props[prop]
      if (!schema) continue
      const values = schema.type === `boolean` ? [true, false] : (schema.values ?? coreCatalog.enums[schema.enum ?? ``] ?? [])
      for (const value of values) combos.push({ ...defaults, [prop]: value })
    }
    for (const part of spec.parts) for (const props of combos) add({ component: name, part, props })
  }
  const trees = [...componentCases.map((c) => reduceNested(c.node, { catalogId: CORE_CATALOG_ID }).root), reduceNested(kitchen, { catalogId: CORE_CATALOG_ID }).root]
  for (const tree of trees) walk(tree, (n) => { if (n.recipe) add({ component: n.recipe.macro, part: n.recipe.part, props: n.recipe.props }) })
  return [...seen.values()]
}

const same = (a: unknown, b: unknown) => JSON.stringify(a) === JSON.stringify(b)

export function recipesFixture(themes: ResolvedTheme[], tuples: RecipeTuple[]) {
  const cases = tuples
    .map((t) => {
      const visuals: Record<string, Record<string, Record<string, ResolvedStyle>>> = {}
      let any = false
      for (const theme of themes) {
        const byMode: Record<string, Record<string, ResolvedStyle>> = {}
        for (const mode of MODES) {
          const base = resolveRecipe(theme, { ...t, states: [] }, mode)
          const byState: Record<string, ResolvedStyle> = { default: base }
          for (const state of RECIPE_STATES) {
            const style = resolveRecipe(theme, { ...t, states: [state] }, mode)
            if (!same(style, base)) byState[state] = style
          }
          if (Object.keys(base).length > 0 || Object.keys(byState).length > 1) any = true
          byMode[mode] = byState
        }
        visuals[theme.id] = byMode
      }
      return any ? { ...t, visuals } : null
    })
    .filter((c): c is NonNullable<typeof c> => c !== null)
    // One case per distinct look: a prop value no theme keys on (Input
    // type=email…) resolves exactly like the defaults and is dropped.
    .filter((c, i, all) => all.findIndex((o) => o.component === c.component && o.part === c.part && same(o.visuals, c.visuals)) === i)
  return {
    $comment: `${THEME_HEADER} theme × component part × recipe props → the resolved visuals per mode (\`default\` = no state; a state appears only where it changes something; one case per distinct look per part). Every painter resolves the same: the native's own recipe < the node's style < the macro part's recipe (src/theme.ts resolveNodeStyle); this file locks the recipe half.`,
    themes: themes.map((t) => t.id),
    states: RECIPE_STATES,
    cases,
  }
}

export function extendsFixture(file: { $comment: string; cases: { name: string; theme: ThemeSource; probes: (RecipeQuery & { mode: ModeName })[] }[] }, sources: ThemeSource[]) {
  return {
    $comment: file.$comment,
    cases: file.cases.map((c) => {
      const theme = loadTheme(c.theme, { themes: sources })
      return {
        name: c.name,
        theme: c.theme,
        probes: c.probes,
        expected: {
          chain: theme.chain,
          probes: c.probes.map((p) => ({ ...p, style: resolveRecipe(theme, { component: p.component, part: p.part, props: p.props, states: p.states }, p.mode) })),
        },
      }
    }),
  }
}

export function invalidFixture(file: { $comment: string; cases: { name: string; theme: unknown }[] }, sources: ThemeSource[]) {
  return {
    $comment: file.$comment,
    cases: file.cases.map((c) => {
      const { theme, issues } = tryLoadTheme(c.theme, { themes: sources })
      if (theme) throw new Error(`theme-invalid.json: "${c.name}" loaded without issues`)
      return { name: c.name, theme: c.theme, issues }
    }),
  }
}

export function geometryFixture(themes: ResolvedTheme[]) {
  const parts = recipeParts()
  const out: Record<string, Record<string, Record<string, unknown>>> = {}
  for (const theme of themes) {
    const byComponent: Record<string, Record<string, unknown>> = {}
    for (const component of Object.keys(CONTROL_PARTS)) {
      const def = coreCatalog.components[component]
      const spec = parts[component]
      const defaults = nativeRecipeProps(component, def.example ?? {})
      const combos: { name: string; props: Record<string, unknown> }[] = [{ name: `default`, props: defaults }]
      for (const prop of spec.props) {
        const schema = def.props[prop]
        if (!schema || schema.type !== `enum`) continue
        for (const value of schema.values ?? coreCatalog.enums[schema.enum ?? ``] ?? []) combos.push({ name: `${prop}=${value}`, props: { ...defaults, [prop]: value } })
      }
      const cases: Record<string, unknown> = {}
      for (const c of combos) cases[c.name] = { props: c.props, geometry: controlGeometry(theme, component, c.props) }
      byComponent[component] = { part: CONTROL_PARTS[component], cases }
    }
    out[theme.id] = byComponent
  }
  return {
    $comment: `${THEME_HEADER} The measure contract: per built-in theme and control, the box the recipe of its sizing part fixes (px). A painter — built in or a host's override (VAPP-91) — must produce exactly this box; src/geometry.ts checkGeometry is the check the conformance suite runs.`,
    parts: CONTROL_PARTS,
    themes: out,
  }
}

export function themesDocs(themes: ResolvedTheme[]) {
  const parts = recipeParts()
  return {
    $comment: `${THEME_HEADER} What ui.exponential.at renders as the theme pages (VAPP-93): the token vocabulary with every built-in's values, the recipe contract per component, the built-ins.`,
    schemaId: THEME_SCHEMA_ID,
    themes: themes.map((t) => ({ id: t.id, name: t.name, chain: t.chain, fonts: t.fonts })),
    tokens: Object.fromEntries(
      Object.entries(TOKEN_GROUPS).map(([group, names]) => [
        group,
        names.map((name) => ({
          name,
          ref: `$${group}.${name}`,
          values: Object.fromEntries(
            themes.map((t) => [
              t.id,
              group === `color` || group === `shadow`
                ? { light: t.modes.light[group as `color` | `shadow`][name], dark: t.modes.dark[group as `color` | `shadow`][name] }
                : group.startsWith(`type.`)
                  ? (t.tokens.type as unknown as Record<string, Record<string, unknown>>)[group.slice(5)][name]
                  : (t.tokens as unknown as Record<string, Record<string, unknown>>)[group][name],
            ])
          ),
        })),
      ])
    ),
    states: RECIPE_STATES,
    keys: RECIPE_KEYS,
    components: Object.entries(parts).map(([name, spec]) => ({ name, kind: coreCatalog.components[name]?.kind, parts: spec.parts, props: spec.props })),
  }
}

function readJson<T>(rel: string): T {
  return JSON.parse(readFileSync(join(pkgRoot, rel), `utf8`)) as T
}

/** Every theme output, keyed by path relative to the package root. */
export function renderThemes(componentCases: { node: NestedNode }[], kitchen: NestedNode): Record<string, string> {
  const sources = builtinSources()
  const themes = sources.map((s) => loadTheme(s, { themes: sources }))
  const exponential = sources[1]
  return {
    "themes/exponential.theme.json": json({ $comment: `${THEME_HEADER} Composed by scripts/generate-themes.ts composeExponential(): edit themes/exponential.recipes.json, packages/design-tokens/tokens.json or packages/ui/src/styles.css and regenerate.`, ...exponential }),
    "catalog/theme.schema.json": json(themeSchema()),
    "generated/ExponentialUIThemes.generated.swift": renderThemesSwift(themes),
    "generated/ExponentialUIThemes.generated.kt": renderThemesKotlin(themes),
    "generated/catalog.themes.generated.rs": renderThemesRust(themes),
    "docs/themes.generated.json": json(themesDocs(themes)),
    "fixtures/theme-resolved.json": json({ $comment: `${THEME_HEADER} Every built-in theme RESOLVED (extends flattened, every token present, recipes merged): what a painter holds at startup and what a native loader must produce from the same source files.`, themes: Object.fromEntries(themes.map((t) => [t.id, t])) }),
    "fixtures/theme-recipes.json": json(recipesFixture(themes, recipeTuples(componentCases, kitchen))),
    "fixtures/theme-extends.json": json(extendsFixture(readJson(`fixtures/theme-extends.json`), sources)),
    "fixtures/theme-invalid.json": json(invalidFixture(readJson(`fixtures/theme-invalid.json`), sources)),
    "fixtures/control-geometry.json": json(geometryFixture(themes)),
  }
}
