#!/usr/bin/env bun
// VAPP-85: emits everything derived from catalog/*.json. Run from the repo
// root with `bun run --filter @exponential-at/ui generate`; generate.test.ts
// re-renders in memory and fails on any committed drift.
//
// Outputs (all committed):
//   catalog/core.schema.json              the catalog as JSON Schema (A2UI catalog shape)
//   src/catalog.generated.ts              names, enums, token names, icon names, basic map
//   generated/ExponentialUICatalog.generated.swift   the same for the SwiftUI painter (VAPP-88)
//   generated/ExponentialUICatalog.generated.kt      the same for the Compose painter (VAPP-89)
//   generated/catalog.generated.rs                   the same for the Rust core (VAPP-86)
//   docs/components.generated.json        one doc page per component, as data (VAPP-93 renders it)
//   fixtures/catalog-components.json      every component × every enum/boolean value
//   fixtures/catalog-macros.json          every macro case → the expanded tree
//   fixtures/catalog-basic-map.json       the hand-written basic cases → expected trees
//   fixtures/catalog-extension.json       the example extension's cases → expected trees
//   fixtures/kitchen-sink.expanded.json   fixtures/kitchen-sink.json, reduced + expanded
//   fixtures/prompt-budget.json           the prompt's size on record
//
// The icon name list is read from packages/icons/icons.json at GENERATE time
// (the registry is the Icon prop's vocabulary); the package has no runtime
// dependency on it.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { A2UI_BASIC_CATALOG_ID, A2UI_VERSION, CORE_CATALOG_ID, CORE_LITE_CATALOG_ID, TOKEN_GROUPS, coreCatalog } from "../src/catalog"
import { basicMap } from "../src/basic-map"
import { catalogPrompt, estimateTokens } from "../src/prompt"
import { reduceNested, reduceSurface } from "../src/reducer"
import { coreSchema } from "../src/schema"
import { STYLE_KEYS, STYLE_STATES } from "../src/style"
import styleJson from "../catalog/style.json" with { type: "json" }
import type { ComponentDef, ExtensionDef, FlatComponent, NestedNode, PropSchema } from "../src/types"

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), `..`)
const repoRoot = join(pkgRoot, `..`, `..`)

const HEADER = `AUTO-GENERATED by packages/exponential-ui/scripts/generate.ts — do not edit.
Source of truth: packages/exponential-ui/catalog/core.catalog.json (+ tokens.json, style.json, basic-map.json).`

// ---------------------------------------------------------------------------
// Inputs
// ---------------------------------------------------------------------------

interface IconRegistry {
  pickable: string[]
  devicePickable: string[]
  semantic: Record<string, string>
  custom?: Record<string, unknown>
  imported?: Record<string, unknown>
}

/** Every name the Icon prop accepts: the concept ids plus every registry
 *  glyph name (pickable, device, the Lucide targets, custom, imported). */
export function iconNames(): string[] {
  const registry = JSON.parse(readFileSync(join(repoRoot, `packages/icons/icons.json`), `utf8`)) as IconRegistry
  const names = new Set<string>()
  for (const name of Object.keys(registry.semantic)) names.add(name)
  for (const name of Object.values(registry.semantic)) names.add(name)
  for (const name of registry.pickable) names.add(name)
  for (const name of registry.devicePickable) names.add(name)
  for (const name of Object.keys(registry.custom ?? {})) names.add(name)
  for (const name of Object.keys(registry.imported ?? {})) names.add(name)
  return [...names].sort()
}

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`
const kebab = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, `$1-$2`).toLowerCase()
const screaming = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, `$1_$2`).replace(/[^A-Za-z0-9]+/g, `_`).toUpperCase()
const capFirst = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)

const components = Object.entries(coreCatalog.components)
const visible = components.filter(([, def]) => !def.hidden)
const names = components.map(([name]) => name)
const natives = components.filter(([, d]) => d.kind === `native`).map(([n]) => n)
const macros = components.filter(([, d]) => d.kind === `macro`).map(([n]) => n)
const lite = visible.filter(([, d]) => d.lite).map(([n]) => n)
const specimenId = (name: string) => `exponential-ui-${kebab(name)}`
const basicTargets = Object.entries(basicMap.components).map(([basic, rule]) => [basic, rule.to] as const)
const basicIcons = Object.entries(basicMap.icons).map(([basic, target]) => [basic, target ?? basicMap.placeholderIcon] as const)

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------

function renderTs(icons: string[]): string {
  const enumConsts = Object.entries(coreCatalog.enums)
    .map(([name, values]) => `  ${name}: ${JSON.stringify(values)},`)
    .join(`\n`)
  const enumTypes = Object.entries(coreCatalog.enums)
    .map(([name]) => `export type ${capFirst(name)}Value = (typeof ENUMS)[${JSON.stringify(name)}][number]`)
    .join(`\n`)
  const tokenConsts = Object.entries(TOKEN_GROUPS)
    .map(([group, values]) => `  ${JSON.stringify(group)}: ${JSON.stringify(values)},`)
    .join(`\n`)
  return `// ${HEADER.split(`\n`).join(`\n// `)}

export const CATALOG_ID = ${JSON.stringify(CORE_CATALOG_ID)}
export const LITE_CATALOG_ID = ${JSON.stringify(CORE_LITE_CATALOG_ID)}
export const BASIC_CATALOG_ID = ${JSON.stringify(A2UI_BASIC_CATALOG_ID)}
export const BASIC_VERSION = ${JSON.stringify(A2UI_VERSION)}
export const CATALOG_VERSION = ${JSON.stringify(coreCatalog.version)}
export const UNKNOWN_COMPONENT_NAME = ${JSON.stringify(coreCatalog.unknownComponent)}

/** Every component in source order (the hidden placeholder included). */
export const COMPONENT_NAMES = ${JSON.stringify(names)} as const
export type ComponentName = (typeof COMPONENT_NAMES)[number]
export const NATIVE_COMPONENTS = ${JSON.stringify(natives)} as const
export const MACRO_COMPONENTS = ${JSON.stringify(macros)} as const
/** The core-lite subset (no overlays, media or Chart). */
export const LITE_COMPONENTS = ${JSON.stringify(lite)} as const
export const COMPONENT_GROUPS: Record<ComponentName, string> = ${JSON.stringify(Object.fromEntries(components.map(([n, d]) => [n, d.group])))}
/** The specimen id each component has on ui.exponential.at. */
export const SPECIMEN_IDS: Record<ComponentName, string> = ${JSON.stringify(Object.fromEntries(names.map((n) => [n, specimenId(n)])))}

export const ENUMS = {
${enumConsts}
} as const
${enumTypes}

/** Token NAMES by group (values come from a theme). */
export const TOKEN_NAMES = {
${tokenConsts}
} as const
export type TokenGroup = keyof typeof TOKEN_NAMES

export const STYLE_KEY_NAMES = ${JSON.stringify(STYLE_KEYS)} as const
export const STYLE_STATE_NAMES = ${JSON.stringify(STYLE_STATES)} as const

/** The Icon prop's vocabulary: packages/icons/icons.json at generate time. */
export const ICON_NAMES = ${JSON.stringify(icons)} as const

export const FUNCTION_NAMES = ${JSON.stringify(coreCatalog.functions.names)} as const

/** A2UI basic component → core component. */
export const BASIC_COMPONENT_MAP: Record<string, string> = ${JSON.stringify(Object.fromEntries(basicTargets))}
/** A2UI basic icon name → icons.json name (the placeholder where none exists). */
export const BASIC_ICON_MAP: Record<string, string> = ${JSON.stringify(Object.fromEntries(basicIcons))}
export const BASIC_PLACEHOLDER_ICON = ${JSON.stringify(basicMap.placeholderIcon)}
`
}

// ---------------------------------------------------------------------------
// Swift / Kotlin / Rust: parallel arrays, like packages/domain-contract
// ---------------------------------------------------------------------------

const propNames = (def: ComponentDef) => Object.keys(def.props).join(`,`)
const eventNames = (def: ComponentDef) => (def.events ?? []).join(`,`)
const rows = {
  componentNames: names,
  componentKinds: components.map(([, d]) => d.kind),
  componentGroups: components.map(([, d]) => d.group),
  componentChildren: components.map(([, d]) => d.children),
  componentProps: components.map(([, d]) => propNames(d)),
  componentEvents: components.map(([, d]) => eventNames(d)),
  componentSlots: components.map(([, d]) => (d.slots ?? []).join(`,`)),
  componentSpecimenIds: names.map(specimenId),
  liteComponents: lite,
  nativeComponents: natives,
  macroComponents: macros,
  enumNames: Object.keys(coreCatalog.enums),
  enumValues: Object.values(coreCatalog.enums).map((v) => v.join(`|`)),
  tokenGroups: Object.keys(TOKEN_GROUPS),
  tokenNames: Object.values(TOKEN_GROUPS).map((v) => v.join(`,`)),
  styleKeys: [...STYLE_KEYS],
  styleLayoutKeys: Object.keys(styleJson.layout),
  styleStates: [...STYLE_STATES],
  functionNames: [...coreCatalog.functions.names],
  basicComponentNames: basicTargets.map(([b]) => b),
  basicComponentTargets: basicTargets.map(([, t]) => t),
  basicIconNames: basicIcons.map(([b]) => b),
  basicIconTargets: basicIcons.map(([, t]) => t),
}
const liteFlags = components.map(([, d]) => d.lite && !d.hidden)
const scalars: [string, string][] = [
  [`catalogId`, CORE_CATALOG_ID],
  [`liteCatalogId`, CORE_LITE_CATALOG_ID],
  [`basicCatalogId`, A2UI_BASIC_CATALOG_ID],
  [`basicVersion`, A2UI_VERSION],
  [`catalogVersion`, coreCatalog.version],
  [`unknownComponent`, coreCatalog.unknownComponent],
  [`basicPlaceholderIcon`, basicMap.placeholderIcon],
  [`styleMediaPattern`, styleJson.conditions.media],
]

function renderSwift(): string {
  const arr = (name: string, values: readonly string[]) => `    public static let ${name}: [String] = [${values.map((v) => JSON.stringify(v)).join(`, `)}]`
  return `// ${HEADER.split(`\n`).join(`\n// `)}

import Foundation

public enum ExponentialUICatalog {
${scalars.map(([k, v]) => `    public static let ${k}: String = ${JSON.stringify(v)}`).join(`\n`)}
${Object.entries(rows).map(([k, v]) => arr(k, v)).join(`\n`)}
    public static let componentLite: [Bool] = [${liteFlags.join(`, `)}]
}
`
}

function renderKotlin(): string {
  const arr = (name: string, values: readonly string[]) => `    val ${name}: List<String> = listOf(${values.map((v) => JSON.stringify(v)).join(`, `)})`
  return `// ${HEADER.split(`\n`).join(`\n// `)}

package at.exponential.ui

object ExponentialUICatalog {
${scalars.map(([k, v]) => `    const val ${k}: String = ${JSON.stringify(v)}`).join(`\n`)}
${Object.entries(rows).map(([k, v]) => arr(k, v)).join(`\n`)}
    val componentLite: List<Boolean> = listOf(${liteFlags.join(`, `)})
}
`
}

function renderRust(): string {
  const arr = (name: string, values: readonly string[]) => `pub const ${screaming(name)}: &[&str] = &[${values.map((v) => JSON.stringify(v)).join(`, `)}];`
  return `// ${HEADER.split(`\n`).join(`\n// `)}
// Consumed by apps/desktop/crates/exponential-ui (VAPP-86) via include!.

${scalars.map(([k, v]) => `pub const ${screaming(k)}: &str = ${JSON.stringify(v)};`).join(`\n`)}
${Object.entries(rows).map(([k, v]) => arr(k, v)).join(`\n`)}
pub const COMPONENT_LITE: &[bool] = &[${liteFlags.join(`, `)}];
`
}

// ---------------------------------------------------------------------------
// Docs: one page per component, as data
// ---------------------------------------------------------------------------

function docProps(def: ComponentDef) {
  const typeOf = (s: PropSchema): string =>
    s.type === `enum`
      ? (s.values ?? coreCatalog.enums[s.enum ?? ``] ?? []).join(` | `)
      : s.type === `array`
        ? `[${s.items ? (s.items.type === `object` ? s.items.shape : typeOf(s.items)) : ``}]`
        : s.type === `object`
          ? (s.shape ?? `object`)
          : s.type
  return Object.entries(def.props).map(([name, s]) => ({
    name,
    type: typeOf(s),
    required: s.required ?? false,
    bindable: s.bindable ?? false,
    ...(s.default !== undefined ? { default: s.default } : {}),
    description: s.description,
  }))
}

function renderDocs() {
  const basicAliases: Record<string, string[]> = {}
  for (const [basic, rule] of Object.entries(basicMap.components)) (basicAliases[rule.to] ??= []).push(basic)
  basicAliases.Heading = [`Text (h1–h4)`]
  basicAliases.Avatar = [`Image (avatar)`]
  basicAliases.Textarea = [`TextField (longText)`]
  basicAliases.ToggleGroup = [`ChoicePicker (chips)`]
  basicAliases.Select = [`ChoicePicker (filterable, multipleSelection)`]
  return {
    $comment: `${HEADER} One entry per component: what ui.exponential.at renders as the component's page (VAPP-93). specimenId = the id of its specimen there, painted once each renderer lands.`,
    catalogId: CORE_CATALOG_ID,
    liteCatalogId: CORE_LITE_CATALOG_ID,
    groups: [...new Set(components.map(([, d]) => d.group))],
    components: visible.map(([name, def]) => ({
      name,
      kind: def.kind,
      group: def.group,
      lite: def.lite,
      ...(def.status ? { status: def.status } : {}),
      specimenId: specimenId(name),
      description: def.description,
      children: def.children,
      slots: def.slots ?? [],
      events: def.events ?? [],
      basic: basicAliases[name] ?? [],
      props: docProps(def),
      example: { id: `example`, component: name, ...(def.example ?? {}) },
      macro: def.kind === `macro` ? `Expands to natives (see catalog/macros.json); the theme styles its parts by recipe ${name}/<part>.` : null,
    })),
  }
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

interface ComponentCase {
  name: string
  node: NestedNode
}

function childFor(name: string): NestedNode {
  return { id: `${kebab(name)}-child`, component: `Text`, props: { text: `Child` } }
}

/** Every visible component: its example, then every enum value of every enum
 *  prop and both values of every boolean prop, over the example. */
function componentCases(): ComponentCase[] {
  const cases: ComponentCase[] = []
  for (const [name, def] of visible) {
    const base = { ...(def.example ?? {}) }
    const make = (suffix: string, props: Record<string, unknown>): ComponentCase => {
      const node: NestedNode = { id: kebab(name), component: name, props }
      if (def.children !== `none`) node.children = [childFor(name)]
      return { name: `${name}/${suffix}`, node }
    }
    cases.push(make(`example`, base))
    for (const [prop, schema] of Object.entries(def.props)) {
      if (schema.type === `enum`) {
        const values = schema.values ?? coreCatalog.enums[schema.enum ?? ``] ?? []
        for (const value of values) cases.push(make(`${prop}=${value}`, { ...base, [prop]: value }))
      } else if (schema.type === `boolean`) {
        for (const value of [true, false]) cases.push(make(`${prop}=${value}`, { ...base, [prop]: value }))
      }
    }
  }
  return cases
}

function macroCases(all: ComponentCase[]) {
  return all
    .filter((c) => coreCatalog.components[c.node.component].kind === `macro`)
    .map((c) => {
      const result = reduceNested(c.node, { catalogId: CORE_CATALOG_ID })
      if (result.issues.length > 0) throw new Error(`${c.name}: ${result.issues.map((i) => i.message).join(`; `)}`)
      return { name: c.name, input: c.node, expected: result.root }
    })
}

interface BasicCaseFile {
  $comment: string
  catalogId: string
  cases: { name: string; components: FlatComponent[]; expected?: unknown }[]
}

function basicCases(file: BasicCaseFile) {
  return {
    ...file,
    cases: file.cases.map((c) => ({
      name: c.name,
      components: c.components,
      expected: reduceSurface(c.components, { catalogId: A2UI_BASIC_CATALOG_ID }),
    })),
  }
}

interface ExtensionCaseFile {
  $comment: string
  extension: ExtensionDef
  cases: { name: string; catalogId: string; components: FlatComponent[]; expected?: unknown }[]
}

function extensionCases(file: ExtensionCaseFile) {
  return {
    ...file,
    cases: file.cases.map((c) => ({
      name: c.name,
      catalogId: c.catalogId,
      components: c.components,
      expected: reduceSurface(c.components, { catalogId: c.catalogId, extensions: [file.extension] }),
    })),
  }
}

function promptBudget() {
  const full = catalogPrompt()
  const liteText = catalogPrompt({ lite: true })
  const terse = catalogPrompt({ terse: true })
  return {
    $comment: `${HEADER} The size of catalogPrompt() on record: prompt.test.ts fails when the full prompt passes budgetTokens (cut descriptions before components) or when these numbers drift from the catalog without being regenerated. tokens = chars / ${4}, an estimate.`,
    budgetTokens: 6500,
    full: { components: visible.length, chars: full.length, tokens: estimateTokens(full) },
    lite: { components: lite.length, chars: liteText.length, tokens: estimateTokens(liteText) },
    terse: { components: visible.length, chars: terse.length, tokens: estimateTokens(terse) },
  }
}

// ---------------------------------------------------------------------------
// Render everything
// ---------------------------------------------------------------------------

function readJson<T>(rel: string): T {
  return JSON.parse(readFileSync(join(pkgRoot, rel), `utf8`)) as T
}

/** Every generated file, keyed by its path relative to the package root. */
export function render(): Record<string, string> {
  const icons = iconNames()
  const cases = componentCases()
  const kitchen = readJson<NestedNode>(`fixtures/kitchen-sink.json`)
  const kitchenResult = reduceNested(kitchen, { catalogId: CORE_CATALOG_ID })
  if (kitchenResult.issues.length > 0)
    throw new Error(`kitchen-sink.json: ${kitchenResult.issues.map((i) => `${i.id}: ${i.message}`).join(`\n`)}`)
  return {
    "catalog/core.schema.json": json(coreSchema(icons)),
    "src/catalog.generated.ts": renderTs(icons),
    "generated/ExponentialUICatalog.generated.swift": renderSwift(),
    "generated/ExponentialUICatalog.generated.kt": renderKotlin(),
    "generated/catalog.generated.rs": renderRust(),
    "docs/components.generated.json": json(renderDocs()),
    "fixtures/catalog-components.json": json({
      $comment: `${HEADER} Every visible component × its example × every enum value of every enum prop × both values of every boolean prop. Each case validates against core.schema.json; a renderer suite paints each case once.`,
      catalogId: CORE_CATALOG_ID,
      cases,
    }),
    "fixtures/catalog-macros.json": json({
      $comment: `${HEADER} Every macro case of catalog-components.json → the tree the expander produces (macros.json applied, recipes attached). The Rust core replays these byte for byte.`,
      catalogId: CORE_CATALOG_ID,
      cases: macroCases(cases),
    }),
    "fixtures/catalog-basic-map.json": json(basicCases(readJson<BasicCaseFile>(`fixtures/catalog-basic-map.json`))),
    "fixtures/catalog-extension.json": json(extensionCases(readJson<ExtensionCaseFile>(`fixtures/catalog-extension.json`))),
    "fixtures/kitchen-sink.expanded.json": json({
      $comment: `${HEADER} fixtures/kitchen-sink.json reduced and expanded: what every painter receives.`,
      ...kitchenResult,
    }),
    "fixtures/prompt-budget.json": json(promptBudget()),
  }
}

if (import.meta.main) {
  const files = render()
  for (const [rel, content] of Object.entries(files)) {
    const path = join(pkgRoot, rel)
    mkdirSync(dirname(path), { recursive: true })
    const before = existsSync(path) ? readFileSync(path, `utf8`) : null
    writeFileSync(path, content)
    console.log(`${before === content ? `unchanged` : `wrote    `} ${rel}`)
  }
}
