#!/usr/bin/env bun
// VAPP-85: emits everything derived from catalog/*.json. Run from the repo
// root with `bun run --filter @exponential-at/ui generate`; generate.test.ts
// re-renders in memory and fails on any committed drift.
//
// Outputs (all committed):
//   catalog/core.schema.json              the catalog as JSON Schema (A2UI catalog shape)
//   src/catalog.generated.ts              names, enums, token names, icon names, basic map
//   generated/ExponentialUICatalog.generated.swift   the same for the SwiftUI painter (VAPP-88)
//   generated/ExponentialUICatalog.generated.kt      the same for the Compose painter (VAPP-89)
//   generated/catalog.generated.rs                   the same for the Rust core (VAPP-86)
//   docs/components.generated.json        one doc page per component, as data (VAPP-93 renders it)
//   fixtures/catalog-components.json      every component × every enum/boolean value
//   fixtures/catalog-macros.json          every macro case → the expanded tree
//   fixtures/catalog-basic-map.json       the hand-written basic cases → expected trees
//   fixtures/catalog-extension.json       the example extension's cases → expected trees
//   fixtures/kitchen-sink.expanded.json   fixtures/kitchen-sink.json, reduced + expanded
//   fixtures/prompt-budget.json           the prompt's size on record
//   fixtures/specimens.json               one surface per component + the demo (VAPP-93: the site's shots)
//   + the theme outputs of scripts/generate-themes.ts (VAPP-92)
//
// The icon name list is read from packages/icons/icons.json at GENERATE time
// (the registry is the Icon prop's vocabulary); the package has no runtime
// dependency on it.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { A2UI_BASIC_CATALOG_ID, A2UI_VERSION, CORE_CATALOG_ID, CORE_LITE_CATALOG_ID, TOKEN_GROUPS, coreCatalog } from "../src/catalog"
import { basicMap } from "../src/basic-map"
import { catalogPrompt, estimateTokens } from "../src/prompt"
import { reduceNested, reduceSurface } from "../src/reducer"
import { coreSchema } from "../src/schema"
import { STYLE_KEYS, STYLE_STATES } from "../src/style"
import { renderThemes } from "./generate-themes"
import { renderHost } from "./generate-host"
import { conformanceManifest } from "../src/conformance"
import styleJson from "../catalog/style.json" with { type: "json" }
import type { ComponentDef, ExtensionDef, FlatComponent, NestedNode, PropSchema } from "../src/types"

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), `..`)
const repoRoot = join(pkgRoot, `..`, `..`)

const HEADER = `AUTO-GENERATED by packages/exponential-ui/scripts/generate.ts — do not edit.
Source of truth: packages/exponential-ui/catalog/core.catalog.json (+ tokens.json, style.json, basic-map.json).`

// ---------------------------------------------------------------------------
// Inputs
// ---------------------------------------------------------------------------

interface IconRegistry {
  pickable: string[]
  devicePickable: string[]
  semantic: Record<string, string>
  custom?: Record<string, unknown>
  imported?: Record<string, unknown>
}

/** Every name the Icon prop accepts: the concept ids plus every registry
 *  glyph name (pickable, device, the Lucide targets, custom, imported). */
export function iconNames(): string[] {
  const registry = JSON.parse(readFileSync(join(repoRoot, `packages/icons/icons.json`), `utf8`)) as IconRegistry
  const names = new Set<string>()
  for (const name of Object.keys(registry.semantic)) names.add(name)
  for (const name of Object.values(registry.semantic)) names.add(name)
  for (const name of registry.pickable) names.add(name)
  for (const name of registry.devicePickable) names.add(name)
  for (const name of Object.keys(registry.custom ?? {})) names.add(name)
  for (const name of Object.keys(registry.imported ?? {})) names.add(name)
  return [...names].sort()
}

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`
const kebab = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, `$1-$2`).toLowerCase()
const screaming = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, `$1_$2`).replace(/[^A-Za-z0-9]+/g, `_`).toUpperCase()
const capFirst = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)

const components = Object.entries(coreCatalog.components)
const visible = components.filter(([, def]) => !def.hidden)
const names = components.map(([name]) => name)
const natives = components.filter(([, d]) => d.kind === `native`).map(([n]) => n)
const macros = components.filter(([, d]) => d.kind === `macro`).map(([n]) => n)
const lite = visible.filter(([, d]) => d.lite).map(([n]) => n)
const specimenId = (name: string) => `exponential-ui-${kebab(name)}`
const basicTargets = Object.entries(basicMap.components).map(([basic, rule]) => [basic, rule.to] as const)
const basicIcons = Object.entries(basicMap.icons).map(([basic, target]) => [basic, target ?? basicMap.placeholderIcon] as const)

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------

function renderTs(icons: string[]): string {
  const enumConsts = Object.entries(coreCatalog.enums)
    .map(([name, values]) => `  ${name}: ${JSON.stringify(values)},`)
    .join(`\n`)
  const enumTypes = Object.entries(coreCatalog.enums)
    .map(([name]) => `export type ${capFirst(name)}Value = (typeof ENUMS)[${JSON.stringify(name)}][number]`)
    .join(`\n`)
  const tokenConsts = Object.entries(TOKEN_GROUPS)
    .map(([group, values]) => `  ${JSON.stringify(group)}: ${JSON.stringify(values)},`)
    .join(`\n`)
  return `// ${HEADER.split(`\n`).join(`\n// `)}

export const CATALOG_ID = ${JSON.stringify(CORE_CATALOG_ID)}
export const LITE_CATALOG_ID = ${JSON.stringify(CORE_LITE_CATALOG_ID)}
export const BASIC_CATALOG_ID = ${JSON.stringify(A2UI_BASIC_CATALOG_ID)}
export const BASIC_VERSION = ${JSON.stringify(A2UI_VERSION)}
export const CATALOG_VERSION = ${JSON.stringify(coreCatalog.version)}
export const UNKNOWN_COMPONENT_NAME = ${JSON.stringify(coreCatalog.unknownComponent)}

/** Every component in source order (the hidden placeholder included). */
export const COMPONENT_NAMES = ${JSON.stringify(names)} as const
export type ComponentName = (typeof COMPONENT_NAMES)[number]
export const NATIVE_COMPONENTS = ${JSON.stringify(natives)} as const
export const MACRO_COMPONENTS = ${JSON.stringify(macros)} as const
/** The core-lite subset (no overlays, media or Chart). */
export const LITE_COMPONENTS = ${JSON.stringify(lite)} as const
export const COMPONENT_GROUPS: Record<ComponentName, string> = ${JSON.stringify(Object.fromEntries(components.map(([n, d]) => [n, d.group])))}
/** The specimen id each component has on ui.exponential.at. */
export const SPECIMEN_IDS: Record<ComponentName, string> = ${JSON.stringify(Object.fromEntries(names.map((n) => [n, specimenId(n)])))}

export const ENUMS = {
${enumConsts}
} as const
${enumTypes}

/** Token NAMES by group (values come from a theme). */
export const TOKEN_NAMES = {
${tokenConsts}
} as const
export type TokenGroup = keyof typeof TOKEN_NAMES

export const STYLE_KEY_NAMES = ${JSON.stringify(STYLE_KEYS)} as const
export const STYLE_STATE_NAMES = ${JSON.stringify(STYLE_STATES)} as const

/** The Icon prop's vocabulary: packages/icons/icons.json at generate time. */
export const ICON_NAMES = ${JSON.stringify(icons)} as const

export const FUNCTION_NAMES = ${JSON.stringify(coreCatalog.functions.names)} as const

/** A2UI basic component → core component. */
export const BASIC_COMPONENT_MAP: Record<string, string> = ${JSON.stringify(Object.fromEntries(basicTargets))}
/** A2UI basic icon name → icons.json name (the placeholder where none exists). */
export const BASIC_ICON_MAP: Record<string, string> = ${JSON.stringify(Object.fromEntries(basicIcons))}
export const BASIC_PLACEHOLDER_ICON = ${JSON.stringify(basicMap.placeholderIcon)}
`
}

// ---------------------------------------------------------------------------
// Swift / Kotlin / Rust: parallel arrays, like packages/domain-contract
// ---------------------------------------------------------------------------

const propNames = (def: ComponentDef) => Object.keys(def.props).join(`,`)
const eventNames = (def: ComponentDef) => (def.events ?? []).join(`,`)
const rows = {
  componentNames: names,
  componentKinds: components.map(([, d]) => d.kind),
  componentGroups: components.map(([, d]) => d.group),
  componentChildren: components.map(([, d]) => d.children),
  componentProps: components.map(([, d]) => propNames(d)),
  componentEvents: components.map(([, d]) => eventNames(d)),
  componentSlots: components.map(([, d]) => (d.slots ?? []).join(`,`)),
  componentSpecimenIds: names.map(specimenId),
  liteComponents: lite,
  nativeComponents: natives,
  macroComponents: macros,
  enumNames: Object.keys(coreCatalog.enums),
  enumValues: Object.values(coreCatalog.enums).map((v) => v.join(`|`)),
  tokenGroups: Object.keys(TOKEN_GROUPS),
  tokenNames: Object.values(TOKEN_GROUPS).map((v) => v.join(`,`)),
  styleKeys: [...STYLE_KEYS],
  styleLayoutKeys: Object.keys(styleJson.layout),
  styleStates: [...STYLE_STATES],
  functionNames: [...coreCatalog.functions.names],
  basicComponentNames: basicTargets.map(([b]) => b),
  basicComponentTargets: basicTargets.map(([, t]) => t),
  basicIconNames: basicIcons.map(([b]) => b),
  basicIconTargets: basicIcons.map(([, t]) => t),
}
const liteFlags = components.map(([, d]) => d.lite && !d.hidden)
const scalars: [string, string][] = [
  [`catalogId`, CORE_CATALOG_ID],
  [`liteCatalogId`, CORE_LITE_CATALOG_ID],
  [`basicCatalogId`, A2UI_BASIC_CATALOG_ID],
  [`basicVersion`, A2UI_VERSION],
  [`catalogVersion`, coreCatalog.version],
  [`unknownComponent`, coreCatalog.unknownComponent],
  [`basicPlaceholderIcon`, basicMap.placeholderIcon],
  [`styleMediaPattern`, styleJson.conditions.media],
]

function renderSwift(): string {
  const arr = (name: string, values: readonly string[]) => `    public static let ${name}: [String] = [${values.map((v) => JSON.stringify(v)).join(`, `)}]`
  return `// ${HEADER.split(`\n`).join(`\n// `)}

import Foundation

public enum ExponentialUICatalog {
${scalars.map(([k, v]) => `    public static let ${k}: String = ${JSON.stringify(v)}`).join(`\n`)}
${Object.entries(rows).map(([k, v]) => arr(k, v)).join(`\n`)}
    public static let componentLite: [Bool] = [${liteFlags.join(`, `)}]
}
`
}

function renderKotlin(): string {
  const arr = (name: string, values: readonly string[]) => `    val ${name}: List<String> = listOf(${values.map((v) => JSON.stringify(v)).join(`, `)})`
  return `// ${HEADER.split(`\n`).join(`\n// `)}

package at.exponential.ui

object ExponentialUICatalog {
${scalars.map(([k, v]) => `    const val ${k}: String = ${JSON.stringify(v)}`).join(`\n`)}
${Object.entries(rows).map(([k, v]) => arr(k, v)).join(`\n`)}
    val componentLite: List<Boolean> = listOf(${liteFlags.join(`, `)})
}
`
}

/** A JSON document as a Rust raw string: minified, no `$comment`s, and a
 *  hash fence long enough that no JSON string can close it early. */
function rustJson(value: unknown): string {
  const text = JSON.stringify(value)
  if (text.includes(`"####`)) throw new Error(`rustJson: the document contains the raw-string fence`)
  return `r####"${text}"####`
}

/** The catalog source files the Rust core (VAPP-86) EMBEDS so the crate
 *  packages standalone: the same JSON the TS reference reads, minus comments. */
function embeddedCatalogJson(): [string, string][] {
  const strip = (v: unknown): unknown => {
    if (Array.isArray(v)) return v.map(strip)
    if (typeof v === `object` && v !== null) return Object.fromEntries(Object.entries(v).filter(([k]) => k !== `$comment`).map(([k, x]) => [k, strip(x)]))
    return v
  }
  const read = (rel: string) => strip(JSON.parse(readFileSync(join(pkgRoot, rel), `utf8`)))
  return [
    [`CORE_CATALOG_JSON`, rustJson(read(`catalog/core.catalog.json`))],
    [`MACROS_JSON`, rustJson(read(`catalog/macros.json`))],
    [`BASIC_MAP_JSON`, rustJson(read(`catalog/basic-map.json`))],
    [`RECIPES_JSON`, rustJson(read(`catalog/recipes.json`))],
    [`STYLE_JSON`, rustJson(read(`catalog/style.json`))],
    [`TOKENS_JSON`, rustJson(read(`catalog/tokens.json`))],
  ]
}

function renderRust(icons: string[]): string {
  const arr = (name: string, values: readonly string[]) => `pub const ${screaming(name)}: &[&str] = &[${values.map((v) => JSON.stringify(v)).join(`, `)}];`
  return `// ${HEADER.split(`\n`).join(`\n// `)}
// Consumed by apps/desktop/crates/exponential-ui (VAPP-86): the generator copies this file to
// apps/desktop/crates/exponential-ui/src/generated/catalog.rs (drift-gated there) so the crate packages standalone.

${scalars.map(([k, v]) => `pub const ${screaming(k)}: &str = ${JSON.stringify(v)};`).join(`\n`)}
${Object.entries(rows).map(([k, v]) => arr(k, v)).join(`\n`)}
pub const COMPONENT_LITE: &[bool] = &[${liteFlags.join(`, `)}];
/// The Icon prop's vocabulary (packages/icons/icons.json at generate time).
${arr(`iconNames`, icons)}
/// The catalog source files, embedded (minified, \`$comment\`s dropped); parse once at startup.
${embeddedCatalogJson().map(([name, raw]) => `pub const ${name}: &str = ${raw};`).join(`\n`)}
`
}

// ---------------------------------------------------------------------------
// Docs: one page per component, as data
// ---------------------------------------------------------------------------

function docProps(def: ComponentDef) {
  const typeOf = (s: PropSchema): string =>
    s.type === `enum`
      ? (s.values ?? coreCatalog.enums[s.enum ?? ``] ?? []).join(` | `)
      : s.type === `array`
        ? `[${s.items ? (s.items.type === `object` ? s.items.shape : typeOf(s.items)) : ``}]`
        : s.type === `object`
          ? (s.shape ?? `object`)
          : s.type
  return Object.entries(def.props).map(([name, s]) => ({
    name,
    type: typeOf(s),
    required: s.required ?? false,
    bindable: s.bindable ?? false,
    ...(s.default !== undefined ? { default: s.default } : {}),
    description: s.description,
  }))
}

function renderDocs() {
  const basicAliases: Record<string, string[]> = {}
  for (const [basic, rule] of Object.entries(basicMap.components)) (basicAliases[rule.to] ??= []).push(basic)
  basicAliases.Heading = [`Text (h1–h4)`]
  basicAliases.Avatar = [`Image (avatar)`]
  basicAliases.Textarea = [`TextField (longText)`]
  basicAliases.ToggleGroup = [`ChoicePicker (chips)`]
  basicAliases.Select = [`ChoicePicker (filterable, multipleSelection)`]
  return {
    $comment: `${HEADER} One entry per component: what ui.exponential.at renders as the component's page (VAPP-93). specimenId = the id of its specimen there, painted once each renderer lands.`,
    catalogId: CORE_CATALOG_ID,
    liteCatalogId: CORE_LITE_CATALOG_ID,
    groups: [...new Set(components.map(([, d]) => d.group))],
    components: visible.map(([name, def]) => ({
      name,
      kind: def.kind,
      group: def.group,
      lite: def.lite,
      ...(def.status ? { status: def.status } : {}),
      specimenId: specimenId(name),
      description: def.description,
      children: def.children,
      slots: def.slots ?? [],
      events: def.events ?? [],
      basic: basicAliases[name] ?? [],
      props: docProps(def),
      example: { id: `example`, component: name, ...(def.example ?? {}) },
      macro: def.kind === `macro` ? `Expands to natives (see catalog/macros.json); the theme styles its parts by recipe ${name}/<part>.` : null,
    })),
  }
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

interface ComponentCase {
  name: string
  node: NestedNode
}

function childFor(name: string): NestedNode {
  return { id: `${kebab(name)}-child`, component: `Text`, props: { text: `Child` } }
}

/** Every visible component: its example, then every enum value of every enum
 *  prop and both values of every boolean prop, over the example. */
function componentCases(): ComponentCase[] {
  const cases: ComponentCase[] = []
  for (const [name, def] of visible) {
    const base = { ...(def.example ?? {}) }
    const make = (suffix: string, props: Record<string, unknown>): ComponentCase => {
      const node: NestedNode = { id: kebab(name), component: name, props }
      if (def.children !== `none`) node.children = [childFor(name)]
      return { name: `${name}/${suffix}`, node }
    }
    cases.push(make(`example`, base))
    for (const [prop, schema] of Object.entries(def.props)) {
      if (schema.type === `enum`) {
        const values = schema.values ?? coreCatalog.enums[schema.enum ?? ``] ?? []
        for (const value of values) cases.push(make(`${prop}=${value}`, { ...base, [prop]: value }))
      } else if (schema.type === `boolean`) {
        for (const value of [true, false]) cases.push(make(`${prop}=${value}`, { ...base, [prop]: value }))
      }
    }
  }
  return cases
}

// ---------------------------------------------------------------------------
// Specimens (VAPP-93): one surface per component, the page shot of
// ui.exponential.at, painted by every renderer from the same JSON
// ---------------------------------------------------------------------------

/** Components that size to their content: their cases sit at the start of the
 *  column instead of stretching across it. */
const INLINE_SPECIMENS = new Set([
  `Avatar`, `Badge`, `Button`, `ButtonGroup`, `Checkbox`, `DropdownMenu`, `EntityChip`, `Icon`, `Link`, `Pill`,
  `Radio`, `Ring`, `Spinner`, `Switch`, `Toggle`, `ToggleGroup`, `Tooltip`, `Popover`, `Pagination`,
])
/** The enum props a specimen shows, in priority order (at most two of them). */
const SPECIMEN_ENUMS = [`variant`, `type`, `kind`, `level`, `size`, `tone`, `density`, `orientation`, `direction`, `fit`]
/** The boolean props a specimen shows `true` for, in priority order (at most two). */
const SPECIMEN_BOOLEANS = [`checked`, `pressed`, `selected`, `disabled`, `loading`, `busy`, `removable`, `attachments`, `chevron`, `padded`, `divided`, `guides`, `tee`, `rounded`]
const SPECIMEN_MAX_CASES = 8

const text = (id: string, value: string, variant = `body`): NestedNode => ({ id, component: `Text`, props: { text: value, variant } })
const button = (id: string, label: string, variant = `default`): NestedNode => ({ id, component: `Button`, props: { label, variant } })
const row = (id: string, title: string, meta: string): NestedNode => ({ id, component: `ListRow`, props: { title, meta } })
const card = (id: string, title: string, description: string): NestedNode => ({ id, component: `Card`, props: { title, description } })

/** What a specimen puts inside a container instead of the cases' generic
 *  `Child` (a component missing here keeps the case's children as they are). */
const SPECIMEN_CHILDREN: Record<string, NestedNode[]> = {
  Box: [text(`t1`, `A Box lays its children out by style.`), text(`t2`, `Flex, grid, spacing and colours come from the whitelist.`, `muted`)],
  Stack: [
    { id: `a`, component: `Avatar`, props: { name: `Ada Lovelace`, size: `sm` } },
    text(`t`, `Ada Lovelace`),
    { id: `b`, component: `Badge`, props: { text: `Owner`, variant: `outline` } },
  ],
  Grid: [1, 2, 3, 4, 5, 6].map((n) => card(`g${n}`, `Cell ${n}`, `Grid item`)),
  Card: [text(`t`, `3 open issues · 2 in review`), button(`b`, `Open board`, `outline`)],
  List: [text(`l1`, `Inbox`), text(`l2`, `Drafts`), text(`l3`, `Archive`)],
  RowList: [row(`r1`, `r/selfhosted`, `312 posts`), row(`r2`, `r/rust`, `128 posts`), row(`r3`, `r/swift`, `64 posts`)],
  Group: [row(`r1`, `Mentions`, `Push + email`), row(`r2`, `Assigned to me`, `Push`)],
  Carousel: [card(`p1`, `Page one`, `Swipe for more`), card(`p2`, `Page two`, ``), card(`p3`, `Page three`, ``)],
  Tabs: [text(`p1`, `The issue panel.`), text(`p2`, `The run panel.`)],
  Accordion: [text(`p`, `Created 2 days ago by Ada; 3 comments.`)],
  Collapsible: [text(`p`, `Retries, timeouts and the proxy live here.`, `muted`)],
  Dialog: [text(`p`, `The board and its 42 issues move to the trash for 48 hours.`)],
  Drawer: [text(`p`, `Status, assignee and labels.`)],
  Sheet: [text(`p`, `Everything about the selected item.`)],
  Popover: [text(`p`, `Popover content.`)],
  Tooltip: [button(`b`, `Hover me`, `outline`)],
  Button: [],
}

/** Slots a specimen fills (triggers and footers of the overlays). */
const SPECIMEN_SLOTS: Record<string, Record<string, NestedNode>> = {
  Dialog: {
    trigger: button(`trigger`, `Delete board`, `destructive`),
    footer: { id: `footer`, component: `Stack`, props: { direction: `horizontal`, gap: `sm`, justify: `end` }, children: [button(`cancel`, `Cancel`, `outline`), button(`ok`, `Delete`, `destructive`)] },
  },
  Drawer: { trigger: button(`trigger`, `Filters`, `outline`), footer: button(`apply`, `Apply`) },
  Sheet: { trigger: button(`trigger`, `Details`, `outline`), footer: button(`close`, `Done`) },
  Popover: { trigger: button(`trigger`, `Open popover`, `outline`) },
  DropdownMenu: { trigger: button(`trigger`, `More`, `outline`) },
}

/** A case node with the specimen's children + slots in place of `Child`. */
function specimenContent(node: NestedNode): NestedNode {
  const children = SPECIMEN_CHILDREN[node.component]
  const slots = SPECIMEN_SLOTS[node.component]
  const out: NestedNode = { ...node }
  if (children) {
    if (children.length > 0) out.children = children
    else delete out.children
  }
  if (slots) out.slots = slots
  return out
}

/** Re-ids a nested tree so several cases of one component share a surface. */
function prefixIds(node: NestedNode, prefix: string): NestedNode {
  const out: NestedNode = { ...node, id: `${prefix}${node.id}` }
  if (node.children) out.children = node.children.map((c) => prefixIds(c, prefix))
  if (node.slots) out.slots = Object.fromEntries(Object.entries(node.slots).map(([k, v]) => [k, prefixIds(v, prefix)]))
  return out
}

/** The cases a component's specimen shows: an overlay (an `open` prop) once,
 *  open; anything else its example, then up to two enum props × every value,
 *  then `true` for up to two booleans, deduplicated, at most SPECIMEN_MAX_CASES. */
function specimenCases(name: string, all: ComponentCase[]): { label: string; node: NestedNode }[] {
  const own = all.filter((c) => c.node.component === name)
  const suffix = (c: ComponentCase) => c.name.slice(name.length + 1)
  const def = coreCatalog.components[name]
  if (def.props.open) {
    const open = own.find((c) => suffix(c) === `open=true`)!
    return [{ label: `open`, node: open.node }]
  }
  const picked: ComponentCase[] = [own.find((c) => suffix(c) === `example`)!]
  const enums = SPECIMEN_ENUMS.filter((p) => def.props[p]?.type === `enum`).slice(0, 2)
  const bools = SPECIMEN_BOOLEANS.filter((p) => def.props[p]?.type === `boolean`).slice(0, 2)
  for (const prop of enums) picked.push(...own.filter((c) => suffix(c).startsWith(`${prop}=`)))
  for (const prop of bools) picked.push(...own.filter((c) => suffix(c) === `${prop}=true`))
  const seen = new Set<string>()
  const out: { label: string; node: NestedNode }[] = []
  for (const c of picked) {
    const key = JSON.stringify(c.node.props ?? {}, Object.keys(c.node.props ?? {}).sort())
    if (seen.has(key)) continue
    seen.add(key)
    const label = suffix(c) === `example` ? `example` : suffix(c).replace(`=`, ` · `)
    out.push({ label, node: c.node })
    if (out.length === SPECIMEN_MAX_CASES) break
  }
  return out
}

/** One component's specimen: a padded column of captioned cases. */
function specimenNode(name: string, all: ComponentCase[]): NestedNode {
  const inline = INLINE_SPECIMENS.has(name)
  const root = `specimen-${kebab(name)}`
  return {
    id: root,
    component: `Box`,
    style: { display: `flex`, flexDirection: `column`, gap: `$spacing.lg`, padding: `$spacing.xl`, maxWidth: 720 },
    children: specimenCases(name, all).map((c, i) => ({
      id: `${root}-case-${i}`,
      component: `Stack`,
      props: { direction: `vertical`, gap: `xs`, align: inline ? `start` : `stretch` },
      children: [
        { id: `${root}-case-${i}-label`, component: `Text`, props: { text: c.label, variant: `caption` } },
        prefixIds(specimenContent(c.node), `c${i}-`),
      ],
    })),
  }
}

interface SpecimenEntry {
  id: string
  component: string | null
  title: string
  node: NestedNode
}

/** fixtures/specimens.json: every visible component's specimen (view id =
 *  its specimenId) plus the home page's demo surface (fixtures/demo-surface.json). */
function renderSpecimens(all: ComponentCase[], demo: NestedNode) {
  const specimens: SpecimenEntry[] = visible.map(([name]) => ({
    id: specimenId(name),
    component: name,
    title: name,
    node: specimenNode(name, all),
  }))
  const { $comment: _, ...demoNode } = demo as NestedNode & { $comment?: string }
  specimens.push({ id: `exponential-ui-demo`, component: null, title: `Demo`, node: demoNode })
  for (const s of specimens) {
    const result = reduceNested(s.node, { catalogId: CORE_CATALOG_ID })
    if (result.issues.length > 0) throw new Error(`specimen ${s.id}: ${result.issues.map((i) => `${i.id}: ${i.message}`).join(`; `)}`)
  }
  return {
    $comment: `${HEADER} One surface per visible component (id = its docs specimenId = its view-catalog id) plus the home page demo (exponential-ui-demo, from fixtures/demo-surface.json). ui.exponential.at shows the four platform shots of each; every renderer's example host paints an entry by id (web harness ?view=specimen&id=, the IDE's EXP_DEV_SCREEN, the Swift example's -shot, the Compose example's shot extra).`,
    catalogId: CORE_CATALOG_ID,
    specimens,
  }
}

function macroCases(all: ComponentCase[]) {
  return all
    .filter((c) => coreCatalog.components[c.node.component].kind === `macro`)
    .map((c) => {
      const result = reduceNested(c.node, { catalogId: CORE_CATALOG_ID })
      if (result.issues.length > 0) throw new Error(`${c.name}: ${result.issues.map((i) => i.message).join(`; `)}`)
      return { name: c.name, input: c.node, expected: result.root }
    })
}

interface BasicCaseFile {
  $comment: string
  catalogId: string
  cases: { name: string; components: FlatComponent[]; expected?: unknown }[]
}

function basicCases(file: BasicCaseFile) {
  return {
    ...file,
    cases: file.cases.map((c) => ({
      name: c.name,
      components: c.components,
      expected: reduceSurface(c.components, { catalogId: A2UI_BASIC_CATALOG_ID }),
    })),
  }
}

interface ExtensionCaseFile {
  $comment: string
  extension: ExtensionDef
  cases: { name: string; catalogId: string; components: FlatComponent[]; expected?: unknown }[]
}

function extensionCases(file: ExtensionCaseFile) {
  return {
    ...file,
    cases: file.cases.map((c) => ({
      name: c.name,
      catalogId: c.catalogId,
      components: c.components,
      expected: reduceSurface(c.components, { catalogId: c.catalogId, extensions: [file.extension] }),
    })),
  }
}

function promptBudget() {
  const full = catalogPrompt()
  const liteText = catalogPrompt({ lite: true })
  const terse = catalogPrompt({ terse: true })
  return {
    $comment: `${HEADER} The size of catalogPrompt() on record: prompt.test.ts fails when the full prompt passes budgetTokens (cut descriptions before components) or when these numbers drift from the catalog without being regenerated. tokens = chars / ${4}, an estimate.`,
    budgetTokens: 6500,
    full: { components: visible.length, chars: full.length, tokens: estimateTokens(full) },
    lite: { components: lite.length, chars: liteText.length, tokens: estimateTokens(liteText) },
    terse: { components: visible.length, chars: terse.length, tokens: estimateTokens(terse) },
  }
}

// ---------------------------------------------------------------------------
// Render everything
// ---------------------------------------------------------------------------

function readJson<T>(rel: string): T {
  return JSON.parse(readFileSync(join(pkgRoot, rel), `utf8`)) as T
}

/** Every generated file, keyed by its path relative to the package root. */
export function render(): Record<string, string> {
  const files = renderFiles()
  // The manifest counts the fixtures being written, not the bundled ones.
  const read = (name: string) => JSON.parse(files[`fixtures/${name}`] ?? readFileSync(join(pkgRoot, `fixtures`, name), `utf8`))
  return { ...files, "conformance/manifest.json": json(conformanceManifest(read)) }
}

function renderFiles(): Record<string, string> {
  const icons = iconNames()
  const cases = componentCases()
  const kitchen = readJson<NestedNode>(`fixtures/kitchen-sink.json`)
  const kitchenResult = reduceNested(kitchen, { catalogId: CORE_CATALOG_ID })
  if (kitchenResult.issues.length > 0)
    throw new Error(`kitchen-sink.json: ${kitchenResult.issues.map((i) => `${i.id}: ${i.message}`).join(`\n`)}`)
  const themeOutputs = renderThemes(cases, kitchen)
  const rust = renderRust(icons)
  return {
    "catalog/core.schema.json": json(coreSchema(icons)),
    "src/catalog.generated.ts": renderTs(icons),
    "generated/ExponentialUICatalog.generated.swift": renderSwift(),
    "generated/ExponentialUICatalog.generated.kt": renderKotlin(),
    "generated/catalog.generated.rs": rust,
    // VAPP-86: the Rust core's copies (a published crate cannot include! a file
    // outside its own directory); src/generate.test.ts gates them like the rest.
    "../../apps/desktop/crates/exponential-ui/src/generated/catalog.rs": rust,
    "../../apps/desktop/crates/exponential-ui/src/generated/themes.rs": themeOutputs[`generated/catalog.themes.generated.rs`],
    "docs/components.generated.json": json(renderDocs()),
    "fixtures/catalog-components.json": json({
      $comment: `${HEADER} Every visible component × its example × every enum value of every enum prop × both values of every boolean prop. Each case validates against core.schema.json; a renderer suite paints each case once.`,
      catalogId: CORE_CATALOG_ID,
      cases,
    }),
    "fixtures/catalog-macros.json": json({
      $comment: `${HEADER} Every macro case of catalog-components.json → the tree the expander produces (macros.json applied, recipes attached). The Rust core replays these byte for byte.`,
      catalogId: CORE_CATALOG_ID,
      cases: macroCases(cases),
    }),
    "fixtures/catalog-basic-map.json": json(basicCases(readJson<BasicCaseFile>(`fixtures/catalog-basic-map.json`))),
    "fixtures/catalog-extension.json": json(extensionCases(readJson<ExtensionCaseFile>(`fixtures/catalog-extension.json`))),
    "fixtures/kitchen-sink.expanded.json": json({
      $comment: `${HEADER} fixtures/kitchen-sink.json reduced and expanded: what every painter receives.`,
      ...kitchenResult,
    }),
    "fixtures/prompt-budget.json": json(promptBudget()),
    "fixtures/specimens.json": json(renderSpecimens(cases, readJson<NestedNode>(`fixtures/demo-surface.json`))),
    ...themeOutputs,
    // VAPP-91: the host fixtures (inputs hand-written, expected filled).
    ...renderHost(),
  }
}

if (import.meta.main) {
  const files = render()
  for (const [rel, content] of Object.entries(files)) {
    const path = join(pkgRoot, rel)
    mkdirSync(dirname(path), { recursive: true })
    const before = existsSync(path) ? readFileSync(path, `utf8`) : null
    writeFileSync(path, content)
    console.log(`${before === content ? `unchanged` : `wrote    `} ${rel}`)
  }
}
