#!/usr/bin/env bun
// VAPP-85: emits everything derived from catalog/*.json. Run from the repo
// root with `bun run --filter @exponential-at/ui generate`; generate.test.ts
// re-renders in memory and fails on any committed drift.
//
// Outputs (all committed):
//   catalog/core.schema.json              the catalog as JSON Schema (A2UI catalog shape)
//   src/catalog.generated.ts              names, enums, token names, icon names, basic map
//   generated/ExponentialUICatalog.generated.swift   the same for the SwiftUI painter (VAPP-88)
//   generated/ExponentialUICatalog.generated.kt      the same for the Compose painter (VAPP-89)
//   generated/catalog.generated.rs                   the same for the Rust core (VAPP-86)
//   docs/components.generated.json        one doc page per component, as data (VAPP-93 renders it)
//   fixtures/catalog-components.json      every component × every enum/boolean value
//   fixtures/catalog-macros.json          every macro case → the expanded tree
//   fixtures/catalog-basic-map.json       the hand-written basic cases → expected trees
//   fixtures/catalog-extension.json       the example extension's cases → expected trees
//   fixtures/kitchen-sink.expanded.json   fixtures/kitchen-sink.json, reduced + expanded
//   fixtures/prompt-budget.json           the prompt's size on record
//   fixtures/bind-time.json               round 1: bound macro cases × data → the BOUND tree + presses
//   fixtures/style-conditions.json        round 1: style × surface/state context → the flattened style
//   fixtures/code-tokens.json             round 1: source × language → CodeBlock tokens per line
//   fixtures/specimens.json               one surface per component + the demo (VAPP-93: the site's shots)
//   + the theme outputs of scripts/generate-themes.ts (VAPP-92)
//   + the round-2 fixtures of scripts/generate-round2.ts (format, template items,
//     text direction, Resizable, virtual lists, animations, the list bench)
//
// The icon name list is read from packages/icons/icons.json at GENERATE time
// (the registry is the Icon prop's vocabulary); the package has no runtime
// dependency on it.

import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { A2UI_BASIC_CATALOG_ID, A2UI_VERSION, CORE_CATALOG_ID, CORE_LITE_CATALOG_ID, TOKEN_GROUPS, coreCatalog } from "../src/catalog"
import { basicMap } from "../src/basic-map"
import { catalogPrompt, estimateTokens } from "../src/prompt"
import { reduceNested, reduceSurface } from "../src/reducer"
import { coreSchema } from "../src/schema"
import { STYLE_KEYS, STYLE_STATES, resolveConditions, type ConditionContext } from "../src/style"
import { BIND_FUNCTION_NAMES, bindRowSlot, bindTree, hasRowSlots, isDataSchema, runAction } from "../src/dynamic"
import { tokenizeCode, CODE_LANGUAGE_NAMES } from "../src/code"
import { A11Y_ROLES, COMPONENT_A11Y } from "../src/a11y"
import { STRING_IDS, DEFAULT_STRINGS } from "../src/strings"
import { renderThemes } from "./generate-themes"
import { renderHost } from "./generate-host"
import { renderRound2 } from "./generate-round2"
import { ANIMATION_NAMES } from "../src/animation"
import { FORMAT_FUNCTION_NAMES } from "../src/format"
import { LAYOUT_CONSTANTS } from "../src/layout"
import { LIMITS } from "../src/limits"
import { treeGuides } from "../src/tree-guides"
import { conformanceManifest } from "../src/conformance"
import styleJson from "../catalog/style.json" with { type: "json" }
import localeJson from "../catalog/locale.json" with { type: "json" }
import type { ComponentDef, ExtensionDef, FlatComponent, NestedNode, PropSchema, UiNode } from "../src/types"

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), `..`)
const repoRoot = join(pkgRoot, `..`, `..`)

const HEADER = `AUTO-GENERATED by packages/exponential-ui/scripts/generate.ts — do not edit.
Source of truth: packages/exponential-ui/catalog/core.catalog.json (+ tokens.json, style.json, basic-map.json, strings.json, locale.json, code.json, a11y.json, layout.json).`

// ---------------------------------------------------------------------------
// Inputs
// ---------------------------------------------------------------------------

interface IconRegistry {
  pickable: string[]
  devicePickable: string[]
  semantic: Record<string, string>
  custom?: Record<string, unknown>
  imported?: Record<string, unknown>
}

/** Every name the Icon prop accepts: the concept ids plus every registry
 *  glyph name (pickable, device, the Lucide targets, custom, imported). */
export function iconNames(): string[] {
  const registry = JSON.parse(readFileSync(join(repoRoot, `packages/icons/icons.json`), `utf8`)) as IconRegistry
  const names = new Set<string>()
  for (const name of Object.keys(registry.semantic)) names.add(name)
  for (const name of Object.values(registry.semantic)) names.add(name)
  for (const name of registry.pickable) names.add(name)
  for (const name of registry.devicePickable) names.add(name)
  for (const name of Object.keys(registry.custom ?? {})) names.add(name)
  for (const name of Object.keys(registry.imported ?? {})) names.add(name)
  return [...names].sort()
}

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`
const kebab = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, `$1-$2`).toLowerCase()
const screaming = (name: string) => name.replace(/([a-z0-9])([A-Z])/g, `$1_$2`).replace(/[^A-Za-z0-9]+/g, `_`).toUpperCase()
const capFirst = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)

/** Round 1: the icon each renderer-owned glyph uses (`<Component>.<part>` →
 *  an icons.json name), so a CodeBlock's copy button or a FileUpload's drop
 *  zone shows the same glyph on every platform. */
function builtinIcons(): Record<string, string> {
  const table = coreCatalog.builtinIcons
  return Object.fromEntries(Object.entries(table).filter(([k]) => !k.startsWith(`$`)))
}

const components = Object.entries(coreCatalog.components)
/** What a model is offered: neither the hidden placeholder nor a deprecated alias (round 3). */
const visible = components.filter(([, def]) => !def.hidden && !def.deprecated)
/** Round 3: the one-release aliases; their example case stays in the fixtures so every renderer replays the alias. */
const deprecated = components.filter(([, def]) => def.deprecated)
const names = components.map(([name]) => name)
const natives = components.filter(([, d]) => d.kind === `native`).map(([n]) => n)
const macros = components.filter(([, d]) => d.kind === `macro`).map(([n]) => n)
const lite = visible.filter(([, d]) => d.lite).map(([n]) => n)
const specimenId = (name: string) => `exponential-ui-${kebab(name)}`
const basicTargets = Object.entries(basicMap.components).map(([basic, rule]) => [basic, rule.to] as const)
const basicIcons = Object.entries(basicMap.icons).map(([basic, target]) => [basic, target ?? basicMap.placeholderIcon] as const)

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------

function renderTs(icons: string[]): string {
  const enumConsts = Object.entries(coreCatalog.enums)
    .map(([name, values]) => `  ${name}: ${JSON.stringify(values)},`)
    .join(`\n`)
  const enumTypes = Object.entries(coreCatalog.enums)
    .map(([name]) => `export type ${capFirst(name)}Value = (typeof ENUMS)[${JSON.stringify(name)}][number]`)
    .join(`\n`)
  const tokenConsts = Object.entries(TOKEN_GROUPS)
    .map(([group, values]) => `  ${JSON.stringify(group)}: ${JSON.stringify(values)},`)
    .join(`\n`)
  return `// ${HEADER.split(`\n`).join(`\n// `)}

export const CATALOG_ID = ${JSON.stringify(CORE_CATALOG_ID)}
export const LITE_CATALOG_ID = ${JSON.stringify(CORE_LITE_CATALOG_ID)}
export const BASIC_CATALOG_ID = ${JSON.stringify(A2UI_BASIC_CATALOG_ID)}
export const BASIC_VERSION = ${JSON.stringify(A2UI_VERSION)}
export const CATALOG_VERSION = ${JSON.stringify(coreCatalog.version)}
export const UNKNOWN_COMPONENT_NAME = ${JSON.stringify(coreCatalog.unknownComponent)}

/** Every component in source order (the hidden placeholder included). */
export const COMPONENT_NAMES = ${JSON.stringify(names)} as const
export type ComponentName = (typeof COMPONENT_NAMES)[number]
export const NATIVE_COMPONENTS = ${JSON.stringify(natives)} as const
export const MACRO_COMPONENTS = ${JSON.stringify(macros)} as const
/** The core-lite subset (no overlays, media or Chart). */
export const LITE_COMPONENTS = ${JSON.stringify(lite)} as const
export const COMPONENT_GROUPS: Record<ComponentName, string> = ${JSON.stringify(Object.fromEntries(components.map(([n, d]) => [n, d.group])))}
/** The specimen id each component has on ui.exponential.at. */
export const SPECIMEN_IDS: Record<ComponentName, string> = ${JSON.stringify(Object.fromEntries(names.map((n) => [n, specimenId(n)])))}

export const ENUMS = {
${enumConsts}
} as const
${enumTypes}

/** Token NAMES by group (values come from a theme). */
export const TOKEN_NAMES = {
${tokenConsts}
} as const
export type TokenGroup = keyof typeof TOKEN_NAMES

export const STYLE_KEY_NAMES = ${JSON.stringify(STYLE_KEYS)} as const
export const STYLE_STATE_NAMES = ${JSON.stringify(STYLE_STATES)} as const

/** The Icon prop's vocabulary: packages/icons/icons.json at generate time. */
export const ICON_NAMES = ${JSON.stringify(icons)} as const

export const FUNCTION_NAMES = ${JSON.stringify(coreCatalog.functions.names)} as const

/** A2UI basic component → core component. */
export const BASIC_COMPONENT_MAP: Record<string, string> = ${JSON.stringify(Object.fromEntries(basicTargets))}
/** A2UI basic icon name → icons.json name (the placeholder where none exists). */
export const BASIC_ICON_MAP: Record<string, string> = ${JSON.stringify(Object.fromEntries(basicIcons))}
export const BASIC_PLACEHOLDER_ICON = ${JSON.stringify(basicMap.placeholderIcon)}
`
}

// ---------------------------------------------------------------------------
// Swift / Kotlin / Rust: parallel arrays, like packages/domain-contract
// ---------------------------------------------------------------------------

const propNames = (def: ComponentDef) => Object.keys(def.props).join(`,`)
const eventNames = (def: ComponentDef) => (def.events ?? []).join(`,`)
const rows = {
  componentNames: names,
  componentKinds: components.map(([, d]) => d.kind),
  componentGroups: components.map(([, d]) => d.group),
  componentChildren: components.map(([, d]) => d.children),
  componentProps: components.map(([, d]) => propNames(d)),
  componentEvents: components.map(([, d]) => eventNames(d)),
  componentSlots: components.map(([, d]) => (d.slots ?? []).join(`,`)),
  componentSpecimenIds: names.map(specimenId),
  // Round 3: the replacement an alias expands to ("" = a live component).
  componentDeprecated: components.map(([, d]) => d.deprecated ?? ``),
  liteComponents: lite,
  nativeComponents: natives,
  macroComponents: macros,
  enumNames: Object.keys(coreCatalog.enums),
  enumValues: Object.values(coreCatalog.enums).map((v) => v.join(`|`)),
  tokenGroups: Object.keys(TOKEN_GROUPS),
  tokenNames: Object.values(TOKEN_GROUPS).map((v) => v.join(`,`)),
  styleKeys: [...STYLE_KEYS],
  styleLayoutKeys: Object.keys(styleJson.layout),
  styleStates: [...STYLE_STATES],
  styleLayoutEffectKeys: Object.entries(styleJson.visual).filter(([, spec]) => (spec as { layoutEffect?: boolean }).layoutEffect).map(([k]) => k),
  functionNames: [...coreCatalog.functions.names],
  coreFunctionNames: Object.keys(coreCatalog.functions.core),
  bindFunctionNames: [...BIND_FUNCTION_NAMES],
  stringIds: [...STRING_IDS],
  stringDefaults: STRING_IDS.map((id) => DEFAULT_STRINGS[id]),
  codeLanguageNames: [...CODE_LANGUAGE_NAMES],
  builtinIconSlots: Object.keys(builtinIcons()),
  builtinIconNames: Object.values(builtinIcons()),
  weekStartRegions: Object.values(localeJson.weekStart.regions).flat(),
  weekStartDays: Object.entries(localeJson.weekStart.regions).flatMap(([day, regions]) => regions.map(() => day)),
  likelyRegionLanguages: Object.keys(localeJson.likelyRegion),
  likelyRegions: Object.values(localeJson.likelyRegion),
  rtlLanguages: [...localeJson.rtl],
  languageAliases: Object.keys(localeJson.languageAliases),
  languageAliasTargets: Object.values(localeJson.languageAliases),
  rtlMirroredIcons: [...localeJson.rtlMirroredIcons],
  a11yRoles: [...A11Y_ROLES],
  rowSlotComponents: components.filter(([, d]) => hasRowSlots(d)).map(([n]) => n),
  dataProps: components.flatMap(([n, d]) => Object.entries(d.props).filter(([, schema]) => isDataSchema(schema)).map(([p]) => `${n}.${p}`)),
  basicComponentNames: basicTargets.map(([b]) => b),
  basicComponentTargets: basicTargets.map(([, t]) => t),
  basicIconNames: basicIcons.map(([b]) => b),
  basicIconTargets: basicIcons.map(([, t]) => t),
  // Round 2 (docs/round-2-contract.md).
  animationNames: [...ANIMATION_NAMES],
  formatFunctionNames: [...FORMAT_FUNCTION_NAMES],
  layoutConstantNames: Object.keys(LAYOUT_CONSTANTS),
  layoutConstantValues: Object.values(LAYOUT_CONSTANTS).map(String),
  // VAPP-103: the input limits (catalog/limits.json).
  limitNames: Object.keys(LIMITS),
  limitValues: Object.values(LIMITS).map(String),
}
const liteFlags = components.map(([, d]) => d.lite && !d.hidden && !d.deprecated)
const scalars: [string, string][] = [
  [`catalogId`, CORE_CATALOG_ID],
  [`liteCatalogId`, CORE_LITE_CATALOG_ID],
  [`basicCatalogId`, A2UI_BASIC_CATALOG_ID],
  [`basicVersion`, A2UI_VERSION],
  [`catalogVersion`, coreCatalog.version],
  [`unknownComponent`, coreCatalog.unknownComponent],
  [`basicPlaceholderIcon`, basicMap.placeholderIcon],
  [`styleMediaPattern`, styleJson.conditions.media],
  [`styleTransformPattern`, styleJson.conditions.transform],
  [`defaultLocale`, localeJson.default],
  [`weekStartDefault`, String(localeJson.weekStart.default)],
]

function renderSwift(): string {
  const arr = (name: string, values: readonly string[]) => `    public static let ${name}: [String] = [${values.map((v) => JSON.stringify(v)).join(`, `)}]`
  return `// ${HEADER.split(`\n`).join(`\n// `)}

import Foundation

public enum ExponentialUICatalog {
${scalars.map(([k, v]) => `    public static let ${k}: String = ${JSON.stringify(v)}`).join(`\n`)}
${Object.entries(rows).map(([k, v]) => arr(k, v)).join(`\n`)}
    public static let componentLite: [Bool] = [${liteFlags.join(`, `)}]
}
`
}

/** A Kotlin string literal: JSON's escapes plus `\$` (a bare `$` starts a
 *  string template in Kotlin: `$breakpoint` would read a variable). */
const ktString = (v: string) => JSON.stringify(v).replace(/\$/g, `\\$`)

function renderKotlin(): string {
  const arr = (name: string, values: readonly string[]) => `    val ${name}: List<String> = listOf(${values.map(ktString).join(`, `)})`
  return `// ${HEADER.split(`\n`).join(`\n// `)}

package at.exponential.ui

object ExponentialUICatalog {
${scalars.map(([k, v]) => `    const val ${k}: String = ${ktString(v)}`).join(`\n`)}
${Object.entries(rows).map(([k, v]) => arr(k, v)).join(`\n`)}
    val componentLite: List<Boolean> = listOf(${liteFlags.join(`, `)})
}
`
}

/** A JSON document as a Rust raw string: minified, no `$comment`s, and a
 *  hash fence long enough that no JSON string can close it early. */
function rustJson(value: unknown): string {
  const text = JSON.stringify(value)
  if (text.includes(`"####`)) throw new Error(`rustJson: the document contains the raw-string fence`)
  return `r####"${text}"####`
}

/** The catalog source files the Rust core (VAPP-86) EMBEDS so the crate
 *  packages standalone: the same JSON the TS reference reads, minus comments. */
function embeddedCatalogJson(): [string, string][] {
  const strip = (v: unknown): unknown => {
    if (Array.isArray(v)) return v.map(strip)
    if (typeof v === `object` && v !== null) return Object.fromEntries(Object.entries(v).filter(([k]) => k !== `$comment`).map(([k, x]) => [k, strip(x)]))
    return v
  }
  const read = (rel: string) => strip(JSON.parse(readFileSync(join(pkgRoot, rel), `utf8`)))
  return [
    [`CORE_CATALOG_JSON`, rustJson(read(`catalog/core.catalog.json`))],
    [`MACROS_JSON`, rustJson(read(`catalog/macros.json`))],
    [`BASIC_MAP_JSON`, rustJson(read(`catalog/basic-map.json`))],
    [`RECIPES_JSON`, rustJson(read(`catalog/recipes.json`))],
    [`STYLE_JSON`, rustJson(read(`catalog/style.json`))],
    [`TOKENS_JSON`, rustJson(read(`catalog/tokens.json`))],
    [`STRINGS_JSON`, rustJson(read(`catalog/strings.json`))],
    [`LOCALE_JSON`, rustJson(read(`catalog/locale.json`))],
    [`CODE_JSON`, rustJson(read(`catalog/code.json`))],
    [`A11Y_JSON`, rustJson(read(`catalog/a11y.json`))],
    [`LAYOUT_JSON`, rustJson(read(`catalog/layout.json`))],
    [`LIMITS_JSON`, rustJson(read(`catalog/limits.json`))],
  ]
}

function renderRust(icons: string[]): string {
  const arr = (name: string, values: readonly string[]) => `pub const ${screaming(name)}: &[&str] = &[${values.map((v) => JSON.stringify(v)).join(`, `)}];`
  return `// ${HEADER.split(`\n`).join(`\n// `)}
// Consumed by apps/desktop/crates/exponential-ui (VAPP-86): the generator copies this file to
// apps/desktop/crates/exponential-ui/src/generated/catalog.rs (drift-gated there) so the crate packages standalone.

${scalars.map(([k, v]) => `pub const ${screaming(k)}: &str = ${JSON.stringify(v)};`).join(`\n`)}
${Object.entries(rows).map(([k, v]) => arr(k, v)).join(`\n`)}
pub const COMPONENT_LITE: &[bool] = &[${liteFlags.join(`, `)}];
/// The Icon prop's vocabulary (packages/icons/icons.json at generate time).
${arr(`iconNames`, icons)}
/// The catalog source files, embedded (minified, \`$comment\`s dropped); parse once at startup.
${embeddedCatalogJson().map(([name, raw]) => `pub const ${name}: &str = ${raw};`).join(`\n`)}
`
}

// ---------------------------------------------------------------------------
// Docs: one page per component, as data
// ---------------------------------------------------------------------------

function docProps(def: ComponentDef) {
  const typeOf = (s: PropSchema): string =>
    s.type === `enum`
      ? (s.values ?? coreCatalog.enums[s.enum ?? ``] ?? []).join(` | `)
      : s.type === `array`
        ? `[${s.items ? (s.items.type === `object` ? (s.items.shape ?? `object`) : typeOf(s.items)) : ``}]`
        : s.type === `object`
          ? (s.shape ?? `object`)
          : s.type
  return Object.entries(def.props).map(([name, s]) => ({
    name,
    type: typeOf(s),
    required: s.required ?? false,
    bindable: s.bindable ?? false,
    responsive: s.responsive ?? false,
    ...(s.default !== undefined ? { default: s.default } : {}),
    description: s.description,
  }))
}

function renderDocs() {
  const basicAliases: Record<string, string[]> = {}
  for (const [basic, rule] of Object.entries(basicMap.components)) (basicAliases[rule.to] ??= []).push(basic)
  basicAliases.Heading = [`Text (h1–h4)`]
  basicAliases.Avatar = [`Image (avatar)`]
  basicAliases.Textarea = [`TextField (longText)`]
  basicAliases.Segmented = [`ChoicePicker (chips)`]
  basicAliases.Select = [`ChoicePicker (filterable, multipleSelection)`]
  return {
    $comment: `${HEADER} One entry per component: what ui.exponential.at renders as the component's page (VAPP-93). specimenId = the id of its specimen there, painted once each renderer lands.`,
    catalogId: CORE_CATALOG_ID,
    liteCatalogId: CORE_LITE_CATALOG_ID,
    groups: [...new Set(components.map(([, d]) => d.group))],
    /** Round 3: the one-release aliases and what replaces them. */
    deprecated: Object.fromEntries(deprecated.map(([name, def]) => [name, def.deprecated])),
    components: visible.map(([name, def]) => ({
      name,
      kind: def.kind,
      group: def.group,
      lite: def.lite,
      ...(def.status ? { status: def.status } : {}),
      specimenId: specimenId(name),
      description: def.description,
      children: def.children,
      slots: def.slots ?? [],
      events: def.events ?? [],
      basic: basicAliases[name] ?? [],
      props: docProps(def),
      accessibility: COMPONENT_A11Y[name] ?? null,
      example: { id: `example`, component: name, ...(def.example ?? {}) },
      macro: def.kind === `macro` ? `Expands to natives (see catalog/macros.json); the theme styles its parts by recipe ${name}/<part>.` : null,
    })),
  }
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

interface ComponentCase {
  name: string
  node: NestedNode
}

function childFor(name: string): NestedNode {
  return { id: `${kebab(name)}-child`, component: `Text`, props: { text: `Child` } }
}

function makeCase(name: string, def: ComponentDef, suffix: string, props: Record<string, unknown>): ComponentCase {
  const node: NestedNode = { id: kebab(name), component: name, props }
  if (def.children !== `none`) node.children = [childFor(name)]
  return { name: `${name}/${suffix}`, node }
}

/** A responsive value worth expanding: the default (else the first value)
 *  at `base`, a different value from md (lg too for numbers). */
function responsiveSample(schema: PropSchema): Record<string, unknown> {
  if (schema.type === `number`) return { base: 1, md: 2, lg: 3 }
  if (schema.type === `boolean`) return { base: false, md: true }
  const values = schema.values ?? coreCatalog.enums[schema.enum ?? ``] ?? []
  const base = schema.default ?? values[0]
  return { base, md: values.find((v) => v !== base) ?? base }
}

/** Round 1: every BINDABLE prop of every macro bound to `/<prop>` and every
 *  RESPONSIVE prop of every macro given a breakpoint object: the cases where
 *  the expander must emit instead of evaluate (docs/round-1-contract.md §1). */
function boundMacroCases(): ComponentCase[] {
  const cases: ComponentCase[] = []
  for (const [name, def] of visible) {
    if (def.kind !== `macro`) continue
    const base = { ...(def.example ?? {}) }
    for (const [prop, schema] of Object.entries(def.props)) {
      if (schema.bindable) cases.push(makeCase(name, def, `bound:${prop}`, { ...base, [prop]: { path: `/${prop}` } }))
      if (schema.responsive) cases.push(makeCase(name, def, `responsive:${prop}`, { ...base, [prop]: responsiveSample(schema) }))
    }
  }
  return cases
}

/** Every visible component: its example, then every enum value of every enum
 *  prop and both values of every boolean prop, over the example. */
function componentCases(): ComponentCase[] {
  const cases: ComponentCase[] = []
  // Round 3: a deprecated alias keeps ONE case (its example) so every
  // renderer proves it still expands.
  for (const [name, def] of deprecated) cases.push(makeCase(name, def, `example`, { ...(def.example ?? {}) }))
  for (const [name, def] of visible) {
    const base = { ...(def.example ?? {}) }
    const make = (suffix: string, props: Record<string, unknown>) => makeCase(name, def, suffix, props)
    cases.push(make(`example`, base))
    for (const [prop, schema] of Object.entries(def.props)) {
      if (schema.type === `enum`) {
        const values = schema.values ?? coreCatalog.enums[schema.enum ?? ``] ?? []
        for (const value of values) cases.push(make(`${prop}=${value}`, { ...base, [prop]: value }))
      } else if (schema.type === `boolean`) {
        for (const value of [true, false]) cases.push(make(`${prop}=${value}`, { ...base, [prop]: value }))
      }
    }
  }
  return cases
}

// ---------------------------------------------------------------------------
// Specimens (VAPP-93): one surface per component, the page shot of
// ui.exponential.at, painted by every renderer from the same JSON
// ---------------------------------------------------------------------------

/** Components that size to their content: their cases sit at the start of the
 *  column instead of stretching across it. */
const INLINE_SPECIMENS = new Set([
  `Avatar`, `Badge`, `Button`, `Checkbox`, `Chip`, `Icon`, `Link`, `Menu`,
  `Radio`, `Ring`, `Spinner`, `Switch`, `Toggle`, `Segmented`, `Tooltip`, `Popover`, `Pagination`,
])
/** The enum props a specimen shows, in priority order (at most two of them). */
const SPECIMEN_ENUMS = [`variant`, `shape`, `surface`, `openOn`, `type`, `kind`, `level`, `size`, `tone`, `tint`, `chevron`, `density`, `orientation`, `direction`, `fit`]
/** The boolean props a specimen shows `true` for, in priority order (at most two). */
const SPECIMEN_BOOLEANS = [`checked`, `pressed`, `selected`, `disabled`, `loading`, `busy`, `removable`, `attachments`, `collapsible`, `tree`, `padded`, `divided`, `rounded`]
const SPECIMEN_MAX_CASES = 8

const text = (id: string, value: string, variant = `body`): NestedNode => ({ id, component: `Text`, props: { text: value, variant } })
const button = (id: string, label: string, variant = `default`): NestedNode => ({ id, component: `Button`, props: { label, variant } })
const row = (id: string, title: string, meta: string, depth = 0): NestedNode => ({ id, component: `Row`, props: { title, meta, pressable: true, ...(depth ? { depth } : {}) } })
const card = (id: string, title: string, description: string): NestedNode => ({ id, component: `Card`, props: { title, description } })

/** What a specimen puts inside a container instead of the cases' generic
 *  `Child` (a component missing here keeps the case's children as they are). */
const SPECIMEN_CHILDREN: Record<string, NestedNode[]> = {
  Box: [text(`t1`, `A Box lays its children out by style.`), text(`t2`, `Flex, grid, spacing and colours come from the whitelist.`, `muted`)],
  Stack: [
    { id: `a`, component: `Avatar`, props: { name: `Ada Lovelace`, size: `sm` } },
    text(`t`, `Ada Lovelace`),
    { id: `b`, component: `Badge`, props: { text: `Owner`, variant: `outline` } },
  ],
  Grid: [1, 2, 3, 4, 5, 6].map((n) => card(`g${n}`, `Cell ${n}`, `Grid item`)),
  Card: [text(`t`, `3 open issues · 2 in review`), button(`b`, `Open board`, `outline`)],
  List: [text(`l1`, `Inbox`), text(`l2`, `Drafts`), text(`l3`, `Archive`)],
  // Round 3: a Section of nested rows shows the elbow, the tee and a pass-through.
  Section: [row(`r1`, `Release 0.18`, `4 runs`), row(`r2`, `Build the macOS app`, `done`, 1), row(`r3`, `Notarize`, `running`, 2), row(`r4`, `Upload the dmg`, `queued`, 2), row(`r5`, `Publish the release notes`, `queued`, 1), row(`r6`, `Release 0.17`, `3 runs`)],
  Group: [row(`r1`, `Mentions`, `Push + email`), row(`r2`, `Assigned to me`, `Push`)],
  Carousel: [card(`p1`, `Page one`, `Swipe for more`), card(`p2`, `Page two`, ``), card(`p3`, `Page three`, ``)],
  Tabs: [text(`p1`, `The issue panel.`), text(`p2`, `The run panel.`)],
  Accordion: [text(`p`, `Created 2 days ago by Ada; 3 comments.`)],
  Collapsible: [text(`p`, `Retries, timeouts and the proxy live here.`, `muted`)],
  Dialog: [text(`p`, `The board and its 42 issues move to the trash for 48 hours.`)],
  Drawer: [text(`p`, `Status, assignee and labels.`)],
  Popover: [text(`p`, `Popover content.`)],
  Tooltip: [button(`b`, `Hover me`, `outline`)],
  Button: [],
  // Round 2: real content for the round-1 containers and Resizable.
  Resizable: [text(`p1`, `Boards`, `label`), text(`p2`, `Drag the handle or use the arrow keys.`, `muted`)],
  ScrollArea: [1, 2, 3, 4, 5, 6, 7, 8].map((n) => row(`r${n}`, `Issue ${n}`, `${n}h`)),
  Sidebar: [text(`main`, `Pick a board on the left.`)],
  AlertDialog: [],
  Menu: [button(`trigger`, `More`, `outline`)],
  Form: [
    { id: `title`, component: `Input`, props: { label: `Title`, name: `title`, placeholder: `What changed?` } },
    { id: `notify`, component: `Switch`, props: { label: `Notify watchers`, name: `notify`, checked: true } },
    { id: `save`, component: `Button`, props: { label: `Save`, submit: true } },
  ],
}

/** Styles a specimen case needs to show anything (a fixed box). */
const SPECIMEN_STYLES: Record<string, Record<string, unknown>> = {
  Resizable: { height: 160 },
  ScrollArea: { height: 160 },
}

/** Slots a specimen fills (triggers and footers of the overlays). */
const SPECIMEN_SLOTS: Record<string, Record<string, NestedNode>> = {
  Dialog: {
    trigger: button(`trigger`, `Delete board`, `destructive`),
    footer: { id: `footer`, component: `Stack`, props: { direction: `horizontal`, gap: `sm`, justify: `end` }, children: [button(`cancel`, `Cancel`, `outline`), button(`ok`, `Delete`, `destructive`)] },
  },
  Drawer: { trigger: button(`trigger`, `Filters`, `outline`), footer: button(`apply`, `Apply`) },
  Popover: { trigger: button(`trigger`, `Open popover`, `outline`) },
  Sidebar: { sidebar: { id: `nav`, component: `Stack`, props: { gap: `xs` }, children: [{ id: `n1`, component: `Row`, props: { title: `Inbox`, icon: `nav-inbox`, selected: true, pressable: true }, slots: { trailing: { id: `n1-count`, component: `Badge`, props: { text: `3`, variant: `secondary` } } } }, { id: `n2`, component: `Row`, props: { title: `Issues`, icon: `nav-issues`, pressable: true } }] } },
  AppBar: { trailing: { id: `more`, component: `Button`, props: { icon: `ui-more`, label: `More`, variant: `ghost`, size: `icon` } } },
  AlertDialog: { trigger: button(`trigger`, `Delete board`, `destructive`) },
}

/** A case node with the specimen's children + slots in place of `Child`. */
function specimenContent(node: NestedNode): NestedNode {
  const children = SPECIMEN_CHILDREN[node.component]
  const slots = SPECIMEN_SLOTS[node.component]
  const out: NestedNode = { ...node }
  if (children) {
    if (children.length > 0) out.children = children
    else delete out.children
  }
  if (slots) out.slots = slots
  const style = SPECIMEN_STYLES[node.component]
  if (style) out.style = { ...(node.style ?? {}), ...style }
  return out
}

/** Re-ids a nested tree so several cases of one component share a surface. */
function prefixIds(node: NestedNode, prefix: string): NestedNode {
  const out: NestedNode = { ...node, id: `${prefix}${node.id}` }
  if (node.children) out.children = node.children.map((c) => prefixIds(c, prefix))
  if (node.slots) out.slots = Object.fromEntries(Object.entries(node.slots).map(([k, v]) => [k, prefixIds(v, prefix)]))
  return out
}

/** The cases a component's specimen shows: an overlay (an `open` prop) once,
 *  open; anything else its example, then up to two enum props × every value,
 *  then `true` for up to two booleans, deduplicated, at most SPECIMEN_MAX_CASES. */
function specimenCases(name: string, all: ComponentCase[]): { label: string; node: NestedNode }[] {
  const own = all.filter((c) => c.node.component === name)
  const suffix = (c: ComponentCase) => c.name.slice(name.length + 1)
  const def = coreCatalog.components[name]
  if (def.props.open) {
    const open = own.find((c) => suffix(c) === `open=true`)!
    return [{ label: `open`, node: open.node }]
  }
  const picked: ComponentCase[] = [own.find((c) => suffix(c) === `example`)!]
  const enums = SPECIMEN_ENUMS.filter((p) => def.props[p]?.type === `enum`).slice(0, 2)
  const bools = SPECIMEN_BOOLEANS.filter((p) => def.props[p]?.type === `boolean`).slice(0, 2)
  for (const prop of enums) picked.push(...own.filter((c) => suffix(c).startsWith(`${prop}=`)))
  for (const prop of bools) picked.push(...own.filter((c) => suffix(c) === `${prop}=true`))
  const seen = new Set<string>()
  const out: { label: string; node: NestedNode }[] = []
  for (const c of picked) {
    const key = JSON.stringify(c.node.props ?? {}, Object.keys(c.node.props ?? {}).sort())
    if (seen.has(key)) continue
    seen.add(key)
    const label = suffix(c) === `example` ? `example` : suffix(c).replace(`=`, ` · `)
    out.push({ label, node: c.node })
    if (out.length === SPECIMEN_MAX_CASES) break
  }
  return out
}

/** One component's specimen: a padded column of captioned cases. */
function specimenNode(name: string, all: ComponentCase[]): NestedNode {
  const inline = INLINE_SPECIMENS.has(name)
  const root = `specimen-${kebab(name)}`
  return {
    id: root,
    component: `Box`,
    style: { display: `flex`, flexDirection: `column`, gap: `$spacing.lg`, padding: `$spacing.xl`, maxWidth: 720 },
    children: specimenCases(name, all).map((c, i) => ({
      id: `${root}-case-${i}`,
      component: `Stack`,
      props: { direction: `vertical`, gap: `xs`, align: inline ? `start` : `stretch` },
      children: [
        { id: `${root}-case-${i}-label`, component: `Text`, props: { text: c.label, variant: `caption` } },
        prefixIds(specimenContent(c.node), `c${i}-`),
      ],
    })),
  }
}

interface SpecimenEntry {
  id: string
  component: string | null
  title: string
  node: NestedNode
}

/** fixtures/specimens.json: every visible component's specimen (view id =
 *  its specimenId) plus the home page's demo surface (fixtures/demo-surface.json). */
function renderSpecimens(all: ComponentCase[], demo: NestedNode) {
  const specimens: SpecimenEntry[] = visible.map(([name]) => ({
    id: specimenId(name),
    component: name,
    title: name,
    node: specimenNode(name, all),
  }))
  const { $comment: _, ...demoNode } = demo as NestedNode & { $comment?: string }
  specimens.push({ id: `exponential-ui-demo`, component: null, title: `Demo`, node: demoNode })
  for (const s of specimens) {
    const result = reduceNested(s.node, { catalogId: CORE_CATALOG_ID })
    if (result.issues.length > 0) throw new Error(`specimen ${s.id}: ${result.issues.map((i) => `${i.id}: ${i.message}`).join(`; `)}`)
  }
  return {
    $comment: `${HEADER} One surface per visible component (id = its docs specimenId = its view-catalog id) plus the home page demo (exponential-ui-demo, from fixtures/demo-surface.json). ui.exponential.at shows the four platform shots of each; every renderer's example host paints an entry by id (web harness ?view=specimen&id=, the IDE's EXP_DEV_SCREEN, the Swift example's -shot, the Compose example's shot extra).`,
    catalogId: CORE_CATALOG_ID,
    specimens,
  }
}

/** Round 3: the depth runs the guides pass must get right (the ×4 vectors of
 *  the app's tree-guides tests), as Row siblings under a Section (any non-Row sibling ends every subtree). */
const TREE_GUIDE_DEPTHS: Record<string, number[]> = {
  flat: [0, 0, 0],
  chain: [0, 1, 2],
  siblings: [0, 1, 1, 1],
  "pass-through": [0, 1, 2, 2, 1],
  "subtree-ends": [0, 1, 2, 3, 2],
  "two-roots": [0, 1, 0, 1],
  orphans: [1, 2, 1],
}

function treeGuideCases(): ComponentCase[] {
  const rows = (depths: number[]) => depths.map((depth, i) => ({ id: `r${i + 1}`, component: `Row`, props: { title: `Row ${i + 1}`, ...(depth ? { depth } : {}) } }))
  const cases: ComponentCase[] = Object.entries(TREE_GUIDE_DEPTHS).map(([name, depths]) => ({
    name: `Row/tree:${name}`,
    node: { id: `tree`, component: `Section`, props: { title: `Tree`, tree: true }, children: rows(depths) },
  }))
  cases.push({ name: `Row/tree:text-breaks-the-subtree`, node: { id: `tree`, component: `Section`, children: [...rows([0, 1]), { id: `t`, component: `Text`, props: { text: `Between` } }, { id: `r3`, component: `Row`, props: { title: `Row 3`, depth: 1 } }] } })
  return cases
}

function treeGuidesFixture() {
  return {
    $comment: `${HEADER} Round 3 (docs/round-3-contract.md §2): the tree connector rule the core computes for nested Rows (src/tree-guides.ts treeGuides, the ×4 app rule): depths → per row the elbow level (null for a root), whether the elbow tees on to a later sibling, and the ancestor levels passing straight through. The Rust core replays it (tree_guides.rs); the painters never compute it.`,
    cases: Object.entries(TREE_GUIDE_DEPTHS).map(([name, depths]) => ({ name, depths, guides: treeGuides(depths) })),
  }
}

function macroCases(all: ComponentCase[]) {
  return [...all, ...boundMacroCases(), ...treeGuideCases()]
    .filter((c) => coreCatalog.components[c.node.component].kind === `macro`)
    .map((c) => {
      const result = reduceNested(c.node, { catalogId: CORE_CATALOG_ID })
      if (result.issues.length > 0) throw new Error(`${c.name}: ${result.issues.map((i) => i.message).join(`; `)}`)
      return { name: c.name, input: c.node, expected: result.root }
    })
}

interface BasicCaseFile {
  $comment: string
  catalogId: string
  cases: { name: string; components: FlatComponent[]; expected?: unknown }[]
}

function basicCases(file: BasicCaseFile) {
  return {
    ...file,
    cases: file.cases.map((c) => ({
      name: c.name,
      components: c.components,
      expected: reduceSurface(c.components, { catalogId: A2UI_BASIC_CATALOG_ID }),
    })),
  }
}

interface ExtensionCaseFile {
  $comment: string
  extension: ExtensionDef
  cases: { name: string; catalogId: string; components: FlatComponent[]; expected?: unknown }[]
}

function extensionCases(file: ExtensionCaseFile) {
  return {
    ...file,
    cases: file.cases.map((c) => ({
      name: c.name,
      catalogId: c.catalogId,
      components: c.components,
      expected: reduceSurface(c.components, { catalogId: c.catalogId, extensions: [file.extension] }),
    })),
  }
}

/** A value a bound prop takes in the bind-time data: the example's, else a
 *  sample by type; the second dataset flips it to its falsy twin (`0` stays
 *  TRUTHY under `truthy`: the number twin exercises the arithmetic, not the
 *  truthiness); the third (`MISSING`) leaves the path out, so every
 *  operand's `fallback{value, default}` takes its default. */
function boundSamples(schema: PropSchema, example: unknown): [unknown, unknown] {
  if (schema.type === `boolean`) return [true, false]
  if (schema.type === `number`) return [typeof example === `number` ? example : 3, 0]
  if (schema.type === `array`) return [example ?? [], []]
  if (schema.type === `object`) return [example ?? {}, null]
  return [typeof example === `string` ? example : `Bound`, ``]
}

function collect(node: UiNode, out: UiNode[] = []): UiNode[] {
  out.push(node)
  for (const slot of Object.values(node.slots ?? {})) collect(slot, out)
  node.children.forEach((c) => collect(c, out))
  return out
}

const BIND_OPTIONS = { strings: DEFAULT_STRINGS }

/** One dataset through the bind pass: the bound tree, every `set` press
 *  (runAction) and, for every ROW-SCOPED component (Table) left in the bound
 *  tree, each row's slot cells bound with the row as their scope
 *  (bindRowSlot; keyed by the row's index in `rows`). */
function bindDataset(root: UiNode, data: Record<string, unknown>) {
  const bound = bindTree(root, data, BIND_OPTIONS)
  const out: Record<string, unknown> = {
    data,
    bound,
    presses: collect(root)
      .filter((n) => n.on?.press?.function)
      .map((n) => ({ id: n.id, outcome: runAction(n.on!.press, data, BIND_OPTIONS) })),
  }
  const unbound = new Map(collect(root).map((n) => [n.id, n]))
  const rowSlots = (bound ? collect(bound) : [])
    .filter((n) => n.slots && hasRowSlots(coreCatalog.components[n.component]))
    .map((n) => {
      const rows = Array.isArray(n.props.rows) ? n.props.rows : []
      const rowsProp = unbound.get(n.id)?.props.rows
      return {
        id: n.id,
        rows: rows.map((_, index) => ({
          index,
          slots: Object.fromEntries(Object.entries(n.slots ?? {}).map(([name, slot]) => [name, bindRowSlot(slot, rowsProp, rows, index, data, BIND_OPTIONS)])),
        })),
      }
    })
  if (rowSlots.length > 0) out.rowSlots = rowSlots
  return out
}

/** Round 1: every bound macro case × three data models → the tree after the
 *  BIND pass (src/dynamic.ts bindTree) and what each press with a `set`
 *  write does (runAction). The renderers' bind-time resolvers replay it. */
function bindTimeCases() {
  return boundMacroCases()
    .filter((c) => c.name.includes(`/bound:`))
    .map((c) => {
      const prop = c.name.split(`/bound:`)[1]
      const def = coreCatalog.components[c.node.component]
      const example = (def.example as Record<string, unknown> | undefined)?.[prop]
      const { root, issues } = reduceNested(c.node, { catalogId: CORE_CATALOG_ID })
      if (issues.length > 0) throw new Error(`${c.name}: ${issues.map((i) => i.message).join(`; `)}`)
      const datasets = [...boundSamples(def.props[prop], example).map((value) => ({ [prop]: value })), {}]
      return { name: c.name, input: c.node, expanded: root, datasets: datasets.map((data) => bindDataset(root, data)) }
    })
}

/** Round 1: the hand-written bind cases the per-prop sweep cannot reach —
 *  row-scoped Table slot cells (bound and literal rows), DATA props copied
 *  verbatim, a bound accessible name, an author function meeting a `$set`
 *  (an issue, the author's call kept) and a numeric prop bound to string
 *  data. `issues` = what the reducer reported. */
const BIND_EXTRA_CASES: { name: string; input: NestedNode; datasets: Record<string, unknown>[] }[] = [
  {
    name: `Table/slot-cell:bound-rows`,
    input: {
      id: `table`,
      component: `Table`,
      props: { columns: [{ key: `name`, label: `Name` }, { key: `s`, label: `Status`, type: `slot`, slot: `status` }], rows: { path: `/rows` } },
      slots: { status: { id: `cell`, component: `Badge`, props: { text: { path: `s` } }, visible: { path: `show` } } },
    },
    datasets: [{ rows: [{ id: `a`, name: `Alice`, s: `ok`, show: true }, { id: `b`, name: `Bob`, s: `late`, show: false }, { id: `c`, name: `Cy`, s: 0, show: 0 }] }, { rows: [] }, {}],
  },
  {
    name: `Table/slot-cell:literal-rows`,
    input: {
      id: `table`,
      component: `Table`,
      props: {
        columns: [{ key: `path`, label: `Path` }, { key: `call`, label: `Call` }, { key: `note`, label: `Note` }, { key: `s`, label: `Status`, type: `slot`, slot: `status` }],
        rows: [
          { id: `a`, path: `/etc/hosts`, call: `openUrl`, note: `$string.cancel`, s: `ok` },
          { id: `b`, path: { path: `/etc/hosts` }, call: { call: `not`, args: { value: true } }, note: `plain`, s: `late` },
        ],
      },
      slots: { status: { id: `cell`, component: `Text`, props: { text: { call: `concat`, args: { values: [{ path: `s` }, ` · `, { path: `/suffix` }] } } } } },
    },
    datasets: [{ etc: { hosts: `PWNED` }, suffix: `today` }, {}],
  },
  {
    name: `Text/accessibility:bound-label`,
    input: { id: `text`, component: `Text`, props: { text: `hi` }, accessibility: { label: { path: `/l` }, description: `$string.close` } },
    datasets: [{ l: `Hello` }, {}],
  },
  {
    name: `Section/set:author-function`,
    input: { id: `section`, component: `Section`, props: { title: `More`, collapsible: true, open: { path: `/open` } }, on: { change: { function: { call: `openUrl`, args: { url: `https://example.com` } } } }, children: [{ id: `r`, component: `Row`, props: { title: `A` } }] },
    datasets: [{ open: true }],
  },
  {
    name: `Pagination/page:string-data`,
    input: { id: `pagination`, component: `Pagination`, props: { totalPages: 5, page: { path: `/page` } } },
    datasets: [{ page: `5` }, { page: `1` }, { page: 9 }, {}],
  },
]

function bindExtraCases() {
  return BIND_EXTRA_CASES.map((c) => {
    const { root, issues } = reduceNested(c.input, { catalogId: CORE_CATALOG_ID })
    return { name: c.name, input: c.input, expanded: root, issues, datasets: c.datasets.map((data) => bindDataset(root, data)) }
  })
}

interface ConditionCaseFile {
  $comment: string
  breakpoints: Record<string, number>
  cases: { name: string; style: Record<string, unknown>; contexts: (ConditionContext & { label: string })[]; expected?: unknown }[]
}

function styleConditionCases(file: ConditionCaseFile) {
  return {
    ...file,
    cases: file.cases.map((c) => ({
      name: c.name,
      style: c.style,
      contexts: c.contexts,
      expected: c.contexts.map((ctx) => resolveConditions(c.style, { ...ctx, breakpoints: ctx.breakpoints ?? file.breakpoints })),
    })),
  }
}

interface CodeCaseFile {
  $comment: string
  cases: { name: string; language: string; code: string; expected?: unknown }[]
}

function codeCases(file: CodeCaseFile) {
  return { ...file, cases: file.cases.map((c) => ({ name: c.name, language: c.language, code: c.code, expected: tokenizeCode(c.code, c.language) })) }
}

function promptBudget() {
  const full = catalogPrompt()
  const liteText = catalogPrompt({ lite: true })
  const terse = catalogPrompt({ terse: true })
  return {
    $comment: `${HEADER} The size of catalogPrompt() on record: prompt.test.ts fails when the full prompt passes budgetTokens (cut descriptions before components) or when these numbers drift from the catalog without being regenerated. tokens = chars / ${4}, an estimate.`,
    budgetTokens: 6500,
    full: { components: visible.length, chars: full.length, tokens: estimateTokens(full) },
    lite: { components: lite.length, chars: liteText.length, tokens: estimateTokens(liteText) },
    terse: { components: visible.length, chars: terse.length, tokens: estimateTokens(terse) },
  }
}

// ---------------------------------------------------------------------------
// Render everything
// ---------------------------------------------------------------------------

function readJson<T>(rel: string): T {
  return JSON.parse(readFileSync(join(pkgRoot, rel), `utf8`)) as T
}

/** Every generated file, keyed by its path relative to the package root. */
export function render(): Record<string, string> {
  const files = renderFiles()
  // The manifest counts the fixtures being written, not the bundled ones.
  const read = (name: string) => JSON.parse(files[`fixtures/${name}`] ?? readFileSync(join(pkgRoot, `fixtures`, name), `utf8`))
  return { ...files, "conformance/manifest.json": json(conformanceManifest(read)) }
}

function renderFiles(): Record<string, string> {
  const icons = iconNames()
  const cases = componentCases()
  const kitchen = readJson<NestedNode>(`fixtures/kitchen-sink.json`)
  const kitchenResult = reduceNested(kitchen, { catalogId: CORE_CATALOG_ID })
  if (kitchenResult.issues.length > 0)
    throw new Error(`kitchen-sink.json: ${kitchenResult.issues.map((i) => `${i.id}: ${i.message}`).join(`\n`)}`)
  const themeOutputs = renderThemes(cases, kitchen)
  const rust = renderRust(icons)
  return {
    "catalog/core.schema.json": json(coreSchema(icons)),
    "src/catalog.generated.ts": renderTs(icons),
    "generated/ExponentialUICatalog.generated.swift": renderSwift(),
    "generated/ExponentialUICatalog.generated.kt": renderKotlin(),
    "generated/catalog.generated.rs": rust,
    // VAPP-86: the Rust core's copies (a published crate cannot include! a file
    // outside its own directory); src/generate.test.ts gates them like the rest.
    "../../apps/desktop/crates/exponential-ui/src/generated/catalog.rs": rust,
    "../../apps/desktop/crates/exponential-ui/src/generated/themes.rs": themeOutputs[`generated/catalog.themes.generated.rs`],
    "docs/components.generated.json": json(renderDocs()),
    "fixtures/catalog-components.json": json({
      $comment: `${HEADER} Every visible component × its example × every enum value of every enum prop × both values of every boolean prop. Each case validates against core.schema.json; a renderer suite paints each case once.`,
      catalogId: CORE_CATALOG_ID,
      cases,
    }),
    "fixtures/catalog-macros.json": json({
      $comment: `${HEADER} Every macro case of catalog-components.json → the tree the expander produces (macros.json applied, recipes attached). The Rust core replays these byte for byte.`,
      catalogId: CORE_CATALOG_ID,
      cases: macroCases(cases),
    }),
    "fixtures/catalog-basic-map.json": json(basicCases(readJson<BasicCaseFile>(`fixtures/catalog-basic-map.json`))),
    "fixtures/catalog-extension.json": json(extensionCases(readJson<ExtensionCaseFile>(`fixtures/catalog-extension.json`))),
    "fixtures/kitchen-sink.expanded.json": json({
      $comment: `${HEADER} fixtures/kitchen-sink.json reduced and expanded: what every painter receives.`,
      ...kitchenResult,
    }),
    "fixtures/prompt-budget.json": json(promptBudget()),
    "fixtures/tree-guides.json": json(treeGuidesFixture()),
    "fixtures/bind-time.json": json({
      $comment: `${HEADER} Round 1 (docs/round-1-contract.md §1): every macro prop that takes a binding, bound to /<prop> → the expansion (calls where the input was dynamic) → for three data models (a sample, its falsy twin, and the path MISSING) the tree after the BIND pass (src/dynamic.ts bindTree: props resolved along their schema with DATA props verbatim, styles, recipe props and \`accessibility\` resolved, falsy \`visible\` nodes dropped, \`$string.<id>\` copy resolved through the DEFAULT string table, row-scoped slots left unbound) and every \`set\` press (runAction: context first, then the write). \`extra\` = hand-written cases (Table slot cells bound PER ROW in \`rowSlots\`, literal data rows, a bound accessible name, an author function meeting \`$set\` with the reducer's \`issues\`, a numeric prop bound to string data). Every renderer's bind-time resolver replays both lists.`,
      catalogId: CORE_CATALOG_ID,
      cases: bindTimeCases(),
      extra: bindExtraCases(),
    }),
    "fixtures/style-conditions.json": json(styleConditionCases(readJson<ConditionCaseFile>(`fixtures/style-conditions.json`))),
    "fixtures/code-tokens.json": json(codeCases(readJson<CodeCaseFile>(`fixtures/code-tokens.json`))),
    "fixtures/specimens.json": json(renderSpecimens(cases, readJson<NestedNode>(`fixtures/demo-surface.json`))),
    ...themeOutputs,
    // VAPP-91: the host fixtures (inputs hand-written, expected filled).
    ...renderHost(),
    // Round 2: the contract fixtures (inputs in scripts/generate-round2.ts).
    ...renderRound2(),
  }
}

/** Write `content` to `path` through a sibling temp file and a rename. */
export function writeAtomic(path: string, content: string): void {
  const temp = `${path}.${process.pid}.tmp`
  writeFileSync(temp, content)
  renameSync(temp, path)
}

if (import.meta.main) {
  const files = render()
  for (const [rel, content] of Object.entries(files)) {
    const path = join(pkgRoot, rel)
    mkdirSync(dirname(path), { recursive: true })
    const before = existsSync(path) ? readFileSync(path, `utf8`) : null
    // VAPP-103: never rewrite an unchanged file, and write a changed one
    // ATOMICALLY (temp + rename): a test reading a fixture while the
    // generator runs sees the old file or the new one, never half of it.
    if (before !== content) writeAtomic(path, content)
    console.log(`${before === content ? `unchanged` : `wrote    `} ${rel}`)
  }
}
