// Round 2 (docs/round-2-contract.md): the round-2 half of the generator
// (scripts/generate.ts merges it). Inputs are hand-written HERE; every
// `expected` comes from the TS reference, so the Rust core and every
// painter replay the same answers.
//
//   fixtures/format.json          the Formatter's English fallback through the format functions + displayString
//   fixtures/template-items.json  item keys (#<index>), row keys, instance suffixes, lifted template nodes
//   fixtures/text-direction.json  per-node direction + physical textAlign
//   fixtures/resizable.json       panel sizes: normalize, drag, keys, extents
//   fixtures/virtual-list.json    the window, scrollToIndex, sections, sticky headers
//   fixtures/animations.json      timing + sampled frames per built-in theme
//   fixtures/bench-list.json      the 100,000-row list every renderer benches

import { CORE_CATALOG_ID } from "../src/catalog"
import { displayString, englishFormatter, fixedOffset, formatFunctions } from "../src/format"
import { resolveDynamic } from "../src/dynamic"
import { reduceNested, reduceSurface } from "../src/reducer"
import { tableRowKeys, templateInstances, templateItemKeys, itemExtents, itemOffsets, listSections, scrollOffsetForIndex, scrollOffsetForItem, sectionRows, stickyHeader, virtualWindow, type ScrollAlign } from "../src/list"
import { dragDelta, keyboardResize, normalizeSizes, panelExtents, resizePanels, type PanelLimits } from "../src/resizable"
import { nodeDirections, nodeTextAlign, type Direction } from "../src/direction"
import { ANIMATION_NAMES, ANIMATION_PROPERTIES_CSS, animationFrame, animationTiming, keyframesCss, paintedOpacity } from "../src/animation"
import { styleToCss } from "../src/css"
import { builtinTheme, BUILTIN_THEME_IDS } from "../src/themes"
import type { ChildTemplate, FlatComponent, NestedNode, UiNode } from "../src/types"

const HEADER = `AUTO-GENERATED by packages/exponential-ui/scripts/generate-round2.ts — do not edit (inputs live there).`
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`

// ---------------------------------------------------------------------------
// format.json
// ---------------------------------------------------------------------------

/** The fixed clock of the relative-time cases: 2026-10-14T12:00:00Z. */
const NOW = Date.UTC(2026, 9, 14, 12, 0, 0)
const DAY = 86_400_000

const FORMAT_CALLS: { name: string; call: string; args: Record<string, unknown> }[] = [
  { name: `number/default`, call: `formatNumber`, args: { value: 1234.5678 } },
  { name: `number/decimals`, call: `formatNumber`, args: { value: 1234.5, decimals: 2 } },
  { name: `number/no-grouping`, call: `formatNumber`, args: { value: 1234567.891, grouping: false } },
  { name: `number/half-away`, call: `formatNumber`, args: { value: 2.5, decimals: 0 } },
  { name: `number/negative-half`, call: `formatNumber`, args: { value: -2.5, decimals: 0 } },
  { name: `number/shortest-decimal`, call: `formatNumber`, args: { value: 1.005, decimals: 2 } },
  { name: `number/large`, call: `formatNumber`, args: { value: 1e21 } },
  { name: `number/tiny`, call: `formatNumber`, args: { value: 0.0001 } },
  { name: `number/float-noise`, call: `formatNumber`, args: { value: 0.30000000000000004 } },
  { name: `number/string`, call: `formatNumber`, args: { value: `42` } },
  { name: `number/not-a-number`, call: `formatNumber`, args: { value: `abc` } },
  { name: `number/string-whitespace`, call: `formatNumber`, args: { value: ` 12 ` } },
  { name: `number/string-exponent`, call: `formatNumber`, args: { value: `1e3` } },
  { name: `number/string-leading-point`, call: `formatNumber`, args: { value: `-.5` } },
  { name: `number/string-hex-is-not`, call: `formatNumber`, args: { value: `0x10` } },
  { name: `number/string-infinity-is-not`, call: `formatNumber`, args: { value: `Infinity` } },
  { name: `number/string-grouped-is-not`, call: `formatNumber`, args: { value: `1,000` } },
  { name: `plural/string-one`, call: `pluralize`, args: { value: ` 1 `, one: `one item`, other: `many items` } },
  { name: `currency/usd`, call: `formatCurrency`, args: { value: 1234.5, currency: `USD` } },
  { name: `currency/eur-negative`, call: `formatCurrency`, args: { value: -0.5, currency: `EUR` } },
  { name: `currency/jpy-no-minor`, call: `formatCurrency`, args: { value: 1234.5, currency: `JPY` } },
  { name: `currency/code-prefix`, call: `formatCurrency`, args: { value: 1234.5, currency: `CHF` } },
  { name: `currency/three-digits`, call: `formatCurrency`, args: { value: 1.2345, currency: `KWD` } },
  { name: `currency/xof`, call: `formatCurrency`, args: { value: 1000, currency: `XOF` } },
  { name: `currency/lower-case`, call: `formatCurrency`, args: { value: 9.99, currency: `gbp` } },
  { name: `currency/decimals`, call: `formatCurrency`, args: { value: 1234.5, currency: `USD`, decimals: 0 } },
  { name: `currency/bad-code`, call: `formatCurrency`, args: { value: 1, currency: `dollars` } },
  { name: `percent/default`, call: `formatPercent`, args: { value: 0.256 } },
  { name: `percent/decimals`, call: `formatPercent`, args: { value: 0.25678, decimals: 1 } },
  { name: `percent/negative`, call: `formatPercent`, args: { value: -0.05 } },
  { name: `percent/over-100`, call: `formatPercent`, args: { value: 12.5 } },
  { name: `percent/exact-shift`, call: `formatPercent`, args: { value: 0.07, decimals: 2 } },
  { name: `date/day-pattern`, call: `formatDate`, args: { value: `2026-10-14`, format: `MMM d, yyyy` } },
  { name: `date/style-short`, call: `formatDate`, args: { value: `2026-10-14`, style: `short` } },
  { name: `date/style-medium`, call: `formatDate`, args: { value: `2026-10-14` } },
  { name: `date/style-long`, call: `formatDate`, args: { value: `2026-10-14`, style: `long` } },
  { name: `date/style-full`, call: `formatDate`, args: { value: `2026-10-14`, style: `full` } },
  { name: `date/instant-time`, call: `formatDate`, args: { value: `2026-10-14T14:30:05Z`, time: true } },
  { name: `date/instant-long-time`, call: `formatDate`, args: { value: `2026-10-14T14:30:05Z`, style: `long`, time: true } },
  { name: `date/offset-to-utc`, call: `formatDate`, args: { value: `2026-10-14T00:30:00+02:00`, format: `yyyy-MM-dd HH:mm` } },
  { name: `date/no-offset-is-utc`, call: `formatDate`, args: { value: `2026-10-14T09:05`, format: `h:mm a` } },
  { name: `date/epoch-ms`, call: `formatDate`, args: { value: Date.UTC(1999, 11, 31, 23, 59, 59), format: `EEEE, d MMMM yy 'at' HH:mm:ss` } },
  { name: `date/quote-escape`, call: `formatDate`, args: { value: `2026-01-05`, format: `'It''s' E, MMMM d` } },
  { name: `date/unreadable`, call: `formatDate`, args: { value: `next tuesday`, format: `yyyy` } },
  ...([
    [`now`, 0],
    [`seconds-ago`, -30_000],
    [`in-seconds`, 59_000],
    [`minute-ago`, -61_000],
    [`in-2-hours`, 2 * 3_600_000],
    [`hour-ago`, -3_600_000],
    [`yesterday`, -DAY],
    [`in-6-days`, 6 * DAY + 3_600_000],
    [`last-week`, -7 * DAY],
    [`in-4-weeks`, 29 * DAY],
    [`last-month`, -31 * DAY],
    [`in-6-months`, 200 * DAY],
    [`12-months-ago`, -364 * DAY],
    [`last-year`, -365 * DAY],
    [`in-1200-years`, 1200 * 365 * DAY],
  ] as [string, number][]).map(([name, delta]) => ({ name: `relative/${name}`, call: `formatRelativeTime`, args: { value: NOW + delta, now: NOW } })),
  { name: `relative/iso-now-arg`, call: `formatRelativeTime`, args: { value: `2026-10-13`, now: `2026-10-14T12:00:00Z` } },
  { name: `plural/zero-arm`, call: `pluralize`, args: { value: 0, zero: `none`, one: `one item`, other: `many items` } },
  { name: `plural/zero-other`, call: `pluralize`, args: { value: 0, one: `one item`, other: `many items` } },
  { name: `plural/one`, call: `pluralize`, args: { value: 1, one: `one item`, other: `many items` } },
  { name: `plural/two`, call: `pluralize`, args: { value: 2, one: `one item`, other: `many items` } },
  { name: `plural/fraction`, call: `pluralize`, args: { value: 1.5, one: `one item`, other: `many items` } },
]

const DISPLAY_VALUES: { name: string; value: unknown }[] = [
  { name: `string`, value: `Hello` },
  { name: `empty-string`, value: `` },
  { name: `integer`, value: 412 },
  { name: `zero`, value: 0 },
  { name: `negative`, value: -3 },
  { name: `fraction`, value: 1.5 },
  { name: `float-noise`, value: 0.30000000000000004 },
  { name: `micro`, value: 0.000001 },
  { name: `exponent-small`, value: 1e-7 },
  { name: `large-integer`, value: 123456789012345680000 },
  { name: `exponent-large`, value: 1e21 },
  { name: `true`, value: true },
  { name: `false`, value: false },
  { name: `null`, value: null },
  { name: `object`, value: { a: 1 } },
  { name: `array`, value: [1, 2] },
]

/** Instants in a non-UTC surface zone: `timeZone` for a Formatter with an
 *  IANA database, `offsetMinutes` (the offset in force at that instant) for
 *  the English fallback. A calendar day never shifts. */
const ZONED_CALLS: { name: string; timeZone: string; offsetMinutes: number; call: string; args: Record<string, unknown> }[] = [
  { name: `berlin-pattern-next-day`, timeZone: `Europe/Berlin`, offsetMinutes: 120, call: `formatDate`, args: { value: `2026-10-14T22:30:00Z`, format: `yyyy-MM-dd HH:mm` } },
  { name: `new-york-preset-time`, timeZone: `America/New_York`, offsetMinutes: -300, call: `formatDate`, args: { value: `2026-01-15T03:00:00Z`, time: true } },
  { name: `kolkata-half-hour`, timeZone: `Asia/Kolkata`, offsetMinutes: 330, call: `formatDate`, args: { value: `2026-10-14T20:00:00Z`, style: `full`, time: true } },
  { name: `epoch-ms-in-zone`, timeZone: `America/Los_Angeles`, offsetMinutes: -420, call: `formatDate`, args: { value: Date.UTC(2026, 6, 4, 2, 15), format: `EEE MMM d h:mm a` } },
  { name: `calendar-day-never-shifts`, timeZone: `Pacific/Kiritimati`, offsetMinutes: 840, call: `formatDate`, args: { value: `2026-10-14`, style: `long` } },
]

function formatFixture() {
  return {
    $comment: `${HEADER} Round 2 (docs/round-2-contract.md §3). \`calls\`: each format function (A2UI basic formatNumber/formatCurrency/formatDate/pluralize + core formatPercent/formatRelativeTime) through the ENGLISH fallback Formatter (src/format.ts englishFormatter; catalog/locale.json \`englishFallback\`; = Intl en-US, ICU 74+), instants in UTC, \`now\` explicit: the Rust core's fallback (and any renderer without ICU) replays them EXACTLY — the conformance run uses the fallback. A platform Formatter (Foundation, android.icu) may be checked too after mapping U+202F and U+00A0 to a space on both sides (newer ICU puts U+202F before AM/PM). A numeric string = optional whitespace, sign, decimal digits, fraction, exponent; hex, Infinity and separators are not numbers. \`zoned\`: the same functions in a non-UTC surface zone: the fallback takes \`offsetMinutes\` (the host's UTC offset at that instant), an ICU Formatter takes \`timeZone\`; a calendar day never shifts. \`display\`: what a string/markdown prop SHOWS for a bound value (src/format.ts displayString: ECMAScript Number→String, booleans, nothing for null/objects); no locale.`,
    locale: `en-US`,
    timeZone: `UTC`,
    calls: FORMAT_CALLS.map((c) => ({ name: c.name, call: { call: c.call, args: c.args }, expected: resolveDynamic({ call: c.call, args: c.args }, {}) })),
    zoned: ZONED_CALLS.map((c) => ({ name: c.name, timeZone: c.timeZone, offsetMinutes: c.offsetMinutes, call: { call: c.call, args: c.args }, expected: formatFunctions(englishFormatter(fixedOffset(c.offsetMinutes)))[c.call as `formatDate`](c.args) })),
    display: DISPLAY_VALUES.map((d) => ({ name: d.name, value: d.value, expected: displayString(d.value) })),
  }
}

// ---------------------------------------------------------------------------
// template-items.json
// ---------------------------------------------------------------------------

const KEY_CASES: { name: string; items: unknown[]; key?: string }[] = [
  { name: `no-key-is-index`, items: [{ id: `a` }, { id: `b` }] },
  { name: `keys`, items: [{ id: `a` }, { id: `b` }, { id: `c` }], key: `id` },
  { name: `duplicate`, items: [{ id: `a` }, { id: `a` }, { id: `b` }], key: `id` },
  { name: `missing-null-empty`, items: [{ id: `a` }, {}, { id: null }, { id: `` }], key: `id` },
  { name: `numbers-and-objects`, items: [{ id: 7 }, { id: { x: 1 } }, { id: true }], key: `/id` },
  { name: `collision-with-hash`, items: [{ id: `#1` }, { id: `a` }, { id: `a` }], key: `id` },
  { name: `nested-pointer`, items: [{ who: { name: `ada` } }, { who: { name: `bob` } }], key: `who/name` },
]

const ROW_KEY_CASES: { name: string; rows: unknown[]; rowKey?: string }[] = [
  { name: `default-id`, rows: [{ id: `alice` }, { id: `bob` }] },
  { name: `own-field`, rows: [{ email: `a@x` }, { email: `b@x` }], rowKey: `email` },
  { name: `missing-and-duplicate`, rows: [{ id: `a` }, { name: `no id` }, { id: `a` }] },
  { name: `field-with-slash`, rows: [{ "a/b": `x` }, { "a/b": `y` }], rowKey: `a/b` },
]

const INSTANCE_DATA = {
  boards: [
    { id: `ops`, issues: [{ id: `1`, t: `Ship` }, { id: `2`, t: `Test` }] },
    { id: `web`, issues: [{ id: `1`, t: `Fix` }] },
    { id: `ops`, issues: [] },
  ],
}

/** Keys holding `.` and `~`: `a.b` + `c` and `a` + `b.c` must not collide. */
const DOTTED_DATA = {
  boards: [
    { id: `a.b`, issues: [{ id: `c` }] },
    { id: `a`, issues: [{ id: `b.c` }, { id: `~1` }] },
  ],
}

function dottedExpected() {
  const outer: ChildTemplate = { component: `board`, path: `/boards`, key: `id` }
  const inner: ChildTemplate = { component: `issue`, path: `issues`, key: `id` }
  return templateInstances(DOTTED_DATA, outer).flatMap((o) => templateInstances(DOTTED_DATA, inner, o.path, o.instance).map((i) => ({ outer: o.key, ...i, ids: { issue: `issue${i.instance}`, title: `issue.title${i.instance}` } })))
}

function instanceCases() {
  const outer: ChildTemplate = { component: `board`, path: `/boards`, key: `id` }
  const inner: ChildTemplate = { component: `issue`, path: `issues`, key: `id` }
  const outerItems = templateInstances(INSTANCE_DATA, outer)
  return [
    { name: `top-level`, data: INSTANCE_DATA, template: outer, scope: ``, instance: ``, expected: outerItems },
    { name: `relative-path-in-scope`, data: INSTANCE_DATA, template: inner, scope: `/boards/0`, instance: `.ops`, expected: templateInstances(INSTANCE_DATA, inner, `/boards/0`, `.ops`) },
    {
      name: `nested-suffix-accumulates`,
      data: INSTANCE_DATA,
      template: outer,
      inner,
      scope: ``,
      instance: ``,
      expected: outerItems.flatMap((o) => templateInstances(INSTANCE_DATA, inner, o.path, o.instance).map((i) => ({ outer: o.key, ...i, ids: { issue: `issue${i.instance}`, title: `issue.title${i.instance}` } }))),
    },
    { name: `not-an-array`, data: { boards: { a: 1 } }, template: outer, scope: ``, instance: ``, expected: templateInstances({ boards: { a: 1 } }, outer) },
    { name: `dotted-keys-escaped`, data: DOTTED_DATA, template: outer, inner, scope: ``, instance: ``, expected: dottedExpected() },
  ]
}

const LIFT_NESTED: NestedNode = {
  id: `root`,
  component: `Box`,
  children: [
    { id: `list`, component: `List`, template: { component: `row`, path: `/items` } },
    { id: `row`, component: `ListRow`, props: { title: { path: `title` } } },
    {
      id: `card`,
      component: `Box`,
      children: [
        { id: `inner`, component: `List`, template: { component: `cell`, path: `cells` } },
        { id: `cell`, component: `Text`, props: { text: { path: `v` } } },
      ],
    },
  ],
}

const LIFT_FLAT: FlatComponent[] = [
  { id: `root`, component: `Box`, children: [`list`, `item`, `ghost-list`] },
  { id: `list`, component: `List`, children: { componentId: `item`, path: `/items`, key: `id` } },
  { id: `item`, component: `Box`, children: [`label`, `sub`] },
  { id: `label`, component: `Text`, text: { path: `name` } },
  { id: `sub`, component: `List`, children: { componentId: `tag`, path: `tags` } },
  { id: `tag`, component: `Badge`, text: { path: `` } },
  { id: `ghost-list`, component: `List`, children: { componentId: `nowhere`, path: `/x` } },
]

/** Templates that would instantiate themselves: reported, never lifted. */
const CYCLE_CASES: { name: string; nested?: NestedNode; components?: FlatComponent[] }[] = [
  { name: `cycle-self`, nested: { id: `root`, component: `Box`, children: [{ id: `l`, component: `List`, template: { component: `l`, path: `/items` } }] } },
  {
    name: `cycle-ancestor`,
    components: [
      { id: `root`, component: `Box`, children: [`col`] },
      { id: `col`, component: `Box`, children: [`l`] },
      { id: `l`, component: `List`, children: { componentId: `col`, path: `/items` } },
    ],
  },
  { name: `cycle-root`, nested: { id: `root`, component: `Box`, children: [{ id: `l`, component: `List`, template: { component: `root`, path: `/items` } }] } },
  {
    name: `cycle-mutual-built`,
    components: [
      { id: `root`, component: `Box`, children: [`a`, `ok`] },
      { id: `a`, component: `List`, children: { componentId: `t1`, path: `/items` } },
      { id: `t1`, component: `Box`, children: [`l2`] },
      { id: `l2`, component: `List`, children: { componentId: `t2`, path: `/items` } },
      { id: `t2`, component: `Box`, children: [`l3`] },
      { id: `l3`, component: `List`, children: { componentId: `t1`, path: `/items` } },
      { id: `ok`, component: `List`, children: { componentId: `row`, path: `/rows` } },
      { id: `row`, component: `Text`, text: { path: `t` } },
    ],
  },
]

function templateItemsFixture() {
  return {
    $comment: `${HEADER} Round 2 (docs/round-2-contract.md §4). \`keys\`: a template's item keys (src/list.ts templateItemKeys: the value at \`key\` — a pointer relative to the item — as a string, objects as JSON; \`#<index>\` when missing, null, empty or a DUPLICATE of an earlier key, more \`#\`s until unique; no key = the index). \`rowKeys\`: Table rows by their \`rowKey\` FIELD, same rules. \`instances\`: the items a template renders in a scope and the instance SUFFIX each item's nodes wear (\`<node id><suffix>\`; suffix = \`.<key>\` with \`~\` → \`~0\` and \`.\` → \`~1\`; it ACCUMULATES through nested templates: \`issue.ops.1\`). \`reduce\`: a node a \`template\` names is LIFTED out of the tree into \`templates\` (never also rendered in place), on the nested and the flat path; an unknown template id is an issue; a template that would instantiate itself (its owner, an ancestor of its owner, the root, or through other templates) is an issue (\`template: cycle through this id\`) and is NOT lifted: it stays in place and its owner renders no items.`,
    keys: KEY_CASES.map((c) => ({ ...c, expected: templateItemKeys(c.items, c.key) })),
    rowKeys: ROW_KEY_CASES.map((c) => ({ ...c, expected: tableRowKeys(c.rows, c.rowKey) })),
    instances: instanceCases(),
    reduce: [
      { name: `nested-lifted`, catalogId: CORE_CATALOG_ID, nested: LIFT_NESTED, expected: reduceNested(LIFT_NESTED, { catalogId: CORE_CATALOG_ID }) },
      { name: `flat-lifted-and-built`, catalogId: CORE_CATALOG_ID, components: LIFT_FLAT, expected: reduceSurface(LIFT_FLAT, { catalogId: CORE_CATALOG_ID }) },
      ...CYCLE_CASES.map((c) => ({ ...c, catalogId: CORE_CATALOG_ID, expected: c.nested ? reduceNested(c.nested, { catalogId: CORE_CATALOG_ID }) : reduceSurface(c.components!, { catalogId: CORE_CATALOG_ID }) })),
    ],
  }
}

// ---------------------------------------------------------------------------
// text-direction.json
// ---------------------------------------------------------------------------

const DIRECTION_TREE: NestedNode = {
  id: `root`,
  component: `Box`,
  children: [
    { id: `plain`, component: `Text`, props: { text: `Hello!` } },
    { id: `end`, component: `Text`, props: { text: `Total`, align: `end` } },
    { id: `center`, component: `Text`, props: { text: `Mid`, align: `center` } },
    { id: `style-wins`, component: `Text`, props: { text: `x`, align: `start` }, style: { textAlign: `end` } },
    { id: `physical`, component: `Text`, props: { text: `x` }, style: { textAlign: `left` } },
    {
      id: `rtl-box`,
      component: `Box`,
      style: { direction: `rtl` },
      children: [
        { id: `rtl-plain`, component: `Text`, props: { text: `مرحبا` } },
        { id: `rtl-end`, component: `Text`, props: { text: `x`, align: `end` } },
        { id: `ltr-island`, component: `Box`, style: { direction: `ltr` }, children: [{ id: `island-text`, component: `Text`, props: { text: `code()` } }] },
        { id: `rtl-heading`, component: `Heading`, props: { text: `عنوان`, level: `h2` } },
      ],
    },
  ],
}

function directionFixture() {
  const cases = ([`ltr`, `rtl`] as Direction[]).map((surface) => {
    const { root } = reduceNested(DIRECTION_TREE, { catalogId: CORE_CATALOG_ID })
    const dirs = nodeDirections(root, surface)
    const expected: Record<string, { direction: Direction; textAlign: string }> = {}
    const walk = (n: UiNode) => {
      expected[n.id] = { direction: dirs[n.id], textAlign: nodeTextAlign(n, dirs[n.id]) }
      n.children.forEach(walk)
    }
    walk(root)
    return { name: `surface-${surface}`, surface, tree: DIRECTION_TREE, expected }
  })
  return {
    $comment: `${HEADER} Round 2 (docs/round-2-contract.md §2). Reduce + expand \`tree\`, then every node's DIRECTION (its own style \`direction\`, else its parent's; the root's parent = the surface) and its PHYSICAL text alignment (style \`textAlign\`, else a Text's \`align\`, else \`start\`; start/end resolved against the node's direction): src/direction.ts. A painter hands this to text layout (the Rust core's Visual carries the resolved align; the bidi paragraph direction = the node's direction).`,
    cases,
  }
}

// ---------------------------------------------------------------------------
// resizable.json
// ---------------------------------------------------------------------------

const LIMITS: PanelLimits[] = [{ min: 20, max: 60 }, { min: 10 }, { min: 15, collapsible: true }]

function resizableFixture() {
  const normalize: { name: string; sizes?: unknown[]; count: number; panels?: PanelLimits[] }[] = [
    { name: `equal-when-unset`, count: 3 },
    { name: `scaled-to-100`, sizes: [1, 1, 2], count: 3 },
    { name: `missing-share-rest`, sizes: [50], count: 3 },
    { name: `invalid-ignored`, sizes: [-5, `x`, 30], count: 3 },
    { name: `extra-ignored`, sizes: [30, 70, 99], count: 2 },
    { name: `clamped-and-redistributed`, sizes: [80, 10, 10], count: 3, panels: LIMITS },
    { name: `collapsed-stays`, sizes: [50, 50, 0], count: 3, panels: LIMITS },
    { name: `min-capped-by-count`, sizes: [50, 50], count: 2, panels: [{ min: 80 }, { min: 80 }] },
    { name: `single-panel`, sizes: [30], count: 1 },
  ]
  const base = [40, 30, 30]
  const resize: { name: string; sizes: number[]; handle: number; delta: number; panels?: PanelLimits[] }[] = [
    { name: `grow-first`, sizes: base, handle: 0, delta: 10 },
    { name: `shrink-first`, sizes: base, handle: 0, delta: -10 },
    { name: `clamped-by-max`, sizes: base, handle: 0, delta: 40, panels: LIMITS },
    { name: `clamped-by-neighbour-min`, sizes: base, handle: 0, delta: 25, panels: LIMITS },
    { name: `clamped-by-own-min`, sizes: base, handle: 0, delta: -35, panels: LIMITS },
    { name: `collapse-below-half-min`, sizes: base, handle: 1, delta: 25, panels: LIMITS },
    { name: `no-collapse-above-half-min`, sizes: base, handle: 1, delta: 20, panels: LIMITS },
    { name: `reopen-at-min`, sizes: [40, 60, 0], handle: 1, delta: -8, panels: LIMITS },
    { name: `stay-collapsed-small-drag`, sizes: [40, 60, 0], handle: 1, delta: -5, panels: LIMITS },
    { name: `reopen-follows-pointer`, sizes: [0, 100], handle: 0, delta: 50, panels: [{ min: 20, collapsible: true }, {}] },
    { name: `reopen-second-follows-pointer`, sizes: [100, 0], handle: 0, delta: -50, panels: [{}, { min: 20, collapsible: true }] },
    { name: `reopen-clamped-by-max`, sizes: [0, 100], handle: 0, delta: 80, panels: [{ min: 20, max: 60, collapsible: true }, {}] },
    { name: `bad-handle`, sizes: base, handle: 2, delta: 10 },
  ]
  const keys: { name: string; sizes: number[]; handle: number; key: string; orientation: `horizontal` | `vertical`; direction: `ltr` | `rtl`; panels?: PanelLimits[] }[] = [
    { name: `right-ltr`, sizes: [50, 50], handle: 0, key: `ArrowRight`, orientation: `horizontal`, direction: `ltr` },
    { name: `right-rtl`, sizes: [50, 50], handle: 0, key: `ArrowRight`, orientation: `horizontal`, direction: `rtl` },
    { name: `left-ltr`, sizes: [50, 50], handle: 0, key: `ArrowLeft`, orientation: `horizontal`, direction: `ltr` },
    { name: `down-vertical`, sizes: [50, 50], handle: 0, key: `ArrowDown`, orientation: `vertical`, direction: `ltr` },
    { name: `up-ignored-horizontal`, sizes: [50, 50], handle: 0, key: `ArrowUp`, orientation: `horizontal`, direction: `ltr` },
    { name: `home`, sizes: [50, 50], handle: 0, key: `Home`, orientation: `horizontal`, direction: `ltr`, panels: [{ min: 25 }, {}] },
    { name: `end`, sizes: [50, 50], handle: 0, key: `End`, orientation: `horizontal`, direction: `ltr`, panels: [{ max: 70 }, {}] },
    { name: `enter-collapses-first`, sizes: [30, 70], handle: 0, key: `Enter`, orientation: `horizontal`, direction: `ltr`, panels: [{ min: 20, collapsible: true }, {}] },
    { name: `enter-reopens-first`, sizes: [0, 100], handle: 0, key: `Enter`, orientation: `horizontal`, direction: `ltr`, panels: [{ min: 20, collapsible: true }, {}] },
    { name: `enter-collapses-second`, sizes: [70, 30], handle: 0, key: `Enter`, orientation: `horizontal`, direction: `ltr`, panels: [{}, { min: 20, collapsible: true }] },
    { name: `enter-noop`, sizes: [50, 50], handle: 0, key: `Enter`, orientation: `horizontal`, direction: `ltr` },
  ]
  return {
    $comment: `${HEADER} Round 2 (docs/round-2-contract.md §1, Resizable): sizes are percent of the group's main axis minus its handles (sum 100), rounded to 1e-6. \`normalize\` = the starting sizes (normalizeSizes), \`resize\` = a drag from the sizes at its START (resizePanels: only the two panels beside the handle change; min/max clamp; collapse below half a collapsible panel's min; a collapsed one dragged past half its min reopens at max(min, the pointer), clamped), \`keys\` = a key on a focused handle (keyboardResize, step 10, rtl flips Left/Right), \`extents\` = px per panel (panelExtents: container minus one hairline per handle), \`drag\` = px of pointer movement → the percent delta (dragDelta). Compare numbers within 1e-6.`,
    normalize: normalize.map((c) => ({ ...c, expected: normalizeSizes(c.sizes, c.count, c.panels) })),
    resize: resize.map((c) => ({ ...c, expected: resizePanels(c.sizes, c.handle, c.delta, c.panels) })),
    keys: keys.map((c) => ({ ...c, expected: keyboardResize(c.sizes, c.handle, c.key, c.orientation, c.direction, c.panels) })),
    extents: [
      { name: `two-panels`, sizes: [30, 70], container: 401, handle: 1 },
      { name: `three-panels-thick-handle`, sizes: [25, 25, 50], container: 1000, handle: 2 },
    ].map((c) => ({ ...c, expected: panelExtents(c.sizes, c.container, c.handle) })),
    drag: [
      { name: `ltr-right`, px: 40, container: 401, panels: 2, orientation: `horizontal` as const, direction: `ltr` as const },
      { name: `rtl-right-shrinks-first`, px: 40, container: 401, panels: 2, orientation: `horizontal` as const, direction: `rtl` as const },
      { name: `vertical-ignores-rtl`, px: -50, container: 501, panels: 2, orientation: `vertical` as const, direction: `rtl` as const },
    ].map((c) => ({ ...c, expected: dragDelta(c.px, c.container, c.panels, c.orientation, c.direction) })),
  }
}

// ---------------------------------------------------------------------------
// virtual-list.json
// ---------------------------------------------------------------------------

const uniform = (count: number, extent: number) => Array.from({ length: count }, () => extent)

/** scrollToIndex on the sectioned `by-day` list (header 32, item 40). */
const SECTIONED_SCROLLS: { name: string; index: number; viewport: number; scroll: number; align: ScrollAlign; stickyHeaders: boolean }[] = [
  { name: `start-under-own-sticky-header`, index: 3, viewport: 100, scroll: 0, align: `start`, stickyHeaders: true },
  { name: `start-without-sticky`, index: 3, viewport: 100, scroll: 0, align: `start`, stickyHeaders: false },
  { name: `data-index-skips-headers`, index: 2, viewport: 100, scroll: 0, align: `end`, stickyHeaders: true },
  { name: `absent-index-no-move`, index: 9, viewport: 100, scroll: 24, align: `start`, stickyHeaders: true },
]

function virtualListFixture() {
  const mixed = [40, 40, 64, 40, 120, 40, 40, 40, 64, 40, 40, 40]
  const windows: { name: string; measured?: (number | null)[]; row?: number; extents: number[] | { count: number; extent: number }; gap: number; scroll: number; viewport: number; overscan?: number }[] = [
    { name: `top`, extents: { count: 1000, extent: 40 }, gap: 0, scroll: 0, viewport: 400 },
    { name: `middle`, extents: { count: 1000, extent: 40 }, gap: 0, scroll: 20_000, viewport: 400 },
    { name: `item-ending-at-viewport-start-counts`, extents: { count: 1000, extent: 40 }, gap: 0, scroll: 400, viewport: 400, overscan: 0 },
    { name: `gap-and-divider`, extents: { count: 200, extent: 40 }, gap: 9, scroll: 4900, viewport: 300 },
    { name: `end-clamped`, extents: { count: 100, extent: 40 }, gap: 0, scroll: 3800, viewport: 400 },
    { name: `mixed-extents`, extents: mixed, gap: 4, scroll: 150, viewport: 200, overscan: 1 },
    { name: `horizontal-axis`, extents: { count: 500, extent: 160 }, gap: 8, scroll: 8400, viewport: 390 },
    { name: `hundred-thousand`, extents: { count: 100_000, extent: 40 }, gap: 0, scroll: 2_000_000, viewport: 800 },
    { name: `empty`, extents: [], gap: 0, scroll: 0, viewport: 400 },
    // Unmeasured items (`measured` null): `$control.row` (`row`) until any
    // item is measured, then the mean measured extent (`itemExtents`).
    { name: `unmeasured-take-row-before-any-measure`, measured: Array.from({ length: 20 }, () => null), row: 36, extents: [], gap: 0, scroll: 100, viewport: 200, overscan: 0 },
    { name: `unmeasured-take-measured-mean`, measured: [40, 64, null, 52, ...Array.from({ length: 26 }, () => null)], row: 36, extents: [], gap: 0, scroll: 300, viewport: 200, overscan: 1 },
  ]
  const expand = (e: number[] | { count: number; extent: number }) => (Array.isArray(e) ? e : uniform(e.count, e.extent))
  const scrolls: { name: string; extents: number[] | { count: number; extent: number }; gap: number; index: number; viewport: number; scroll: number; align: ScrollAlign; inset?: number }[] = [
    { name: `nearest-below`, extents: { count: 100, extent: 40 }, gap: 0, index: 30, viewport: 400, scroll: 0, align: `nearest` },
    { name: `nearest-visible-no-move`, extents: { count: 100, extent: 40 }, gap: 0, index: 5, viewport: 400, scroll: 0, align: `nearest` },
    { name: `nearest-above`, extents: { count: 100, extent: 40 }, gap: 0, index: 2, viewport: 400, scroll: 800, align: `nearest` },
    { name: `start`, extents: { count: 100, extent: 40 }, gap: 0, index: 50, viewport: 400, scroll: 0, align: `start` },
    { name: `center`, extents: { count: 100, extent: 40 }, gap: 0, index: 50, viewport: 400, scroll: 0, align: `center` },
    { name: `end`, extents: { count: 100, extent: 40 }, gap: 0, index: 50, viewport: 400, scroll: 0, align: `end` },
    { name: `start-clamped-at-end`, extents: { count: 100, extent: 40 }, gap: 0, index: 99, viewport: 400, scroll: 0, align: `start` },
    { name: `start-under-sticky-header`, extents: mixed, gap: 4, index: 6, viewport: 200, scroll: 0, align: `start`, inset: 32 },
    { name: `out-of-range-no-move`, extents: { count: 10, extent: 40 }, gap: 0, index: 10, viewport: 200, scroll: 40, align: `start` },
  ]
  const items = [
    { id: `1`, day: `Today` },
    { id: `2`, day: `Today` },
    { id: `3`, day: `Yesterday` },
    { id: `4`, day: `Today` },
    { id: `5` },
    { id: `6` },
  ]
  const sections = listSections(items, `day`)
  const rows = sectionRows(sections)
  const rowExtents = rows.map((r) => (`header` in r ? 32 : 40))
  const offsets = itemOffsets(rowExtents, 0)
  const headerRows = rows.flatMap((r, i) => (`header` in r ? [i] : []))
  return {
    $comment: `${HEADER} Round 2 (docs/round-2-contract.md §5). ONE axis (vertical or horizontal Lists alike); offsets relative to the list's content start; a list without a bounded size windows against its nearest scrolling ancestor or the host viewport, translated into this frame. \`windows\` (virtualWindow; \`{count, extent}\` = that many equal extents; \`measured\` + \`row\` = itemExtents: an unmeasured item (null) takes the mean measured extent, else \`row\` = \`$control.row\` before any is measured, giving \`extents\`): every item intersecting [scroll, scroll + viewport) — an item ending exactly at the start counts — plus \`overscan\` (default 5) each side; \`before\`/\`after\` = the spacers. \`scrollTo\` (scrollOffsetForIndex = the scrollToIndex command): start/center/end/nearest, \`inset\` = the pinned header over the item, clamped to the content. \`sections\` (listSections + sectionRows): consecutive items sharing \`sectionBy\` form a section; the flat rows put a header before each. \`sectionedScrollTo\` (scrollOffsetForItem): scrollToIndex on a sectioned list maps the DATA index to its flat row, inset = its own section header's extent when headers are sticky. \`sticky\` (stickyHeader): the pinned header row and its offset per scroll (pushed back by the next header).`,
    windows: windows
      .map((c) => (c.measured ? { ...c, extents: itemExtents(c.measured, c.row ?? 0) } : c))
      .map((c) => ({ ...c, expected: virtualWindow(expand(c.extents), c.gap, c.scroll, c.viewport, c.overscan) })),
    scrollTo: scrolls.map((c) => ({ ...c, expected: scrollOffsetForIndex(expand(c.extents), c.gap, c.index, c.viewport, c.scroll, c.align, c.inset) })),
    sections: [{ name: `by-day`, items, sectionBy: `day`, expected: { sections, rows } }],
    sectionedScrollTo: SECTIONED_SCROLLS.map((c) => {
      const sRows = sectionRows(listSections(items, `day`))
      const ext = sRows.map((r) => (`header` in r ? 32 : 40))
      return { ...c, items, sectionBy: `day`, headerExtent: 32, itemExtent: 40, gap: 0, expected: scrollOffsetForItem(sRows, ext, 0, c.index, c.viewport, c.scroll, c.align, c.stickyHeaders) }
    }),
    sticky: [
      {
        name: `push-back`,
        rowExtents,
        headerRows,
        scrolls: [0, 10, 60, 100, 120, 160, 300],
        expected: [0, 10, 60, 100, 120, 160, 300].map((s) => stickyHeader(offsets, rowExtents, headerRows, s)),
      },
    ],
  }
}

// ---------------------------------------------------------------------------
// animations.json
// ---------------------------------------------------------------------------

/** An animation's opacity MULTIPLIES the node's own (at `at` durations). */
const OPACITY_CASES: { name: string; own: number; animation: string; at: number }[] = [
  { name: `pulse-half-at-mid`, own: 0.5, animation: `pulse`, at: 0.5 },
  { name: `fade-in-start`, own: 0.6, animation: `fade-in`, at: 0 },
  { name: `fade-in-keeps-own-after`, own: 0.6, animation: `fade-in`, at: 1.5 },
  { name: `slide-in-mid`, own: 0.8, animation: `slide-in-up`, at: 0.5 },
  { name: `spin-leaves-opacity`, own: 0.4, animation: `spin`, at: 0.25 },
]

function animationsFixture() {
  const themes: Record<string, unknown> = {}
  for (const id of BUILTIN_THEME_IDS) {
    const theme = builtinTheme(id)
    const entries: Record<string, unknown> = {}
    for (const name of ANIMATION_NAMES) {
      const timing = animationTiming(name, theme)!
      const d = timing.durationMs
      const times = [0, d * 0.25, d * 0.5, d * 0.75, d, d * 1.5]
      entries[name] = {
        timing,
        frames: times.map((t) => ({ t, frame: animationFrame(name, t, theme) })),
        reduced: animationFrame(name, d * 0.5, theme, { reducedMotion: true }),
      }
    }
    themes[id] = entries
  }
  const neutral = builtinTheme(`neutral`)
  return {
    $comment: `${HEADER} Round 2 (docs/round-2-contract.md §2, animation): per built-in theme and keyframe set (catalog/style.json \`animations\`) the TIMING (the duration token's ms × factor, the easing: a \`$ease\` curve or linear, the iterations) and the FRAME at t ms after the node entered the tree (0, ¼, ½, ¾, 1 and 1½ durations; per-segment easing, cubic-bezier solved by bisection; finished animations hold the last keyframe), plus the reduced-motion frame (the \`rest\` keyframe, no band). Channels: opacity, translateX/Y px, rotate deg, scale, band (shimmer, -1..1; null = none). Compare within 1e-3. \`override\` = \`animationDuration: $motion.fast\`. \`css\` = the @keyframes rule a CSS renderer emits (opacity moves \`--xui-a-opacity\`), \`properties\` = the @property rules it registers once. \`opacity\`: the painted opacity = the node's own × the frame's (never replaced; a finished fade-in keeps the author's opacity); \`css\` = styleToCss of \`{opacity: own, animation}\`.`,
    themes,
    override: { theme: `neutral`, name: `fade-in`, durationToken: `$motion.fast`, timing: animationTiming(`fade-in`, neutral, `$motion.fast`), frame: animationFrame(`fade-in`, 60, neutral, { durationToken: `$motion.fast` }) },
    css: Object.fromEntries(ANIMATION_NAMES.map((n) => [n, keyframesCss(n)])),
    properties: ANIMATION_PROPERTIES_CSS,
    opacity: OPACITY_CASES.map((c) => {
      const timing = animationTiming(c.animation, neutral)!
      const t = timing.durationMs * c.at
      return { ...c, theme: `neutral`, t, expected: paintedOpacity(c.own, animationFrame(c.animation, t, neutral)), css: styleToCss({ opacity: c.own, animation: c.animation }, {}, neutral) }
    }),
  }
}

// ---------------------------------------------------------------------------
// bench-list.json
// ---------------------------------------------------------------------------

function benchFixture() {
  return {
    $comment: `${HEADER} Round 2 (docs/round-2-contract.md §5): the list bench EVERY renderer runs (React jsdom + Chromium, the Rust core, gpui headless, Compose JVM) and reports in its README. The surface is a List over \`rows\` = the generated data below (row i = {id: "r<i>", title: "Row <i>", meta: String(i % 97)}); measure on a 390×800 surface under the neutral theme: \`firstPaintMs\` (reduce + bind + lay out + paint the first window), \`scrollStepMs\` (mean of 100 steps of one viewport each), \`scrollToIndexMs\` (scrollToIndex 50000, align start), \`renderedItems\` (items alive after the jump: must be ≤ the window + 2 × overscan + the pinned header). Numbers are machine-dependent: report the machine.`,
    rows: { count: 100_000, id: `r{i}`, title: `Row {i}`, meta: `{i % 97}` },
    viewport: { width: 390, height: 800 },
    theme: `neutral`,
    catalogId: CORE_CATALOG_ID,
    components: [
      { id: `root`, component: `List`, direction: `vertical`, divided: true, style: { height: 800 }, children: { componentId: `bench-row`, path: `/rows`, key: `id` } },
      { id: `bench-row`, component: `ListRow`, title: { path: `title` }, meta: { path: `meta` } },
    ],
    steps: { scroll: { count: 100, by: `viewport` }, scrollToIndex: { index: 50_000, align: `start` } },
    metrics: [`firstPaintMs`, `scrollStepMs`, `scrollToIndexMs`, `renderedItems`],
  }
}

export function renderRound2(): Record<string, string> {
  return {
    "fixtures/format.json": json(formatFixture()),
    "fixtures/template-items.json": json(templateItemsFixture()),
    "fixtures/text-direction.json": json(directionFixture()),
    "fixtures/resizable.json": json(resizableFixture()),
    "fixtures/virtual-list.json": json(virtualListFixture()),
    "fixtures/animations.json": json(animationsFixture()),
    "fixtures/bench-list.json": json(benchFixture()),
  }
}
