/* ─── UI islands codegen (EXP-887) ───

   Runs under Bun BEFORE `vite`/`tsc` in every marketing script:

     bun run scripts/ui-demos.tsx && vite
     bun run scripts/ui-demos.tsx && tsc --noEmit && vite build && …

   It compiles `@exp/ui`'s stylesheet ONCE (~1s) and renders every entry of
   src/ui-demos/demos.tsx to static markup inside a declarative shadow root,
   then writes src/ui-demos/generated.ts — a gitignored module the page bundle
   imports. `@exp/ui/island` is server-only (react-dom/server + the Tailwind
   compiler), which is exactly why this is a build step and not a component.

   The compiled CSS is spliced INTO each island's `<template>`, so an island is
   one self-contained blob `UiDemo` can inject: the web theme reaches the
   components and never the marketing document, whose own `--border`/`--input`/
   `--accent` tokens are different colours.

   The write is diff-skipped: `bun run dev` regenerates on every start and an
   identical rewrite would bounce Vite's HMR for nothing. */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { compileUiCss, renderIsland } from "@exp/ui/island"

import { UI_DEMOS_SOURCE } from "../src/ui-demos/demos"

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), `..`)
/* The Tailwind scan base: the demo map's own directory, so the wrapper
   classes in demos.tsx are emitted next to the components' own utilities. */
const DEMOS_DIR = resolve(ROOT, `src/ui-demos`)
const OUT_FILE = resolve(DEMOS_DIR, `generated.ts`)

const OPEN_TEMPLATE = `<template shadowrootmode="open">`

const started = Date.now()
const css = await compileUiCss({ base: DEMOS_DIR })

const ids = Object.keys(UI_DEMOS_SOURCE).sort()
if (ids.length === 0) throw new Error(`ui-demos: demos.tsx exports no demos`)

const entries = ids.map((id) => {
  const markup = renderIsland(UI_DEMOS_SOURCE[id]())
  if (!markup.includes(OPEN_TEMPLATE)) {
    throw new Error(`ui-demos: island "${id}" carries no shadow-root template`)
  }
  return `  ${JSON.stringify(id)}: ${JSON.stringify(markup)},`
})

const file = `// AUTO-GENERATED by scripts/ui-demos.tsx — do not edit, do not commit
// (it is gitignored). Source of truth: src/ui-demos/demos.tsx; every marketing
// dev/build/typecheck script regenerates this first.

/** The compiled \`@exp/ui\` stylesheet, minified. Spliced into every island
 *  below; exported on its own so a test can assert against it. */
export const UI_DEMO_CSS = ${JSON.stringify(css)}

const OPEN_TEMPLATE = ${JSON.stringify(OPEN_TEMPLATE)}

/** \`renderIsland\` output per demo id — markup only. */
const UI_DEMO_MARKUP: Record<string, string> = {
${entries.join(`\n`)}
}

/** Ready to inject: the stylesheet inside each island's own template, so the
 *  shadow tree is styled and the host document is never touched. */
export const UI_DEMOS: Record<string, string> = Object.fromEntries(
  Object.entries(UI_DEMO_MARKUP).map(([id, markup]) => [
    id,
    // A function replacement: \`$&\`/\`$1\` in the CSS must stay literal.
    markup.replace(
      OPEN_TEMPLATE,
      () => \`\${OPEN_TEMPLATE}<style>\${UI_DEMO_CSS}</style>\`
    ),
  ])
)
`

mkdirSync(DEMOS_DIR, { recursive: true })
const unchanged = existsSync(OUT_FILE) && readFileSync(OUT_FILE, `utf8`) === file
if (!unchanged) writeFileSync(OUT_FILE, file)

console.log(
  `ui-demos: ${ids.length} island${ids.length === 1 ? `` : `s`} (${ids.join(`, `)}), ` +
    `${(css.length / 1024).toFixed(1)}kB css, ${Date.now() - started}ms` +
    `${unchanged ? ` — unchanged` : ``}`
)
