// AUTO-GENERATED by packages/icons/scripts/generate.ts — do not edit.
// Source of truth: packages/icons/icons.json + lucide-react's shipped geometry.
//
// The icon geometry reproduced in this file is from Lucide
// (https://lucide.dev) and is licensed ISC. Glyphs listed under icons.json
// `custom` are Exponential's own work, licensed Apache-2.0 with the rest of
// this repository (see the top-level LICENSE).
//
// ISC License
//
// Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as
// part of Feather (MIT). All other copyright (c) for Lucide are held by
// Lucide Contributors 2022.
//
// Permission to use, copy, modify, and/or distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//
// Asset names for the bundled Lucide imagesets. Render them through
// `AppIcon` (AppIcon.swift), never `Image(systemName:)` — these are template
// images in the app bundle's asset catalog, not SF Symbols.

import Foundation

public enum AppIcons {
    /// The user-facing pickable set (board icons + action icons), display order.
    public static let pickable: [String] = [
        "code",
        "square-kanban",
        "megaphone",
        "bug",
        "rocket",
        "book-open",
        "globe",
        "heart",
        "star",
        "zap",
        "wrench",
        "shield",
        "package",
        "terminal",
        "lightbulb",
        "message-circle",
        "palette",
        "pen-tool",
        "database",
        "server",
        "cloud",
        "cpu",
        "layers",
        "boxes",
        "folder",
        "file-text",
        "calendar",
        "clock",
        "users",
        "user",
        "flag",
        "target",
        "trophy",
        "lock",
        "key",
        "mail",
        "phone",
        "bell",
        "git-branch",
        "bot",
        "sparkles",
        "flask-conical",
        "shopping-cart",
        "credit-card",
        "map-pin",
        "compass",
        "briefcase",
        "graduation-cap",
        "puzzle",
        "gamepad-2",
        "coffee",
        "plane",
        "house",
        "building",
        "leaf",
        "sun",
        "activity",
        "chart-line",
        "scale",
        "car"
    ]

    /// Every registry name that ships as an imageset.
    public static let allNames: Set<String> = [
        "activity",
        "archive",
        "arrow-down-left",
        "arrow-left",
        "arrow-left-right",
        "arrow-right",
        "arrow-up-right",
        "at-sign",
        "bell",
        "bell-off",
        "bold",
        "book-open",
        "bot",
        "boxes",
        "briefcase",
        "brush-cleaning",
        "bug",
        "building",
        "building-2",
        "calendar",
        "calendar-days",
        "car",
        "chart-line",
        "check",
        "chevron-down",
        "chevron-left",
        "chevron-right",
        "chevron-up",
        "chevrons-up-down",
        "circle",
        "circle-arrow-up",
        "circle-check",
        "circle-dashed",
        "circle-dot",
        "circle-question-mark",
        "circle-user",
        "circle-x",
        "clipboard-list",
        "clock",
        "cloud",
        "code",
        "coffee",
        "compass",
        "copy",
        "cpu",
        "credit-card",
        "crown",
        "database",
        "download",
        "ellipsis",
        "ellipsis-vertical",
        "external-link",
        "eye",
        "file",
        "file-diff",
        "file-text",
        "flag",
        "flask-conical",
        "folder",
        "folder-kanban",
        "folder-open",
        "gamepad-2",
        "git-branch",
        "git-merge",
        "git-pull-request",
        "github",
        "globe",
        "graduation-cap",
        "hard-drive",
        "hash",
        "heading-1",
        "heading-2",
        "heading-3",
        "heart",
        "house",
        "image",
        "inbox",
        "info",
        "italic",
        "key",
        "layers",
        "leaf",
        "life-buoy",
        "lightbulb",
        "link",
        "list",
        "list-checks",
        "list-filter",
        "list-ordered",
        "list-todo",
        "loader-circle",
        "lock",
        "log-in",
        "log-out",
        "mail",
        "map-pin",
        "megaphone",
        "message-circle",
        "message-square",
        "message-square-plus",
        "minus",
        "monitor",
        "monitor-off",
        "move",
        "package",
        "palette",
        "panel-left-close",
        "panel-left-open",
        "paperclip",
        "pen-tool",
        "pencil",
        "phone",
        "plane",
        "play",
        "plug",
        "plus",
        "progress-1-4",
        "progress-1-5",
        "progress-2-4",
        "progress-2-5",
        "progress-3-4",
        "progress-3-5",
        "progress-4-5",
        "puzzle",
        "quote",
        "refresh-cw",
        "remove-formatting",
        "repeat",
        "rocket",
        "scale",
        "search",
        "search-x",
        "send",
        "server",
        "settings",
        "share-2",
        "shield",
        "shield-check",
        "shield-question-mark",
        "shopping-cart",
        "signal-high",
        "signal-low",
        "signal-medium",
        "sliders-horizontal",
        "sparkles",
        "square-kanban",
        "square-pen",
        "square-terminal",
        "star",
        "strikethrough",
        "sun",
        "tag",
        "target",
        "terminal",
        "trash-2",
        "triangle-alert",
        "trophy",
        "undo-2",
        "unlink",
        "upload",
        "user",
        "user-minus",
        "user-plus",
        "user-x",
        "users",
        "wifi-off",
        "wrench",
        "x",
        "zap"
    ]

    /// Registry name -> asset-catalog imageset name.
    public static func assetName(_ name: String) -> String? {
        allNames.contains(name) ? "lucide-\(name)" : nil
    }

    /// Concept `action-automation`.
    public static let actionAutomation: String = "zap"
    /// Concept `action-create`.
    public static let actionCreate: String = "plus"
    /// Concept `action-default`.
    public static let actionDefault: String = "zap"
    /// Concept `action-repository`.
    public static let actionRepository: String = "git-branch"
    /// Concept `action-run`.
    public static let actionRun: String = "play"
    /// Concept `action-suggestion`.
    public static let actionSuggestion: String = "lightbulb"
    /// Concept `coding-assistant`.
    public static let codingAssistant: String = "sparkles"
    /// Concept `coding-diff`.
    public static let codingDiff: String = "file-diff"
    /// Concept `coding-ended`.
    public static let codingEnded: String = "circle-check"
    /// Concept `coding-in-review`.
    public static let codingInReview: String = "git-pull-request"
    /// Concept `coding-needs-input`.
    public static let codingNeedsInput: String = "triangle-alert"
    /// Concept `coding-plan`.
    public static let codingPlan: String = "clipboard-list"
    /// Concept `coding-running`.
    public static let codingRunning: String = "play"
    /// Concept `coding-stop`.
    public static let codingStop: String = "circle-x"
    /// Concept `coding-subagent`.
    public static let codingSubagent: String = "bot"
    /// Concept `coding-tool`.
    public static let codingTool: String = "wrench"
    /// Concept `editor-bold`.
    public static let editorBold: String = "bold"
    /// Concept `editor-clear-formatting`.
    public static let editorClearFormatting: String = "remove-formatting"
    /// Concept `editor-code`.
    public static let editorCode: String = "code"
    /// Concept `editor-heading-1`.
    public static let editorHeading1: String = "heading-1"
    /// Concept `editor-heading-2`.
    public static let editorHeading2: String = "heading-2"
    /// Concept `editor-heading-3`.
    public static let editorHeading3: String = "heading-3"
    /// Concept `editor-image`.
    public static let editorImage: String = "image"
    /// Concept `editor-issue-ref`.
    public static let editorIssueRef: String = "hash"
    /// Concept `editor-italic`.
    public static let editorItalic: String = "italic"
    /// Concept `editor-link`.
    public static let editorLink: String = "link"
    /// Concept `editor-list`.
    public static let editorList: String = "list"
    /// Concept `editor-list-ordered`.
    public static let editorListOrdered: String = "list-ordered"
    /// Concept `editor-list-todo`.
    public static let editorListTodo: String = "list-todo"
    /// Concept `editor-mention`.
    public static let editorMention: String = "at-sign"
    /// Concept `editor-quote`.
    public static let editorQuote: String = "quote"
    /// Concept `editor-strikethrough`.
    public static let editorStrikethrough: String = "strikethrough"
    /// Concept `editor-unlink`.
    public static let editorUnlink: String = "unlink"
    /// Concept `event-assignee-changed`.
    public static let eventAssigneeChanged: String = "user-plus"
    /// Concept `event-board-moved`.
    public static let eventBoardMoved: String = "move"
    /// Concept `event-label-added`.
    public static let eventLabelAdded: String = "tag"
    /// Concept `event-label-removed`.
    public static let eventLabelRemoved: String = "tag"
    /// Concept `event-priority-changed`.
    public static let eventPriorityChanged: String = "signal-high"
    /// Concept `event-status-changed`.
    public static let eventStatusChanged: String = "circle-dot"
    /// Concept `nav-account`.
    public static let navAccount: String = "circle-user"
    /// Concept `nav-admin`.
    public static let navAdmin: String = "shield"
    /// Concept `nav-agents`.
    public static let navAgents: String = "bot"
    /// Concept `nav-boards`.
    public static let navBoards: String = "folder-kanban"
    /// Concept `nav-changelog`.
    public static let navChangelog: String = "megaphone"
    /// Concept `nav-create-issue`.
    public static let navCreateIssue: String = "square-pen"
    /// Concept `nav-files`.
    public static let navFiles: String = "folder"
    /// Concept `nav-filter`.
    public static let navFilter: String = "list-filter"
    /// Concept `nav-getting-started`.
    public static let navGettingStarted: String = "sparkles"
    /// Concept `nav-inbox`.
    public static let navInbox: String = "inbox"
    /// Concept `nav-issues`.
    public static let navIssues: String = "list"
    /// Concept `nav-my-issues`.
    public static let navMyIssues: String = "list"
    /// Concept `nav-notifications`.
    public static let navNotifications: String = "bell"
    /// Concept `nav-rail-collapse`.
    public static let navRailCollapse: String = "panel-left-close"
    /// Concept `nav-rail-expand`.
    public static let navRailExpand: String = "panel-left-open"
    /// Concept `nav-reviews`.
    public static let navReviews: String = "git-pull-request"
    /// Concept `nav-search`.
    public static let navSearch: String = "search"
    /// Concept `nav-settings`.
    public static let navSettings: String = "settings"
    /// Concept `nav-sign-out`.
    public static let navSignOut: String = "log-out"
    /// Concept `nav-source-control`.
    public static let navSourceControl: String = "git-merge"
    /// Concept `nav-support`.
    public static let navSupport: String = "life-buoy"
    /// Concept `nav-team-switcher`.
    public static let navTeamSwitcher: String = "chevrons-up-down"
    /// Concept `nav-terminal`.
    public static let navTerminal: String = "square-terminal"
    /// Concept `notification-issue-assigned`.
    public static let notificationIssueAssigned: String = "user-plus"
    /// Concept `notification-issue-comment`.
    public static let notificationIssueComment: String = "message-square"
    /// Concept `notification-issue-created`.
    public static let notificationIssueCreated: String = "circle-dot"
    /// Concept `notification-issue-mention`.
    public static let notificationIssueMention: String = "at-sign"
    /// Concept `notification-issue-status-changed`.
    public static let notificationIssueStatusChanged: String = "circle-check"
    /// Concept `notification-mark-read`.
    public static let notificationMarkRead: String = "list-checks"
    /// Concept `notification-mute`.
    public static let notificationMute: String = "bell-off"
    /// Concept `notification-pr-merged`.
    public static let notificationPrMerged: String = "git-merge"
    /// Concept `notification-pr-opened`.
    public static let notificationPrOpened: String = "git-pull-request"
    /// Concept `notification-support-reply`.
    public static let notificationSupportReply: String = "life-buoy"
    /// Concept `pr-closed`.
    public static let prClosed: String = "circle-x"
    /// Concept `pr-draft`.
    public static let prDraft: String = "circle-dot"
    /// Concept `pr-merged`.
    public static let prMerged: String = "git-merge"
    /// Concept `pr-open`.
    public static let prOpen: String = "git-pull-request"
    /// Concept `priority-high`.
    public static let priorityHigh: String = "signal-high"
    /// Concept `priority-low`.
    public static let priorityLow: String = "signal-low"
    /// Concept `priority-medium`.
    public static let priorityMedium: String = "signal-medium"
    /// Concept `priority-none`.
    public static let priorityNone: String = "minus"
    /// Concept `priority-urgent`.
    public static let priorityUrgent: String = "triangle-alert"
    /// Concept `sc-push`.
    public static let scPush: String = "upload"
    /// Concept `settings-about`.
    public static let settingsAbout: String = "info"
    /// Concept `settings-account`.
    public static let settingsAccount: String = "circle-user"
    /// Concept `settings-agents`.
    public static let settingsAgents: String = "bot"
    /// Concept `settings-api`.
    public static let settingsApi: String = "key"
    /// Concept `settings-billing`.
    public static let settingsBilling: String = "credit-card"
    /// Concept `settings-boards`.
    public static let settingsBoards: String = "square-kanban"
    /// Concept `settings-general`.
    public static let settingsGeneral: String = "building-2"
    /// Concept `settings-labels`.
    public static let settingsLabels: String = "tag"
    /// Concept `settings-licenses`.
    public static let settingsLicenses: String = "scale"
    /// Concept `settings-local-repos`.
    public static let settingsLocalRepos: String = "hard-drive"
    /// Concept `settings-members`.
    public static let settingsMembers: String = "users"
    /// Concept `settings-notifications`.
    public static let settingsNotifications: String = "bell"
    /// Concept `settings-rate`.
    public static let settingsRate: String = "star"
    /// Concept `settings-repositories`.
    public static let settingsRepositories: String = "github"
    /// Concept `settings-servers`.
    public static let settingsServers: String = "server"
    /// Concept `settings-statuses`.
    public static let settingsStatuses: String = "circle-dot"
    /// Concept `settings-storage`.
    public static let settingsStorage: String = "hard-drive"
    /// Concept `settings-sync`.
    public static let settingsSync: String = "refresh-cw"
    /// Concept `settings-tools`.
    public static let settingsTools: String = "square-terminal"
    /// Concept `settings-widget`.
    public static let settingsWidget: String = "message-square-plus"
    /// Concept `status-backlog`.
    public static let statusBacklog: String = "circle-dashed"
    /// Concept `status-cancelled`.
    public static let statusCancelled: String = "circle-x"
    /// Concept `status-done`.
    public static let statusDone: String = "circle-check"
    /// Concept `status-duplicate`.
    public static let statusDuplicate: String = "copy"
    /// Concept `status-in-progress`.
    public static let statusInProgress: String = "progress-2-4"
    /// Concept `status-in-review`.
    public static let statusInReview: String = "progress-3-4"
    /// Concept `status-todo`.
    public static let statusTodo: String = "circle"
    /// Concept `support-open`.
    public static let supportOpen: String = "circle-dot"
    /// Concept `support-resolved`.
    public static let supportResolved: String = "circle-check"
    /// Concept `ui-add`.
    public static let uiAdd: String = "plus"
    /// Concept `ui-agent-source`.
    public static let uiAgentSource: String = "bot"
    /// Concept `ui-archive`.
    public static let uiArchive: String = "archive"
    /// Concept `ui-arrow-right`.
    public static let uiArrowRight: String = "arrow-right"
    /// Concept `ui-assignee`.
    public static let uiAssignee: String = "circle-user"
    /// Concept `ui-attach`.
    public static let uiAttach: String = "paperclip"
    /// Concept `ui-avatar-placeholder`.
    public static let uiAvatarPlaceholder: String = "user"
    /// Concept `ui-back`.
    public static let uiBack: String = "arrow-left"
    /// Concept `ui-branch`.
    public static let uiBranch: String = "git-branch"
    /// Concept `ui-check`.
    public static let uiCheck: String = "check"
    /// Concept `ui-checklist`.
    public static let uiChecklist: String = "list-checks"
    /// Concept `ui-chevron-down`.
    public static let uiChevronDown: String = "chevron-down"
    /// Concept `ui-chevron-left`.
    public static let uiChevronLeft: String = "chevron-left"
    /// Concept `ui-chevron-right`.
    public static let uiChevronRight: String = "chevron-right"
    /// Concept `ui-chevron-up`.
    public static let uiChevronUp: String = "chevron-up"
    /// Concept `ui-clean`.
    public static let uiClean: String = "brush-cleaning"
    /// Concept `ui-clear`.
    public static let uiClear: String = "circle-x"
    /// Concept `ui-clock`.
    public static let uiClock: String = "clock"
    /// Concept `ui-close`.
    public static let uiClose: String = "x"
    /// Concept `ui-cloud`.
    public static let uiCloud: String = "cloud"
    /// Concept `ui-copy`.
    public static let uiCopy: String = "copy"
    /// Concept `ui-delete`.
    public static let uiDelete: String = "trash-2"
    /// Concept `ui-delete-account`.
    public static let uiDeleteAccount: String = "user-x"
    /// Concept `ui-device`.
    public static let uiDevice: String = "monitor"
    /// Concept `ui-device-offline`.
    public static let uiDeviceOffline: String = "monitor-off"
    /// Concept `ui-download`.
    public static let uiDownload: String = "download"
    /// Concept `ui-due-date`.
    public static let uiDueDate: String = "calendar-days"
    /// Concept `ui-edit`.
    public static let uiEdit: String = "pencil"
    /// Concept `ui-empty-search`.
    public static let uiEmptySearch: String = "search-x"
    /// Concept `ui-error`.
    public static let uiError: String = "circle-x"
    /// Concept `ui-external-link`.
    public static let uiExternalLink: String = "external-link"
    /// Concept `ui-file`.
    public static let uiFile: String = "file"
    /// Concept `ui-folder`.
    public static let uiFolder: String = "folder"
    /// Concept `ui-folder-open`.
    public static let uiFolderOpen: String = "folder-open"
    /// Concept `ui-github`.
    public static let uiGithub: String = "github"
    /// Concept `ui-help`.
    public static let uiHelp: String = "circle-question-mark"
    /// Concept `ui-info`.
    public static let uiInfo: String = "info"
    /// Concept `ui-invite`.
    public static let uiInvite: String = "user-plus"
    /// Concept `ui-issue`.
    public static let uiIssue: String = "file-text"
    /// Concept `ui-loading`.
    public static let uiLoading: String = "loader-circle"
    /// Concept `ui-mcp`.
    public static let uiMcp: String = "plug"
    /// Concept `ui-member`.
    public static let uiMember: String = "shield-check"
    /// Concept `ui-minus`.
    public static let uiMinus: String = "minus"
    /// Concept `ui-more`.
    public static let uiMore: String = "ellipsis"
    /// Concept `ui-more-vertical`.
    public static let uiMoreVertical: String = "ellipsis-vertical"
    /// Concept `ui-offline`.
    public static let uiOffline: String = "wifi-off"
    /// Concept `ui-organization`.
    public static let uiOrganization: String = "building-2"
    /// Concept `ui-owner`.
    public static let uiOwner: String = "crown"
    /// Concept `ui-permission`.
    public static let uiPermission: String = "shield-question-mark"
    /// Concept `ui-private`.
    public static let uiPrivate: String = "lock"
    /// Concept `ui-properties`.
    public static let uiProperties: String = "sliders-horizontal"
    /// Concept `ui-redock`.
    public static let uiRedock: String = "arrow-down-left"
    /// Concept `ui-refresh`.
    public static let uiRefresh: String = "refresh-cw"
    /// Concept `ui-remove-member`.
    public static let uiRemoveMember: String = "user-minus"
    /// Concept `ui-repeat`.
    public static let uiRepeat: String = "repeat"
    /// Concept `ui-repository`.
    public static let uiRepository: String = "code"
    /// Concept `ui-selected`.
    public static let uiSelected: String = "circle-check"
    /// Concept `ui-selector`.
    public static let uiSelector: String = "chevrons-up-down"
    /// Concept `ui-send`.
    public static let uiSend: String = "send"
    /// Concept `ui-server`.
    public static let uiServer: String = "server"
    /// Concept `ui-share`.
    public static let uiShare: String = "share-2"
    /// Concept `ui-sign-in`.
    public static let uiSignIn: String = "log-in"
    /// Concept `ui-staging`.
    public static let uiStaging: String = "flask-conical"
    /// Concept `ui-submit`.
    public static let uiSubmit: String = "circle-arrow-up"
    /// Concept `ui-subscribe`.
    public static let uiSubscribe: String = "bell"
    /// Concept `ui-success`.
    public static let uiSuccess: String = "circle-check"
    /// Concept `ui-swap`.
    public static let uiSwap: String = "arrow-left-right"
    /// Concept `ui-team`.
    public static let uiTeam: String = "users"
    /// Concept `ui-unassigned`.
    public static let uiUnassigned: String = "user-x"
    /// Concept `ui-undo`.
    public static let uiUndo: String = "undo-2"
    /// Concept `ui-undock`.
    public static let uiUndock: String = "arrow-up-right"
    /// Concept `ui-unselected`.
    public static let uiUnselected: String = "circle"
    /// Concept `ui-unsubscribe`.
    public static let uiUnsubscribe: String = "bell-off"
    /// Concept `ui-update`.
    public static let uiUpdate: String = "circle-arrow-up"
    /// Concept `ui-warning`.
    public static let uiWarning: String = "triangle-alert"
    /// Concept `ui-watch`.
    public static let uiWatch: String = "eye"
    /// Concept `ui-widget`.
    public static let uiWidget: String = "megaphone"
}
