// @exponential-at/ui-react — Exponential UI's React renderer (VAPP-87).
export { ExponentialSurface, resolveThemeInput } from "./surface"
export type { ExponentialSurfaceProps, ThemeInput } from "./surface"
export { useSurface, templateNodeFrom } from "./use-surface"
export type { A2uiMessage, SurfaceState, UseSurfaceOptions } from "./use-surface"
export { registerExtension, defineReactExtension, registeredExtensions, extensionCatalogs } from "./extensions"
export type { ReactExtension, ExtensionComponent, RegisterExtensionOptions } from "./extensions"
export type { HostPlugin, IconComponent, IconMap, SurfaceActionEvent, SurfaceInputEvent, ExtensionComponentProps } from "./host"
export { compileTheme, compiledTheme, themeScope, partClass, propAttribute, tokenVar, tokenVarName, cssValue, declarations, ruleSelectors, STATE_SELECTORS, LAYERS } from "./theme-css"
export type { CompiledTheme } from "./theme-css"
export { nodeSheet, nodeClass, surfaceClass, walkNodes } from "./box-css"
export { BASE_CSS } from "./base-css"
export { getPointer, setPointer, absolutePath, resolveValue, resolveProps, boundPath, isBinding, isCall, CLIENT_FUNCTIONS } from "./data"
export type { DataModel, DataBinding, FunctionCall, ClientFunction, ResolveContext } from "./data"
export { useHostOwnedValue, DEBOUNCE_MS } from "./inputs"
export type { HostOwnedOptions, HostOwnedValue } from "./inputs"
export { WindowedList } from "./list"
export type { WindowedListProps } from "./list"
export { NodeView, useRootProps, useEmitter } from "./node-view"
export type { NativeProps } from "./node-view"
export { NATIVES, NATIVE_NAMES } from "./natives"
export { useSurfaceContext, SurfaceContext, ScopeContext } from "./context"
export type { SurfaceContextValue } from "./context"
export { IconGlyph, resolveIcon } from "./icons"
export { BuiltinMarkdown, renderMarkdown } from "./markdown"
export { useParts, str, num, bool, arr } from "./natives/shared"
