// @exponential-at/ui-react — Exponential UI's React renderer (VAPP-87 + round 1).
export { ExponentialSurface, resolveThemeInput, surfaceTheme } from "./surface"
export type { ExponentialSurfaceProps, ThemeInput, SurfaceHandle } from "./surface"
export { useSurface } from "./use-surface"
export type { A2uiMessage, SurfaceState, UseSurfaceOptions } from "./use-surface"
export { registerExtension, defineReactExtension, registeredExtensions, extensionCatalogs } from "./extensions"
export type { ReactExtension, ExtensionComponent, RegisterExtensionOptions } from "./extensions"
export type { HostPlugin, IconComponent, IconMap, SurfaceActionEvent, SurfaceInputEvent, ExtensionComponentProps, SourceOption } from "./host"
export { compileTheme, compiledTheme, themeScope, partClass, propAttribute, tokenVar, tokenVarName, cssValue, declarations, ruleSelectors, STATE_SELECTORS, LAYERS } from "./theme-css"
export type { CompiledTheme } from "./theme-css"
export { nodeSheet, compileNodeSheet, dynamicStyleEntries, queryToken, nodeClass, surfaceClass, walkNodes } from "./box-css"
export type { NodeSheet, DynamicStyleEntry } from "./box-css"
export { BASE_CSS } from "./base-css"
export { getPointer, setPointer, absolutePath, resolveValue, resolveProps, resolveNodeProps, resolveVisible, bindTree, boundPath, isBinding, isCall, hasDynamic, memoFormatter, CLIENT_FUNCTIONS } from "./data"
export type { DataModel, DataBinding, FunctionCall, ClientFunction, ResolveContext } from "./data"
export { useHostOwnedValue, DEBOUNCE_MS } from "./inputs"
export type { HostOwnedOptions, HostOwnedValue } from "./inputs"
export { WindowedList } from "./list"
export type { WindowedListProps, WindowedListHandle } from "./list"
export { NodeView, useRootProps, useEmitter, runNodeAction, templateItems, itemInstance, mergeStyle } from "./node-view"
export type { NativeProps, TemplateItem } from "./node-view"
export { NATIVES, NATIVE_NAMES } from "./natives"
export { useSurfaceContext, SurfaceContext, ScopeContext, InstanceContext } from "./context"
export type { SurfaceContextValue } from "./context"
export { IconGlyph, resolveIcon, FALLBACK_ICONS } from "./icons"
export { BuiltinMarkdown, renderMarkdown } from "./markdown"
export { useParts, str, num, bool, arr, BuiltinIcon, builtinIconName, failingChecks } from "./natives/shared"
export { FormContext, useForm, useField } from "./form"
export type { FieldHandle, FormContextValue, FieldState } from "./form"
export { useMediaQuery, useElementSize } from "./platform"
export { sortRows } from "./natives/table"
export { parseLocaleNumber } from "./natives/inputs"
export { acceptsFile } from "./natives/chips"
export { monthGrid } from "./natives/dates"
// VAPP-91: the host API on React.
export { HostSurface, hostPlugin, useHostSurface, useHostSurfaceIds, useHostStatus } from "./host-surface"
export type { HostSurfaceProps } from "./host-surface"
export { useMediaSource, useMediaSrc } from "./media"
