// The committed web BASELINE (fixtures/conformance-baseline.json): the React
// renderer's frame dump of the whole matrix, stored compactly — per fixture
// ONE node table (the union of every case's nodes: id, component, part,
// parent, text) and per case one frame row per placed node
// `[node, x, y, w, h, lines?, lh?]`, one row per line so a layout change
// diffs as the rows it moved. `decodeBaseline` gives the plain dump back;
// the Rust gate (tests/conformance.rs) decodes the same shape.

import { BASELINE_PATH, type CaseDump, type Dump, type DumpNode } from "./dump"

export const BASELINE_FILE = BASELINE_PATH
export const BASELINE_FORMAT = `xui-conformance-baseline/1`

type NodeRow = [id: string, component: string, part: string | null, parent: string | null, text: string | null]
type FrameRow = [node: number, x: number, y: number, w: number, h: number, lines?: number, lh?: number]

export interface Baseline {
  $comment: string
  format: string
  renderer: string
  fonts: string
  /** How the baseline was produced (browser version, launch flags). */
  producer: string
  fixtures: Record<string, { nodes: NodeRow[] }>
  cases: Record<string, { width: number; height: number; frames: FrameRow[] }>
}

const fixtureOf = (key: string) => key.split(`/`)[0]

export function toBaseline(dump: Dump, producer: string): Baseline {
  const fixtures: Baseline[`fixtures`] = {}
  const index = new Map<string, Map<string, number>>()
  const cases: Baseline[`cases`] = {}
  for (const [key, c] of Object.entries(dump.cases)) {
    const fx = fixtureOf(key)
    fixtures[fx] ??= { nodes: [] }
    const ids = index.get(fx) ?? new Map<string, number>()
    index.set(fx, ids)
    const frames: FrameRow[] = []
    for (const n of c.nodes) {
      const sig = JSON.stringify([n.id, n.component, n.part ?? null, n.parent ?? null, n.text ?? null])
      let i = ids.get(sig)
      if (i === undefined) {
        i = fixtures[fx].nodes.length
        fixtures[fx].nodes.push(JSON.parse(sig) as NodeRow)
        ids.set(sig, i)
      }
      const row: FrameRow = [i, n.x, n.y, n.w, n.h]
      if (n.lines !== undefined) row.push(n.lines, n.lh ?? 0)
      frames.push(row)
    }
    cases[key] = { width: c.width, height: c.height, frames }
  }
  return {
    $comment: `GENERATED by \`bun run --filter @exponential-at/ui conformance -- --write-baseline\` (packages/exponential-ui/conformance): the React renderer's frame dump of fixtures/conformance-cases.json in headless Chromium with the conformance font set. Decoded by conformance/baseline.ts and the Rust gate. Never hand-edit.`,
    format: BASELINE_FORMAT,
    renderer: dump.renderer,
    fonts: dump.fonts,
    producer,
    fixtures,
    cases,
  }
}

export function decodeBaseline(b: Baseline): Dump {
  if (b.format !== BASELINE_FORMAT) throw new Error(`baseline format ${b.format} ≠ ${BASELINE_FORMAT}`)
  const cases: Record<string, CaseDump> = {}
  for (const [key, c] of Object.entries(b.cases)) {
    const table = b.fixtures[fixtureOf(key)].nodes
    cases[key] = {
      width: c.width,
      height: c.height,
      nodes: c.frames.map(([i, x, y, w, h, lines, lh]) => {
        const [id, component, part, parent, text] = table[i]
        const n: DumpNode = { id, component, x, y, w, h }
        if (part !== null) n.part = part
        if (parent !== null) n.parent = parent
        if (text !== null) n.text = text
        if (lines !== undefined) {
          n.lines = lines
          n.lh = lh
        }
        return n
      }),
    }
  }
  return { format: `xui-frame-dump/1`, renderer: b.renderer, fonts: b.fonts, cases }
}

/** The baseline as committed: the envelope pretty, one node row / frame row per line. */
export function encodeBaseline(dump: Dump, producer: string): string {
  const b = toBaseline(dump, producer)
  const rows = (items: unknown[], indent: string) => (items.length ? `[\n${items.map((r) => `${indent}  ${JSON.stringify(r)}`).join(`,\n`)}\n${indent}]` : `[]`)
  const fixtures = Object.entries(b.fixtures)
    .map(([k, f]) => `    ${JSON.stringify(k)}: { "nodes": ${rows(f.nodes, `    `)} }`)
    .join(`,\n`)
  const cases = Object.entries(b.cases)
    .map(([k, c]) => `    ${JSON.stringify(k)}: { "width": ${c.width}, "height": ${c.height}, "frames": ${rows(c.frames, `    `)} }`)
    .join(`,\n`)
  return `{\n  "$comment": ${JSON.stringify(b.$comment)},\n  "format": ${JSON.stringify(b.format)},\n  "renderer": ${JSON.stringify(b.renderer)},\n  "fonts": ${JSON.stringify(b.fonts)},\n  "producer": ${JSON.stringify(b.producer)},\n  "fixtures": {\n${fixtures}\n  },\n  "cases": {\n${cases}\n  }\n}\n`
}
