/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiShapesWorkspacesRouteImport } from './routes/api/shapes/workspaces'
import { Route as ApiShapesWorkspaceMembersRouteImport } from './routes/api/shapes/workspace-members'
import { Route as ApiShapesWorkspaceInvitesRouteImport } from './routes/api/shapes/workspace-invites'
import { Route as ApiShapesUsersRouteImport } from './routes/api/shapes/users'
import { Route as ApiShapesProjectsRouteImport } from './routes/api/shapes/projects'
import { Route as ApiShapesLabelsRouteImport } from './routes/api/shapes/labels'
import { Route as ApiShapesIssuesRouteImport } from './routes/api/shapes/issues'
import { Route as ApiShapesIssueLabelsRouteImport } from './routes/api/shapes/issue-labels'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedWWorkspaceSlugRouteRouteImport } from './routes/_authenticated/w/$workspaceSlug/route'
import { Route as AuthenticatedWWorkspaceSlugIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/index'
import { Route as AuthenticatedWWorkspaceSlugSettingsIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/settings/index'
import { Route as AuthenticatedWWorkspaceSlugProjectsProjectSlugIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/projects/$projectSlug/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesWorkspacesRoute = ApiShapesWorkspacesRouteImport.update({
  id: '/api/shapes/workspaces',
  path: '/api/shapes/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesWorkspaceMembersRoute =
  ApiShapesWorkspaceMembersRouteImport.update({
    id: '/api/shapes/workspace-members',
    path: '/api/shapes/workspace-members',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShapesWorkspaceInvitesRoute =
  ApiShapesWorkspaceInvitesRouteImport.update({
    id: '/api/shapes/workspace-invites',
    path: '/api/shapes/workspace-invites',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShapesUsersRoute = ApiShapesUsersRouteImport.update({
  id: '/api/shapes/users',
  path: '/api/shapes/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesProjectsRoute = ApiShapesProjectsRouteImport.update({
  id: '/api/shapes/projects',
  path: '/api/shapes/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesLabelsRoute = ApiShapesLabelsRouteImport.update({
  id: '/api/shapes/labels',
  path: '/api/shapes/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesIssuesRoute = ApiShapesIssuesRouteImport.update({
  id: '/api/shapes/issues',
  path: '/api/shapes/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesIssueLabelsRoute = ApiShapesIssueLabelsRouteImport.update({
  id: '/api/shapes/issue-labels',
  path: '/api/shapes/issue-labels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWWorkspaceSlugRouteRoute =
  AuthenticatedWWorkspaceSlugRouteRouteImport.update({
    id: '/w/$workspaceSlug',
    path: '/w/$workspaceSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWWorkspaceSlugIndexRoute =
  AuthenticatedWWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugSettingsIndexRoute =
  AuthenticatedWWorkspaceSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugProjectsProjectSlugIndexRoute =
  AuthenticatedWWorkspaceSlugProjectsProjectSlugIndexRouteImport.update({
    id: '/projects/$projectSlug/',
    path: '/projects/$projectSlug/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/w/$workspaceSlug': typeof AuthenticatedWWorkspaceSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shapes/issue-labels': typeof ApiShapesIssueLabelsRoute
  '/api/shapes/issues': typeof ApiShapesIssuesRoute
  '/api/shapes/labels': typeof ApiShapesLabelsRoute
  '/api/shapes/projects': typeof ApiShapesProjectsRoute
  '/api/shapes/users': typeof ApiShapesUsersRoute
  '/api/shapes/workspace-invites': typeof ApiShapesWorkspaceInvitesRoute
  '/api/shapes/workspace-members': typeof ApiShapesWorkspaceMembersRoute
  '/api/shapes/workspaces': typeof ApiShapesWorkspacesRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/w/$workspaceSlug/': typeof AuthenticatedWWorkspaceSlugIndexRoute
  '/w/$workspaceSlug/settings/': typeof AuthenticatedWWorkspaceSlugSettingsIndexRoute
  '/w/$workspaceSlug/projects/$projectSlug/': typeof AuthenticatedWWorkspaceSlugProjectsProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shapes/issue-labels': typeof ApiShapesIssueLabelsRoute
  '/api/shapes/issues': typeof ApiShapesIssuesRoute
  '/api/shapes/labels': typeof ApiShapesLabelsRoute
  '/api/shapes/projects': typeof ApiShapesProjectsRoute
  '/api/shapes/users': typeof ApiShapesUsersRoute
  '/api/shapes/workspace-invites': typeof ApiShapesWorkspaceInvitesRoute
  '/api/shapes/workspace-members': typeof ApiShapesWorkspaceMembersRoute
  '/api/shapes/workspaces': typeof ApiShapesWorkspacesRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/w/$workspaceSlug': typeof AuthenticatedWWorkspaceSlugIndexRoute
  '/w/$workspaceSlug/settings': typeof AuthenticatedWWorkspaceSlugSettingsIndexRoute
  '/w/$workspaceSlug/projects/$projectSlug': typeof AuthenticatedWWorkspaceSlugProjectsProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/w/$workspaceSlug': typeof AuthenticatedWWorkspaceSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shapes/issue-labels': typeof ApiShapesIssueLabelsRoute
  '/api/shapes/issues': typeof ApiShapesIssuesRoute
  '/api/shapes/labels': typeof ApiShapesLabelsRoute
  '/api/shapes/projects': typeof ApiShapesProjectsRoute
  '/api/shapes/users': typeof ApiShapesUsersRoute
  '/api/shapes/workspace-invites': typeof ApiShapesWorkspaceInvitesRoute
  '/api/shapes/workspace-members': typeof ApiShapesWorkspaceMembersRoute
  '/api/shapes/workspaces': typeof ApiShapesWorkspacesRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/w/$workspaceSlug/': typeof AuthenticatedWWorkspaceSlugIndexRoute
  '/_authenticated/w/$workspaceSlug/settings/': typeof AuthenticatedWWorkspaceSlugSettingsIndexRoute
  '/_authenticated/w/$workspaceSlug/projects/$projectSlug/': typeof AuthenticatedWWorkspaceSlugProjectsProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/invite/$token'
    | '/w/$workspaceSlug'
    | '/api/auth/$'
    | '/api/shapes/issue-labels'
    | '/api/shapes/issues'
    | '/api/shapes/labels'
    | '/api/shapes/projects'
    | '/api/shapes/users'
    | '/api/shapes/workspace-invites'
    | '/api/shapes/workspace-members'
    | '/api/shapes/workspaces'
    | '/api/trpc/$'
    | '/w/$workspaceSlug/'
    | '/w/$workspaceSlug/settings/'
    | '/w/$workspaceSlug/projects/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/invite/$token'
    | '/api/auth/$'
    | '/api/shapes/issue-labels'
    | '/api/shapes/issues'
    | '/api/shapes/labels'
    | '/api/shapes/projects'
    | '/api/shapes/users'
    | '/api/shapes/workspace-invites'
    | '/api/shapes/workspace-members'
    | '/api/shapes/workspaces'
    | '/api/trpc/$'
    | '/w/$workspaceSlug'
    | '/w/$workspaceSlug/settings'
    | '/w/$workspaceSlug/projects/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/login'
    | '/auth/register'
    | '/invite/$token'
    | '/_authenticated/w/$workspaceSlug'
    | '/api/auth/$'
    | '/api/shapes/issue-labels'
    | '/api/shapes/issues'
    | '/api/shapes/labels'
    | '/api/shapes/projects'
    | '/api/shapes/users'
    | '/api/shapes/workspace-invites'
    | '/api/shapes/workspace-members'
    | '/api/shapes/workspaces'
    | '/api/trpc/$'
    | '/_authenticated/w/$workspaceSlug/'
    | '/_authenticated/w/$workspaceSlug/settings/'
    | '/_authenticated/w/$workspaceSlug/projects/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiShapesIssueLabelsRoute: typeof ApiShapesIssueLabelsRoute
  ApiShapesIssuesRoute: typeof ApiShapesIssuesRoute
  ApiShapesLabelsRoute: typeof ApiShapesLabelsRoute
  ApiShapesProjectsRoute: typeof ApiShapesProjectsRoute
  ApiShapesUsersRoute: typeof ApiShapesUsersRoute
  ApiShapesWorkspaceInvitesRoute: typeof ApiShapesWorkspaceInvitesRoute
  ApiShapesWorkspaceMembersRoute: typeof ApiShapesWorkspaceMembersRoute
  ApiShapesWorkspacesRoute: typeof ApiShapesWorkspacesRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/workspaces': {
      id: '/api/shapes/workspaces'
      path: '/api/shapes/workspaces'
      fullPath: '/api/shapes/workspaces'
      preLoaderRoute: typeof ApiShapesWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/workspace-members': {
      id: '/api/shapes/workspace-members'
      path: '/api/shapes/workspace-members'
      fullPath: '/api/shapes/workspace-members'
      preLoaderRoute: typeof ApiShapesWorkspaceMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/workspace-invites': {
      id: '/api/shapes/workspace-invites'
      path: '/api/shapes/workspace-invites'
      fullPath: '/api/shapes/workspace-invites'
      preLoaderRoute: typeof ApiShapesWorkspaceInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/users': {
      id: '/api/shapes/users'
      path: '/api/shapes/users'
      fullPath: '/api/shapes/users'
      preLoaderRoute: typeof ApiShapesUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/projects': {
      id: '/api/shapes/projects'
      path: '/api/shapes/projects'
      fullPath: '/api/shapes/projects'
      preLoaderRoute: typeof ApiShapesProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/labels': {
      id: '/api/shapes/labels'
      path: '/api/shapes/labels'
      fullPath: '/api/shapes/labels'
      preLoaderRoute: typeof ApiShapesLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/issues': {
      id: '/api/shapes/issues'
      path: '/api/shapes/issues'
      fullPath: '/api/shapes/issues'
      preLoaderRoute: typeof ApiShapesIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/issue-labels': {
      id: '/api/shapes/issue-labels'
      path: '/api/shapes/issue-labels'
      fullPath: '/api/shapes/issue-labels'
      preLoaderRoute: typeof ApiShapesIssueLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/w/$workspaceSlug': {
      id: '/_authenticated/w/$workspaceSlug'
      path: '/w/$workspaceSlug'
      fullPath: '/w/$workspaceSlug'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$workspaceSlug/': {
      id: '/_authenticated/w/$workspaceSlug/'
      path: '/'
      fullPath: '/w/$workspaceSlug/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/settings/': {
      id: '/_authenticated/w/$workspaceSlug/settings/'
      path: '/settings'
      fullPath: '/w/$workspaceSlug/settings/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/projects/$projectSlug/': {
      id: '/_authenticated/w/$workspaceSlug/projects/$projectSlug/'
      path: '/projects/$projectSlug'
      fullPath: '/w/$workspaceSlug/projects/$projectSlug/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
  }
}

interface AuthenticatedWWorkspaceSlugRouteRouteChildren {
  AuthenticatedWWorkspaceSlugIndexRoute: typeof AuthenticatedWWorkspaceSlugIndexRoute
  AuthenticatedWWorkspaceSlugSettingsIndexRoute: typeof AuthenticatedWWorkspaceSlugSettingsIndexRoute
  AuthenticatedWWorkspaceSlugProjectsProjectSlugIndexRoute: typeof AuthenticatedWWorkspaceSlugProjectsProjectSlugIndexRoute
}

const AuthenticatedWWorkspaceSlugRouteRouteChildren: AuthenticatedWWorkspaceSlugRouteRouteChildren =
  {
    AuthenticatedWWorkspaceSlugIndexRoute:
      AuthenticatedWWorkspaceSlugIndexRoute,
    AuthenticatedWWorkspaceSlugSettingsIndexRoute:
      AuthenticatedWWorkspaceSlugSettingsIndexRoute,
    AuthenticatedWWorkspaceSlugProjectsProjectSlugIndexRoute:
      AuthenticatedWWorkspaceSlugProjectsProjectSlugIndexRoute,
  }

const AuthenticatedWWorkspaceSlugRouteRouteWithChildren =
  AuthenticatedWWorkspaceSlugRouteRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWWorkspaceSlugRouteRoute: typeof AuthenticatedWWorkspaceSlugRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWWorkspaceSlugRouteRoute:
    AuthenticatedWWorkspaceSlugRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiShapesIssueLabelsRoute: ApiShapesIssueLabelsRoute,
  ApiShapesIssuesRoute: ApiShapesIssuesRoute,
  ApiShapesLabelsRoute: ApiShapesLabelsRoute,
  ApiShapesProjectsRoute: ApiShapesProjectsRoute,
  ApiShapesUsersRoute: ApiShapesUsersRoute,
  ApiShapesWorkspaceInvitesRoute: ApiShapesWorkspaceInvitesRoute,
  ApiShapesWorkspaceMembersRoute: ApiShapesWorkspaceMembersRoute,
  ApiShapesWorkspacesRoute: ApiShapesWorkspacesRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
