// EXP-551 — emoji picker + `:shortcode` typeahead data for the web app.
//
// The dataset is the shared one generated by packages/emoji into
// `emoji.generated.json` (labels, GitHub shortcodes, tags; same file on
// iOS/Android/desktop, so every client searches the same names). It is
// dynamic-imported so the ~245KB chunk only loads when a picker opens or a
// `:xx` token is typed. Pickers insert the UNICODE — never `:shortcode:`
// text — because `issues.description` / `comments.body` are plain GFM shared
// with clients that render only unicode. Always the BASE record: EXP-600
// dropped the skin-tone picker on every client (the dataset's `k` variants
// are deliberately unread).
//
// The ranking and recents rules below are mirrored by hand on the three
// native clients (EmojiCatalog.swift / EmojiCatalog.kt / emoji.rs).

import { useEffect, useState } from "react"
import type { EmojiDataset, EmojiRecord } from "@exp/emoji"
import { safeLocalStorage } from "@/lib/local-storage"

export type { EmojiDataset, EmojiRecord }

export interface EmojiGroup {
  index: number
  label: string
  emojis: EmojiRecord[]
}

export interface EmojiData {
  dataset: EmojiDataset
  groups: EmojiGroup[]
  /** Lowercased shortcode → record (first record wins on collisions). */
  byShortcode: Map<string, EmojiRecord>
  /** Base unicode → record. */
  byUnicode: Map<string, EmojiRecord>
}

let loaded: Promise<EmojiData> | null = null

/** Loads (once) and indexes the dataset. */
export function loadEmojiData(): Promise<EmojiData> {
  if (!loaded) {
    loaded = import(`@/lib/emoji.generated.json`).then((mod) =>
      indexEmojiData(mod.default)
    )
    // Let a failed chunk load be retried on the next call instead of caching
    // the rejection forever.
    loaded.catch(() => {
      loaded = null
    })
  }
  return loaded
}

export function indexEmojiData(dataset: EmojiDataset): EmojiData {
  const groups: EmojiGroup[] = dataset.groups.map((label, index) => ({
    index,
    label,
    emojis: [],
  }))
  const byShortcode = new Map<string, EmojiRecord>()
  const byUnicode = new Map<string, EmojiRecord>()
  for (const emoji of dataset.emojis) {
    groups[emoji.g]?.emojis.push(emoji)
    byUnicode.set(emoji.u, emoji)
    for (const code of emoji.s) {
      const key = code.toLowerCase()
      if (!byShortcode.has(key)) byShortcode.set(key, emoji)
    }
  }
  return { dataset, groups, byShortcode, byUnicode }
}

/**
 * React hook: kicks the lazy load when `enabled` and returns the indexed data
 * once it is there (null before). Safe to call with `enabled=false` — nothing
 * loads until the first picker/typeahead needs it.
 */
export function useEmojiData(enabled: boolean): EmojiData | null {
  const [data, setData] = useState<EmojiData | null>(null)
  useEffect(() => {
    if (!enabled || data) return
    let cancelled = false
    loadEmojiData().then(
      (result) => {
        if (!cancelled) setData(result)
      },
      () => {}
    )
    return () => {
      cancelled = true
    }
  }, [enabled, data])
  return data
}

// ── Search ──

/**
 * Ranked search: shortcode prefix > label prefix > tag prefix > label/tag
 * substring; ties keep dataset order. Empty query → nothing.
 */
export function searchEmoji(
  data: EmojiData,
  query: string,
  limit: number
): EmojiRecord[] {
  const q = query.trim().toLowerCase().replace(/^:|:$/g, ``)
  if (!q) return []
  const scored: { emoji: EmojiRecord; rank: number; order: number }[] = []
  const emojis = data.dataset.emojis
  for (let order = 0; order < emojis.length; order++) {
    const emoji = emojis[order]
    const rank = rankEmoji(emoji, q)
    if (rank !== null) scored.push({ emoji, rank, order })
  }
  scored.sort((a, b) => a.rank - b.rank || a.order - b.order)
  return scored.slice(0, limit).map((s) => s.emoji)
}

function rankEmoji(emoji: EmojiRecord, q: string): number | null {
  const label = emoji.l.toLowerCase()
  if (emoji.s.some((code) => code.toLowerCase() === q)) return 0
  if (emoji.s.some((code) => code.toLowerCase().startsWith(q))) return 1
  if (label.startsWith(q)) return 2
  if (emoji.t.some((tag) => tag === q || tag.startsWith(q))) return 3
  if (label.includes(q) || emoji.t.some((tag) => tag.includes(q))) return 4
  return null
}

/** Exact shortcode lookup (`tada` → 🎉), used by the `:tada:` auto-commit. */
export function findEmojiByShortcode(
  data: EmojiData,
  shortcode: string
): EmojiRecord | null {
  return data.byShortcode.get(shortcode.toLowerCase()) ?? null
}

// ── Per-device prefs ──

const RECENT_KEY = `exp.emojiRecent`
export const MAX_RECENT_EMOJI = 24

/** Recently picked BASE emoji, most recent first. */
export function readRecentEmoji(): string[] {
  const storage = safeLocalStorage()
  if (!storage) return []
  try {
    const raw = storage.getItem(RECENT_KEY)
    if (!raw) return []
    const parsed: unknown = JSON.parse(raw)
    if (!Array.isArray(parsed)) return []
    return parsed
      .filter((item): item is string => typeof item === `string`)
      .slice(0, MAX_RECENT_EMOJI)
  } catch {
    return []
  }
}

/** Records a pick (by base unicode) at the head of the recents list. */
export function pushRecentEmoji(unicode: string): string[] {
  const next = [
    unicode,
    ...readRecentEmoji().filter((item) => item !== unicode),
  ].slice(0, MAX_RECENT_EMOJI)
  try {
    safeLocalStorage()?.setItem(RECENT_KEY, JSON.stringify(next))
  } catch {
    // Storage full or blocked — recents are a nicety.
  }
  return next
}

// ── `:shortcode` typeahead ──

/**
 * The in-progress `:shortcode` token at the end of `textBefore` (the text
 * before the caret): a colon at start-of-text or after whitespace, then at
 * least two shortcode characters, optionally the closing colon. Two chars keep
 * `12:30`, `note:` and `:)` from ever opening a menu; the optional closing
 * colon keeps the menu alive when the user habitually types `:smile:` so it
 * can auto-commit (`closed`) instead of leaving literal shortcode text.
 * Shared with the mention/issue-ref regexes' shape (mention-textarea.tsx,
 * editor-autocomplete.ts).
 */
export const EMOJI_AT_CARET = /(?:^|\s):([a-z0-9_+-]{2,})(:?)$/i

export interface EmojiTokenMatch {
  query: string
  closed: boolean
  /** Length of the whole token (`:` + query + optional `:`). */
  length: number
}

export function matchEmojiToken(textBefore: string): EmojiTokenMatch | null {
  const match = textBefore.match(EMOJI_AT_CARET)
  if (!match) return null
  const closed = match[2] === `:`
  return {
    query: match[1],
    closed,
    length: match[1].length + 1 + (closed ? 1 : 0),
  }
}
